### ISSUE TITLE
Add method SobolSimulationResult::draw

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1001]
The draw method of SobolSimulationAlgorithm can make OpenTURNS crash.

The following script makes OT crash with RunTimeError. The script creates a SobolSimulationAlgorithm and tries to draw the Sobol' indices.

```
from openturns.viewer import View
import openturns as ot
from math import sqrt

ot.RandomGenerator.SetSeed(0)

# 1. The function G
def functionCrue(X) :
    Q, Ks, Zv, Zm = X
    alpha = (Zm - Zv)/5.0e3
    H = (Q/(Ks*300.0*sqrt(alpha)))**(3.0/5.0)
    S = [H + Zv]
    return S

# Creation of the problem function
g = ot.PythonFunction(4, 1, functionCrue) 

# 2. Random vector definition
myParamQ = ot.GumbelAB(1013., 558.)
Q = ot.ParametrizedDistribution(myParamQ)
otLOW = ot.TruncatedDistribution.LOWER
Q = ot.TruncatedDistribution(Q, 0, otLOW)
Ks = ot.Normal(30.0, 7.5)
Ks = ot.TruncatedDistribution(Ks, 0, otLOW)
Zv = ot.Uniform(49.0, 51.0)
Zm = ot.Uniform(54.0, 56.0)

# 4. Create the joint distribution function, 
#    the output and the event. 
X = ot.ComposedDistribution([Q, Ks, Zv, Zm])
Y = ot.RandomVector(g, ot.RandomVector(X))

# Sensitivity analysis
estimator = ot.SaltelliSensitivityAlgorithm()
estimator.setUseAsymptoticDistribution(True)
algo = ot.SobolSimulationAlgorithm(X, g, estimator)
algo.setMaximumOuterSampling(25) # number of iterations
algo.setBlockSize(100) # size of Sobol experiment at each iteration
algo.setBatchSize(4) # number of points evaluated simultaneously
algo.setIndexQuantileLevel(0.05) # alpha
algo.setIndexQuantileEpsilon(1e-2) # epsilon
algo.run()
saest = algo.getEstimator()

View(saest.draw()) # Fail
```
This produces 
```
(base) Z:\scripts>python testCrue-SA-fail.py
WRN - RandomVector(Function, RandomVector) is deprecated, use CompositeRandomVector
Traceback (most recent call last):
  File "testCrue-SA-fail.py", line 51, in <module>
    View(saest.draw()) # Fail
  File "C:\Users\c61372\AppData\Local\Continuum\anaconda3\lib\site-packages\openturns\simulation.py", line 1696, in draw
    return _simulation.SobolIndicesAlgorithm_draw(self, *args)
RuntimeError: InternalException : Error: cannot compute the mean of an empty sample.
```
The exception is likely to come from the mean() method of the Sample() class.  My guess is that the estimate of the confidence intervals fail in this particular case.

**Comment by mbaudin47** [comment]
It sounds weird : the algorithm is based on a stopping criteria which makes use of the distribution of the estimator, but this information cannot be plot after the algorithm has run.

**Comment by mbaudin47** [comment]
I think I found a simpler way of generating the bug : 
```
import openturns as ot
estimator = ot.SaltelliSensitivityAlgorithm()
estimator.draw()
```
generates the same message.

**Comment by jschueller** [comment]
In this context the  SaltelliSensitivity class used to specify the algorithm to use at each step of the simulation but it doesnt hold the data and hence cannot draw the indices.

**Comment by mbaudin47** [comment]
The following script is a workaround, based on the computeBilateralConfidenceInterval() method (and Matplotlib) : 

<pre>
dist_fo = result.getFirstOrderIndicesDistribution()
dist_to = result.getTotalOrderIndicesDistribution()

alpha = 0.05
pl.figure()
pl.plot(range(input_dimension),fo,"ro",label="First Order")
pl.plot(range(input_dimension),to,"bo",label="Total Order")
pl.xlabel("Inputs")
pl.ylabel("Sensitivity indices")
size = g.getEvaluationCallsNumber()
pl.title("Sobol' indices - n=%d - 1-alpha=%.4f %%" % (size,(1-alpha)*100))
pl.axis([-0.5,input_dimension-0.5,-0.1,1.1])
for i in range(input_dimension):
    dist_fo_i = dist_fo.getMarginal(i)
    dist_to_i = dist_to.getMarginal(i)
    fo_ci = dist_fo_i.computeBilateralConfidenceInterval(1-alpha)
    to_ci = dist_to_i.computeBilateralConfidenceInterval(1-alpha)
    fo_ci_a = fo_ci.getLowerBound()[0]
    fo_ci_b = fo_ci.getUpperBound()[0]
    to_ci_a = to_ci.getLowerBound()[0]
    to_ci_b = to_ci.getUpperBound()[0]
    pl.plot([i,i],[fo_ci_a,fo_ci_b],"r-")
    pl.plot([i,i],[to_ci_a,to_ci_b],"b-")
pl.legend()
</pre>

**Comment by mbaudin47** [comment]
The fact that algo.draw() does not exist is a bug.

**Comment by mbaudin47** [comment]
I cannot reopen the ticket (I do not have the appropriate rights), but I would if I could because the "draw" method should work.

**Comment by timjim333** [comment]
Hi, I'm not sure if this is the best place for this but I was trying to follow the code in this [OpenTURNS tutorial](https://openturns.github.io/openturns/master/examples/reliability_sensitivity/sensitivity_sobol.html) but I had two issues and I'm not sure if they are connected with the draw() method.

Firstly, on reaching the line `inputDesign = ot.SobolIndicesExperiment(distribution, size, True).generate()`, I get a warning:
`WRN - Warning! The description of the distribution ComposedDistribution is [X0,X1,X2,X0,X1,X2] and cannot identify uniquely the marginal distribution. Use default description instead.`

and on running `sensitivityAnalysis.draw()`, nothing happens. I searched through the source code and it seems that `sensitivityAnalysis.draw()` actually calls `_simulation.SobolIndicesAlgorithmImplementation_draw(self, *args)` which in turn returns nothing. Is the plotting of Sobol indices not yet supported?

Kind regards.

**Comment by jschueller** [comment]
@timjim333 sensitivityAnalysis.draw() returns an ot.Graph object, and it is only plotted automatically in the context of a jupyter notebook, in the context of a plain python script you have to use the viewer module:
```
from openturns.viewer import View
view = View(sensitivityAnalysis.draw())
view.ShowAll(block=True)
```

**Comment by timjim333** [comment]
I see! Thank you! How about the warning? Is that important?
Thanks.

**Comment by jschueller** [comment]
no, you can ignore it

**Comment by timjim333** [comment]
Thanks, Julien! This works!

**Comment by timjim333** [comment]
Hi Julien, sorry if this is stated elsewhere - I have a dataset I've output
as a CSV of observations in rows, and inputs and outputs in columns. What
is the best way to get this data into a Model class that can then be used
to generate the indices?

Thanks.

**Comment by mbaudin47** [comment]
Hit on this issue again. 

The following script produces:

```
import openturns as ot
import openturns.viewer as otv
ot.RandomGenerator.SetSeed(1976)
dist_E = ot.Beta(0.9, 3.1, 2.8e7, 4.8e7)
dist_E.setDescription(["E"])
F_para = ot.LogNormalMuSigma(3.0e4, 9.0e3, 15.0e3) # in N
dist_F = ot.ParametrizedDistribution(F_para)
dist_F.setDescription(["F"])
dist_L = ot.Uniform(250., 260.) # in cm
dist_L.setDescription(["L"])
dist_I = ot.Beta(2.5, 4, 310., 450.) # in cm^4
dist_I.setDescription(["I"])

X = ot.ComposedDistribution([dist_E, dist_F, dist_L, dist_I])
g = ot.SymbolicFunction( ["E","F","L","I"],["F* L^3 /  (3 * E * I)"])

# With SobolSimulationAlgorithm
alpha = 0.05 # i.e. 90% confidence interval
epsilon = 0.2 # Confidence interval length
blocksize = 50 # size of Sobol experiment at each iteration
batchsize = 16 # number of points evaluated simultaneously

estimator = ot.SaltelliSensitivityAlgorithm()
estimator.setUseAsymptoticDistribution(True)
algo = ot.SobolSimulationAlgorithm(X, g, estimator)
algo.setMaximumOuterSampling(100) # number of iterations
algo.setBlockSize(blocksize) 
algo.setBatchSize(batchsize) 
algo.setIndexQuantileLevel(alpha) # alpha
algo.setIndexQuantileEpsilon(epsilon) # epsilon
algo.run()

algo.draw() # Error
```
produces:
```
AttributeError: 'SobolSimulationResult' object has no attribute 'draw'
```
but it should produce:

![SaltelliSensitivityAlgorithm-draw](https://user-images.githubusercontent.com/31351465/71307899-58ae5080-23f5-11ea-99d8-b43d4321592a.png)

**Comment by mbaudin47** [comment]
Here is a temporary workaround.
```
def plotSobolSimulationResult(sobolSimulationResult,input_names,alpha=0.05):
    fo = sobolSimulationResult.getFirstOrderIndicesEstimate()
    to = sobolSimulationResult.getTotalOrderIndicesEstimate()
    dist_fo = sobolSimulationResult.getFirstOrderIndicesDistribution()
    dist_to = sobolSimulationResult.getTotalOrderIndicesDistribution()
    dim = dist_to.getDimension()
    graph = ot.Graph("Sobol' sensivity indices","Inputs","Sensivity indices",True,"topright")
    # Indices
    curve = ot.Cloud(range(dim),fo)
    curve.setColor("red")
    curve.setLegend("First order")
    graph.add(curve)
    curve = ot.Cloud(range(dim),to)
    curve.setColor("blue")
    curve.setLegend("Total order")
    graph.add(curve)
    # Labels
    x = ot.Point(range(dim)) + ot.Point([0.1]*dim)
    text = ot.Text(x, to, input_names)
    text.setColor("black")
    graph.add(text)
    # Error bars
    for i in range(dim):
        dist_fo_i = dist_fo.getMarginal(i)
        dist_to_i = dist_to.getMarginal(i)
        fo_ci = dist_fo_i.computeBilateralConfidenceInterval(1-2*alpha)
        to_ci = dist_to_i.computeBilateralConfidenceInterval(1-2*alpha)
        fo_a = fo_ci.getLowerBound()[0]
        fo_b = fo_ci.getUpperBound()[0]
        to_a = to_ci.getLowerBound()[0]
        to_b = to_ci.getUpperBound()[0]
        curve = ot.Curve([i,i],[fo_a,fo_b])
        curve.setColor("red")
        graph.add(curve)
        curve = ot.Curve([i,i],[to_a,to_b])
        curve.setColor("blue")
        graph.add(curve)
    return graph

input_names = X.getDescription()
sobolSimulationResult = algo.getResult()
graph = plotSobolSimulationResult(sobolSimulationResult,input_names)
otv.View(graph)
```

**Comment by sofianehaddad** [comment]
IMHO `algorithm` classes should not provide such a method (`draw`). The main methods of these classes should be :
 - `run` --> perform the embedded algorithm
 - `getResult` --> provide a result class.

We can also have specific setters. The `draw` method should be in the `result` class or a `post-processing` class that rely on the `result`

**Comment by mbaudin47** [comment]
> IMHO `algorithm` classes should not provide such a method (`draw`).

I agree: the design you suggest is clearer. This is why I updated the failing example.

**Comment by sofianehaddad** [comment]
Thus I suggest to remove the `draw` method
