### ISSUE TITLE
The doc for SobolSimulationAlgorithm has issues

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1004]
The doc for SobolSimulationAlgorithm has issues. 

It states that the stopping criteria is based on 
$$
\Phi_j^F(1-\alpha) - \Phi_j^F(\alpha) \leq \epsilon
$$
which does not match the code : the computeQuantile function is used, so that this is not Phi but Phi^-1. Moreover, the meaning of Phi is unspecified in the text.

The text should write : 
$$
(\Phi_j^F)^{-1}(1-\alpha) - (\Phi_j^F)^{-1}(\alpha) \leq \epsilon
$$
where $\Phi_j^F$ (resp. $\Phi_j^T$) is the cumulated distribution function of the gaussian asymptotic distribution of the estimator of the Sobol' first (resp. total) order indice.

**Comment by jschueller** [comment]
fixed in #1249
