### ISSUE TITLE
The ot.viewer.View() function does not always load

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1019]
When we directly use the ot.viewer.View() function, it seems that this is not possible. 

See for example the following script exemple-viewer.py:  

```
import openturns as ot
myBeta = ot.Beta(5, 7, 9, 10)
myPDFBeta = myBeta.drawPDF()
ot.viewer.View(myPDFBeta)
``` 
Executing the script in a fresh Ipython session produces an error: 
```
runfile('Z:/exemple-viewer.py', wdir='Z:/')
Traceback (most recent call last):
  File "<ipython-input-1-e1b09375ffea>", line 1, in <module>
    runfile('Z:/Activites2019/VIGIE-HDRPlot-2019/exemple-viewer.py', wdir='Z:/Activites2019/VIGIE-HDRPlot-2019')
  File "C:\Users\mylogin\AppData\Local\Continuum\anaconda3-5-3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)
  File "C:\Users\mylogin\AppData\Local\Continuum\anaconda3-5-3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "Z:/exemple-viewer.py", line 12, in <module>
    ot.viewer.View(myPDFBeta)

AttributeError: module 'openturns' has no attribute 'viewer'
```

If, however, we start by viewing the graph, e.g. 
```
myPDFBeta
```
the previous session prints the graph in the console. 
Executing again the original script then works. 

This seems to show that the viewer module does not loads up when executing directly the "ot.viewer.View". This seems to be a bug to me.

**Comment by jschueller** [comment]
in the notebook context viewer is loaded by jupyter when inspecting the graph, but else the viewer is still a separate package

**Comment by mbaudin47** [comment]
I do not get it: what difference does it make with other OT packages ? My session was in a raw Python console: should'n it work ?
