### ISSUE TITLE
Build fails with clang-60: token is not a valid binary operator in a preprocessor subexpression

### ISSUE THREAD

**Issue by yurivict** [openturns/openturns#1028]
```
/usr/ports/math/openturns/work/openturns-1.12/lib/include/openturns/OTdebug.h:52:53: error: token is not a valid binary operator in a preprocessor subexpression
#    if defined(__GNU_LIBRARY__) && ! __GLIBC_PREREQ(2, 10)
                                    ~~~~~~~~~~~~~~~~^
1 error generated.
```

FreeBSD 11.2

**Comment by jschueller** [comment]
hi @yurivict, could you try our #1029 patch ?

**Comment by yurivict** [comment]
This patch fixed the problem.

**Comment by jschueller** [comment]
Cool.
I'm curious. Are you the port maintainer ?
Also, have you tried to build the Python module ? Do the tests pass ?

**Comment by yurivict** [comment]
> I'm curious. Are you the port maintainer ?

I'm trying to create the port.

> Also, have you tried to build the Python module ?

I has built successfully.

> Do the tests pass ?

All tests fail.

**Comment by jschueller** [comment]
oh... just the c++ tests or even the Python tests ?

**Comment by yurivict** [comment]
C++ tests.

**Comment by jschueller** [comment]
They arent build by default, just do "make tests".

**Comment by yurivict** [comment]
All C++ tests still fail with 1.12rc1-227--g16de04bc3

**Comment by jschueller** [comment]
Does ctest's LastTest.log file show any clue ? or you can also run ctest with `--output-on-failure`

**Comment by yurivict** [comment]
https://people.freebsd.org/~yuri/openturns-LastTest.log

**Comment by jschueller** [comment]
It seems the c++ tests are not built (do "make tests"), for the python tests they can only be run after "make install".

**Comment by yurivict** [comment]
Usually, in cmake-based projects ```-DBUILD_TESTING:BOOL=ON``` turns on testing, see here: https://cmake.org/cmake/help/v3.7/module/CTest.html

**Comment by yurivict** [comment]
Now still a lot of cases fail:
```
48% tests passed, 497 tests failed out of 957

Total Test time (real) = 263.23 sec

The following tests FAILED:
	208 - cppcheck_Beta_std (Failed)
	214 - cppcheck_Chi_std (Failed)
	216 - cppcheck_ChiSquare_std (Failed)
	232 - cppcheck_FisherSnedecor_std (Failed)
	236 - cppcheck_Gamma_std (Failed)
	247 - cppcheck_InverseChiSquare_std (Failed)
	248 - cppcheck_InverseGamma_std (Failed)
	251 - cppcheck_InverseWishart_std (Failed)
```

I've updated the log: https://people.freebsd.org/~yuri/openturns-LastTest.log
