### ISSUE TITLE
ProbabilitySimulationResult does not provide the distribution of the probability

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1035]
The getProbabilityDistribution method does not exist for this class. This is a pity, given that, if a Monte-Carlo experiment is used, the asymptotic distribution is known. This is a gaussian distribution with mean pf and variance pf*(1-pf)/n, where n is the sample size. This variance is approximate, given that the exact pf is unknown.

This is unconsistent with the ExpectationSimulationResult class which provides the getExpectationDistribution method. 

There is a bonus bug : the doc for ProbabilitySimulationAlgorithm.getResult states that the result is a SimulationResult, but it is a ProbabilitySimulationResult.

**Comment by regislebrun** [comment]
In fact, as soon as you rely on iid samples to estimate a sum or an empirical mean, you have the *exact* distribution (up to the value of the parameter) using the RandomMixture class. You don't even have to bother with an online simplification such as "the sum of iid Bernouli is a Binomial", as RandomMixture is smart enough to do that for you! So:
+ the algorithm runs to completion
+ using the estimated value of the probability a RandomMixture is built with the relevant atoms

**Comment by mbaudin47** [comment]
Thanks for the interesting comment : I tried, and there is a _surprise_. 

Consider the following parameters.
```
import openturns as ot
import numpy as np
n = 1000
pf = 0.5
alpha = 0.05
```
The following script works:
```
# Sol #1
sigmapf = np.sqrt(pf*(1-pf)/n)
pf_dist = ot.Normal(pf,sigmapf)
bounds = pf_dist.computeBilateralConfidenceInterval(1-alpha)
lb = bounds.getLowerBound()[0]
up = bounds.getUpperBound()[0]
print("%.2f%% confidence interval = [%f,%f]" % ((1-alpha)*100,lb,up))
```
and produces: 
```
95.00% confidence interval = [0.469010,0.530990]
```
But the following script: 
```
# Sol #2
pf_dist = ot.Binomial(n,pf)
bounds = pf_dist.computeBilateralConfidenceInterval(1-alpha)
lb = bounds.getLowerBound()[0]
up = bounds.getUpperBound()[0]
print("%.2f%% confidence interval = [%f,%f]" % ((1-alpha)*100,lb,up))
```
fails: 
```
RuntimeError: NotYetImplementedException : In DistributionImplementation::computeMinimumVolumeInterval()
```
Didn't expect that: for a 1D distribution, it should be the computation of the quantile at levels 1-alpha/2 and alpha/2, isn'it ? That is: the more general minimumVolume methods do not have to be evaluated for such a simple test case. The other possibility is that the computeBilateralConfidenceInterval method was not intended for that particular purpose, so that I should have used another method: but do not see any other which matches more.

**Comment by mbaudin47** [comment]
Below is a full example of my feature request. 
```
import openturns as ot
dist_E = ot.Beta(0.9, 3.1, 2.8e7, 4.8e7)
F_para = ot.LogNormalMuSigma(3.0e4, 9.0e3, 15.0e3)
dist_F = ot.ParametrizedDistribution(F_para)
dist_L = ot.Uniform(250., 260.)
dist_I = ot.Beta(2.5, 4, 310., 450.)
X = ot.ComposedDistribution([dist_E, dist_F, dist_L, dist_I])
g = ot.SymbolicFunction( ["E","F","L","I"],["F* L^3 /  (3 * E * I)"])
XRV = ot.RandomVector(X)
Y = ot.RandomVector(g, XRV)
myEvent = ot.Event(Y, ot.Greater(), 20.0)
experiment = ot.MonteCarloExperiment()
myAlgo = ot.ProbabilitySimulationAlgorithm(myEvent, experiment)
myAlgo.setMaximumOuterSampling(10000)
myAlgo.setBlockSize(1000)
myAlgo.setMaximumCoefficientOfVariation(0.01)
myAlgo.run()
result = myAlgo.getResult()
pf_dist = result.getProbabilityDistribution()
```
The previous script fails with:
```
AttributeError: 'ProbabilitySimulationResult' object has no attribute 'getProbabilityDistribution'
```
I hope that this may clarify my purpose.

**Comment by regislebrun** [comment]
There are 2 bugs here:
- the exception message is wrong: it mentions computeMinimumVolumeInterval() instead of computeBilateralConfidenceInterval()
- in computeBilateralConfidenceIntervalWithProbability() the continuity test is done too early. It should be done only in the multivariate case

**Comment by jschueller** [comment]
adressed in #1040
