### ISSUE TITLE
Doc error for KrigingAlgorithm method getReducedLogLikelihoodFunction()

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1036]
The documentation of the KrigingAlgorithm method [getReducedLogLikelihoodFunction()](http://openturns.github.io/openturns/latest/user_manual/response_surface/_generated/openturns.KrigingAlgorithm.html?highlight=krigingalgorithm#openturns.KrigingAlgorithm.getReducedLogLikelihoodFunction) contains a mistake:

Instead of 

> The reduced log-likelihood function as a function of $(\boldsymbol{\theta}, \boldsymbol{\sigma})$

it should read

> The reduced log-likelihood function as a function of $\boldsymbol{\theta}$.

Indeed, precisely because the likelihood function is reduced, it does not take $\boldsymbol{\sigma}$ as an argument.

**Comment by regislebrun** [comment]
The situation is more involved. The reduction of the log-likelihood function if and only if the following conditions are met:
- The model to be fitted has an output dimension of 1
- The amplitude parameter of the covariance model is in the active set of parameters
- The `"GeneralLinearModelAlgorithm-UseAnalyticalAmplitudeEstimate"` key of ResourceMap is set to `True`

In this case, the amplitude is removed from the set of active parameters and its value is obtained as an explicit expression involving the other parameters. It is misleading to reduce the parameters to $\sigma$ and $\theta$, as one may want to estimate also some shape parameters or correlation parameters for models of output dimension greater than 1. In my opinion, the documentation should read:
```
The *potentially* reduced log-likelihood function where $\sigma$ may be deduced from the
other parameters.

More precisely, such a reduction is done under the following conditions:
- The model to be fitted has an output dimension of 1
- The amplitude parameter of the covariance model is in the active set of parameters
- The *GeneralLinearModelAlgorithm-UseAnalyticalAmplitudeEstimate* key of :class:`~openturns.ResourceMap`
is set to *True*
```

**Comment by josephmure** [comment]
About the third condition :

> The *GeneralLinearModelAlgorithm-UseAnalyticalAmplitudeEstimate* key of :class:`~openturns.ResourceMap` is set to *True*

Is there any situation in which one would *not* want to use the analytical amplitude estimate, when such an estimate exists?

**Comment by regislebrun** [comment]
Yes: by enlarging the dimension of the search space, some optimization algorithms avoid to get stuck in a local maximum.

**Comment by josephmure** [comment]
In that case I think the doc should also mention what `getReducedLogLikelihoodFunction()` returns when one of the 3 conditions is not satisfied. Does it return the non-reduced log-likelihood function ?
