### ISSUE TITLE
The LinearModel class does not compute the R2.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1038]
The LinearModel class does not compute the R2.

This is, unexpected, given that all the data is available at this point.

Here is an example.
```
import openturns as ot
n= 10 
noise = ot.Normal(0.,0.1).getSample(n)
sampleX = ot.Normal(3).getSample(n)
sampleY = sampleX[:,0]+ 2*sampleX[:,0]+ 3*sampleX[:,0] + noise
LMF = ot.LinearModelFactory()
linearModel = LMF.build(sampleX, sampleY)
linearModel.computeR2() # Fails !
```
The workaround is:
```
predictions = linearModel.getPredicted(sampleX)
residuals = sampleY-predictions
SSRes = residuals.computeRawMoment(2)[0]
SSTot = sampleY.computeCenteredMoment(2)[0]
R2 = 1.0 - SSRes / SSTot
```
which shows that all the data is available to make the computation. 

More tricky: the computation could theorically be done with the computePredictivityFactor method of MetaModelValidation, but the "Function" required by MetaModelValidation cannot be generated from the LinearModel. The LinearLeastSquares class has the getResponseSurface method for that purpose, but the LinearModel does not.

**Comment by jschueller** [comment]
see the new LinearModelResult class

**Comment by mbaudin47** [comment]
Ok: OT 1.13 will include a LinearModelResult. But does this class solves the issue ? There is no R2 there.

**Comment by jschueller** [comment]
see getRelativeErrors

**Comment by mbaudin47** [comment]
Thanks for pointing this out. I did not find because the name did not ring any bell.

Shouldn't it be named getR2, getR2score, getRsquared or getCoefficientOfDetermination ?

In scikit, this is the r2_score function :

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html

In Wikipedia:

https://en.wikipedia.org/wiki/Coefficient_of_determination

In Matlab, this is the Rsquared field of the LinearModel:

https://nl.mathworks.com/help/stats/linearmodel-class.html

In R, this is r.squared:

https://stat.ethz.ch/R-manual/R-devel/library/stats/html/summary.lm.html
