### ISSUE TITLE
The KarhunenLoeveSVDAlgorithm cannot set the number of components

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1049]
In our application, we would like to set the number of components used in the KL decomposition. But the following constructor is missing:
```
KarhunenLoeveSVDAlgorithm(sample, K)
```
Within the code, this would compute the threshold depending on the number of components (and not the other way).

**Comment by jschueller** [comment]
With KLP1 using spectra you can now

**Comment by jschueller** [comment]
dup of #1470
