### ISSUE TITLE
KarhunenLoeveResult does not produce the explained variance ratio.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1050]
KarhunenLoeveResult does not product the explained variance ratio.

Once the number of eigenvalues has been reduced by thresholding, this information cannot be recovered.

**Comment by sofianehaddad** [comment]
@mbaudin47 agreed. I think we should allow/define several truncate strategies

**Comment by jschueller** [comment]
This has been resolved in 1.16
