### ISSUE TITLE
FittingTest.BestModelBIC to return bic value

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1057]
The following script:
```
import openturns as ot
N = ot.Normal()
sample = N.getSample(100)
tested_distributions = [ot.NormalFactory(),ot.BetaFactory()]
best_model, best_result = ot.FittingTest_BestModelBIC(sample, tested_distributions)
```
produces
```
TypeError: cannot unpack non-iterable Distribution object
```
This is with OT 1.12.

**Comment by jschueller** [comment]
it returns a Distribution, so ?

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.FittingTest_BestModelBIC.html?highlight=bestmodelbic#openturns.FittingTest_BestModelBIC

**Comment by mbaudin47** [comment]
I didn't get it: FittingTest_BestModelKolmogorov and FittingTest_BestModelBIC have the same input, but not the same output. That's an invalid issue.

**Comment by sofianehaddad** [comment]
@mbaudin47 IMO the difference is due to the interpretation of the results.
On the one hand, p-value is easily interpreted (Kolmogorov distribution)
On the other hand, there is no "natural" interpretation of the BIC value

Bty, agreed about heterogenous result outputs issue!

**Comment by jschueller** [comment]
I dont see what could be fixed here

**Comment by sofianehaddad** [comment]
@jschueller get the same output as Kolmogorov, ie both a Distribution and a BIC value
