### ISSUE TITLE
otlhs does not seem to be maintained anymore on conda-forge

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1066]
The latest release was two years ago on conda forge:

https://anaconda.org/conda-forge/otlhs/files

Hence, installing it on Python 36 or 37 is not possible. 

Why not to include otlhs within OT itself ?

**Comment by jschueller** [comment]
it is

**Comment by mbaudin47** [comment]
I forgot about this. The classes have been included in OT 1.9:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.OptimalLHSExperiment.html

Sorry !

**Comment by mbaudin47** [comment]
I guess this should be written on the Readme of:

https://github.com/openturns/otlhs
