### ISSUE TITLE
ProductCovarianceModel has no accessor to the underlying CovarianceModels

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1072]
Consider the following script:

```
import openturns as ot

COV5DEMIS_1 = ot.MaternModel([0.4], 1.0, 2.5)
COV5DEMIS_2 = ot.MaternModel([0.8], 1.0, 2.5)
COV5DEMIS_3 = ot.MaternModel([0.2], 1.0, 2.5)

PRODUIT_MATERN_CINQ_DEMIS = ot.ProductCovarianceModel([COV5DEMIS_1, COV5DEMIS_2, COV5DEMIS_3])
```
It would be useful to be able to access the models that were used to create the [ProductCovarianceModel](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.ProductCovarianceModel.html).

**Comment by jschueller** [comment]
see getCollection
