### ISSUE TITLE
Docstrings suggest kwargs are available

### ISSUE THREAD

**Issue by jjramsey** [openturns/openturns#1077]
The current documentation for SquaredExponential (http://openturns.github.io/openturns/master/user_manual/_generated/openturns.SquaredExponential.html) reads:

> **Available constructors**: 
>     SquaredExponential(*spatialDim*=1) 
>     SquaredExponential(*scale*)
>     SquaredExponential(*scale*, *amplitude*)

Apparently, this is *meant* to indicate that the SquaredExponential constructor accepts an integer argument that indicates the dimension of the covariance function inputs, and the default value of this argument is 1. However, there's an ambiguity, because unlike C++, Python functions may accept keyword arguments, so an expression like `spatialDim = 1` not only implies a default value of `spatialDim`, but seems to suggest that it is a keyword argument as well.

Yes, that the documentation for SquaredExponential begins with `SquaredExponential(*args)` rather than `SquaredExponential(*args, **kwargs)` might imply otherwise, but that's subtle and very easy to miss.

A possible fix to the documentation may be something roughly like this:

> **Available constructors**: 
>     SquaredExponential(*scale_or_spatial_dim*)
>     SquaredExponential(*scale*, *amplitude*)
>     SquaredExponential()
>
> **Parameters**:
> * *scale_or_spatial_dim*: Either a sequence of floats or an integer. If a sequence of floats, then it represents a vector of scale coefficients $\theta\in\mathbb{R}^n$. If an integer, then it represents the *length* of the vector of scale coefficients.
> * *amplitude*: ... same as before ...
>
> If the SquaredExponential constructor is called with no arguments, that is equivalent to the case where *scale_or_spatial_dim* equals 1.

**Comment by josephmure** [comment]
The same comments hold for the doc pages concerning the [Bernoulli](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.Bernoulli.html?) distribution, the [Normal](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.Normal.html?) distribution, the [BoxCoxTransform](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.BoxCoxTransform.html) and countless others.

The thing is, to the best of my knowledge, the OpenTURNS Python interface _never_ accepts keyword arguments.

I do not know how to address this in the documentation. Anyway, I think this issue should be renamed

> Documentation misleadingly suggests constructors accept keyword arguments

**Comment by mbaudin47** [comment]
I think that the issue can be solved if we write:
```
SquaredExponential(spatialDim)
```

**Comment by mdelozzo** [comment]
From my understanding, there are four constructors:
```python
SquaredExponential()
SquaredExponential(spatialDim)
SquaredExponential(scale)
SquaredExponential(scale, amplitude)
```
The default values should be documented only in the docstrings of the parameters, not in the constructors.

**Comment by mbaudin47** [comment]
There is the same issue for:
- https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.MaternModel.html?highlight=maternmodel

<img width="315" height="166" alt="Image" src="https://github.com/user-attachments/assets/1123a7c7-fd58-426b-8daf-d3c4f5c0ca90" />

- https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.AbsoluteExponential.html

- https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.DiracCovarianceModel.html

... and all other covariance models.

This is why I reopen this issue.
