### ISSUE TITLE
LogNormalFactory documentation

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#1087]
Hi
The LogNormalFactory documentation is false about its estimator: 
the final equation that enables to determine \gamma has a terme nS_4(\gamma): it should be nS_3(\gamma).
Anne

**Comment by jschueller** [comment]
@adutfoy you can edit files directly on your browser; select the file in the code tab, then click on the edit pencil on the right, then click on the commit button, that's it: a branch is automatically created along with its pull request.
