### ISSUE TITLE
The parameterGradient of a ParametricFunction can loss accuracy

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1092]
I observe an accuracy issue in the gradient of a symbolic parametric function.  This accuracy issue seems inconsistent because :
* the function is symbolic, so that the gradient should be exact,
* the gradient of the function is correct, but the gradient of the ParametricFunction is not.

This bug limits the accuracy of calibration, because calibration makes extensive use of ParametricFunctions. With inaccurate gradient, the calibration cannot go right.

See the following script, where i define a symbolic function involving the sum of the two last components.
```
import openturns as ot
modelFunc = ot.SymbolicFunction(["s", "r", "c"],["r + c"])
s = [1.]
r = 1e9
c = 1e8
theta = ot.Point([r,c])
calibratedIndices = [1,2]
mycf = ot.ParametricFunction(modelFunc, calibratedIndices, theta)
```
The value of:
```
modelFunc.gradient([s[0],r,c]).transpose()
```
is
```
[[ 0 1 1 ]]
```
But the value of:
```
mycf.parameterGradient(s).transpose()
```
is
```
[[ 0 0 ]]
```
instead of beeing equal to [[1 1]]. 
Reducing the values of r and c to 1.e2 allows to get correct results. This shows that something is not right and may involve finite differences in a case where an exact gradient should be used.

Replacing the symbolic function with a Python function reveals the same issue:
```
def myfunc(x):
    s,r,c = x
    return [r+c]
modelFunc = ot.PythonFunction(3,1,myfunc)
```
I looked at the code, but didn't find where the gradient was actually computed. I should perhaps use a debugger to find this.

[Parameter-function-gradient.zip](https://github.com/openturns/openturns/files/3103673/Parameter-function-gradient.zip)

**Comment by jschueller** [comment]
The gradient wrt parameters is computed in EvaluationImplementation::parameterGradient by finite difference (non-centered schemed, value=NumericalMathEvaluation-ParameterEpsilon).
ParametricEvaluation should reimplement it to extract the rows from the full gradient of the underlying function.

**Comment by regislebrun** [comment]
Ok its fixed now. The PR is coming soon, just after the local checks. There is no parameterHessian(), any need for it? It would take a little bit more work so not sure to be done for the release.

**Comment by jschueller** [comment]
#1093
