### ISSUE TITLE
The method used to generate the pseudo-random numbers can be surprising

### ISSUE THREAD

**Issue by RRiva** [openturns/openturns#1102]
Let us consider two composed distributions, one with an independent copula and another with a dependent one.

```
import openturns as ot

dist_1 = ot.ComposedDistribution([ot.Normal(), ot.Uniform()])

correlation = ot.CorrelationMatrix(2)
correlation[1, 0] = 0.25
aCopula = ot.NormalCopula(correlation)
dist_2 = ot.ComposedDistribution([ot.Normal(), ot.Uniform()], aCopula)
```

And now let's draw some samples.

```
print('Independent')

ot.RandomGenerator.SetSeed(0)
print(dist_1.getSample(2))

ot.RandomGenerator.SetSeed(0)
print(dist_1.getSample(3))

print('Dependent')

ot.RandomGenerator.SetSeed(0)
print(dist_2.getSample(2))

ot.RandomGenerator.SetSeed(0)
print(dist_2.getSample(3))
```

For the distribution with the dependent copula the first two samples are equal. Instead, in the independent case only the samples associated to the first marginal are the same.

It looks like OpenTURNS treat the two cases in a rather different manner. Is there a way to get the same initial samples also for the distributions with independent copula? Thanks!

**Comment by jschueller** [comment]
xref http://trac.openturns.org/ticket/984

**Comment by RRiva** [comment]
Hi, thanks for the answer 😊 I couldn't figure out how to implement your suggestion, but I discovered that setting 
```
ot.ResourceMap.SetAsBool('Distribution-Parallel', False)
```
does the trick. Is that what you meant?

**Comment by sofianehaddad** [comment]
> Hi, thanks for the answer 😊 I couldn't figure out how to implement your suggestion, but I discovered that setting
> 
> ```
> ot.ResourceMap.SetAsBool('Distribution-Parallel', False)
> ```
> 
> does the trick. Is that what you meant?

No it means that we (developers) should implement this feature.

**Comment by mbaudin47** [comment]
> > Hi, thanks for the answer 😊 I couldn't figure out how to implement your suggestion, but I discovered that setting
> > ```
> > ot.ResourceMap.SetAsBool('Distribution-Parallel', False)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > does the trick. Is that what you meant?
> 
> No it means that we (developers) should implement this feature.

I am sorry @sofianehaddad , but I do not understand your message. What do you mean? What particular feature is to be implemented and how is that related to the 'Distribution-Parallel' key of the `ResourceMap`?

**Comment by mbaudin47** [comment]
- The title is wrong because it the topic is not the way we plot a sample. I suggest to rename it : "The method used to generate the pseudo-random numbers can be surprising".
- There is no actual bug, in the sense that the statistical properties of the numbers are satisfied.
- I do not understand why it could be interesting to implement such a feature. Is this a variance reduction method involved in a Markov Monte Carlo chain? Is this the "common random numbers" method? In other words, what is the purpose of getting exactly the same numbers?

**Comment by RRiva** [comment]
My use case is about generating the sample for training a surrogate model. An iterative, manual, approach is:

1. Set the seed and generate some samples.
2. Run the simulations, train the surrogate and see how it performs.
3. Repeat.

For this, it would be nice if setting the same seed would provide the same points, i.e. rows. This is also coherent with `numpy`, as shown by the following snippet

```
import numpy as np

rng_1 = np.random.default_rng(seed=123)
sample_1 = rng_1.normal(size=(5, 3))

rng_2 = np.random.default_rng(seed=123)
sample_2 = rng_2.normal(size=(8, 3))
```

**Comment by mbaudin47** [comment]
What happens if you call the getRealization() two times, then three times?

**Comment by RRiva** [comment]
No, with this method the rows match. Thanks for the suggestion 🙂 

I'll leave here a code snippet hereafter for clarity.

```python
import numpy as np
import openturns as ot

dist = ot.ComposedDistribution([ot.Normal(), ot.Uniform(), ot.Beta()])

ot.RandomGenerator.SetSeed(0)
sample_1 = np.array([dist.getRealization() for _ in range(5)])

ot.RandomGenerator.SetSeed(0)
sample_2 = np.array([dist.getRealization() for _ in range(10)])
```

**Comment by RRiva** [comment]
Sorry for the long wait. Somehow I missed the edit 😅 Here is the code for the benchmark.
```
from timeit import timeit

import numpy as np
import openturns as ot

rng = np.random.default_rng(seed=0)
mean = np.array([0.0, 0.0, 0.0])
cov = np.eye(3)
def make_sample_np(n):
    rng.multivariate_normal(mean, cov, n)

ot.RandomGenerator.SetSeed(0)

dist_1 = ot.ComposedDistribution([ot.Normal(), ot.Normal(), ot.Normal()])
dist_2 = ot.Normal(3)

def make_sample_ot_1(n):
    ot.ResourceMap.SetAsBool('Distribution-Parallel', True)
    dist_1.getSample(n)

def make_sample_ot_2(n):
    ot.ResourceMap.SetAsBool('Distribution-Parallel', False)
    dist_1.getSample(n)

def make_sample_ot_3(n):
    ot.Sample([dist_1.getRealization() for _ in range(n)])

def make_sample_ot_4(n):
    dist_2.getSample(n)

time_np = timeit("make_sample_np(100000)", setup='from __main__ import make_sample_np', number=1000)
time_ot_1 = timeit("make_sample_ot_1(100000)", setup='from __main__ import make_sample_ot_1', number=1000)
time_ot_2 = timeit("make_sample_ot_2(100000)", setup='from __main__ import make_sample_ot_2', number=1000)
time_ot_3 = timeit("make_sample_ot_3(100000)", setup='from __main__ import make_sample_ot_3', number=100)
time_ot_4 = timeit("make_sample_ot_4(100000)", setup='from __main__ import make_sample_ot_4', number=1000)

print(f"Time numpy: {time_np:.2f}")
print(f"Time OpenTURNS, composed, sample, parallel: {time_ot_1:.2f}")
print(f"Time OpenTURNS, composed, sample, serial: {time_ot_2:.2f}")
print(f"Time OpenTURNS, composed, realization: {time_ot_3:.2f}")
print(f"Time OpenTURNS, normal, sample: {time_ot_4:.2f}")
```

On my laptop, with an Intel i5, the results are
```
Time numpy: 4.98
Time OpenTURNS, composed, sample, parallel: 10.82
Time OpenTURNS, composed, sample, serial: 10.80
Time OpenTURNS, composed, realization: 56.79
Time OpenTURNS, normal, sample: 5.52
```
So, it looks like OpenTURNS has room for improvement.

**Comment by jschueller** [comment]
you're not measuring exactly the same thing: in make_sample_ot_3 most of the time is spent in the list->Sample conversion

**Comment by mbaudin47** [comment]
So I think that we are to create an issue on Numpy, so that it can be as fast as OT when the dimension is getting large :)
