### ISSUE TITLE
Please add cmake options turning docs and examples on/off 

### ISSUE THREAD

**Issue by yurivict** [openturns/openturns#1107]
In the package it should be possible to enable/disable docs and examples with an option, it shouldn't be based on package auto-detection.

**Comment by jschueller** [comment]
Hi,
Currently it's not possible to force the configuration to fail if the documentation cannot be built,
however you can still disable the documentation generation with USE_SPHINX=OFF.
What are you trying to do that you cannot achieve here ?

**Comment by yurivict** [comment]
It should be an appropriately named cmake option enabling/disabling docs, and another one for examples.

> What are you trying to do that you cannot achieve here ?
Create a FreeBSD port.

**Comment by jschueller** [comment]
I still dont understand what bothers you here, is it just the name of the options, or something that cannot be achieved with the current behavior ?

**Comment by yurivict** [comment]
Currently there are 2 docs-related options: ```USE_DOXYGEN``` and ```USE_SPHINX```. I see 2 problems:
* ```USE_DOXYGEN``` doesn't do anything when set. It doesn't cause documentation to be installed
* ```USE_SPHINX``` is only checked when ```BUILD_PYTHON``` is set.

Do these two complement each other?

**Comment by jschueller** [comment]
These are independent options:
- USE_DOXYGEN doesnt do much, it just allows to detect doxygen. If ON and doxygen is found, then 'make html' allows to build the doxygen documentation, but it's not built by default when typing 'make'.
- USE_SPHINX allows to detect sphinx. If ON and most dependencies are found (python, libxml2, ...) then the sphinx documentation is built on 'make'.

For packaging, my opinion is that it makes little sense to package the documentation as it is available online. Anyways packages are often built on a remote vm where you only install the most needed dependencies, ie without sphinx/doxygen.

**Comment by yurivict** [comment]
I will leave docs out for now, thanks!

---------------

Also, what is the option to turn examples off?

**Comment by jschueller** [comment]
You dont have to worry about disabling examples/tests, nothing is enabled by default:

- C++ tests are not built by default they are only built on 'make tests'.
- The Python tests only the Python bindings to be built, and no tests are run unless explicitly running 'make test' or 'make pyinstallcheck', so you dont have to worry about disabling those.
- There are also documentation examples (jupyter notebooks rendered into html), and they are disabled if the sphinx doc is disabled.
