### ISSUE TITLE
question about histogram

### ISSUE THREAD

**Issue by swimhiking** [openturns/openturns#1109]
It's may not an issue, just want to ask when I draw a histogram graph using OpenTurns, and want to print specif range along axis, then I need to adjust bin size for histogram, how to do it in OpenTurns? Thank you very much.

**Comment by adutfoy** [comment]
I,
You should use the Histogram class (http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Histogram.html). Using this class, you can specify either custom ticks and frequencies or custom bin widths, heights and the global origin. Note that in all cases, the actual height of each bin is adjusted such that the total surface of the histogram is 1, as expected for a probability distribution.
Cheers
Anne
