### ISSUE TITLE
CopulaImplementation should derive from DistributionImplementation

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1139]
This is required for the MarshallOlkin copula:

https://github.com/openturns/openturns/compare/master...mbaudin47:newMarshallOlkinCopula#diff-eca7910e8a05945828d49f6006be96cf

However, this change breaks some unit tests, including Frank copula:

    [ 42%] Building CXX object lib/test/CMakeFiles/t_FrankCopula_std.dir/t_FrankCopula_std.cxx.o
    /home/osboxes/GIT/openturns/lib/test/t_FrankCopula_std.cxx: In function ‘int main(int, char**)’:
    /home/osboxes/GIT/openturns/lib/test/t_FrankCopula_std.cxx:77:65: 
    error:     ‘OT::ContinuousDistribution’ is not a base of ‘OT::FrankCopula’
               << " ddf (FD)=" << copula.ContinuousDistribution::computeDDF(point)
                                                                 ^~~~~~~~~~

**Comment by jschueller** [comment]
just remove the "ContinuousDistribution::"

**Comment by regislebrun** [comment]
Yes I have done the job, but the PR is not yet ready. In the mean time, you can replace ContinuousDistribution by DistributionImplementation in the C++ tests.
