### ISSUE TITLE
Bayesian calibration of a computer code

### ISSUE THREAD

**Issue by M2CI-ONERA** [openturns/openturns#1142]
Hi,

I am not sure to understand the example presented in the Bayesian calibration of a computer code.
Indeed, in the presented example, the input data are of dimension 1:

``x = ot.Sample(obsSize, covNum)
for i in range(obsSize):
    x[i, 0] = -2 + 5. * i / 9.``

but the considered compute code to calibrate is in dimension 3 in x (and has 3 parameters to be calibrated p1, p2 and p3):

```
fullModel = ot.SymbolicFunction(
    ['p1', 'p2', 'p3', 'x1', 'x2', 'x3'], ['p1*x1+p2*x2+p3*x3', '1.0'])# assume sigma=1 is known
# f:(x1, x2, x3)->(z) with parameters (p1, p2, p3)
model = ot.ParametricFunction(fullModel, list(range(paramDim)), [0.0]*paramDim)
```
this difference of dimension is not clear to me.

Secondly, in the _ParametricFunction_ definition, the parameters are frozen but we are trying to calibrate these parameters therefore it is not clear why these parameters are frozen.

Thirdly, I do not understand why in the entire example the input data x is not used (only y_obs is used) in the calibration of the model parameters, but it succeed to provide the a-posteri distribution on the model parameters.

Finally, considering a slightly different problem, having a model to calibrate such that f(x,p) = p1 +p2*x+p3*x^2, but with the rest being exactly the same:

```
# Number of covariates
covNum = 1
# Dimension of the observations
obsDim = 1
# Dimension of the vector of parameters to calibrate
paramDim = 3
# The number of obesrvations
obsSize = 10

x = ot.Sample(obsSize, covNum)
for i in range(obsSize):
    x[i, 0] = -2 + 5. * i / 9.
x

y_obs = ot.Sample(obsSize, obsDim)
y_obs[0, 0] = -9.50794871493506
y_obs[1, 0] = -3.83296694500105
y_obs[2, 0] = -2.44545713047953
y_obs[3, 0] = 0.0803625289211318
y_obs[4, 0] = 1.01898069723583
y_obs[5, 0] = 0.661725805623086
y_obs[6, 0] = -1.57581204592385
y_obs[7, 0] = -2.95308465670895
y_obs[8, 0] = -8.8878164296758
y_obs[9, 0] = -13.0812290405651

p = ot.Sample(obsSize, paramDim)
for i in range(obsSize):
    for j in range(paramDim):
        p[i, j] = (-2 + 5. * i / 9.) ** j
        
fullModel = ot.SymbolicFunction(
    ['p1', 'p2', 'p3', 'x'], ['p1+p2*x+p3*x**2'])# assume sigma=1 is known
# f:(x)->(z) with parameters (p1, p2, p3)
model = ot.ParametricFunction(fullModel, [3], [0.0])

conditional = ot.Normal()
conditional

sigma0 = ot.Point(paramDim, 10.0)  # standard deviations
C0 = ot.CorrelationMatrix(paramDim)       # variance matrix
for i in range(paramDim):
    C0[i, i] = sigma0[i] * sigma0[i]

m0 = ot.Point(paramDim, 0.0)      # mean
prior = ot.Normal(m0, C0)
prior.setDescription(['p1', 'p2', 'p3'])
prior

# Additional inputs for the random walk Metropolis-Hastings
# sampler constructor:

# 1) Initial state: the prior mean
theta0 = prior.getMean()

# 2) Proposal distribution: uniform
proposal = [ot.Uniform(-1., 1.)] * paramDim

# Creation of the Random Walk Metropolis-Hastings (RWMH) sampler
RWMHsampler = ot.RandomWalkMetropolisHastings(
    prior, conditional, model, p, y_obs, theta0, proposal)

# Tuning of the RWMH algorithm:

# 1) Strategy of calibration for the random walk (trivial example: default)
strategy = ot.CalibrationStrategyCollection(paramDim)
RWMHsampler.setCalibrationStrategyPerComponent(strategy)

# 2) Other parameters
RWMHsampler.setVerbose(True)
RWMHsampler.setThinning(1)
RWMHsampler.setBurnIn(2000)

# Ready to generate a sample from the posterior distribution
# of the parameters theta
sampleSize = 10000
sample = RWMHsampler.getSample(sampleSize)
```
I've got an error about the matching of the dimensions at the last line:

`InvalidArgumentException : Error: expected a parameters of dimension=1, got dimension=3 `

**Comment by regislebrun** [comment]
Hi,
It looks like there is a bug in the example: in the text, the function to calibrate is quadratic wrt the scalar variable x, and not linear wrt a 3D vector x.
Concerning your remark on the ParametricFunction class, we should have introduced a simplified constructor with no mention of the parameter values when they are not relevant. They are not "frozen", they are just *explicitely* initialized but can (and will) be changed at any time.
IMO this example should be rewritten from scratch, as it contains obvious bugs and some misleading statements. For example, it is not mandatory to use the ParametricFunction class to expose a parametric model. There is a parameter attribute in any Function, and you are free to use it in the definition of your function (eg in Python) directly. ParametricFunction is just a convenient way to partition the input of a Function into a vector of parameter and a vector of actual input.
Many thanks for your comments.
Cheers
Régis

    Le mercredi 22 mai 2019 à 14:55:23 UTC+2, M2CI-ONERA <notifications@github.com> a écrit :  
 
 
Hi,

I am not sure to understand the example presented in the Bayesian calibration of a computer code.
Indeed, in the presented example, the input data are of dimension 1:

x = ot.Sample(obsSize, covNum) for i in range(obsSize): x[i, 0] = -2 + 5. * i / 9.

but the considered compute code to calibrate is in dimension 3 in x (and has 3 parameters to be calibrated p1, p2 and p3):
fullModel = ot.SymbolicFunction(
    ['p1', 'p2', 'p3', 'x1', 'x2', 'x3'], ['p1*x1+p2*x2+p3*x3', '1.0'])# assume sigma=1 is known
# f:(x1, x2, x3)->(z) with parameters (p1, p2, p3)
model = ot.ParametricFunction(fullModel, list(range(paramDim)), [0.0]*paramDim)

this difference of dimension is not clear to me.

Secondly, in the ParametricFunction definition, the parameters are frozen but we are trying to calibrate these parameters therefore it is not clear why these parameters are frozen.

Thirdly, I do not understand why in the entire example the input data x is not used (only y_obs is used) in the calibration of the model parameters, but it succeed to provide the a-posteri distribution on the model parameters.

Finally, considering a slightly different problem, having a model to calibrate such that f(x,p) = p1 +p2x+p3x^2, but with the rest being exactly the same:
# Number of covariates
covNum = 1
# Dimension of the observations
obsDim = 1
# Dimension of the vector of parameters to calibrate
paramDim = 3
# The number of obesrvations
obsSize = 10

x = ot.Sample(obsSize, covNum)
for i in range(obsSize):
    x[i, 0] = -2 + 5. * i / 9.
x

y_obs = ot.Sample(obsSize, obsDim)
y_obs[0, 0] = -9.50794871493506
y_obs[1, 0] = -3.83296694500105
y_obs[2, 0] = -2.44545713047953
y_obs[3, 0] = 0.0803625289211318
y_obs[4, 0] = 1.01898069723583
y_obs[5, 0] = 0.661725805623086
y_obs[6, 0] = -1.57581204592385
y_obs[7, 0] = -2.95308465670895
y_obs[8, 0] = -8.8878164296758
y_obs[9, 0] = -13.0812290405651

p = ot.Sample(obsSize, paramDim)
for i in range(obsSize):
    for j in range(paramDim):
        p[i, j] = (-2 + 5. * i / 9.) ** j
        
fullModel = ot.SymbolicFunction(
    ['p1', 'p2', 'p3', 'x'], ['p1+p2*x+p3*x**2'])# assume sigma=1 is known
# f:(x)->(z) with parameters (p1, p2, p3)
model = ot.ParametricFunction(fullModel, [3], [0.0])

conditional = ot.Normal()
conditional

sigma0 = ot.Point(paramDim, 10.0)  # standard deviations
C0 = ot.CorrelationMatrix(paramDim)       # variance matrix
for i in range(paramDim):
    C0[i, i] = sigma0[i] * sigma0[i]

m0 = ot.Point(paramDim, 0.0)      # mean
prior = ot.Normal(m0, C0)
prior.setDescription(['p1', 'p2', 'p3'])
prior

# Additional inputs for the random walk Metropolis-Hastings
# sampler constructor:

# 1) Initial state: the prior mean
theta0 = prior.getMean()

# 2) Proposal distribution: uniform
proposal = [ot.Uniform(-1., 1.)] * paramDim

# Creation of the Random Walk Metropolis-Hastings (RWMH) sampler
RWMHsampler = ot.RandomWalkMetropolisHastings(
    prior, conditional, model, p, y_obs, theta0, proposal)

# Tuning of the RWMH algorithm:

# 1) Strategy of calibration for the random walk (trivial example: default)
strategy = ot.CalibrationStrategyCollection(paramDim)
RWMHsampler.setCalibrationStrategyPerComponent(strategy)

# 2) Other parameters
RWMHsampler.setVerbose(True)
RWMHsampler.setThinning(1)
RWMHsampler.setBurnIn(2000)

# Ready to generate a sample from the posterior distribution
# of the parameters theta
sampleSize = 10000
sample = RWMHsampler.getSample(sampleSize)

I've got an error about the matching of the dimensions at the last line:

InvalidArgumentException : Error: expected a parameters of dimension=1, got dimension=3

**Comment by mbaudin47** [comment]
The second issue Loïc mentions is clearer for me now. "Secondly, in the ParametricFunction definition, the parameters are frozen but we are trying to calibrate these parameters therefore it is not clear why these parameters are frozen."

This is because the objects we manipulate in OT are as close as possible to the maths. Hence, the model y|theta is implemented with a parametric function which input is x, with theta as a parameter. However, there is a bug in the example, where x and theta are switched. The reason of the bug in the example might by the following: the author may have think to the *implementation* in which the only variable which changes in the MCMC algorithm is theta. This, however, is a focus on one particular way of implementing the algorithm. The implementation in OT is clearer I think. 

I will propose an improved version of the algorithm as a PR.

**Comment by mbaudin47** [comment]
Ok. I see the error in Loic's example. 

Please look at the following Python re-implementation.

```
def MCMC_computeLogLikelihood(currentParameterValue,prior,conditional,model,parameters):
    obsSize = parameters.getSize()
    value = prior.computeLogPDF(currentParameterValue)
    for i in range(obsSize):
        model.setParameter(parameters[i])
        zi = model(currentParameterValue)
        pI = ot.Distribution(conditional)
        pI.setParameter(zi)
        logPdf = pI.computeLogPDF(y_obs[i])
        value += logPdf
    return value
```
As you can see, each row in the parameters sample is given as the argument of the "setParameter" method of the model. This means that the number of columns in the "parameters" argument of the Metropolis-Hastings algorithm must match the number of parameters of the model. Here you have three columns in the parameters but only one parameter in the model. The example is a mess: the actual parameters of this model are the inputs x.

The example I have here is good to go: i will create the PR within a few minutes (after that f***g proxy allows me to work).
