### ISSUE TITLE
The GaussianLinearCalibration implementation may be improved

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1146]
The GaussianNonLinearCalibration implementation is based on the Cholesky decomposition of the matrices R and B:

https://github.com/openturns/openturns/blob/58c5816da936fccc2c7c9984c8df5e231f016765/lib/src/Uncertainty/Bayesian/GaussianNonLinearCalibration.cxx#L336

This excellent implementation allows to express the convert the problem into a general non linear least squares problem based on a modified residual. This sounds excellent to me. 

The *simpler* linear case, however, does not use this trick, involving the direct inversion of the R and B matrices to compute the Kalman matrix

https://github.com/openturns/openturns/blob/58c5816da936fccc2c7c9984c8df5e231f016765/lib/src/Uncertainty/Bayesian/GaussianLinearCalibration.cxx#L137

This sounds a naive implementation and might be improved using the same Cholesky decomposition as in the nonlinear case. This should lead to a modified linear least squares problem with a modified residual, which may be solved using internal OT features, using e.g. the lower level LinearLeastSquaresCalibration class and the QR or SVD methods. 

This issue is not a bug: it is an enhancement proposal.

**Comment by mbaudin47** [comment]
I have the equations: I experiment with an Python draft.

**Comment by mbaudin47** [comment]
I have a Python draft for the estimator. I currently work on the covariance matrix.

**Comment by jschueller** [comment]
adressed in #1165
