### ISSUE TITLE
Fails to find cminpack

### ISSUE THREAD

**Issue by yurivict** [openturns/openturns#1148]
It is installed with these files:
```
cminpack-1.3.6:
        /usr/local/include/cminpack-1/cminpack.h
        /usr/local/include/cminpack-1/minpack.h
        /usr/local/lib/libcminpack_s.a
        /usr/local/libdata/pkgconfig/cminpack.pc
        /usr/local/share/cmake/CMinpack/CMinpackConfig.cmake
```
but OpenTURNS fails to find it.

Is this because it is a static library?

**Comment by yurivict** [comment]
Yes, I verified, it does find the shared library for cminpack. This is either a bug in ```cminpack``` or in your cmake scripts, can't tell.

**Comment by jschueller** [comment]
Indeed, I dont look for cminpack_s, I'll fix it.
What in the filename of the shared library ? Is is built with -fPIC ?

**Comment by yurivict** [comment]
It is ```libcminpack.so```.

I think you should use ```pkg-config``` to find it:
```
$ pkg-config --cflags cminpack
-I/usr/local/include/cminpack-1 
$ pkg-config --libs cminpack
-L/usr/local/lib -lcminpack -lm -l/usr/local/lib/libopenblas.so 
```

It is built with ```-fPIC```.

**Comment by jschueller** [comment]
The current code should find `libcminpack.so` what's the output of cmake with the shared lib ?

**Comment by yurivict** [comment]
It must be finding includes/libs, I didn't try.

I've created the FreeBSD port, but w/out the ```minpack``` library for now.
Will update it with the next release.

**Comment by jschueller** [comment]
Ok, cool, the 1.13 should happen next week.

**Comment by jschueller** [comment]
Where can I see it ? Can advertise it through my install page ? What's the command to install openturns in freebsd ?

**Comment by yurivict** [comment]
Sure:
* The announcement on FreshPorts https://www.freshports.org/math/openturns/
* The command to install is: ```pkg install openturns```

Please advertise it! Thank you!

**Comment by jschueller** [comment]
A few notes:
- the license is incorrect, it is LGPL3 not GPL3.
- openturns only uses boost headers at build-time, so boost-libs is probably uneeded
- you can drop the heavy R dependency, as it's only for drawing graphs the old fashion way these days, and you have already the matplotlib dependency that allows to generate much nicer graphs
- libmuparser.so can probably be dropped also as we embed exprtk now (it's not even used by default)

**Comment by yurivict** [comment]
> the license is incorrect, it is LGPL3 not GPL3.

But the ```COPYING``` file has GPL3: https://github.com/openturns/openturns/blob/master/COPYING

> openturns only uses boost headers at build-time, so boost-libs is probably uneeded

No, all boost is in one package, unfortunately, and ```BUILD_DEPENDS``` means that it is only present at the build-time, not at the run-time.

> you can drop the heavy R dependency

Ok, will do this.

> libmuparser.so can probably be dropped also

You should drop it from your cmake scripts, we usually follow what cmake looks for.




Thank you for your notes!

**Comment by jschueller** [comment]
see COPYING.LESSER for the license

**Comment by jschueller** [comment]
@yurivict numpy/scipy/nbconvert/chaospy should not be listed as build/runtime dependencies of openturns, they only enable aditional testing.
also 1.13 is out

**Comment by yurivict** [comment]
Thanks for letting me know!

I'll remove ```chaospy``` and will update te port.

**Comment by jschueller** [comment]
you can remove numpy, scipy, and nbconvert as well

**Comment by yurivict** [comment]
But CMakeLists.txt requires ```nbconvert```: https://github.com/openturns/openturns/blob/master/CMakeLists.txt#L490, and ```chaospy```: https://github.com/openturns/openturns/blob/master/CMakeLists.txt#L488

**Comment by jschueller** [comment]
Yes, as I said it is only for doc or aditionnal testing.
