### ISSUE TITLE
The description of Points can be set, but get is empty

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1155]
```
import openturns as ot
candidate = ot.Point([700,2500,8])
candidate.setDescription(["R", "C", "Gamma"])
print(candidate.getDescription())
```
prints:
```
[,,]
```
In other words, we can set the description of a Point, but the get method returns an list of empty strings.

**Comment by sofianehaddad** [comment]
Indeed. 
IMHO we should fix it quickly and drop the `PointWithDescription`
