### ISSUE TITLE
The (diagonal) conditionnal covariance of a kriging result might be computed faster.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1184]
In the case where we want to compute the prediction conditional variance of a kriging, we can use the `getConditionalCovariance` method. However, this method returns the full covariance matrix, while we generally only require its diagonal part. In order to compute the standard deviation of the diagonal, we can use the following Python statement:

    covGrid = result.getConditionalCovariance(x_test) 
    conditionalStDev = ot.Sample([np.sqrt(covGrid[i, i]) for i in range(n_test)],1)

where `x_test` is the sample of x inputs where we want to compute the conditional covariance.

An full example of this situation is given at :

https://github.com/mbaudin47/otsupgalilee-eleve/blob/master/6-krigeage/Exemple-krigeage-1D.ipynb

When the number of x points is large, this procedure fails either because the computation is too long or because it requires to much memory. 

The good news is that it is possible to compute only the diagonal, by looping over the points where the standard deviation is to be evaluated. For a given point x, the standard deviation can be computed by using the conditional covariance vector between all the data points and this particular x. This is what is done in Scikit-learn with the "return_std =True" option (thanks to Loic B. for finding this). 

The bad news is that this feature is not implemented in OT yet: this issue is not a bug, it is an enhancement request.

**Comment by mbaudin47** [comment]
As a workaround (before the feature can be provided by the KrigingAlgorithm class), maybe some advanced kriging user may provide a Python loop that does this job ?

**Comment by sofianehaddad** [comment]
@mbaudin47 I will provide one soon

**Comment by sofianehaddad** [comment]
@mbaudin47 in the following script https://gist.github.com/sofianehaddad/4db9447ca81c08a6b485f81daa27166b, we define the `getConditionalMarginalCovariance` function which returns a `n_test`-collection of `CovarianceMatrix`

With your use-case and `n_test = 10000`, it takes less than `0.5 s` on my laptop (and `13 s` with current implementation)

We have also in mind to implement `getConditionalMarginalVariance` : similar to the previous one if output dimension is one (different return type)

**Comment by mbaudin47** [comment]
This is very simple and does the job : many thanks !
