### ISSUE TITLE
computeProbability clamped by Domain-SmallVolume

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#1190]
And another issue is when I try to create a Truncated Normal distribution with following example, it won't work in version 1.12 or 1.13, only a Normal Distribution is successfully created; only version 1.10 can success create a Truncated Distribution. Thanks and please be advised. 

Try to create a Truncated distribution only works in version 1.10:
```
import openturns as ot
dist = ot.Normal(6.3E-19, 2.1E-19)             
dist = ot.TruncatedDistribution(dist, 4.2E-19, ot.TruncatedDistribution.LOWER)
```

cc @swimhiking

**Comment by jschueller** [comment]
It comes down to computeProbability returning 0:
```
import openturns as ot
dist = ot.Normal(6.3E-19, 2.1E-19)
dist.computeProbability(ot.Interval(4.2e-19,2.23663e-18))
```

Normal::computeProbability (and the computeProbability methods) uses ```if (interval.isNumericallyEmpty()) return 0.0;```
and Interval::isNumericallyEmpty uses a fixed value: Domain-SmallVolume=1e-12,
so if the range is <1e-12 computeProbability is always 0.

**Comment by swimhiking** [comment]
Thanks you.
