### ISSUE TITLE
There is no way to configure the calibration optimization solver

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1196]
In the current implementation, the NonLinearLeastSquaresCalibration class has a rule to automatically select to the solver. According to the doc, "if OpenTURNS was built with least squares optimization algorithms, then the algorithm used is the first found in GetLeastSquaresAlgorithmNames of OptimizationAlgorithm. Otherwise, the algorithm TNC is used combined with a multistart algorithm which makes use of the NonLinearLeastSquaresCalibration-MultiStartSize key in the ResourceMap."

This is was is currently coded in :

https://github.com/openturns/openturns/blob/1d239227325b14be172277101c630df621ad1fc2/lib/src/Uncertainty/Bayesian/NonLinearLeastSquaresCalibration.cxx#L70

This is a choice which is consistent with the fact that Cminpack (which is the default solver) succeeds in general. But what if this solver fails ? Actually, there is no way to configure the solver in the current interface. This is a pity, because it seems that little extra work could be done in order to solve that problem.

The following script works.
```
import numpy as np
import openturns as ot
ot.RandomGenerator.SetSeed(3)
m = 10
xobs = ot.Sample(np.linspace(-10,10,m),1)
inVars = ['a', 'b', 'g', 'x']
formulas = ['a/(1 + ((g - x)/b)^2)']
model = ot.SymbolicFunction(inVars, formulas)
p_ref = [2.8, 1.2, 0.5]
params = [0, 1, 2]
modelX = ot.ParametricFunction(model, params, p_ref)
sigma = 0.1
noise = ot.Normal(0.0, sigma).getSample(m)
yobs = modelX(xobs) + noise
candidate = [1.0,1.0,0.4]

# With default solver
algo = ot.NonLinearLeastSquaresCalibration(modelX, xobs, yobs, candidate)
algo.run()
pstar = algo.getResult().getParameterMAP()
print(pstar)
```

The following interface should do the required job.
```
# CERES setup
problem = ot.LeastSquaresProblem()
algo = ot.Ceres(problem, 'LEVENBERG_MARQUARDT')
algo = ot.NonLinearLeastSquaresCalibration(modelX, xobs, yobs, candidate, algo)
algo.run()
pstar = algo.getResult().getParameterMAP()
```

**Comment by jschueller** [comment]
see the setAlgorithm method

**Comment by mbaudin47** [comment]
Thank you Julien ! You are right ; I did not notice.

Below is a working example.
```
import numpy as np
import openturns as ot
ot.RandomGenerator.SetSeed(3)
m = 10
xobs = ot.Sample(np.linspace(-10,10,m),1)
inVars = ['a', 'b', 'g', 'x']
formulas = ['a/(1 + ((g - x)/b)^2)']
model = ot.SymbolicFunction(inVars, formulas)
p_ref = [2.8, 1.2, 0.5]
params = [0, 1, 2]
modelX = ot.ParametricFunction(model, params, p_ref)
sigma = 0.1
noise = ot.Normal(0.0, sigma).getSample(m)
yobs = modelX(xobs) + noise
candidate = [1.0,1.0,0.4]
# CERES setup
problem = ot.LeastSquaresProblem()
optimAlgo = ot.Ceres(problem, 'LEVENBERG_MARQUARDT')
calibAlgo = ot.NonLinearLeastSquaresCalibration(modelX, xobs, yobs, candidate)
calibAlgo.setAlgorithm(optimAlgo)
calibAlgo.run()
pstar = calibAlgo.getResult().getParameterMAP()
```
However, a more interesting application is to be able to use a multistart algorithm, given that least squares problems may have local optimums.
```
# 1. Generate points
distributionA = ot.Uniform(1.,3.)
distributionB = ot.Uniform(-3.,3.)
distributionC = ot.Uniform(0.,1.)
distrColl = ot.ComposedDistribution((distributionA,distributionB,distributionC))
size = 10
experiment = ot.MonteCarloExperiment(distrColl, size)
startingPoints = experiment.generate()
# 2. Configure the solver
problem = ot.LeastSquaresProblem()
optimAlgo = ot.CMinpack(problem)
MSoptimAlgo = ot.MultiStart(optimAlgo, startingPoints)
# 3. Calibrate
calibAlgo = ot.NonLinearLeastSquaresCalibration(modelX, xobs, yobs, candidate)
calibAlgo.setAlgorithm(MSoptimAlgo)
calibAlgo.run()
pstar = calibAlgo.getResult().getParameterMAP()
```
The previous script works with OT 1.13, but, according to:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.NonLinearLeastSquaresCalibration.html

the next release will provide the setOptimizationAlgorithm method instead.
