### ISSUE TITLE
LinearModelTest_LinearModelDurbinWatson does not take the firstSample into account in the actual Durbin-Watson test

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1199]
The OpenTURNS implementation of the [Durbin-Watson](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.LinearModelTest_LinearModelDurbinWatson.html) autocorrelation test for linear regression models is confusing.

Since this is an autocorrelation test, the order of the values in the `secondSample` should be specified. The `LinearModelTest_LinearModelDurbinWatson` class assumes that the `secondSample` (criterion variable) is already ordered (eg, a time series), but this is not intuitively clear. Given that the class constructor expects a `firstSample` (explanatory variable), users might assume that that the `secondSample` is reordered based on the `firstSample`. The `dwtest` function of the `R` package [lmtest](https://cran.r-project.org/web/packages/lmtest) behaves this way: the user can provide the vector containing the values of the explanatory variable as its `order.by` argument. 

Consider the following code:

```
import openturns as ot
import numpy as np

# Define the functional relationship between criterion and explanatory variables.
func = ot.SymbolicFunction('x', 'x^2')

# Define the values of the explanatory variable.
var = np.arange(-5,5).reshape(-1,1)

# Put the values of the explanatory variable in a Sample 
# and compute the corresponding values for the criterion variable.
firstSample = ot.Sample(var)
secondSample = func(firstSample)

# Shuffle both Samples the same way.
np.random.seed(1)
np.random.shuffle(var)
firstSample_shuffled = ot.Sample(var)
secondSample_shuffled = func(firstSample_shuffled)

# Test result for the original Samples.
print("Original order:")
print(firstSample)
test_result = ot.LinearModelTest.LinearModelDurbinWatson(firstSample, secondSample, 'Greater')
print("p-value: {}".format(test_result.getPValue()))

print(" ")

# Test result for the shuffled Samples.
print("Shuffled order:")
print(firstSample_shuffled)
test_result_shuffled = ot.LinearModelTest.LinearModelDurbinWatson(firstSample_shuffled, secondSample_shuffled, 'Greater')
print("p-value: {}".format(test_result_shuffled.getPValue()))
```

It yields the following output:

```
Original order:
0 : [ -5 ]
1 : [ -4 ]
2 : [ -3 ]
3 : [ -2 ]
4 : [ -1 ]
5 : [  0 ]
6 : [  1 ]
7 : [  2 ]
8 : [  3 ]
9 : [  4 ]
p-value: 0.9994420578119858
 
Shuffled order:
0 : [ -3 ]
1 : [  4 ]
2 : [  1 ]
3 : [ -1 ]
4 : [ -5 ]
5 : [ -2 ]
6 : [ -4 ]
7 : [  2 ]
8 : [  3 ]
9 : [  0 ]
p-value: 0.053982299495233185
```

If `LinearModelTest_LinearModelDurbinWatson` behaved like `dwtest`, both test results would be the same since `firstSample_shuffled` and `secondSample_shuffled` were shuffled the same way.

I feel that there are 2 possible ways to improve this:
 
- either state in the documentation that the `secondSample` is expected to be ordered
- or change the behavior of the class to make it resemble `dwtest`.

Of course, if there are more than one explanatory variable (ie if `firstSample` has dimension > 1), then no obvious order is available. In that case, users must manually define the order of both `firstSample` and `secondSample`.

**Comment by sofianehaddad** [comment]
Hi @josephmure 

The `lmtest` supposes indeed that `secondSample` is ordered but do not make any check. I can complete your code by using the R package :
```
from rpy2.robjects import Formula, r
from rpy2.robjects.numpy2ri import numpy2ri, ri2py
from rpy2.robjects.packages import importr                                
import openturns as ot
lmtest = importr('lmtest') 

formula = Formula('y ~ x')
x = numpy2ri(np.array(firstSample))
r.assign('x', x)

y = numpy2ri(np.array(secondSample))
r.assign('y', y)

dw_test = lmtest.dwtest(formula, alternative="less", exact=True)
print('Result from R (Original order) , p-value =', dw_test[3][0])

formula = Formula('y ~ x')
x = numpy2ri(np.array(firstSample_shuffled))
r.assign('x', x)

y = numpy2ri(np.array(secondSample_shuffled))
r.assign('y', y)

dw_test = lmtest.dwtest(formula, alternative="less", exact=True)
print('Result from R (Shuffled order) , p-value =', dw_test[3][0])
``` 

which returns : 
```
Result from R (Original order) , p-value = 0.9999956621146325
Result from R (Shuffled order) , p-value = 0.05245990105624021
```

IMHO we should reorder samples but I did not understand the issue with explanatory variable is of dim > 1. `firstSample` should be sorted according to `secondSample` ?

**Comment by josephmure** [comment]
Thanks for the quick answer @sofianehaddad . I had not fully understood the behavior of `lmtest`: as you said, it assumes `secondSample` is ordered without checking. 
But this is only its default behavior, when the `order.by`/`order_by` parameter (R and rpy2 formulation respectively) takes its default value `NULL`. 

If `firstSample` is specified as the `order.by` parameter, then `dwtest` does reorder `secondSample` based on `firstSample`.

Here is a modified version of your code. All I did was add `order_by=x` in the second call to `lmtest.dwtest`.

```
formula = Formula('y ~ x')
x = numpy2ri(np.array(firstSample))
r.assign('x', x)

y = numpy2ri(np.array(secondSample))
r.assign('y', y)

dw_test = lmtest.dwtest(formula, alternative="less", exact=True)
print('Result from R (Original order) , p-value =', dw_test[3][0])

formula = Formula('y ~ x')
x = numpy2ri(np.array(firstSample_shuffled))
r.assign('x', x)

y = numpy2ri(np.array(secondSample_shuffled))
r.assign('y', y)

dw_test = lmtest.dwtest(formula, alternative="less", exact=True, order_by=x)
print('Result from R (Shuffled order) , p-value =', dw_test[3][0])

```
This code returns:

```
Result from R (Original order) , p-value = 0.9999956621146325
Result from R (Shuffled order) , p-value = 0.9999956621146325
```

Concerning the part about a multidimensional `firstSample`, after thinking about it a bit more, I believe it makes little sense to conduct a Durbin-Watson test in such a case. Durbin-Watson is about detecting autocorrelation, which can only be defined for time series (or time series-like objects like spatial models with input dimension one). The source of my confusion was the [doc page](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.LinearModelTest_LinearModelDurbinWatson.html) making it seem like a multidimensional `firstSample` could be admitted by the constructor of `LinearModelTest_LinearModelDurbinWatson`.

Actually, trying to input a 2-dimensional `firstSample` causes an error:

```
var2 = np.arange(-10,10).reshape(10,2)
np.random.seed(1)
np.random.shuffle(var2)
firstSample2 = ot.Sample(var2)
secondSample2 = func(firstSample2.getMarginal(0))
test_result = ot.LinearModelTest.LinearModelDurbinWatson(firstSample2, secondSample2, 'Greater')
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
      4 firstSample2 = ot.Sample(var2)
      5 secondSample2 = func(firstSample2.getMarginal(0))
----> 6 test_result = ot.LinearModelTest.LinearModelDurbinWatson(firstSample2, secondSample2, 'Greater')

/.../lib/python3.7/site-packages/openturns/metamodel.py in LinearModelDurbinWatson(*args)
   6425 
   6426         """
-> 6427         return _metamodel.LinearModelTest_LinearModelDurbinWatson(*args)
   6428 
   6429     LinearModelDurbinWatson = staticmethod(LinearModelDurbinWatson)

RuntimeError: NotDefinedException : Error: the matrix is singular.
```

I think the doc should describe  `firstSample` as 

> First tested sample, of dimension 1.

`firstSample` is described that way in the doc pages of the homoscedasticity tests [LinearModelTest_LinearModelBreuschPagan](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.LinearModelTest_LinearModelBreuschPagan.html) and [LinearModelTest_LinearModelHarrisonMcCabe](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.LinearModelTest_LinearModelHarrisonMcCabe.html).

And the error message in case the user inputs a multidimensional `firstSample` should rather be something like

```
RuntimeError: NotDefinedException : Error: the conversion to Point is defined only for a sample of dimension=1, here dimension=2
```

**Comment by sofianehaddad** [comment]
@josephmure have a look at "Testing for serial correlation in least squares regression, II".
I don't think first sample should be only of dim 1

**Comment by sofianehaddad** [comment]
Maybe @adumasphi may have some suggestions on the issue

**Comment by josephmure** [comment]
> @josephmure have a look at "Testing for serial correlation in least squares regression, II".
> I don't think first sample should be only of dim 1

@sofianehaddad Thanks for the reference. I agree with you now, firstSample must be allowed to be multidimensional. In the paper, all examples are time series. The ordering variable (time) is distinct from the explanatory variables.

I believe that the best way to solve the issue is to introduce an order_by argument for the ordering variable. This is how `lmtest` does it, after all.
