### ISSUE TITLE
SpaceFillingMinDist documentation

### ISSUE THREAD

**Issue by mathieu-couplet** [openturns/openturns#1203]
Hello.

Apparently, this class performs a scaling (to get numbers between 0 and 1) along each marginal before computing the minimum (euclidean) distance: this scaling is not documented. This may lead to a wrong use of the class.

The fact that the computed distance is the euclidean one should be indicated.

Thanks,
regards,
Mathieu

**Comment by mbaudin47** [comment]
@mathieu-couplet : it seems to me that the code uses the `normalize` method of the sample:
https://github.com/openturns/openturns/blob/a9346d73f4f0b3353ce50e2c0726eaab9b37696b/lib/src/Uncertainty/Algorithm/WeightedExperiments/SpaceFillingMinDist.cxx#L62
This method does not seem to be available at the Python level, but is implemented here:
https://github.com/openturns/openturns/blob/1d239227325b14be172277101c630df621ad1fc2/lib/src/Uncertainty/Algorithm/WeightedExperiments/SpaceFillingImplementation.cxx#L69

The code is clear: only the min and the max of the sample are used to normalize it (not the distribution as I thought).
