### ISSUE TITLE
LinearModelStepwiseAlgorithm from otlm does not exist in OT

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1209]
According to the changes in the log :

https://github.com/openturns/openturns/blob/d15e64faef88e6647d8bc735f76bcb03a0b74819/ChangeLog#L77

new linear model features, which were previously available in otlm are now in OT, starting from 1.13. 

However, it seems that the 

https://github.com/openturns/otlm/blob/master/lib/src/LinearModelStepwiseAlgorithm.cxx

class does not belong to OT. 

I noticed that the otlm was not maintained anymore

http://trac.openturns.org/wiki/Modules?action=diff&version=62

which makes sense.

**Comment by sofianehaddad** [comment]
@mbaudin47 I have it in mind. First implementation (in OT) will be available soon.
