### ISSUE TITLE
We cannot define a Normal from a mean and a coefficient of variation

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1210]
The current Normal class allows to create a gaussian distribution, but not from a coefficient of variation.

**Comment by sofianehaddad** [comment]
Do you have a UC ?

**Comment by mbaudin47** [comment]
You are right, I should have written it.

```
# Parameters
mu = 12.
cv = 0.1
# Works
sigma = cv * mu
dist = ot.Normal(mu, sigma)
print(dist)
# Fails because NormalMuSigmaOverMu does not exist yet
parameters = ot.NormalMuSigmaOverMu(mu, cv)
dist = ot.ParametrizedDistribution(parameters)
print(dist)
```

**Comment by jschueller** [comment]
Maybe this is not worth adding a parametrization class just to avoid a division

**Comment by mbaudin47** [comment]
The goal is not to avoid a division. The purpose is to provide the interface that is as close as possible to the actual parametrization. For example, in fields such as chemistry or physical measurements, the coefficient of variation is widely used. In PERSALYS, this is the default parametrization with the gaussian distribution (with a CV equal to 0.1), but this is hidden to the user because this parametrization is not available. In other softwares, this parametrization is rarely available, because all other softwares cannot provide several parametrizations ; given that they can only provide one, the (mu,sigma) parametrization is used. OpenTURNS, however, *can* provide several parametrizations.

This feature, however would only be a slight advantage. This is why I close this issue until someone else feel this need with stronger motivations.
