### ISSUE TITLE
The legend of the graphics in MetaModelValidation is wrong

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1213]
The following script produces a polynomial chaos on the cantilever beam example.

```
# Chaos on cantilever beam
import openturns as ot

dist_E = ot.Beta(0.9, 3.1, 2.8e7, 4.8e7)
F_para = ot.LogNormalMuSigma(3.0e4, 9.0e3, 15.0e3) # in N
dist_F = ot.ParametrizedDistribution(F_para)
dist_L = ot.Uniform(250., 260.) # in cm
dist_I = ot.Beta(2.5, 4, 310., 450.) # in cm^4

myDistribution = ot.ComposedDistribution([dist_E, dist_F, dist_L, dist_I])

dim_input = 4 # dimension of the input
dim_output = 1 # dimension of the output

def function_beam(X):
    E, F, L, I = X
    Y = F* (L**3) /  (3 * E * I)
    return [Y]

g = ot.PythonFunction( dim_input, dim_output, function_beam)
g.setInputDescription(myDistribution.getDescription())

# ## Create a polynomial chaos decomposition
multivariateBasis = ot.OrthogonalProductPolynomialFactory([dist_E, dist_F, dist_L, dist_I])

# Generate an training sample 
inputTrain = myDistribution.getSample(50)
outputTrain = g(inputTrain)

# Chaos
selectionAlgorithm = ot.LeastSquaresMetaModelSelectionFactory()
projectionStrategy = ot.LeastSquaresStrategy(inputTrain, outputTrain, selectionAlgorithm)
totalDegree = 5
enumfunc = multivariateBasis.getEnumerateFunction()
P = enumfunc.getStrataCumulatedCardinal(totalDegree)
adaptiveStrategy = ot.FixedStrategy(multivariateBasis, P)

chaosalgo = ot.FunctionalChaosAlgorithm(inputTrain, outputTrain, myDistribution, adaptiveStrategy, projectionStrategy)
chaosalgo.run()

# Get the result
result = chaosalgo.getResult() # get the result
metamodel = result.getMetaModel() # get the metamodel

# ## Validate the metamodel
# Generate a validation sample (which is independent of the training sample).
inputTest = myDistribution.getSample(100)
outputTest = g(inputTest)

val = ot.MetaModelValidation(inputTest, outputTest, metamodel)

# Plot the observed versus the predicted outputs.
import openturns.viewer as otv
graph = val.drawValidation()
otv.View(graph)
```
![Metamodel-validation-bug](https://user-images.githubusercontent.com/31351465/64428856-0e5acb00-d0b5-11e9-8012-9b36db666df7.png)

The legend of this graphics is obviously wrong: the blue line is *not* the model and the red points are *not* the metamodel. This legend must be simply removed. 

Below is a fix, along with an enhancement which prints the Q2 coefficient in the title (the Q2 is available within the validation object):
```
graph = val.drawValidation()
Q2 = val.computePredictivityFactor()
graph.setTitle("Q2=%.2f%%" % (Q2*100))
graph.setLegends(["",""])
otv.View(graph)
```

![Metamodel-validation-fixed](https://user-images.githubusercontent.com/31351465/64429097-904af400-d0b5-11e9-96ee-31b5b26d7718.png)

My suggestion is that this should be the default setting.

**Comment by sofianehaddad** [comment]
Hi @mbaudin47 I am back on this issue.
I don't understand why do you want to remove the legend ? Blue line is the model (the given output) and red points are estimated with the provided metamodel

**Comment by mbaudin47** [comment]
Hi @sofianehaddad 
* "Blue line is the model": no. The blue line is just the diagonal. 
* "red points are estimated with the provided metamodel": no. The red points correspond to the validation sample. 

In fact, *each* red point has two coordinates: 
* the X-coordinate is the model value, 
* the-Y coordinate is the metamodel value. 

Hence, the legend is wrong. 

It would be appropriate to set a legend with e.g. two metamodels: the red points would be for metamodel #1 (e.g. polynomial chaos) while blue points would be for the metamodel #2. Here, there is just one single sample, so no legend is required.
