### ISSUE TITLE
There is no example with IntegrationStrategy on a database

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1214]
The current advanced chaos example:

http://openturns.github.io/openturns/master/examples/meta_modeling/functional_chaos_advanced_ctors.html

does not show how to create a chaos from integration on a database. 

Moreover, it does not show that other integration strategies such as Monte-Carlo, LHS or Low Discrepancy are available.

I have an example at hand, that I wish to share. I would assign this ticket to myself if I could.

**Comment by josephmure** [comment]
Did #1296 fix this?

**Comment by sofianehaddad** [comment]
See https://openturns.github.io/openturns/latest/auto_meta_modeling/polynomial_chaos_metamodel/plot_chaos_cantilever_beam_integration.html and https://openturns.github.io/openturns/latest/auto_meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_advanced_ctors.html

**Comment by mbaudin47** [comment]
> Did #1296 fix this?

No. I created an example using `GaussProductExperiment`, which is the most classical way of performing chaos with integration. However, it does not show how to create a chaos from integration and a Monte-Carlo or LHS or QMC design. Notice that this is possible, since the input argument of `IntegrationStrategy` is an `Experiment`. This is a very interesting property of the OpenTURNS library, which is very difficult to implement in other contexts with full generality. Hence, it highly deserves more than one example. For example, in addition to request mentioned in the title of this issue, we could show the convergence (or lack of convergence) on specific functions when the sample size increases : Ishigami would be a nice example, but g(x)=|x| or the g-Sobol' function would show something that is not shown in the library yet. Please feel free to pick the relevant part of the code at otbenchmark:

https://github.com/mbaudin47/otbenchmark/blob/master/otbenchmark/GSobolSensitivity.py

**Comment by josephmure** [comment]
I think I will let you handle this ;)

**Comment by mbaudin47** [comment]
The example I have is at:

https://github.com/mbaudin47/otsupgalilee-eleve/blob/master/5-Chaos/Exercice-chaos-cantilever-beam-Integration.ipynb

**Comment by mbaudin47** [comment]
This issue will be closed when PR #2081 is merged, because the required example is provided in python/doc/examples/meta_modeling/polynomial_chaos_metamodel/plot_chaos_cantilever_beam_integration.py.
