### ISSUE TITLE
The doc of the BasisFactory class has no example.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1218]
In the doc of the `BasisFactory` class:

http://openturns.github.io/openturns/master/user_manual/response_surface/_generated/openturns.BasisFactory.html

there is no example.

**Comment by josephmure** [comment]
I think `python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_beam_arbitrary_trend.py` a.k.a. "Configuring an arbitrary trend in Kriging" shows what you want. What do you think @mbaudin47 ?

**Comment by mbaudin47** [comment]
Not in my sense. My message highlights the fact that the API help page has no example. 

There are at least two different places for examples, each with a specific content.
* In my dreams, any API page has a minimal example showing the *minimum number of lines of codes* (the minimal working example) which creates the object and use its main methods. It focuses on the *software* and presents the input and output arguments of the class and its methods.
* On the other hand, examples in the "Examples" section shows how to *combine* several classes in order to create something meaningful in practice. This is a synthesis exercise. Such a page has interesting examples, which are relevant to the UQ methodology.

**Comment by mbaudin47** [comment]
Three examples may be created :
- create a basis with several functions, based on Symbolic or Python functions,
- create a basis from the several outputs of a multivariate function.

**Comment by josephmure** [comment]
The child classes of `Basis` have examples in their respective API pages, and this is enough.
