### ISSUE TITLE
There is no kriging example based on HMAT

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1222]
Up to my knowledge, there is no example in the doc which shows how to use the HMAT implementation in the kriging context. 

The only code we have is:

https://github.com/openturns/openturns/blob/82a8a95fa9e9a3d7cfb5bf40ea95d76b08c7d78c/python/test/t_HMatrix_std.py

Various options should be shown in an example, for example the "HMatrix-*" and "KrigingAlgorithm-LinearAlgebra" ResourceMap keys.

**Comment by mbaudin47** [comment]
@sofianehaddad : you seem to have practical examples to share - thank you very much for this.

**Comment by mbaudin47** [comment]
Below is the example you shared by mail.
```
import openturns as ot
import time

ot.ResourceMap.Set("GeneralLinearModelAlgorithm-DefaultOptimizationAlgorithm", "LD_LBFGS")
ot.ResourceMap.SetAsUnsignedInteger("OptimizationAlgorithm-DefaultMaximumIteration", 200)
ot.ResourceMap.SetAsScalar("GeneralLinearModelAlgorithm-DefaultOptimizationLowerBound", 1.0e-10) 
ot.ResourceMap.SetAsScalar("GeneralLinearModelAlgorithm-DefaultOptimizationUpperBound", 2.0)     

# Use HMat
ot.ResourceMap.SetAsString("KrigingAlgorithm-LinearAlgebra",  "HMAT")

# Parametrization of HMat
ot.ResourceMap.SetAsScalar("HMatrix-AssemblyEpsilon",  1e-6)
ot.ResourceMap.SetAsScalar( "HMatrix-RecompressionEpsilon",  1e-6)

# Example : reading in/out files (See Loic Le Gratiet UC)
InputSample = ot.Sample.ImportFromCSVFile('INPUT.dat', ';')
OutputSample = ot.Sample.ImportFromCSVFile('OUTPUT.dat', ';')

dim = InputSample.getDimension()
basis = ot.LinearBasisFactory(dim).build()
covarianceModel = ot.MaternModel([2.0]*dim, 2.5)
covarianceModel.setNu
algo = ot.KrigingAlgorithm(InputSample, OutputSample, covarianceModel, basis)

t1 = time.time()
algo.run()
print(time.time() - t1)
result = algo.getResult()
```

**Comment by mbaudin47** [comment]
@KieranDelamotte : Would you share the example you showed in the PRACE training.

**Comment by mbaudin47** [comment]
We should also show how to use the setsamplingmethod method of the GaussianProcess class:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.ConditionedGaussianProcess.html?highlight=setsamplingmethod#openturns.ConditionedGaussianProcess.setSamplingMethod

**Comment by mbaudin47** [comment]
A second example would be interesting to share in the sensitivity analysis context. Indeed, it is not rare to estimate the Sobol' sensitivity indices based on sampling a metamodel. In this situation, a large sample size with 10000 points is not rare, because this gives roughly 2 digits. However, using kriging with 10000 points generates a 10000x10000 matrix, which can make OT crash. HMAT may mitigate this. This is why such an example would be interesting.

**Comment by sofianehaddad** [comment]
@mbaudin47 I think you are wrong. There is no 10000x10000 matrix in such a case.

**Comment by sofianehaddad** [comment]
I added two notebooks in #1341 involving usage of HMatrix.
For the `setSamplingMethod`, the method is due to inheritance from `GaussianProcess` and it is impossible to remove it at this level (`GaussianConditionedProcess`). 
Current implementation is indeed useless and only warns user that method has no effects...

So I close this issue

**Comment by mbaudin47** [comment]
> @mbaudin47 I think you are wrong. There is no 10000x10000 matrix in such a case.

You are right. There is, however, a large matrix when we generate a realization of the conditioned gaussian process on a fine mesh. @KieranDelamotte will create such an example soon.

**Comment by regislebrun** [comment]
@mbaudin47 You may be disappointed to learn that there is *no* hmat implementation of the ConditionedGaussianProcess sampling method. One of your colleagues has already asked for this feature, and I spent some time thinking about it, but to now I didn't found a way to do it...

**Comment by mbaudin47** [comment]
Indeed, I *am* disappointed ;) May you suggest an example which may reveal the interest in using Hmat then?
