### ISSUE TITLE
Cannot save OpenTURNS objects

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1228]
Hi,

When one try to save an instance of an OpenTURNSPythonFunction with pure python attributes, it works perfectly well, but if there is at least one OpenTURNS attribute (such as a NumericalPoint or a Distribution) then it doesn't work, picckle is not able to serialize it.

Régis

Reference: http://trac.openturns.org/ticket/582

**Comment by mbaudin47** [comment]
Changed 7 years ago by regis.lebrun@…

    Attachment bug_save_python_function.py​ added

Script to show an example of an OpenTURNSPythonFunction with OpenTURNS attributes that cannot be saved :
```
from openturns import *

class FUNC(OpenTURNSPythonFunction):

    def __init__(self):
        OpenTURNSPythonFunction.__init__(self, 2, 1)
        self.setInputDescription( ['R','S'] )
        self.setOutputDescription( ['T'] )
        # Add a pure python attribute
        self.pyAttribute_ = [1, 2, 3]
        # Add an OT attribute
        self.otAttribute_ = Indices([1, 2, 3])
        
    def _exec(self, X):
        return [ X[0] + X[1] ]


myFunc = NumericalMathFunction( FUNC() )

st = Study()
fileName = 'PyNMF.xml'
st.setStorageManager( XMLStorageManager( fileName ) )

st.add( "F", myFunc )
st.save()
```

comment:1 Changed 7 years ago by schueller

    Type changed from defect to enhancement

None of OT objects were ever designed to implement the pickle protocol. I move the ticket to enhancement.
comment:2 Changed 6 years ago by schueller

    Milestone changed from openturns-1.2 to not defined
    Priority changed from major to minor
    Version changed from 1.1rc1 to 1.1

http://trac.openturns.org/changeset/3098
http://trac.openturns.org/changeset/3100

Should be ok for 1.2 release.
For now it assumes xml support.

Ivan's BinaryStorageManager would be more appropriate,
but I doubt I will get it in shape anytime soon.

J.
comment:3 Changed 5 years ago by schueller

    Summary changed from Cannot save an OpenTURNSPythonFunction if it has OT-typed attributes to Cannot save OpenTURNS objects

comment:4 Changed 5 years ago by schueller

Cannot save *Collection template objects:

```
from openturns import *
import pickle

obj = CopulaCollection([NormalCopula()])

with open('test.pkl','wb') as myFile:
    pickle.dump(obj, myFile)

loadedObj = pickle.load(open('test.pkl'))
```

comment:5 Changed 3 years ago by schueller

Idea: avoid dumping to disk for more performance
comment:6 Changed 3 years ago by michael.baudin@…

See Also http://trac.openturns.org/ticket/795

**Comment by josephmure** [comment]
I am unable to reproduce this very old bug. Maybe it is solved? What do you think @jschueller ?

**Comment by jschueller** [comment]
it got better thanks to dill

**Comment by josephmure** [comment]
Should we close this issue?

**Comment by mbaudin47** [comment]
I updated the script to OT 1.21. Here is the result. The first part is OK.

```python
import openturns as ot

# Part 1: OK


class FUNC(ot.OpenTURNSPythonFunction):
    def __init__(self):
        ot.OpenTURNSPythonFunction.__init__(self, 2, 1)
        self.setInputDescription(["R", "S"])
        self.setOutputDescription(["T"])
        # Add a pure python attribute
        self.pyAttribute_ = [1, 2, 3]
        # Add an OT attribute
        self.otAttribute_ = ot.Indices([1, 2, 3])

    def _exec(self, X):
        return [X[0] + X[1]]


myFunc = ot.Function(FUNC())

st = ot.Study()
fileName = "PyNMF.xml"
st.setStorageManager(ot.XMLStorageManager(fileName))

st.add("F", myFunc)
st.save()  # No problemo
```

The second part 2 fails:
```python
import openturns as ot
import pickle

obj = ot.ComposedCopula([ot.NormalCopula()])

with open("test.pkl", "wb") as myFile:
    pickle.dump(obj, myFile)

loadedObj = pickle.load(open("test.pkl"))  # Fails
```
The second script produces the exception:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
@josephmure : This means that we can keep that issue open, with the updated content.
