### ISSUE TITLE
Missing test case for BayesDistribution

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1233]
Reported by: | schueller

At least a python unit-test must be provided.

Reference: http://trac.openturns.org/ticket/776

**Comment by mbaudin47** [comment]
Changed 4 years ago by schueller
Owner changed from schueller to lebrun

Also add a test for DIstribution::maximum

comment:2 Changed 4 years ago by schueller

Last edited 3 years ago by schueller (previous) (diff)
comment:3 Changed 3 years ago by schueller

PenalizedLeastSquares, PosteriorDistribution either.

comment:4 Changed 2 years ago by schueller
Type changed from defect to enhancement

**Comment by jschueller** [comment]
d03ca3d1ff68d9d796d47f93a80eb70d4b7cd68b
