### ISSUE TITLE
Compatibility save/open studies with different OpenTURNS versions

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1235]
Reported by: | haddad

 Hi,

When saving meta models using OpenTURNS 1.3 (and probably older versions too) and trying to load them with OpenTURNS 1.4rc1, the compatibility is not assured because element's names changed, classes moved...

In the example given, the meta model is saved using OpenTURNS 1.3

We could try to load with OpenTURNS 1.4rc1 and we get the following error:
```
TypeError: InvalidArgumentException : No factory named 'PersistentCollection<UnsignedLong>' in Catalog
```

Sofiane

Reference: http://trac.openturns.org/ticket/728

**Comment by mbaudin47** [comment]
[meta_model.xml.txt](https://github.com/openturns/openturns/files/3617467/meta_model.xml.txt)
[create_metamodel.py.txt](https://github.com/openturns/openturns/files/3617469/create_metamodel.py.txt)
[load_metamodel.py.txt](https://github.com/openturns/openturns/files/3617470/load_metamodel.py.txt)

**Comment by mbaudin47** [comment]
Changed 5 years ago by haddad
Attachment meta_model.xml​ added

Meta model saved with ot 1.3

Changed 5 years ago by haddad
Attachment create_metamodel.py​ added

create model

Changed 5 years ago by haddad
Attachment load_metamodel.py​ added

Meta model loader
comment:1 Changed 5 years ago by haddad

Notice also that if one replaces "UnsignedLong" by "UnsignedInteger" in the xml file, other errors are mentionned, such as :
```
TypeError: InvalidArgumentException : No factory named 'NumericalMathEvaluationImplementationCache' in Catalog
```

Sofiane

comment:2 Changed 5 years ago by schueller
Type changed from defect to enhancement

comment:3 Changed 11 months ago by michael.baudin@…

If within a Study, several objects are loadable and other are not, then the loadable objects should be loaded, and the other ones should not.
comment:4 Changed 11 months ago by lebrun

Michael's proposal is implemented into ​https://github.com/openturns/openturns/pull/870

I can't see any reasonable way to cope with changes in type names, either simple types (UnsignedInteger/UnsignedLong) or complex types (Point/NumericalPoint). A missing factory is much more complex to catch than a failure within an existing factory.

Cheers

Régis

**Comment by jschueller** [comment]
wont fix, at least with the current rate of api changes
