### ISSUE TITLE
KrigingAlgorithm could not compute amplitude analytically with ProductCovarianceModel 

### ISSUE THREAD

**Issue by mathieu-couplet** [openturns/openturns#1247]
Hello.

I don't understand the result of the method mentioned in object in a particular case. See the script provided, please ([k.py.txt](https://github.com/openturns/openturns/files/3620051/k.py.txt)).
I don't known whether it is a bug or a doc issue.

There are two cases with univariate output and with different d-dimensional Matern models.
In the first case, the covariance is built by one call to MaternModel.
In the second case, the covariance is built as a product of d one-dimensional Matern covariances.
Why a parameter 'amplitude' is listed as an input parameter of the reduced likelihood in this second case?

Thanks.

**Comment by sofianehaddad** [comment]
@mathieu-couplet indeed it is a bug
