### ISSUE TITLE
computeStandardRepresentative of the covariance models

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1251]
The standard representative of a covariance model is the function
(\vect{s}, \vect{t}) --> \rho(\vect{s}, \vect{t}) that models the dependence between the process at index \vect{s} and the process at index \vect{s}.
In the current code source, the method computeStandardRepresentative(s,t) evaluates \rho(\frac{\vect{s}}{\theta}, \frac{
vect{t}}{\theta}) where \vect{\theta} is the scale vector of the process.
I propose that the method computeStandardRepresentative(s,t) evaluates \rho(\vect{s}, \vect{t})) and that the method be called with the scaled parameters when used.
The, it will be coherent with the documentation.

Linked to [http://trac.openturns.org/ticket/834](http://trac.openturns.org/ticket/834)

**Comment by josephmure** [comment]
Since `computeStandardRepresentative` was removed by @sofianehaddad's PR #1699, I think this issue is no longer relevant and can be closed.

**Comment by sofianehaddad** [comment]
Agreed

**Comment by jschueller** [comment]
it wasnt used anywhere ?

**Comment by sofianehaddad** [comment]
Now there is only a `computeStandardRepresentative` in `SpectralModel`. One day I will drop it ;-)
In cov models the method does not exist anymore
