### ISSUE TITLE
The diagonal of a scatter plot matrix should have the histograms

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1259]
The diagonal of a scatter plot matrix should have the histograms. Currently, when we use the Pairs class, only the (Xi,Xj) scatter plots for i different from j are printed. The diagonal could be used to print the histogram of Xi.

Linked to [http://trac.openturns.org/ticket/573](http://trac.openturns.org/ticket/573)

**Comment by mbaudin47** [comment]
A Python/OpenTURNS implementation of this in available in the MatrixPlot class from othdrplot:

https://github.com/mbaudin47/othdrplot
