### ISSUE TITLE
 RandomWalkMetropolisHastings does not handle non-symmetric proposals properly

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1260]
I can't see where the likelihood ratio accounts for non-symmetric proposals in the current implementation of the RandomWalkMetropolisHastings stepper.

Let me put the thing clearly: let L denote the likelihood, p the prior and q the proposal, xTry the candidate and xOld the seed. Then, the general expression for the likelihood ratio is as follows:
```
alpha = L(xTry) * p(xTry) * q(xOld|xTry) / (L(xOld) * p(xOld) * q(xTry|xOld))
```
This ratio simplifies to:
```
alpha = L(xTry) * p(xTry) / (L(xOld) * p(xOld))
```
but only in the case you have a symmetric proposal distribution q for which you have q(xOld|xTry) = q(xTry|xOld).

Since the RandomWalkMetropolisHastings always makes use of the second simplified expression, I would say there is a bug.

Linked to [http://trac.openturns.org/ticket/658](http://trac.openturns.org/ticket/658)

**Comment by jschueller** [comment]
cc @dubourg :)
