### ISSUE TITLE
ParetoFactory::buildMethodOfLeastSquares does not use the linear least squares

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1285]
The current implementation uses `LeastSquaresDistributionFactory`:

https://github.com/openturns/openturns/blob/23fecee7e9388cc09bee8e70417f37a7fbc6810a/lib/src/Uncertainty/Distribution/ParetoFactory.cxx#L90

It should make use of the log transformation of the survival function. 

I will handle this: please assign the issue to me.

**Comment by jschueller** [comment]
#1588
