### ISSUE TITLE
Add assert_equal

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#1326]
Add assertEqual in OTtestcode.hxx

**Comment by mbaudin47** [comment]
Please consider the code here as a sample implementation and a potential client:
https://github.com/openturns/openturns/blob/9ecc7cce7dd48d6ae2932b2a5eac5da22da56db3/lib/test/t_MarshallOlkinCopula_std.cxx#L40
https://github.com/openturns/openturns/blob/9ecc7cce7dd48d6ae2932b2a5eac5da22da56db3/lib/test/t_MarshallOlkinCopula_std.cxx#L46
https://github.com/openturns/openturns/blob/9ecc7cce7dd48d6ae2932b2a5eac5da22da56db3/lib/test/t_MarshallOlkinCopula_std.cxx#L52
https://github.com/openturns/openturns/blob/9ecc7cce7dd48d6ae2932b2a5eac5da22da56db3/lib/test/t_MarshallOlkinCopula_std.cxx#L61

**Comment by jschueller** [comment]
it does not makes much sense to compare one single value as ```assert x==4.5, "incorrect value"``` is shorter!
