### ISSUE TITLE
Cannot calibrate a function with unobserved inputs

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1327]
In this example, we calibrate the flooding model. We assume that there are true, but unknown, values of the parameters Q, Ks and DeltaZ. We also assume that we are given a sample of noisy observed river heights H, but no observed input. In other words, we assume that there is no input observation. 

```
# ## Generate the observations
import numpy as np
import openturns as ot
# We define the model $g$ which has 3 inputs and one output H.
# 
def functionFlooding(X) :
    L = 5.0e3
    B = 300.0
    Q, K_s, DeltaZ = X
    alpha = DeltaZ/L
    if alpha < 0.0 or K_s <= 0.0:
        H = np.inf
    else:
        H = (Q/(K_s*B*np.sqrt(alpha)))**(3.0/5.0)
    return [H]
g = ot.PythonFunction(3, 1, functionFlooding) 
g = ot.MemoizeFunction(g)
g.setOutputDescription(["H (m)"])
# Set the parameters to be calibrated.
Q = ot.Dirac(1013.0)
K_s = ot.Dirac(30.0)
DeltaZ = ot.Dirac(5.0)
# Create the joint input distribution.
inputRandomVector = ot.ComposedDistribution([Q, K_s, DeltaZ])
# Create a Monte-Carlo sample of the output H.
# This is a sample which contains a constant value.
nbobs = 100
inputSample = inputRandomVector.getSample(nbobs)
outputH = g(inputSample)
# Observe the distribution of the output H.
print(outputH[0:5])
# Generate the observation noise and add it to the output of the model.
sigmaObservationNoiseH = 0.1 # (m)
noiseH = ot.Normal(0.,sigmaObservationNoiseH)
sampleNoiseH = noiseH.getSample(nbobs)
Hobs = outputH + sampleNoiseH
# ## Setting the calibration parameters
# Define the value of the reference values of the $\theta$ parameter. 
QInitial = 1000.
KsInitial = 20.
DeltaZInitial = 2.
thetaPrior = ot.Point([QInitial,KsInitial,DeltaZInitial])
# The following statement create the calibrated function from the model.
calibratedIndices = [0,1,2]
mycf = ot.ParametricFunction(g, calibratedIndices, thetaPrior)
# Therefore, the calibrated function has no input and this is why we set an empty list as input argument.
mycf([])
# ## Calibration with linear least squares
# Since we have no input observation, we set the empty list `[]` as input.
algo = ot.LinearLeastSquaresCalibration(mycf, [], Hobs, thetaPrior, "SVD")
```

The previous script generates the following output:
```
TypeError: InvalidArgumentException : Error: expected a model of input dimension=1, got input dimension=0
```

The equations make clear the fact that the dependency to X is optional: only the dependency to theta is mandatory. 

The line which generates the exception is:

https://github.com/openturns/openturns/blob/e28c9eae3b145d3602f800cfacd1bc8d942219c8/lib/src/Uncertainty/Bayesian/LinearLeastSquaresCalibration.cxx#L57

This is consistent: the code requires that the dimension of the input sample matches the input dimension of the model. We are, however, in a situation were an empty input sample is provided.

I tried to create an empty sample with dimension 0:
```
inputObservations = ot.Sample([],0)
```
This kills the library!

So there are two bugs:
* the `Sample` class fails;
* the case where there is no observed input sample is not taken into account in the calibration classes.

My guess is that a new constructor should be provided, where there is no input sample:
```
LinearLeastSquaresCalibration(model, outputObservations, candidate, methodName)
```

**Comment by regislebrun** [comment]
According to the documentation:
[http://openturns.github.io/openturns/master/user_manual/_generated/openturns.LinearLeastSquaresCalibration.html](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.LinearLeastSquaresCalibration.html)
the second argument must be a 2D array of float of the same size as its third argument. Replace the line:
```
algo = ot.LinearLeastSquaresCalibration(mycf, [], Hobs, thetaPrior, "SVD")
```
by:
```
algo = ot.LinearLeastSquaresCalibration(mycf, [[]]*len(Hobs), Hobs, thetaPrior, "SVD")
```
and it works like a charm!
BTW, you use an *undocumented* constructor of `ot.Sample` which is *not* a part of its C++ API. It is pure crap and should be removed ASAP. I already mentioned it during the review of one of your PRs. Don't use it because the undocumented constructor Sample(1D array of float, UnsignedInteger) is very close to Sample(UnsignedInteger, 1D array of float) but has a very different meaning.
I agree with you: a new constructor should be introduced as the construction `[[]]*len(Hobs)` is quite obfuscated ;-)

**Comment by mbaudin47** [comment]
Ok: the trick is to create a input observation sample with dimension 0, with a size equal to the size of the output sample.

**Comment by jschueller** [comment]
Also, note that Sample(nobs, 0) works to build a sample of dimension 0, and may be more exlicit than `[[]]*len(Hobs)`
This being supported, except for GaussianNonLinearCalibration for which I provided a fix, I propose to close the issue.
