### ISSUE TITLE
NuggetFactor cannot be made active

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1330]
As discussed with @regislebrun and @mbaudin47 , there is a nugget factor-related  bug in covariance models: the nugget factor cannot be made active.

This bug exists even in version 1.14.

**Comment by sofianehaddad** [comment]
@josephmure what do you mean by "active" ?

**Comment by regislebrun** [comment]
He means: cannot be a part of the active parameters set. It is a discussion we had at the end of the last technical meeting: the user may want to estimate the nugget factor as well as the other parameters. I already have a branch fixing it, not yet pushed.

**Comment by regislebrun** [comment]
And technically it is not a bug (crash, wrong result) but a missing feature.

**Comment by josephmure** [comment]
At the technical committee meeting of December 9th 2019 @regislebrun argued that the NuggetFactor should be removed entirely. If I understand his argument correctly, instead of specifying the NuggetFactor as a parameter to a CovarianceModel, users should add a DiracCovarianceMode to their CovarianceModel.
Indeed, the amplitude parameter of a DiracCovarianceModel plays the same role as a NuggetFactor.

This idea is elegant, but after mulling it over, I have several objections: 

1.  It goes against established practice. In the literature, nugget effects are viewed as accessory to the "main" covariance model. Therefore, people familiar with the Gaussian Process model/Kriging literature would expect nugget factors to be called "nugget factors" in software. They would **not** expect to have to rebuild them through the algebra of covariance kernels.
2. In the current implementation, the NuggetFactor is not set to 0 by default but to 1e-12. 1e-12 is not the machine zero, so I guess it must have been chosen for the sake of numerical stability. If we remove the NuggetFactor parameter, we must either forfeit this advantage or make all covariance models have a hard-coded nugget factor of 1e-12, on top of which users will be able to define a DiracCovarianceModel with amplitude equal to their desired nugget factor value. 
3. Objective Bayesian methods like the reference prior rely on a knowledge of the structure of the model. More precisely, in the case of the reference prior, parameters need to be ordered (trend parameter low, amplitude higher, scales and nugget factor highest). If all parameters including the nugget factor are viewed as belonging to a single model, then this hierarchy can be implemented easily. This is not true for models mixing different kernels (except ProductCovarianceModels which are thoroughly studied in the literature). Given @jschueller has already implemented one Objective Bayesian technique, the [Gu method](https://github.com/jschueller/openturns/tree/gu) (soon to be made into a pull request), and that more are likely to be implemented in the future, this concern needs to be addressed if we really mean to go through with @regislebrun 's suggestion.
4. Use of nugget factors is very frequent. In fact, one could argue that the presence of a nugget factor should be assumed by default. It seems weird, therefore, to represent a standard Gaussian process model by something as sophisticated as a sum of covariance models in OpenTURNS.

However, taking all this into account, one could still imagine having nugget factors be represented by DiracCovarianceModel s "under the hood". The API, however, should in my opinion continue to rely on a NuggetFactor parameter.
