### ISSUE TITLE
FittingTest_BestModelBIC sometimes fail

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1331]
The following script:
```
import openturns as ot
true_dist = ot.Beta(0.9, 2., 3e7, 5e7)
data = true_dist.getSample(229)
tested_distributions = ot.DistributionFactory().GetContinuousUniVariateFactories()
dist, test_result = ot.FittingTest_BestModelBIC(data,tested_distributions)
```
produces:
```
RuntimeError: Error in function boost::math::tgamma<long double>(long double,long double): Series evaluation exceeded 1000000 iterations, giving up now.
```
with OT 1.14

**Comment by jschueller** [comment]
I cannot reproduce locally, what platform ? with the conda package ?

**Comment by sofianehaddad** [comment]
@jschueller I reproduce it with OT 1.14, using conda package  on osx

**Comment by jschueller** [comment]
something must have changed in recent boost then, as we're using 1.70 in conda

**Comment by sofianehaddad** [comment]
what about if we do not rely on `boost` ?

**Comment by jschueller** [comment]
I can reproduce with boost 1.70
without boost it builds a Chi with a huge nu: `Chi(nu = 1.33937e+15)`

**Comment by jschueller** [comment]
we are calling RegularizedIncompleteGammaInverse with `a=6.69687e+14`, `x=1e-14`, `tail=1`
and in turn `boost::math::gamma_q_inv(a, x)` fails

**Comment by mbaudin47** [comment]
Thank you very much!
