### ISSUE TITLE
Multi-objective optimization

### ISSUE THREAD

**Issue by nelinnemann** [openturns/openturns#1334]
Is there plan to have multi-objective optimization as part of openturns?
Going through the docs and code I cannot find any mention of it.

**Comment by jschueller** [comment]
hello,
yes, we talked about adding support for pagmo, which supports multi-objective
the question is structure of result in the context of uncertainties, just the points ? something more ?

**Comment by nelinnemann** [comment]
Hi, 

We use optimization to drive designs using CFD/FEA.
We build the objective "function" by combining the different software packages together.
This might be a lot of development and I do not know the roadmap of openturns, but you really have a quite comprehensible set of features already.

Gaussian assisted MOGA tend to use 50-60% less iterations as compared to regular MOGA's so there is great benefit in doing so.

Here is a Link to two R-based Gaussian assisted MOGA packages.
The first one has a MEGO implementation, very similar to your EGO just with multi objective.
http://www.scielo.br/pdf/lajss/v15n10/1679-7825-lajss-15-10-e74.pdf
https://github.com/mbinois/GPareto

Here are some examples of how Gaussian MOGA optimization is combined to drive CFD workflows.

https://hpc-forge.cineca.it/files/CoursesDev/public/2015/Workshop_HPC_enabling_of_OpenFOAM_for_CFD_applications/guerrero_unige.pdf
http://cerfacs.fr/~cfdbib/repository/TR_CFD_08_38.pdf
https://pdfs.semanticscholar.org/6b2a/92f74658a79a164fc449e37246c4467b931f.pdf

**Comment by jschueller** [comment]
thanks for the links

**Comment by jschueller** [comment]
we interfaced the pagmo solvers in the new version 1.19rc1
