### ISSUE TITLE
The "Estimate a probability with FORM" example is unclear

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1336]
In the following example:

http://openturns.github.io/openturns/master/examples/reliability_sensitivity/estimate_probability_form.html

the sentence: "where E_1 is the spheric univariate distribution of the standard space and \beta the reliability index." is unclear. 

* What does the "spheric univariate distribution" have to do with this? 
* What is that distribution? 
* Why do we care about this "mean point in the standard event space" which never comes up again in the notebook?

**Comment by adutfoy** [comment]
The PR is treated in #2749
