### ISSUE TITLE
The example in `UserDefined` does not show how to create a uniform discrete distribution

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1338]
The example in `UserDefined` does not show how to create a simple 1D uniform discrete distribution. The current example shows how to define a 2D discrete distribution, which is a little more complicated. 

However, this is possible, as shown by the following example. 
```python
import openturns as ot
points = [[i] for i in range(10)]
distribution = ot.UserDefined(points)  # By default, with equal weights.
for i in range(12):
    x = distribution.getRealization()
    print(i, x)
```
This prints:
```
0 [8]
1 [7]
2 [4]
3 [7]
4 [3]
5 [3]
6 [2]
7 [9]
8 [0]
9 [5]
10 [9]
11 [6]
```

**Comment by mbaudin47** [comment]
Below is a much simpler example.
```
points = ot.Sample([[1.0], [2.0], [3.0]])
weights = ot.Point([0.4, 0.5, 1.0])
my_distribution = ot.UserDefined(points, weights)
```

The `UserDefinedFactory` is also example-less:
```
sample = ot.Sample([2.0, 2.0, 1.0, 1.0, 2.0, 3.0, 1.0, 2.0, 2.0, 1.0], 1)
factory = ot.UserDefinedFactory()
distribution = factory.build(sample)
```

**Comment by regislebrun** [comment]
I find the constructor of Sample based on a list and an integer very error prone: if you reverse the order of the arguments you get something legal but completely different. BTW, this constructor exists only in the Python layer, which looks weird to me as it is not based on any Python-specific structure. Something has to be done here before to promote it through the examples.

**Comment by mbaudin47** [comment]
> I find the constructor of Sample based on a list and an integer very error prone.

I agree, but this is off-topic.

**Comment by mbaudin47** [comment]
The figure of the UserDefinedFactory is poor.

![image](https://user-images.githubusercontent.com/31351465/80349730-f3b9aa00-886f-11ea-81d3-318e69bf3096.png)

**Comment by mbaudin47** [comment]
The UserDefined class implements the idea of a joint discrete distributions. An application of a bivariate discrete distribution should be presented.

Examples of this:
* S.Ross, Introduction to probability and statistics for engineers and scientists. Third Ed. Examples 4.3a and 4.3b pages 97-99. The Ex. 4.3 describes the number of new and used batteries in a set. The Ex.4.3b describes the number of girls and boys in a family.
* W.Feller. "An introduction to probability theory and its applications", Volume I, 3d edition. Example (a), p.215. The variables are the number of occupied cells and the number of balls in the first cell when 3 balls are distributed randomly in 3 cells.
* A.H.S. Ang and W.H.Tang, "Probability concepts in engineering planning and design", Volume I, Basic principles. Example 3.24, p.135. Variables are the duration (Hours) and productivity of labor (%).
