### ISSUE TITLE
Problem in the graph of Histogram

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#1349]
Helle,
When I draw the PDF graph of a Histogram, it changes according to the interval where I draw it!
```
from openturns import *
from openturns.viewer import View

# First case
ticks = [1.0, 2.0, 3.0, 4.0]
freq = [0.2, 0.3, 0.5]
h=Histogram(ticks, freq)

# Reference graph
g=h.drawPDF(0.0, 5.0, 101)
g.setTitle('drawPDF(0.0, 5.0, 101)')
view = View(g)
view.show()

# No problem here
g=h.drawPDF(0.5, 5.0, 101)
g.setTitle('drawPDF(0.5, 5.0, 101)')
view = View(g)
view.show()

# Big problem here!
g=h.drawPDF(1.5, 5.0, 101)
g.setTitle('drawPDF(1.5, 5.0, 101)')
view = View(g)
view.show()

# Second case
# Reference graph
freq = [0,0,0,0,1.55224,2.76647,0.664671,0.318612,0.105516,0.0464217,0.00580271,0.00386847,0,0,0]
ticks =  [1, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5]
h=Histogram(ticks, freq)
g=h.drawPDF(0.0, 7.0, 101)
g.setTitle('drawPDF(0.0, 7.0, 101)')
view = View(g)
view.show()

# Big problem here!
g=h.drawPDF(2.0, 7.0, 101)
g.setTitle('drawPDF(2.0, 7.0, 101)')
view = View(g)
view.show()

# Big problem here!
g=h.drawPDF(2.5, 7.0, 101)
g.setTitle('drawPDF(2.5, 7.0, 101)')
view = View(g)
view.show()

# Big problem here!
g=h.drawPDF(3.8, 7.0, 101)
g.setTitle('drawPDF(3.8, 7.0, 101)')
view = View(g)
view.show()
```
case 1:
![a](https://user-images.githubusercontent.com/3832365/72518208-1b52ac80-3855-11ea-80d1-85aaef5fb7b8.png)
![c](https://user-images.githubusercontent.com/3832365/72518251-31f90380-3855-11ea-91d7-0b067a4e7f8e.png)
case 2:
![a](https://user-images.githubusercontent.com/3832365/72523581-6aeaa580-3860-11ea-8b1a-70ece6e4ce5b.png)
![a](https://user-images.githubusercontent.com/3832365/72523652-89e93780-3860-11ea-859e-3817cd55ccc7.png)
![a](https://user-images.githubusercontent.com/3832365/72523680-9bcada80-3860-11ea-8797-8ac233af6d81.png)
![a](https://user-images.githubusercontent.com/3832365/72523723-b1400480-3860-11ea-9339-309aae09effa.png)

**Comment by adutfoy** [comment]
I closed it by mistake....

**Comment by adutfoy** [comment]
No problem with the CDF graph...

**Comment by mbaudin47** [comment]
This sounds interesting, but I suggest to add the pictures of the graphics in the issue to make it clearer : the current issue is rather implicit at this point.
