### ISSUE TITLE
Feature: Add global counter to functions

### ISSUE THREAD

**Issue by nelinnemann** [openturns/openturns#1362]
Adding a counter to the function either seriel or parallel would help immensely in housekeeping.

Doing simulations outside openturns there is a lot of housekeeping to get things running.

Adding an accessible global counter in the function would be of great help.

This is not a problem using serial runs but using the parallel runs it needs to be implemented in the calls to the multiprocessing code.

**Comment by jschueller** [comment]
Did you look at `Function.getEvaluationCallsNumber` ?

**Comment by nelinnemann** [comment]
Yes, it always just prints the same number.

I recon that this is since the call to Function.getEvaluationCallsNumber happens outside the function loop and this will just show the number og the amount of samples you have set.
I see no way to pass the function to itself so that you can run it inside the function.

`import openturns as ot
import math as m


# define a pure Python function from R^3 to R^2
def regularFunc(X):
    x0, x1, x2 = X
    y0 = x0 + x1 + x2
    y1 = (x1 - 1.0) * m.exp(x0) * x2
    return [y0, y1]


# create a Function object from a regular Python function
function = ot.PythonFunction(3, 2, regularFunc, n_cpus=2)
print('Number of calls =', function.getEvaluationCallsNumber())

# evaluate the function on a Point
x = [1.0, 2.0, 3.0]
print('x=', x, 'f(x)=', function(x))
print('Number of calls =', function.getEvaluationCallsNumber())

xs = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0],[6.0, 7.0, 8.0]]
print('xs=', xs, '\nf(xs)=', function(xs))

print('Number of calls =', function.getEvaluationCallsNumber())`

Also I see no setting of that parameter from the function call.

**Comment by jschueller** [comment]
You can define a counter inside the function, or even pass the PythonFunction to regularFunc via an attribute:
```
def regularFunc(X):
   ...:     if not hasattr(regularFunc, 'count'):
   ...:         regularFunc.count = 0
   ...:     x0, x1, x2 = X
   ...:     y0 = x0 + x1 + x2
   ...:     y1 = (x1 - 1.0) * m.exp(x0) * x2
   ...:     regularFunc.count +=1
   ...:     print('count=', regularFunc.count)
   ...:     print('evals=', regularFunc.function.getEvaluationCallsNumber())
   ...:     return [y0, y1]
   ...: 
   ...: 
   ...: # create a Function object from a regular Python function
   ...: function = ot.PythonFunction(3, 2, regularFunc, n_cpus=2)
   ...: regularFunc.function = function
```


I close the issue as this is not in the scope of openturns.

**Comment by nelinnemann** [comment]
Always good to learn something new, unfortunately your solution will not give correct output.

```
import openturns as ot
import math as m


# define a pure Python function from R^3 to R^2
def regularFunc(X):
    if not hasattr(regularFunc, 'count'):
         regularFunc.count = 0
    x0, x1, x2 = X
    y0 = x0 + x1 + x2
    y1 = (x1 - 1.0) * m.exp(x0) * x2
    regularFunc.count +=1
    print('count=', regularFunc.count)
    print('evals=', regularFunc.function.getEvaluationCallsNumber())
    return [y0, y1]


# create a Function object from a regular Python function
function = ot.PythonFunction(3, 2, regularFunc, n_cpus=4)
regularFunc.function = function

# evaluate the function on a Point
x = [1.0, 2.0, 3.0]
function(x)

xs = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0],[6.0, 7.0, 8.0],[6.0, 7.0, 8.0],[6.0, 7.0, 8.0],[6.0, 7.0, 8.0],[6.0, 7.0, 8.0],[6.0, 7.0, 8.0]]
function(xs)
```
```
count= 1
evals= 1
count= 2
count= 2
evals= 9
evals= 9
count= 2
evals= 9
count= 3
evals= 9
count= 2
evals= 9
count= 3
evals= 9
count= 3
count= 4
evals= 9
evals= 9
```

I understand that this is maybe outside of scope of openturns. To do it properly it needs to be implemented in the multiprocessing code with thread-locks to that the variable cannot be accessed multiple places at the same time.

**Comment by mbaudin47** [comment]
Here is the output of the script:
```
>>> import openturns as ot
>>> import math as m
>>> 
>>> 
>>> # define a pure Python function from R^3 to R^2
... def regularFunc(X):
...     x0, x1, x2 = X
...     y0 = x0 + x1 + x2
...     y1 = (x1 - 1.0) * m.exp(x0) * x2
...     return [y0, y1]
... 
>>> 
>>> # create a Function object from a regular Python function
... function = ot.PythonFunction(3, 2, regularFunc, n_cpus=2)
>>> print('Number of calls =', function.getEvaluationCallsNumber())
Number of calls = 0
>>> 
>>> # evaluate the function on a Point
... x = [1.0, 2.0, 3.0]
>>> print('x=', x, 'f(x)=', function(x))
x= [1.0, 2.0, 3.0] f(x)= [6,8.15485]
>>> print('Number of calls =', function.getEvaluationCallsNumber())
Number of calls = 1
>>> 
>>> xs = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0],[6.0, 7.0, 8.0]]
>>> print('xs=', xs, '\nf(xs)=', function(xs))
xs= [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [6.0, 7.0, 8.0]] 
f(xs)=     [ y0          y1          ]
0 : [     6           8.15485 ]
1 : [    15        1310.36    ]
2 : [    21       19364.6     ]
>>> 
>>> print('Number of calls =', function.getEvaluationCallsNumber())
Number of calls = 4
```
The `getEvaluationCallsNumber` method works fine in my case.
