### ISSUE TITLE
Memory leak in ot.TruncatedDistribution

### ISSUE THREAD

**Issue by captain-facepalm** [openturns/openturns#1371]
I think I found a memory leak in ot.TruncatedDistribution.  I am using OT 1.14 from conda forge with Python 3.7.6. When I compare the memory use of ot.Normal and ot.TruncatedDistribution I see the values as given in the table. ot.Normal's memory use is more like minor noise, ot.TruncatedDistribution blows up in memory. I do not store any objects created by OT in Python.

I also include a close to minimum working example.

| repetitions  | ot.Normal | ot.TruncatedDistribution |
| ------------- | ------------- | ------------- |
| 10**5  | 0.3618 MiB  | 19.55 MiB  |
| 2*10**5  | 0.016 MiB  | 38.16 MiB  |
| 5*10**5  | 0.0 MiB  | 95.37 MiB  |
| 8*10**5  | 0.0 MiB  | 152.59 MiB  |
| 10**6  | 0.0 MiB  | 190.7 3 MiB |

```
#Demontrate a memory leak in OpenTURNS when using ot.TruncatedDistribution
import os
import psutil
import openturns as ot

def no_leak(iters, process):
    start_mem = process.memory_info()[0] / (8 * 1024**2)
    for i in range(iters):
        ot.Normal()
    no_leak_mem = process.memory_info()[0] / (8 * 1024**2)
    return start_mem, no_leak_mem

def mem_leak(iters, process):
    norm = ot.Normal()
    for i in range(iters):
        ot.TruncatedDistribution(norm, 0., 10.)
    return process.memory_info()[0] / (8 * 1024**2)

if __name__ == "__main__":
    pid = os.getpid()
    print("pid", pid)
    process = psutil.Process(pid)
    start_mem = []; no_leak_mem = []; leak_mem =[]; 
    iterations = [10**5, 2*10**5, 5*10**5, 8*10**5, 10**6]
    
    for i, iters in enumerate(iterations):
        sm, nlm = no_leak(iters, process)
        start_mem.append(sm)
        no_leak_mem.append(nlm)

        leak_mem.append(mem_leak(iters, process))
    
print("memory use in MiB")
print("repetitions\t\tot.Normal\tot.TruncatedDistribution")
for iters, sm, nlm, lm in zip(iterations, start_mem, no_leak_mem, leak_mem):
    print(iters, "\t\t", nlm-sm, "\t", lm-sm)
```

**Comment by jschueller** [comment]
confirmed, the interface typemap is leaking:
https://github.com/openturns/openturns/blob/master/python/src/TypedInterfaceObject.i#L23
