### ISSUE TITLE
The PlotDesign class has no example

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1375]
The current documentation of the PlotDesign module has no graphics:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.viewer.PlotDesign.html

It would be interesting to show the result of the class in graphics terms:

![LHS](https://user-images.githubusercontent.com/31351465/74536861-35a5a600-4f39-11ea-9126-c3826540ee19.png)

**Comment by mbaudin47** [comment]
I have a branch that fixes that bug: 

https://github.com/mbaudin47/openturns/blob/FixDocForExamples/python/doc/examples/reliability_sensitivity/plot_design.ipynb

Moreover, I added a graphical example of the LHS and Sobol' experiments: 

https://github.com/mbaudin47/openturns/blob/FixDocForExamples/python/doc/examples/reliability_sensitivity/design_of_experiments.ipynb

**Comment by mbaudin47** [comment]
This was fixed in #1400.

**Comment by mbaudin47** [comment]
Oups : the PlotDesign still has no graphics:

http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.viewer.PlotDesign.html

**Comment by mbaudin47** [comment]
See also #1070

**Comment by sofianehaddad** [comment]
it was fixed http://openturns.github.io/openturns/master/user_manual/_generated/openturns.viewer.PlotDesign.html
