### ISSUE TITLE
The View class has no example

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1376]
The View class has no example:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.viewer.View.html

The smallest possible example shows how to save a figure into a file, which shows how to use the `save` method:

```
import openturns as ot
import openturns.viewer as otv
n = ot.Normal()
graph = n.drawPDF()
view = otv.View(graph)
view.save("normal.png")
```

**Comment by mbaudin47** [comment]
Another useful example is useful to configure the size of the graphics.

```
view = otv.View(graph, figure_kwargs = {"figsize": (12, 8)})
```

**Comment by mbaudin47** [comment]
I currently have a branch to fix this : https://github.com/mbaudin47/openturns/commit/e0f481c63cb590474012931e6e15f26a725967a7

**Comment by sofianehaddad** [comment]
@mbaudin47 ok thus ticket is for you :-)
