### ISSUE TITLE
The ExprTk engine for SymbolicFunction does not document the "var" keyword.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1383]
The ExprTk engine supports the "var" keyword, but its usage is undocumented.

Below is an example.
```
inputs = ['Q', 'Ks', 'Zv', 'Zm', 'Hd', 'Zb', 'L', 'B']
outputs = ['H', 'S']
formula = 'var alpha := (Zm - Zv)/L; H := (Q/(Ks*B*sqrt(alpha)))^(3.0/5.0); var Zc := H + Zv; var Zd := Zb + Hd; S := Zc - Zd'
myFunction = ot.SymbolicFunction(inputs, outputs, formula)
X = [1013.0, 30.0, 50.0, 55.0, 8, 55.5, 5000, 300]
print(myFunction(X))
```

**Comment by mbaudin47** [comment]
Fixed in a development branch at bdccd000bd4e7624f9513980e1fedc4cef1375c9

**Comment by ArashPartow** [comment]
The **var** keyword  has been documented for nearly two decades:  

SECTION 13 - VARIABLE, VECTOR & STRING DEFINITION

https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L1575

**Comment by jschueller** [comment]
@ArashPartow the issue was on our side
