### ISSUE TITLE
The ExprTk engine is not case-sensitive

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1384]
The ExprTk engine is not case-sensitive, which can produce errors. 
```
inputsvars=["D","d"]
formula = ["D-d"]
g = ot.SymbolicFunction(inputsvars,formula)
```
An exception should be generated in the case where two input variables cannot be distinguished by the evaluation engine.

**Comment by regislebrun** [comment]
The question has been asked [here](https://stackoverflow.com/questions/39168895/are-variables-case-sensitive-in-exprtk) and the fix is pretty obvious.

**Comment by mbaudin47** [comment]
Indeed : "Just include #define exprtk_disable_caseinsensitivity and you are good to go!"

**Comment by mbaudin47** [comment]
Here is a failing test.
```
import openturns as ot
inputsvars=["D", "d"]
formula = ["1 / (D - d)"]
g = ot.SymbolicFunction(inputsvars, formula)
X = [1.0, 0.8]
g(X)
```
generates:
```
RuntimeError: InternalException : Cannot evaluate 1 / (D - d) at [D,d]=[1,0.8]
```
