### ISSUE TITLE
The PythonDistribution does not manage computeLogPDF with a Sample

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1391]
In the simplified example I want to create, I consider a `Sample` that I want to fit with a `Mixture` of two `Normal` distributions. Then I want to estimate its parameters. I use the `MaximumLikelihoodFactory` class. However, this class performs repeated calls to the `computeLogPDF` method, which makes its speed crucial. 

The point is that the `computeLogPDF` method does not evaluate the log-PDF of the `Sample`, but loops over the `Point`s inside the `Sample`. Hence one single evaluation of the log-PDF requires n evaluations of the `computeLogPDF` method, where n is the sample size. This makes the performance of the algorithm poor. 

Here is a minimal example.

I first create a `Sample`.

```Python
import openturns as ot
collDist = [ot.Normal(-3.0, 1.0), ot.Normal(7.0, 2.0)]
weight = [0.5, 2.0]
mixture = ot.Mixture(collDist, weight)
mixture.drawPDF()
sample = mixture.getSample(10)
```

The following `GaussianMixture` class implements a basic "otmixmod". 

```Python
class GaussianMixture(ot.PythonDistribution):
    def __init__(self, mu1 = -5.0, sigma1 = 1.0,\
                 mu2 = 5.0, sigma2 = 1.0, \
                 w1 = 1.0, w2 = 1.0):
        super(GaussianMixture, self).__init__(1)
        self.mu1 = mu2
        self.sigma1 = sigma1
        self.mu2 = mu2
        self.sigma2 = sigma2
        self.w1 = w1
        self.w2 = w2
        collDist = [ot.Normal(mu1, sigma1), ot.Normal(mu2, sigma2)]
        weight = [w1, w2]
        self.distribution = ot.Mixture(collDist, weight)

    def computeCDF(self, x):
        p = self.distribution.computeCDF(x)
        return p

    def computePDF(self, x):
        p = self.distribution.computePDF(x)
        return p

    def computeQuantile(self, prob, tail = False):
        quantile = self.distribution.computeQuantile(prob, tail)
        return quantile

    def getSample(self, size):
        X = self.distribution.getSample(size)
        return X

    def getParameter(self):
        parameter = ot.Point([self.mu1, self.sigma1, \
                              self.mu2, self.sigma2,\
                              self.w1, self.w2])
        return parameter

    def setParameter(self, parameter):
        [mu1, sigma1, mu2, sigma2, w1, w2] = parameter
        # Set the parameters
        self.mu1 = mu1
        self.sigma1 = sigma1
        self.mu2 = mu2
        self.sigma2 = sigma2
        self.w1 = w1
        self.w2 = w2
        # Create the mixture
        collDist = [ot.Normal(mu1, sigma1), ot.Normal(mu2, sigma2)]
        weight = [w1, w2]
        self.distribution = ot.Mixture(collDist, weight)
        return parameter

    def computeLogPDF(self, sample):
        parametersStr = "mu1 = %f, sigma1 = %f, mu2 = %f, sigma2 = %f, w1 = %f, w2 = %f"
        formatStr = "GaussianMixture(" + parametersStr + ")"
        objectStr = formatStr % (self.mu1, self.sigma1, \
                                 self.mu2, self.sigma2, \
                                 self.w1, self.w2)
        print(objectStr)
        logpdf = self.distribution.computeLogPDF(sample)
        return logpdf
```

The following code creates a gaussian mixture and then evaluates the log-PDF.

```Python
gm = ot.Distribution(GaussianMixture())
gm.computeLogPDF(sample)
```

The previous script prints 10 messages like the following:

```
GaussianMixture(mu1 = -5.000000, sigma1 = 1.000000, mu2 = 5.000000, sigma2 = 1.000000, w1 = 1.000000, w2 = 1.000000)
...
```

If the `Sample` was provided, one single message would be printed.

**Comment by mbaudin47** [comment]
The problem seems to be in:

https://github.com/openturns/openturns/blob/8eabdf99702a96e4bcfd2ccaeb04cc8620aa9208/python/src/PythonDistribution.cxx#L247

which manages a `Point`. No support for `Sample` is provided. This may be impossible because the Python layer does not allow to distinguish between a `Point` and a `Sample` ?

**Comment by josephmure** [comment]
Isn't there a way to write the C++ class in such a way that it can guess the type of the argument supplied by Python and call the `PythonDistribution::computeLogPDF` with the appropriate prototype? My knowledge of C++ is too limited to answer that question, but maybe [this StackExchange answer](https://stackoverflow.com/a/48085486) can help?

Otherwise, I wonder if the solution is not simply to rewrite it as:

```
 Sample PythonDistribution::computeLogPDF(const Sample & inS) const 
```

After all, you can always write a `Point` as a `Sample` with size 1 and then extract the `Scalar` you expect from the output `Sample`.

**Comment by mbaudin47** [comment]
Working again on this topic, I think that my analysis is wrong. Here is a benchmark, where I evaluate the log-PDF on a sample with size equal to 100 000.
```Python
import openturns as ot
import time

class GaussianMixture(ot.PythonDistribution):
    def __init__(self, mu1 = -5.0, sigma1 = 1.0,\
                 mu2 = 5.0, sigma2 = 1.0, \
                 w1 = 1.0, w2 = 1.0):
        super(GaussianMixture, self).__init__(1)
        collDist = [ot.Normal(mu1, sigma1), ot.Normal(mu2, sigma2)]
        weight = [w1, w2]
        self.distribution = ot.Mixture(collDist, weight)

    def computeCDF(self, x):
        p = self.distribution.computeCDF(x)
        return p

    def computeLogPDF(self, sample):
        logpdf = self.distribution.computeLogPDF(sample)
        return logpdf
    
collDist = [ot.Normal(-3.0, 1.0), ot.Normal(7.0, 2.0)]
weight = [0.5, 2.0]
mixture = ot.Mixture(collDist, weight)
mixture.drawPDF()
sample_size = 100000
sample = mixture.getSample(sample_size)

gm = ot.Distribution(GaussianMixture())
t1 = time.time()
gm.computeLogPDF(sample)
t2 = time.time()
print("Elapsed = ", t2 - t1, "(s)")
```
This requires 0.18 (s). This is a fast result. This is why I tag this bug as invalid.

**Comment by sofianehaddad** [comment]
Hi,

The python does not allow to distinguish between `Point`/`Sample` arguments. However we might change the rules and implement specific `Sample` methods (for example `computePDFSample`/`computeLogPDFSample`...). These methods need to be wrapped in `PythonDistribution` and call the specific python code (if exists)

For example, if with the previous use-case,

```pytthon
import openturns as ot
import time

class GaussianMixture(ot.PythonDistribution):
    def __init__(self, mu1 = -5.0, sigma1 = 1.0,\
                 mu2 = 5.0, sigma2 = 1.0, \
                 w1 = 1.0, w2 = 1.0):
        super(GaussianMixture, self).__init__(1)
        collDist = [ot.Normal(mu1, sigma1), ot.Normal(mu2, sigma2)]
        weight = [w1, w2]
        self.distribution = ot.Mixture(collDist, weight)

    def computeCDF(self, x):
        p = self.distribution.computeCDF(x)
        return p

    def computeLogPDF(self, point):
        logpdf = self.distribution.computeLogPDF(point)
        return logpdf

    def computeLogPDFSample(self, sample):
        logpdf = self.distribution.computeLogPDF(sample)
        return logpdf

collDist = [ot.Normal(-3.0, 1.0), ot.Normal(7.0, 2.0)]
weight = [0.5, 2.0]
mixture = ot.Mixture(collDist, weight)
mixture.drawPDF()
sample_size = 100000
sample = mixture.getSample(sample_size)

gm = ot.Distribution(GaussianMixture())
t1 = time.time()
gm.computeLogPDF(sample)
t2 = time.time()
print("Elapsed = ", t2 - t1, "(s)")

gm_py = GaussianMixture()
t1 = time.time()
gm_py.computeLogPDFSample(sample)
t2 = time.time()
print("Elapsed = ", t2 - t1, "(s)")
```

I got 

```
Elapsed =  0.4287550449371338 (s)
Elapsed =  0.019735097885131836 (s)
```
Note that we already have such a mechanism for `Function` (see `_exec` and `_exec_sample` methods)

**Comment by mbaudin47** [comment]
Thank you for the benchmark. It at least proves that the issue is not "wrong". I admit that your script shows to performance improvement, but that is not sufficient to motivate a development in my opinion. This is because the performance improvement is dramatic only for a _very_ large sample.

In my particular case, the actual performance issue is that the default optimization solver used in the `MaximumLikelihoodFactory` is TNC. This algorithm performs badly in my case and, I guess, in most difficult cases. Replacing this solver by, say, NLOPT/Cobyla solved the actual issue.

**Comment by regislebrun** [comment]
Maybe it would be useful in the context of fieldS/time series, e.g. when one want to estimate the distribution of the residual? It is a case where large samples are common...
