### ISSUE TITLE
The units in the cantilever beam example are wrong

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1397]
The cantilever beam example has wrong units:

http://openturns.github.io/openturns/master/examples/reliability_sensitivity/estimate_probability_importance_sampling.html

Look at the units in the calculation.
* The mean Young modulus is 3e7 i.e. 30 MPa = 0.03 GPa which is close to rubber, see 

https://en.wikipedia.org/wiki/Young%27s_modulus#Approximate_values

for reference.

* The mean beam length is 255. This seems like a bridge.
* The mean force is close to 30 000 N, i.e. 3000 kg. This could be a small truck. 
* The event is when the deviation is larger than 30 meters. The text states that this is in cm, which is wrong because all units are in m, not in cm. 

All in all, computing the probability of a 30 meters deviation on a rubber bridge loaded with a truck is bizarre. More physically sounded parameters should be chosen.

**Comment by mbaudin47** [comment]
From OT 1.13 to OT 1.14, the `Beta` distribution has a different parametrization. Two inputs in the cantilever beam example have the Beta distribution : E and I. However, the corresponding examples in the doc were not updated accordingly. 

The code 
```
dist_E = ot.Beta(0.9, 3.1, 2.8e7, 4.8e7)
dist_I = ot.Beta(2.5, 4, 310.0, 450.0)
```

must be replaced with:

```
dist_E = ot.Beta(0.9, 2.2, 2.8e7, 4.8e7) # because 3.1 - 0.9 = 2.2
dist_I = ot.Beta(2.5, 1.5, 310.0, 450.0) # because 4.0 - 2.5 = 1.5
```

The examples which are to be updated are at least:
* http://openturns.github.io/openturns/master/examples/meta_modeling/chaos_cantilever_beam_integration.html
* http://openturns.github.io/openturns/master/examples/meta_modeling/kriging_cantilever_beam.html
* http://openturns.github.io/openturns/master/examples/meta_modeling/kriging_cantilever_beam_hmat.html
* http://openturns.github.io/openturns/master/examples/reliability_sensitivity/estimate_probability_importance_sampling.html
* http://openturns.github.io/openturns/master/examples/meta_modeling/kriging_beam_arbitrary_trend.html

Moreover, the parameters of this test case in the examples are not always the same. For example, the following example uses E_r = 3.2 instead of 3.1:

http://openturns.github.io/openturns/master/examples/reliability_sensitivity/estimate_probability_randomized_qmc.html

This does not allow to compare the results across examples. 

Moreover, the script uses parameter values that are difference from the mathematical description.

**Comment by josephmure** [comment]
Better parameters are given in PR #1493
