### ISSUE TITLE
The BuildDistribution static method should not use the KS-test

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1415]
In the functional chaos algorithm, when a input sample is used, then the `BuildDistribution` static method is used to fit a distribution. 

For one given marginal, this method uses the Kolmogorov-Smirnov test to compute the p-value: 

https://github.com/openturns/openturns/blob/96543814e19406e169727f9c08d2bcb77b2d0b95/lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos/FunctionalChaosAlgorithm.cxx#L192

Then the distribution which has the highest p-value is used with the `BestModelKolmogorov` method. 
This is technically wrong, because distributions which have more parameters will fit best. This is why the `BestModelBIC` method should be used instead.

**Comment by mbaudin47** [comment]
Once this is fixed, the `FittingTest-KolmogorovSamplingSize` ResourceMap key should be set to 1000.

**Comment by regislebrun** [comment]
Remember that the Kolmogorov statistics is *supposed* to take into account the number of estimated parameters and to correct the p-value. In this case, one would expect the KernelSmoothing result to be rejected excepted if it leads to a huge improvement in terms of inf norm.
My feeling is that using nonparametric factories is risky here. I suspect that it is not mathematically sounded to use KernelSmoothing or HistogramFactory here, but with no strong theorem to support this feeling...

**Comment by mbaudin47** [comment]
I agree, but what you mean is rather implicit: do you imply that using the BIC criterion instead of the KS p-value would be a mistake? 

This does not fit in the general framework that the BIC is a model selection criterion, but not the p-value. Hence, the `BestModelBIC` is the method which exactly fits your goal: select the distribution which best fit the data.

**Comment by regislebrun** [comment]
A p-value CAN BE an element for a selection criterion: you select the most credible model, ie the one with the higher p-value. My concern is the ability to compute this p-value correctly for the Kolmogorov-Smirnov statistic as the distribution depends on the estimated parameters in a complex way.
For an information-based criterion, I am much more doubtful on the mathematical soundness of such an approach for nonparametric models. A basic kernel smoothing gives you a model with as many parameters as the sample size, a more advanced kernel smoothing (eg with binning) can give you even more parameters. On the other hand, an histogram can give you a non-parametric model with a growing number of parameters but negligible wrt the sample size.

All in all: nonparametric models are hard to deal with in both frameworks, for different reasons (at least for my understanding).

**Comment by mbaudin47** [comment]
In otsklearn, @sofianehaddad implemented the BuildDistribution() static method with another method:

https://github.com/sofianehaddad/otsklearn/blob/master/otsklearn/otsklearn.py#L7

This is based on fitting an Histogram, then using the orthogonal polynomials for a histogram distribution. This prevents from using a KS-test and seems a consistent method for me. However, when the sample is large, it might have performance issue, so that this is not bulletproof.  Given that this prevents from generating bugs such as #1585, the advantages outweight the drawbacks, isn'it?

**Comment by mbaudin47** [comment]
@regislebrun Your suggestion : We may limit the distribution for which have a strong implementation of the orthogonal polynomials: Gaussian (Hermite), Uniform (Legendre), etc...

**Comment by jschueller** [comment]
sofiane: we can use AIC, or have a parameter that choses the criterion

**Comment by jschueller** [comment]
in #1588 we exclude histogram+ few costly models, and default to BIC, it's not perfect but it's a good start, feel free to comment
