### ISSUE TITLE
The Contour example does not present the second constructor

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1418]
Here is an example.

```
import openturns as ot

g = ot.SymbolicFunction(["R","S"],["R - S"])

lowerBound = ot.Point([1.6, -0.5])
upperBound = ot.Point([6.3, 4.3])

bounds = ot.Interval(lowerBound, upperBound)

nX = 10
nY = 10
boxExperiment = ot.Box([nX, nY], bounds)
inputSample = boxExperiment.generate()

outputSample = g(inputSample)

xstep = (upperBound[0] - lowerBound[0])/(nX + 1)
x = ot.RegularGrid(lowerBound[0], xstep, nX + 2).getVertices()
ystep = (upperBound[1] - lowerBound[1])/(nY + 1)
y = ot.RegularGrid(lowerBound[1], ystep, nY + 2).getVertices()

myGraph = ot.Graph('Contour', 'X1', 'X2', True, '')
levels = ot.Point([-1.0, 1.0, 3.0, 5.0])
labels = ["Level 0", "Level 1", "Level 2", "Level 3"]
drawLabels = True
myContour = ot.Contour(x, y, outputSample, levels, labels, drawLabels)
myGraph.add(myContour)
```

Here is the result.

![Capture](https://user-images.githubusercontent.com/31351465/77296837-aaae8d00-6ce8-11ea-9f33-a437eee5fb3f.PNG)

**Comment by josephmure** [comment]
I do not understand what must be done. Can you elaborate?

**Comment by mbaudin47** [comment]
The current example at:
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.Contour.html
shows the following constructor in action:
```
myContour = ot.Contour(nX + 2, nY + 2, data)
```
The second constructor is:
```
Contour(sampleX, sampleY, data, levels, labels, drawLabels=True, legend=’ ‘)
```
It allows to set the levels of the Contour, which is interesting in practice. This is why an example should be added to the API help page. Remember: one class can have as many example as required, not just one). Since there are two constructors available, at least two examples should be provided.
I guess that this might be an interesting exercise for a candidate OpenTURNS developer :)

**Comment by josephmure** [comment]
Perhaps we could implement a slightly more visually interesting example:

```
import openturns as ot
from openturns.viewer import View

g = ot.SymbolicFunction(["R","S"],["(R * S)^0.75"])

lowerBound = ot.Point([1.6, 0.0])
upperBound = ot.Point([6.3, 4.3])

bounds = ot.Interval(lowerBound, upperBound)

nX = 10
nY = 10
boxExperiment = ot.Box([nX, nY], bounds)
inputSample = boxExperiment.generate()

outputSample = g(inputSample)

xstep = (upperBound[0] - lowerBound[0])/(nX + 1)
x = ot.RegularGrid(lowerBound[0], xstep, nX + 2).getVertices()
ystep = (upperBound[1] - lowerBound[1])/(nY + 1)
y = ot.RegularGrid(lowerBound[1], ystep, nY + 2).getVertices()

myGraph = ot.Graph('Contour', 'X1', 'X2', True, '')
levels = ot.Point([-1.0, 1.0, 3.0, 5.0, 7.0, 9.0])
labels = ["Level 0", "Level 1", "Level 2", "Level 3", "Level 4", "Level 5"]
drawLabels = True
myContour = ot.Contour(x, y, outputSample, levels, labels, drawLabels)
myGraph.add(myContour)
_ = View(myGraph)
```


![image](https://user-images.githubusercontent.com/31989332/111975268-afc33980-8b00-11eb-8e7c-f8d4d0ae5c90.png)

This code will also need to be used to inside [Contour.py](https://github.com/openturns/openturns/blob/master/python/doc/pyplots/Contour.py) in tandem with the class [GridLayout](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.GridLayout.html).
