### ISSUE TITLE
UserDefinedStationaryCovarianceModel doc suggests input dimension can be >1

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1421]
This is both a doc error report and a feature request.

The documentation of the class [UserDefinedStationaryCovarianceModel](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.UserDefinedStationaryCovarianceModel.html) makes 2 contradictory statements:

1. The class takes a RegularGrid as input parameter.
2. In the notes: "We consider a process X : Omega x D --> R^d with D \in R^n."

![UserDefinedStationaryCovarianceModel_webdoc](https://user-images.githubusercontent.com/31989332/77409825-33492e00-6dba-11ea-9d3a-b5b86e0f5589.png)

With a RegularGrid as input, _n_ is necessarily equal to 1, and I feel this should be explicitely stated. [Aside: D is a subset and not an element of R^n so the statement "D \in R^n" is, strictly speaking, false.]

This also applies to the example page [Create a custom stationary covariance model](http://openturns.github.io/openturns/master/examples/probabilistic_modeling/user_stationary_covmodel.html):

![Create_a_custom_stationary_covariance_model](https://user-images.githubusercontent.com/31989332/77410764-b0c16e00-6dbb-11ea-96a9-737829c5f010.png)

My feature request is the following: is it possible to change the class in order to make a UserDefinedStationaryCovarianceModel with _n_ >1 possible?

**Comment by regislebrun** [comment]
It is much more involved to define a stationary covariance model by hand when the input dimension is greater than 1. You have to give all the covariance matrices for all the pair of points of your underlying mesh for all the possible differences of such points. Think about a square of side 2 regularly meshed into a grid of 9 points (the vertices of the square, the middle of each side and the center). Then you have the following possible difference vectors (only those with nondecreasing components): (0, 0), (1,0), (2,0), (0,1), (0,2), (1,1), (1,2), (2,1), (2,2), already complex to describe. It becomes worse if you increase the dimension or the number of points, not talking about non-Cartesian domains. Do you have a more formal description of your needs?

**Comment by josephmure** [comment]
It is not something I really "need", as I am quite satisfied with the list of currently available covariance models. The error in the documentation is the real issue here. i am going to propose a fix as soon as possible.

I am a little surprised, though: the UsedDefinedCovarianceModel does not seem to be limited to n=1, and isn't it even more difficult to describe a non-stationary covariance model?
