### ISSUE TITLE
The MetaModelValidation class has no graphics

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1430]
There is no picture at the top of the `MetaModelValidation` help page: 

http://openturns.github.io/openturns/master/user_manual/response_surface/_generated/openturns.MetaModelValidation.html

This is a pity, since the `draw` produces such a useful plot.

**Comment by m-balesdent** [comment]
@mbaudin47 I think this issue could be closed as the MetamodelValidation help page now contains graphics.

However, the method `computePredictivityFactor` is not documented.

**Comment by jschueller** [comment]
thats ok since its deprecated for computeR2Score
