### ISSUE TITLE
The figure for LHSExperiment is not accurate

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1431]
The following picture is in the help page of LHSExperiment:

![image](https://user-images.githubusercontent.com/31351465/78157590-6df93900-7440-11ea-8842-dad882ddbc85.png)

The grid is not accurate enough: a 10x10 grid would be much more appropriate on this case to reveal the LHS structure.

**Comment by mbaudin47** [comment]
The following figure reveals more of the structure:

http://openturns.github.io/openturns/master/examples/reliability_sensitivity/design_of_experiments.html#Latin-Hypercube-Sampling

**Comment by josephmure** [comment]
This issue was solved by PR #1735 and should be closed.
