### ISSUE TITLE
The style of the curves is unpleasing to my eyes

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1436]
The style of most graphics is generally unpleasing. Please look at the following typical graph.

![Screenshot from 2020-04-06 23-06-31](https://user-images.githubusercontent.com/31351465/78605245-79db6580-785b-11ea-9b35-3e9a6be41b86.png)

I created it with the following statements:

```
import openturns as ot
ncurves = 5
palette = ot.Drawable.BuildDefaultPalette(ncurves)
graph = ot.Graph("BuildDefaultPalette", "X", "Y", True, "topright")
n = 20
for i in range(ncurves):
    x = ot.Sample(range(n), 1)
    y = ot.Normal().getSample(n)
    curve = ot.Curve(x, y)
    curve.setColor(palette[i])
    curve.setLegend("Curve #%d" % (i))
    graph.add(curve)
```

We see that there are 3 visually unpleasing elements.
* The grid is unnecessary in general. The default should be to disable it.
* The legends have a vintage shadow.
* The colors are so flashy.

Please compare with the following graphics with default settings and Matplotlib. 

![Screenshot from 2020-04-06 23-06-42](https://user-images.githubusercontent.com/31351465/78605403-bc04a700-785b-11ea-875d-c4bcdfd2dfc6.png)

I created it with the following statements.

```
import openturns as ot
import pylab as pl
n = 20
for i in range(ncurves):
    x = ot.Sample(range(n), 1)
    y = ot.Normal().getSample(n)
    pl.plot(x, y, label = "Curve #%d" % (i))
pl.legend();
```

Notice that the first three colors are not plain colors: a kind of blue, orange, green and red, but no plain blue, green and red. These colors are called "Tableau" in Matplotlib:

https://matplotlib.org/3.1.0/gallery/color/named_colors.html

I created a script which searches for the colors which best match these colors. Here is the result:
```
#1f77b4 [31,119,180] dodgerblue3
#ff7f0e [255,127,14] darkorange1
#2ca02c [44,160,44] forestgreen
#d62728 [214,39,40] firebrick3
#9467bd [148,103,189] mediumpurple3
#8c564b [140,86,75] lightsalmon4
#e377c2 [227,119,194] orchid
#7f7f7f [127,127,127] gray50
#bcbd22 [188,189,34] goldenrod3
#17becf [23,190,207] turquoise3
```

In order to experiment with it, I wrap this up in a function.

```
def BuildTableauPalette(ncurves):
    """
    Create a palette of named colors suitable for OpenTuRNS 
    graphics.
    
    Parameters
    ----------
    ncurves : int
        The number of colors in the palette to create.
    
    Returns
    -------
    palette : list of str
        The list of named colors of the palette.
    """
    if ncurves > 10:
        raise ValueError("Number of curves equal to %d, which is greater than 10." % (ncurves))
    palette = ["dodgerblue3",
               "darkorange1", 
               "forestgreen", 
               "firebrick3", 
               "mediumpurple3", 
               "lightsalmon4", 
               "orchid", 
               "gray50", 
               "goldenrod3", 
               "turquoise3"
              ]
    truePalette = palette[:ncurves]
    return truePalette
```

This allows to produce the following plot with OpenTURNS:

![Screenshot from 2020-04-06 23-06-54](https://user-images.githubusercontent.com/31351465/78605876-9fb53a00-785c-11ea-9f46-1c763cf61d01.png)

This is done with the following statements:

```
palette = BuildTableauPalette(ncurves)
graph = ot.Graph("BuildTableauPalette", "X", "Y", True, "topright")
n = 20
for i in range(ncurves):
    x = ot.Sample(range(n), 1)
    y = ot.Normal().getSample(n)
    curve = ot.Curve(x, y)
    curve.setColor(palette[i])
    curve.setLegend("Curve #%d" % (i))
    graph.add(curve)
graph.setGrid(False)
view = otv.View(graph, legend_kwargs = {'shadow' : False})
```

Here are the updates I suggest.
* Remove the "shadow" customization in "viewer.py":

https://github.com/openturns/openturns/blob/f56be6d04a8df51d6f924cab66e7d3dca29a2ed0/python/src/viewer.py#L538

* Remove the default grid in "viewer.py":

https://github.com/openturns/openturns/blob/f56be6d04a8df51d6f924cab66e7d3dca29a2ed0/python/src/viewer.py#L228

* Create a new `BuildTableauPalette` along with the `BuildDefaultPalette` in `DrawableImplementation.cxx`:

https://github.com/openturns/openturns/blob/f56be6d04a8df51d6f924cab66e7d3dca29a2ed0/lib/src/Base/Graph/DrawableImplementation.cxx#L1461

This would benefit to both the C++ and Python layers, not only the Python one.

Overall, I do not suggest to create tons of new palettes in the library. However, I suggest to use the minimum default settings which allow to create efficient and modern-looking graphs. 

@sofianehaddad : would you approve these changes if I create the corresponding PR?

**Comment by sofianehaddad** [comment]
@mbaudin47 we should keep in mind that the purpose of the `View` class is interpreting `Graph` or `Drawable` objects and 'translate' them onto `matplotlib` objects.
Concerning the `grid`, we might set a `ResourceMap` key (https://github.com/openturns/openturns/blob/f56be6d04a8df51d6f924cab66e7d3dca29a2ed0/lib/src/Base/Graph/GraphImplementation.cxx#L105)
For the `shadow`, it is specific to `matplotlib`. Thus how efficiently should we handle it ? `dict` or other solutions?
For the palette, no particular opinion

**Comment by mbaudin47** [comment]
* I did not know that the grid is an option of the `Graph`. In this case, the configuration of the grid should be dependent on this option. The second update would be to change the default from True to False. 
* For the `shadow`, my option would be to just remove it. There are two goals in this: 1) configure the least possible set of options so as to get a plot which leaves the smallest possible difference with the default settings. 2) The user always has the possibility to *add* specific options.

**Comment by regislebrun** [comment]
I would say it's a matter of taste. The grid is activated by default when using the verbose constructor of a Graph, and deactivated when using the default constructor. You can always switch the grid using the setGrid() method of a Graph. In my opinion the grid is really useful when you are plotting clouds, or curves on a log-scale.

Concerning the colors,  the BuildDefaultPalette() method was intended to provide well-contrasted colors when there are many different graphical entities. I decided to use the hue-saturation-value space and to loop through the hue in concentric circles, reducing the value (ie the brightness) at each cycle (see Drawable-DefaultPalettePhase in ResourceMap). Other options are obviously possible and nothing prevent us from providing other palettes (eg like matlab do). I prefer to have well-contrasted colors than half-tone colors, but once again it is a matter of taste. If you *really* want to reproduce matplotlib's default behavior you can introduce a new palette and populate it with the *exact* colors using the hexadecimal code of each color, see [here](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Drawable.html?highlight=drawable#openturns.Drawable.ConvertFromRGB)

For the legend, my main concern is that most of the time I would prefer to have it outside of the plotting region but don't know how to do that.

All in all, I am not sure that there is something to change here. Maybe a new palette, or an example of how to change it using matplotlib (if possible).

**Comment by mbaudin47** [comment]
@jschueller : you did not provide any input on this issue. Any opinion?

**Comment by jschueller** [comment]
I globally agree on all your remarks.

**Comment by mbaudin47** [comment]
Because of the code at:
https://github.com/openturns/openturns/blob/539fc81dee231523101cd7d2a30f83fa636ba248/lib/src/Base/Func/EvaluationImplementation.cxx#L421
the ConvertFromHSV function is still used in the contour plots. @regislebrun
