### ISSUE TITLE
ERROR: No matching distribution found for openturns

### ISSUE THREAD

**Issue by VinceDuve** [openturns/openturns#1446]
Within a virtual environment (venv), I've been trying to install openturns from pip with no success. No guidance can be found in the documentation to help solving this error.

**Comment by jschueller** [comment]
maybe you could provide more infos ? os ? arch ? python version ?

**Comment by VinceDuve** [comment]
yep, sorry: win32, virtualenv, Python 3.7.1

**Comment by jschueller** [comment]
32bits python binaries are not supported
maybe you could switch to a 64 bits python if host allows ?

**Comment by VinceDuve** [comment]
pip does not work either, but dowloading the source file could overcome the issue
