### ISSUE TITLE
P1LagrangeInterpolation sometimes fails

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1449]
Hi,
I am trying to interpolate the values of a Field defined on a Mesh m1 at the vertices of another Mesh m2, using P1LagrangeInterpolation. I can create the interpolation object but when I use it I get an exception (InvalidArgumentException with no description...). Either the two meshes are incompatible and it should be checked in the constructor, or there is a more subtile bug. The strange thing is that it occurs with no apparent regularity (eg when mesh2 has a simplex fully outside of mesh1), as the following example shows:
```
import openturns as ot
import openturns.viewer as otv

N = 5
m1 = ot.IntervalMesher([1]*2).build(ot.Interval([0.0]*2, [1.0]*2))
ns1 = m1.getSimplicesNumber()
m2 = ot.IntervalMesher([N]*2).build(ot.Interval([-1.0]*2, [2.0]*2))
ns2 = m2.getSimplicesNumber()

ot.ResourceMap.SetAsUnsignedInteger("Mesh-LargeSize", 5000)
g = m1.draw()
g.add(m2.draw())
c = ["red"]*(1+ns1) + ["blue"]*(1+ns2)
print(len(c))
g.setColors(c)
g.setTitle("Interpolation from mesh 1 to mesh 2, N=" + str(N))
view = otv.View(g, square_axes=True)
view.save("Interpolation_N_" + str(N) + ".png")
view.close()


interpolation = ot.P1LagrangeInterpolation(m1, m2, 1)
nv1 = m1.getVerticesNumber()
values = ot.Sample(nv1, [1.0])
res = interpolation(values)
print("res=", res)
```
When I use this script with `N=4` it works like a charm, corresponding to the following meshes:
![Interpolation_N_4](https://user-images.githubusercontent.com/8220933/79201704-c402af00-7e38-11ea-8e16-1302e745eb47.png)

but when I use it with `N=5` I get the exception:
![Interpolation_N_5](https://user-images.githubusercontent.com/8220933/79201792-e4326e00-7e38-11ea-9336-d19ce5f4ac75.png)

**Comment by jschueller** [comment]
hello,

it fails here:
https://github.com/openturns/openturns/blob/master/lib/src/Base/Func/P1LagrangeInterpolation.cxx#L174
```
      if (!inputMesh_.checkPointInSimplexWithCoordinates(outputVertices[i], simplexIndices[i], coordinates))
      {
        throw InvalidArgumentException(HERE);
      }
```

**Comment by regislebrun** [comment]
Yes, but it shouldn't ;-)! And the message could be more explicit...

**Comment by jschueller** [comment]
ok, let's try this
