### ISSUE TITLE
GeneralLinearModelAlgorithm::setCovarianceModel could lead to unexpected behavior of parameter optimization in KrigingAlgorithm

### ISSUE THREAD

**Issue by tbittar** [openturns/openturns#1455]
Suppose that we construct a metamodel for a function and then add points sequentially. We compute a new metamodel at every iteration but reestimate the hyperparameters every k>1 iterations. We use the previous hyperparameters as starting points for this hyperparameter optimization. The problem is that the hyperparameters might not be updated.

Consider the following example:
```python

import openturns as ot

# We wish to create a metamodel for f
f = ot.SymbolicFunction(['x'],  ['sin(x)'])

ot.RandomGenerator.SetSeed(0)
inputSample = ot.Uniform(0, 10).getSample(10)
outputSample = f(sampleX)

basis = ot.ConstantBasisFactory(1).build()
covarianceModel = ot.SquaredExponential([1.0])

# First metamodel computation without parameter optimization
algo = ot.KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
algo.setOptimizeParameters(False)
algo.run()

result = algo.getResult()
print(result.getCovarianceModel())  # Return SquaredExponential(scale=[1], amplitude=[1]), ok

# Now compute the metamodel using the covariance model that is output by the previous KrigingAlgorithm, this time we aim at optimizing the hyperparameters
algo2 = ot.KrigingAlgorithm(sampleX, sampleY, result.getCovarianceModel(), basis)
algo2.setOptimizeParameters(True)  # We expect to optimize the covariance parameters
algo2.run()

result2 = algo2.getResult()
print(result2.getCovarianceModel()) # Return SquaredExponential(scale=[1], amplitude=[1]), the covariance parameters are not optimized

# Origin of the problem
print(covarianceModel.getActiveParameter())  # Return [0, 1]
print(result.getCovarianceModel().getActiveParameter())  # Return []

# This is how we can force the optimization of parameters
covarianceModel2 = result.getCovarianceModel() 
covarianceModel2.setActiveParameter([0,1])  # We need to manually set the active parameters
algo3 = ot.KrigingAlgorithm(sampleX, sampleY, covarianceModel2, basis)
algo3.setOptimizeParameters(True)
algo3.run()
result3 = algo3.getResult()
print(result3.getCovarianceModel())  # Return SquaredExponential(scale=[0.743496], amplitude=[5.19971]), parameters have been optimzed
```

After looking at the source code, I guess that the problem comes from `GeneralLinearModelAlgorithm::setOptimizeParameters` which then calls `GeneralLinearModelAlgorithm::setCovarianceModel`. If we have `optimizeParameters=True` and the user specifies a covarianceModel which has no active parameters, the method `setCovarianceModel` fails to reactivate the parameters and the optimization cannot occur.

This behaviour can be particularly misleading for the user. 

In particular, after looking at the code, I guess that if we use a `parameterEstimationPeriod` different from 1 in `EfficientGlobalOptimization`, the metamodel is actually never reestimated after the first iteration. I have not checked this last assertion though.

**Comment by sofianehaddad** [comment]
IMO, it is more a misunderstanding concerning the usage of `Kriging` like that.

But your issue allows highlighting some problems in `EGO`
 
First there is indeed no check concerning the active parameters when the class is instanciated.
(https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/Optimization/EfficientGlobalOptimization.cxx#L66). 

Second it seems that internal `krigingResult_` is used 
https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/Optimization/EfficientGlobalOptimization.cxx#L238 but never updated.

**Comment by jschueller** [comment]
For EGO, it would be useful for the covariance model returned through the KrigingResult to have the original active parameters, ie GLM should act on a copy or restore the active parameters field.
