### ISSUE TITLE
truncation of distribution

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#1456]
Hello,
When we truncate a distribution on a domain defined by an Interval where some bounds are not finite, this information is not taken into account in the truncation!
See the script below:
```
from openturns import *
loi = Normal(2)
domTrunc = Interval([-2, -3], [2, 3.0], [True, False], [True, True])
loi_trunc = TruncatedDistribution(loi, domTrunc)
# This probability should not be equal to 0.0!!!
print('proba = ', loi_trunc.computeCDF([3.0, -3]))
# proba = 0.0
```

**Comment by jschueller** [comment]
The issue is that the -3 (inf) lower bound is kept in the intersection which defines the range:
```
const Interval range(distributionRange.intersect(bounds_));
setRange(range);
```
