### ISSUE TITLE
The Sample constructor based on a list and an integer should not exist

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1465]
We can create a 1D sample with:
```
sample = ot.Sample([2.0, 2.0, 1.0, 1.0, 2.0, 3.0, 1.0, 2.0, 2.0, 1.0], 1)
```
This should not be possible, since a list cannot be a structure for a sample: a 2D object should be used as input, instead of a list. Hence, the previous example should be:
```
sample = ot.Sample([[2.0], [2.0], [1.0], [1.0], [2.0], [3.0], [1.0], [2.0], [2.0], [1.0]], 1)
```
However, this example requires a significant amount of square brackets, which may explain why this constructor is available.

**Comment by mbaudin47** [comment]
Before dropping this constructor, a solution should be found in order to get a simple method to create such a sample.
Below is an attempt based on numpy:
```
>>> import openturns as ot
>>> import numpy as np
>>> data = np.array([2.0, 2.0, 1.0, 1.0, 2.0, 3.0, 1.0, 2.0, 2.0, 1.0])
>>> data = data.reshape(10, 1)
>>> sample = ot.Sample(data)
>>> sample.getSize()
10
>>> sample.getDimension()
1
```

**Comment by sofianehaddad** [comment]
I think we have all elements to generate a sample properly.
Notice that the C++ API implements a `setData` method. Thus we might add a static method to the `Sample` class (`BuildFromSequence`) for example. 
```
>>> import openturns as ot
>>> import numpy as np
>>> data = np.array([2.0, 2.0, 1.0, 1.0, 2.0, 3.0, 1.0, 2.0, 2.0, 1.0])
>>> sample = ot.Sample.BuildFromSequence(data, 10, 1)
>>> sample.getSize()
10
>>> sample.getDimension()
1
```
What do you think?

**Comment by jschueller** [comment]
Agreed

**Comment by mbaudin47** [comment]
True : `BuildFromSequence` is the very correct way of handling this. However, it is not documented, which is a bug: #1589

**Comment by mbaudin47** [comment]
The `BuildFromSequence` actually does not exist: I suggest to implement it because the commit 9613095d12bbcc2a3d6b2fce8e14fcb482739fc3 is a regression which makes the library more complicated to use.

**Comment by mbaudin47** [comment]
@sofianehaddad : The release is coming, which introduces a change in the API. The following code works with 1.15:

```
n = 20
x = ot.Sample(range(n), 1)
```
but fails in the current master. 
Shouldn't this regression be fixed by implementing the `BuildFromSequence` function before the RC is produced?

**Comment by sofianehaddad** [comment]
ok I have it in a branch

**Comment by mbaudin47** [comment]
The issue is closed, but the problem is still there, since OT1.16 has the bug and the PR#1612 is unmerged. 
In the meantime, in order to port to 1.16, tricks are required. Here is one way:
In OT1.15:
```
s = ot.Sample(range(5), 1)
```
In OT 1.16:
```
s = ot.Sample([[x] for x in range(5)])
```

**Comment by mbaudin47** [comment]
In OT 1.15:
```
x = ot.Sample(range(6), 2)
```
In OT 1.16:
```
x = ot.Sample([[2 * i, 2 * i + 1] for i in range(3)])
```
@sofianehaddad : I guess that these example might provide some use cases.
