### ISSUE TITLE
Should a ParametricFunction without inputs be evaluated without inputs?

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1494]
Consider a ParametricFunction where all inputs are set as parameters of a ParametricFunction. In this case, the function has no input anymore: the required values to evaluate the function are then parameters. Hence, we should be able to evaluate it with y=g(), without any input argument. This is, however, not possible.

In the following script, I create a `ParametricFunction` used to build the flooding calibration test case.

```
import numpy as np
import openturns as ot
model = ot.SymbolicFunction(
    ["Q", "Ks", "DeltaZ"], ["(Q / (Ks*300.0 * sqrt(DeltaZ / 5000.0)))^(3.0 / 5.0)"]
)
# Define the value of the reference values of the $\theta$ parameter.
QInitial = 1000.0
KsInitial = 20.0
DeltaZInitial = 2.0
thetaPrior = ot.Point([QInitial, KsInitial, DeltaZInitial])

# The following statement create the calibrated function from the model.
calibratedIndices = [0, 1, 2]
mycf = ot.ParametricFunction(model, calibratedIndices, thetaPrior)
```
Therefore, the calibrated function has no input and this is why we set an empty list as input argument.
```
y = mycf([])
print(y)
```
The previous script works and prints [3.56855]. The previous script is bizarre, given that the function really has no input. Actually, the purpose of the empty list is to create a Point with dimension 0, which is then used to evaluate the function with the Function(Point) prototype.

However, the following script fails:
```
y = mycf()
```
with the following error:
```
TypeError: Wrong number or type of arguments for overloaded function 'Function___call__'.
  Possible C/C++ prototypes are:
    OT::Function::operator ()(OT::Point const &) const
    OT::Function::operator ()(OT::Sample const &) const
    OT::Function::operator ()(OT::Field const &) const
```
Can a `OT::Function::operator ()() const` prototype be created?

**Comment by jschueller** [comment]
what's the use-case ?

**Comment by mbaudin47** [comment]
The use case is the calibration without observed inputs #1490. Please look at the script:

https://github.com/openturns/openturns/pull/1490/files#diff-785e961b0b67ff7c67aaca3ba19cf175

In order to get a clean code, I used the SymbolicFunction g. It would have been simpler to use the ParametricFunction `model`, but this would require to use the very unexpected code presented in the previous message in this issue (with the empty list argument).

**Comment by regislebrun** [comment]
IMO there are two reasons why this operator should NOT be introduced:
- the aim of a Function is to produce a value given an argument, so the evaluation operator will be propagated everywhere to be used only in very specific cases;
- the C++ concept of a Function is here to mimic its mathematical counterpart, where both an input space and an output space are expected, and in this view it makes much more sense to provide an input point of dimension zero than no input in the case where the input space is empty.

**Comment by jschueller** [comment]
yes, I see nothing wrong with f([])

**Comment by mbaudin47** [comment]
I agree.
