### ISSUE TITLE
ot.Ceres('LEVENBERG_MARQUARDT') and ot.Ceres('DOGLEG') do not handle bound constraints

### ISSUE THREAD

**Issue by tbittar** [openturns/openturns#1510]
From the docs, I read that in the Ceres library, the algorithms LEVENBERG_MARQUARDT and DOGLEG should handle bound contraints. However, it fails on the following simple example:
```python

def test(X):
    return [sum(x**2 for x in X)]

dim = 2

model = ot.PythonFunction(dim, 1, test)
problem = ot.OptimizationProblem()
problem.setObjective(model)

bounds = ot.Interval([1] * dim, [5] * dim)
problem.setBounds(bounds)

algo = ot.Ceres(problem, 'LEVENBERG_MARQUARDT')  # The same example fails with 'DOGLEG'
algo.setStartingPoint([2]*dim)
algo.run()
result = algo.getResult()
result.getOptimalPoint()  # Returns [1.11022e-11,1.11022e-11] whereas we expect [1, 1]
```

**Comment by jschueller** [comment]
bounds constraints are only available for nlls problems, not for general optimization, but that's still a bug

**Comment by tbittar** [comment]
Ah ok, we have to use the LeastSquaresProblem class to use bound constraints, I didn't get that at first

**Comment by jschueller** [comment]
yes, if your problem is really a least-squares problem
