### ISSUE TITLE
Display problem of OpenTURNS graphs in Spyder "Graphes" Window

### ISSUE THREAD

**Issue by EmmanuelArdillon** [openturns/openturns#1512]
Environment: Python 3.7.6 - Spyder 4.0 - OT 1.15 - Windows VM VirtualBox

Graphs from various OT commands are not displayed in the Spyder "Graphes" Window (nothing appears in the tab), whereas Matplotlib graphs appear correctly. Examples: distribution.drawPDF(), ...

See the joined script

**Comment by jschueller** [comment]
distribution.drawPDF() does not actually draw anything outside a notebook context, it just gives you the graph data, to draw something from a regular python console you must use the viewer module:
http://openturns.github.io/openturns/master/examples/graphs/graphs_basics.html

this should be better explained in the doc

**Comment by sofianehaddad** [comment]
works for me on osx 
![image](https://user-images.githubusercontent.com/1433220/83883205-76713700-a743-11ea-9fc8-f16067a82d01.png)
