### ISSUE TITLE
FORM calculation: impossible to get importance factors and other important results

### ISSUE THREAD

**Issue by EmmanuelArdillon** [openturns/openturns#1514]
Beta_HL index and U* point are computed correctly, but the Importance and sensitivity factors are not computed. The getresult() command confirms that importance factors are equal to zero...

The corresponding accessors do not appear in the API FORM class.

The accessor getPhysicalStartingPoint() is available but does not work.

[Bug FORM 03jun20.docx](https://github.com/openturns/openturns/files/4724435/Bug.FORM.03jun20.docx)

Message:
  print("\nPoint de départ:", result.getPhysicalStartingPoint())

AttributeError: 'FORMResult' object has no attribute 'getPhysicalStartingPoint'

**Comment by jschueller** [comment]
they are set to zero, but they not actually computed until you use getImportanceFactors
getPhysicalStartingPoint is not a valid method name, check the doc of FORMResult
