### ISSUE TITLE
KernelSmoothing build failure

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1515]
The KernelSmoothing build() method sometimes fails inexplicably.
 ```
 import openturns as ot
 import numpy as np
 
 
 #a1 is a 254 x 1 matrix with 5 non-zero elements equal to 0.25
 #a1 is a 255 x 1 matrix with 5 non-zero elements equal to 0.25
 a1 = np.append(np.repeat(0.0,249), np.repeat(0.25,5)).reshape(-1, 1)
 a2 = np.append(np.repeat(0.0,250), np.repeat(0.25,5)).reshape(-1, 1)
 
 #a1 et a2 are turned into Samples s1 and s2
 s1 = ot.Sample(a1)
 s2 = ot.Sample(a2)
 
 #Kernel smoothing succeeds with s1, but fails with s2
 ks = ot.KernelSmoothing()
 k1 = ks.build(s1)
 k2 = ks.build(s2)
 ```
 The Distribution k1 is constructed without error, but the last line of this script produces the following error:
 ```
 RuntimeError: InternalException : Error: Brent method requires that the function takes different signs at the endpoints of the given starting interval, here infPoint=0, supPoint=0, value=0, f(infPoint) - value=-nan and f(supPoint) - value=-nan
 ```
 I realize that kernel smoothing should not be attempted on 2-valued Samples anyway, but I would like to understand the error.
 It looks like the Brent algorithm does not realize there is more than one value in the Sample when building k2, although it does when building k1.

**Comment by jschueller** [comment]
the problem is we dont check that the variance is > 0

**Comment by sofianehaddad** [comment]
@jschueller agreed that we should add some checks. However the variance here is not 0
The issue is related to the evaluation of the bandwidth using the `MixedPlugin` method

```
bw1 = ks.computeMixedBandwidth(s1) # ok
bw2 = ks.computeMixedBandwidth(s2) # fails and provide the previous msg
```

**Comment by jschueller** [comment]
yes, falling back to silverman is also a solution, i'll do that

**Comment by sofianehaddad** [comment]
@jschueller I see your point concerning the `sd` equals to 0. Indeed the bw is evaluated only through a small sample and not the full one. Small being here `250`
If we increase this size to 255 for example (using `ot.ResourceMap.SetAsUnsignedInteger("KernelSmoothing-SmallSize", 255)`), the problem vanishes...

Probably we also should consider how to select the small sample, check `sd` value... In other words makes the estimate more robust

**Comment by jschueller** [comment]
now we check the sd value, so problem solved isnt it ?

**Comment by mbaudin47** [comment]
I experienced the same issue when configuring the cutoff used in the "solve-the-equation" rule:
```
import openturns as ot
distribution = ot.Normal()
kernel = ot.Normal()
factory = ot.KernelSmoothing(kernel)
ot.ResourceMap_SetAsScalar("KernelSmoothing-CutOffPlugin", 3.0)
ot.RandomGenerator.SetSeed(1)
sample = distribution.getSample(100)
h = factory.computePluginBandwidth(sample)[0]
```
produces:
```
RuntimeError: InternalException : Error: Brent method requires that the function takes different signs at the endpoints of the given starting interval, here infPoint=0.350888, supPoint=1.61108, value=0, f(infPoint) - value=-nan and f(supPoint) - value=0.954103
```
My goal was to see what exact speed advantage the cutoff provides to the algorithm. In practice, choosing a cutoff less than 4 makes it fail very often, and increasing it beyond 5 does not make it more robust. 

Actually, the "solve-the-equation" rule is not bulletproof method. Falling back to Silverman makes sense, so I agree with Julien: as far as the `build` method is concerned, the problem is solved, although I would check that the issue I mention is also catched by JS's trick.

**Comment by regislebrun** [comment]
Hi all,

There is a bug in the `computeBandwidthConstraint()` method of `PluginConstraint` when `phiGammaH` is negative. While the fifth root of a negative number is well-defined, it cannot be computed using std::pow.
None of the methods available to compute a bandwidth should fail if the standard deviation is positive. If it is zero, then the sample is constant and the distribution is discrete: kernel smoothing should not be used at the first place!

**Comment by jschueller** [comment]
ok, let's also raise an exception here then

**Comment by mbaudin47** [comment]
> Hi all,
> 
> There is a bug in the `computeBandwidthConstraint()` method of `PluginConstraint` when `phiGammaH` is negative. While the fifth root of a negative number is well-defined, it cannot be computed using std::pow.
> None of the methods available to compute a bandwidth should fail if the standard deviation is positive. If it is zero, then the sample is constant and the distribution is discrete: kernel smoothing should not be used at the first place!

Just to clarify this point. According to my experiments, `phiGammaH<0` in the issue that I mentioned (with cutoff=3), but not in @josephmure's initial issue where the list of values of phiGammaH is the following:
```
phiGammaH=6.27353e+09
phiGammaH=3.45546e+09
phiGammaH=7.45795e+10
phiGammaH=2.90669e+08
phiGammaH=8.86597e+11
phiGammaH=2.44507e+07
phiGammaH=1.05398e+13
phiGammaH=2.05685e+06
phiGammaH=1.25297e+14
phiGammaH=173162
phiGammaH=1.48953e+15
phiGammaH=14493.9
phiGammaH=1.77074e+16
phiGammaH=14493.9
phiGammaH=1.77074e+16
phiGammaH=1.51387e+16
phiGammaH=172895
phiGammaH=1.35694e+16
phiGammaH=2.04717e+06
phiGammaH=1.25775e+16
phiGammaH=2.41784e+07
phiGammaH=1.19382e+16
phiGammaH=2.83686e+08
phiGammaH=1.15228e+16
phiGammaH=3.28474e+09
phiGammaH=1.1254e+16
phiGammaH=3.70528e+10
phiGammaH=1.1083e+16
phiGammaH=3.97325e+11
phiGammaH=1.09779e+16
phiGammaH=3.87406e+12
phiGammaH=1.09172e+16
phiGammaH=3.19152e+13
phiGammaH=1.08857e+16
phiGammaH=2.00606e+14
phiGammaH=1.08719e+16
phiGammaH=1.08661e+16
phiGammaH=nan
phiGammaH=nan
phiGammaH=nan
phiGammaH=nan
```
Please see the #1517 for a proposal to fix the expression when phiGammaH<0.
