### ISSUE TITLE
NumericalMathFunction in current version

### ISSUE THREAD

**Issue by A-ep93** [openturns/openturns#1523]
Hello,
Does the function "NumericalMathFunction" exist in openturns now?
I try to use it based on examples in the following link:
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.NumericalMathFunction.html
However, I get the following error:
AttributeError: module 'openturns' has no attribute 'NumericalMathFunction'
If it does not exist in the current version, what I should use instead of it?

**Comment by sofianehaddad** [comment]
Hi strange that we still have such doc. Thanks for the report.
You should have a look at http://openturns.github.io/openturns/master/user_manual/functions.html

**Comment by jschueller** [comment]
The file exists in the folder from a previous version of master, but it not generated or used.
I'm removing it manually.

**Comment by A-ep93** [comment]
Thank you for your response. 
Do you know what function should I use in the current version instead of this function? I have an old code that I want to run. In that code, this function is applied to a class defined by "OpenTURNSPythonFunction" command.
I would really appreciate it if you can help me as I am new to openturns. 
If you do not know what command should I use instead of this command, do you know in what older version I can use this command?

**Comment by sofianehaddad** [comment]
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.OpenTURNSPythonFunction.html#openturns.OpenTURNSPythonFunction

**Comment by ElissonRodrigues** [comment]
```python
class modelePYTHON(OpenTURNSPythonFunction):
    def __init__(self, formula):
        self.formula = formula
        if formula == 0: self.formula = ((A - 0.0025)*(210000000*0.00796))/(0.50*L)
        else: self.formula = (1.10*0.80*66.00*0.5)/(2*B+A)
        OpenTURNSPythonFunction.__init__(self,3,1)
    def _exec(self,x):
        A = x[0]
        C = x[1]
        L = x[2]
        # A = K , C = solicitação , L = comprimento cravado
        A = A/1000
        Ru = self.formula
        if Ru > 2237.0:
            Ru = 2237.0
        else:
            Ru = Ru   
        M = Ru - C  
        return[float(M)]


def function():
    resultado = NumericalMathFunction(modelePYTHON())
    #características das variáveis aleatorias
    distributionA = Normal(18.17, 2.357)
    distributionC = Normal(513, 203)
    distributionL = Normal(27.22, 5.742)
```

**Comment by ElissonRodrigues** [comment]
```python
class modelePYTHON(OpenTURNSPythonFunction):
    def __init__(self, formula):
        self.formula = formula
        if formula == 0: self.formula = ((A - 0.0025)*(210000000*0.00796))/(0.50*L)
        else: self.formula = (1.10*0.80*66.00*0.5)/(2*B+A)
        OpenTURNSPythonFunction.__init__(self,3,1)
    def _exec(self,x):
        A = x[0]
        C = x[1]
        L = x[2]
        # A = K , C = solicitação , L = comprimento cravado
        A = A/1000
        Ru = self.formula
        if Ru > 2237.0:
            Ru = 2237.0
        else:
            Ru = Ru   
        M = Ru - C  
        return[float(M)]


def function():
    resultado = NumericalMathFunction(modelePYTHON())
    #características das variáveis aleatorias
    distributionA = Normal(18.17, 2.357)
    distributionC = Normal(513, 203)
    distributionL = Normal(27.22, 5.742)
```

I have this same issue. I tried using old versions (1.15, 1.17, 1.18, 1.19) in all versions does not have this function. 

in this code above, how could I adapt to the new version?
