### ISSUE TITLE
The error of the NonLinearLeastSquaresCalibration and GaussianNonLinearCalibration are different.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1529]
The error of the NonLinearLeastSquaresCalibration is the only one which can have a non zero mean. The GaussianNonLinearCalibration error has a zero mean. This might mean that one of them has a bug.

Let us focus on the distribution error of various calibration algorithms.
* LinearLeastSquaresCalibration: The resulting distribution of the output error is a Normal and is computed from the residuals.
* NonLinearLeastSquaresCalibration: The resulting distribution of the output error is a Normal and is computed from the residuals.
* GaussianLinearCalibration: The resulting error distribution is Normal with a zero mean and with a covariance matrix equal to the errorCovariance input argument.
* GaussianNonLinearCalibration: The resulting error distribution is Normal with a zero mean and with a covariance matrix equal to the errorCovariance input argument.

The fact that linear algorithms have a zero error mean is expected, because the residuals for these method is always centered on zero by design. The fact that the mean of the error of the NonLinearLeastSquaresCalibration algorithm can be non zero seems right to me, because a non linear algorithm does not always produce a zero mean error. The Normal distribution makes sense if we want to link this result to the maximum likelihood estimator. 

From these facts, I conclude that the GaussianNonLinearCalibration has a bug: the distribution of the error should be Normal and computed from the residuals. This way, the mean of the error can be nonzero.

**Comment by jschueller** [comment]
difficult to answer without any specific math argument here, deferring to @regislebrun

**Comment by regislebrun** [comment]
@mbaudin47 Could you provide simple examples showing what you get and what you expected from the different algorithms?
