### ISSUE TITLE
Mesh does not check the simplices indices

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1547]
Consider the following script where I create a 1D mesh with given vertices and simplices.

```
import openturns as ot
vertices = [[2.1], [2.8], [3.5], [4.2], [4.9], [5.6], [6.3], [7.0]]
simplices = [[3, 4], [4, 5], [5, 6], [6, 7], [7, 8], [8, 9], [9, 10]]
mesh = ot.Mesh(vertices, simplices)
print(mesh.computeWeights())
```

The simplices indices are wrong: they should begin at index 0 instead of 3. Because of this, the last vertex index in the last simplex is 10, which does not exists. Hence, an exception stating that a wrong vertex index should be raised, but it is not, which is a bug.

**Comment by jschueller** [comment]
see isValid

**Comment by mbaudin47** [comment]
This generates a memory crash, because invalid indices are adressed.

**Comment by jschueller** [comment]
so I closed it too quickly

**Comment by jschueller** [comment]
isvalid is potentially costly, at creation or load
