### ISSUE TITLE
Doc of evaluation operator of KrigingResult 

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1549]
The KrigingResult class has a () operator which produces a distribution. However, this operator has no API documentation or example.
Moreover, the getResult method of KrigingAlgorithm has no API documentation.

An example in the KrigingAlgorithm API doc would be the following.
```
import openturns as ot
f = ot.SymbolicFunction(['x'],  ['x * sin(x)'])
sampleX = [[1.0], [2.0], [3.0], [4.0], [5.0], [6.0]]
sampleY = f(sampleX)
basis = ot.Basis([ot.SymbolicFunction(['x'], ['x']), ot.SymbolicFunction(['x'], ['x^2'])])
covarianceModel = ot.GeneralizedExponential([2.0], 2.0)
algoKriging = ot.KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
algoKriging.run()
x = ot.Point([1.0])
unknownVariableType = algoKriging(x)
```

An example in the KrigingResult API doc would be the following.
```
import openturns as ot
f = ot.SymbolicFunction(['x'],  ['x * sin(x)'])
sampleX = [[1.0], [2.0], [3.0], [4.0], [5.0], [6.0]]
sampleY = f(sampleX)
basis = ot.Basis([ot.SymbolicFunction(['x'], ['x']), ot.SymbolicFunction(['x'], ['x^2'])])
covarianceModel = ot.GeneralizedExponential([2.0], 2.0)
algoKriging = ot.KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
algoKriging.run()
resKriging = algoKriging.getResult()
x = ot.Point([1.0])
unknownVariableType = resKriging(x)
```

In both cases, a description of what exactly is this variable would be useful. An example with a detailed analysis would be interesting for users.

**Comment by regislebrun** [comment]
So we are talking about KrigingResult and not KrigingAlgorithm

**Comment by jschueller** [comment]
c++ says "Compute joint normal distribution conditionally to observations"
