### ISSUE TITLE
Docstrings suggest kwargs are available

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#1550]
Docstrings with '=' suggest that keyword arguments are available, eventhough methods bound to c++ objects dont allow them:
```
Available constructors:
    Triangular(*a=-1.0, m=0.0, b=1.0*)
...
    Cloud(*data, legend=' '*)

    Cloud(*dataX, dataY, legend=' '*)

    Cloud(*data, color, pointStyle, legend=' '*)

    Cloud(*dataComplex, legend=' '*)
```
Also listing constructors when only one is available is useless.

**Comment by josephmure** [comment]
This is a duplicate of #1077, isn't it?

**Comment by jschueller** [comment]
yes, thanks
