### ISSUE TITLE
Misc. bugs in PosteriorDistribution

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1552]
``PosteriorDistribution::getMarginal`` yields prior marginals instead of posterior marginals.
Look at the following script (adapted from the [doc](http://openturns.github.io/openturns/1.15/user_manual/_generated/openturns.PosteriorDistribution.html)):
```
import openturns as ot
ot.RandomGenerator.SetSeed(0)
# Normal model
conditionedDistribution = ot.Normal()
# Conditional distribution
atoms = [ot.Uniform(0.0, 1.0), ot.Uniform(1.0, 2.0)]
conditioning = ot.ComposedDistribution(atoms)
conditional = ot.ConditionalDistribution(conditionedDistribution, conditioning)
# Observations
observationsSize = 5
observationsDistribution = ot.Distribution(conditionedDistribution)
observationsDistribution.setParameter(conditioning.getMean())
observations = observationsDistribution.getSample(observationsSize)
# Posterior distribution
posterior_distribution  = ot.PosteriorDistribution(conditional, observations)

# Draw the PDF of the second marginal of the posterior distribution: it is the
# posterior distribution of the standard deviation of the Normal model.
posterior_distribution.getMarginal(1).drawPDF()

# Get a sample from the posterior distribution.
ot.RandomGenerator.SetSeed(1)
posterior_sample = posterior_distribution.getSample(1000)

# Draw the same PDF based on a kernel smoothing on the sample from the posterior.
ot.KernelSmoothing().build(posterior_sample.getMarginal(1)).drawPDF()

# Draw the posterior PDF.
posterior_distribution.drawPDF()

# Draw the posterior sample.
import maplotlib.pyplot as plt
plt.scatter(posterior_sample[:, 0], posterior_sample[:, 1])
```

The first picture is the output of ``posterior_distribution.getMarginal(1).drawPDF()``:
![bug_PosteriorDistribution_getMarginal](https://user-images.githubusercontent.com/31989332/87290634-87f5ed80-c4fe-11ea-8224-e35c9790f8fc.png)

It is the PDF of the prior uniform distribution on the second parameter (standard deviation of the normal model). Compare with the PDF estimated using kernel smoothing on a sample from the posterior distribution:
![bug_PosteriorDistribution_kernelsmoothing](https://user-images.githubusercontent.com/31989332/87290984-fc309100-c4fe-11ea-83ac-07f70a134211.png)

There is also something weird going on with that sample, however. Let us take a look:
![bug_PosteriorDistribution_sample](https://user-images.githubusercontent.com/31989332/87291236-4e71b200-c4ff-11ea-9839-542209a7dc8a.png)

Compare with the posterior PDF:
![bug_PosteriorDistribution_isodensities](https://user-images.githubusercontent.com/31989332/87291342-77924280-c4ff-11ea-95fd-1c1592de5f8c.png)

The most probable area, on the top left-hand corner (mean parameter close to 0 and standard deviation parameter close to 2), contains no point in the sample.

**Comment by jschueller** [comment]
MarginalDistribution does not implement computeCDF, but still it should go through DistirbutionIMPL::computeCDF and yield correct PDF values

**Comment by jschueller** [comment]
with the fix from #1565:
![Figure_1](https://user-images.githubusercontent.com/3832365/90019037-274d0280-dcae-11ea-8fd8-cf5095d8cff6.png)

![post](https://user-images.githubusercontent.com/3832365/90019148-4cda0c00-dcae-11ea-9ba1-d86b9fa376cf.png)

**Comment by josephmure** [comment]
Well, the sample seems wrong too, so I am not sure there actually is a spike to catch.

**Comment by jschueller** [comment]
it goes better if we use the generic ContinuousDistribution::computeCDF:
![posterior_pdf](https://github.com/openturns/openturns/assets/3832365/807175da-0f22-4d49-89d1-bf5a30747ec5)
but the cdf has singularities

**Comment by jschueller** [comment]
it goes better after I tweak the normalization factor:
![posterior_pdf](https://github.com/openturns/openturns/assets/3832365/3e5e00ad-bdc2-4e10-bbcd-424c93b014be)

![posterior_cdf_x0](https://github.com/openturns/openturns/assets/3832365/09f93cb5-7cf0-4fdc-834d-31ec6385b9f4)
![posterior_cdf_x1](https://github.com/openturns/openturns/assets/3832365/fdf81b00-69f1-4ada-8f45-7e6da5d495e7)
