### ISSUE TITLE
Optimization algorithms ignore MaxEvaluationNumber parameter in SORM

### ISSUE THREAD

**Issue by tsiplugin** [openturns/openturns#1553]
Good evening!
I try to solve reliability analysis problem using SORM with the Cobyla optimization algorithm. I've set the MaximumEvaluationsNumber to 3, but I'd get much more calls of the PythonFunction. Then I've made an experiment. After experiment l could see, that if blackbox function gets i-dimentional vector as argument and returns j-dimentional vector as result, then:
               if  j == 1 then extra_function_calls = 2(i^2) + 6i + 2
               if  j > 1 then extra_function_calls = 2(i^2) + 4i + 5

Here is my experiment code:

```
import openturns as ot
ot.RandomGenerator.SetSeed(100)
global counter
max_eval = 3
for i in range(1, 10):
    for j in range(1, 10):
        counter = 0
        input_amount = i
        output_amount = j
        def my_func(args) -> ot.Point:
            global counter
            counter+=1
            returnum = [0]*output_amount
            for n in range(output_amount):
                for m in range(input_amount):
                    returnum[n] = m*(args[m]**m)
            return returnum
        my_function = ot.PythonFunction(input_amount, output_amount, func=my_func)
        a = [200]*input_amount
        b = [10]*input_amount
        my_distribution = ot.Normal(a, b, ot.IdentityMatrix(input_amount))
        vect = ot.RandomVector(my_distribution)
        output = ot.CompositeRandomVector(my_function, vect)
        lower_bounds = [0]*output_amount
        upper_bounds = [1]*output_amount
        lower_bounds_finite = [False]*output_amount
        upper_bounds_finite = [True]*output_amount
        domain = ot.Interval(lower_bounds, upper_bounds, lower_bounds_finite, upper_bounds_finite)
        event = ot.ThresholdEvent(output, domain)
        solver = ot.Cobyla()
        #solver = ot.AbdoRackwitz()
        solver.setMaximumEvaluationNumber(max_eval)
        solver.setVerbose(True)
        solver.setMaximumAbsoluteError(1e-10)
        algo = ot.SORM(solver, event, my_distribution.getMean())
        algo.run()
        result = algo.getResult()
        print("Input args amount = %s" % str(input_amount))
        print("Output results amount = %s" % str(output_amount))
        print("Total number of function calls = %s" % str(my_function.getEvaluationCallsNumber()))
        print("counter = %s" % counter)
        print("Extra function call = %s\n" % (counter - max_eval))
```

Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
OpenTURNS version 1.15

I'm sorry about my english. English is not my native language.

**Comment by regislebrun** [comment]
Hi,
The different stopping criteria (maximum number of evaluations, maximum number of iteration and so on) are enforced as much as possible, it means:
- for the native OpenTURNS optimization algorithms (SQP&AbdoRackwitz) they are enforced
- for external algorithms interfaced with OpenTURNS (NLopt, Cobyla, TNC and so on) they are enforced as soon as the underlying algorithm implements them.
The maximum number of evaluations is one of Cobyla's stopping criteria, so it should stop (and it does) as soon as this maximum is reached, but up to OpenTURNS 1.15, the Lagrange multipliers of the constraints are systematically computed, involving a call to the gradient of each constraint. If these gradients are based on finite differences, you get additional calls to the function but **outside of** the optimization process.
This behavior has been changed in the upcoming version, you can switched off this computation thanks to the `OptimizationAlgorithm::enableLagrangeMultipliers()` method, see [here](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.OptimizationAlgorithm.html#openturns.OptimizationAlgorithm.enableLagrangeMultipliers).

Using Cobyla, you can trick OpenTURNS by providing a dummy implementation of the gradient as it is not used during the optimization process. In the case of a threshold event based on a comparison with a value it works, but in the case of a threshold event based on an interval it fails as it involves the computation of the gradient of a min/max function, which is not defined and triggers an evaluation using finite differences.

To summarize:
- with OpenTURNS 1.15 and below the Lagrange multipliers are always computed, which involves the computation of the gradient of the objective function. You will be able to deactivate it in the new release.
- if the gradient is computed using finite differences (which is the default when you don't provide the gradient of your PythonFunction) you get additional calls to the function. The default is to use centered differences, you ca reduce the number of additional calls by using non-centered differences
- if you don't need the gradient during the optimization you can provide a dummy gradient. Keep in mind that the actual gradient of interest is the gradient of the composed function between the characteristic function of your interval, your function and the iso-probabilistic transformation of your input distribution. As this characteristic function is not differentiable at the boundary of the interval the computation falls back to centered finite differences and there is no way to change it. This trick works perfectly if you define your event as a ThresholdEvent based on a comparison wrt a scalar.

**Comment by jschueller** [comment]
@regislebrun I had also had an user complaining about that previously.
I propose to disable the lagrange multipliers by default, what do you think ?

**Comment by regislebrun** [comment]
Good idea. It is even possible to compute them as a post-processing if we move the computeLagrangeMultipliers() method from OptimizationAlgorithmImplementation to OptimizationResult, as it only needs the optimal point and the optimization problem, both being already available in the OptimizationResult.
