### ISSUE TITLE
Pictures do not appear in "latest" doc

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1557]
Pictures included in the doc do not appear in "latest" version:

http://openturns.github.io/openturns/latest/examples/reliability_sensitivity/flood_model.html

They do appear in the "master" version:

http://openturns.github.io/openturns/master/examples/reliability_sensitivity/flood_model.html

**Comment by jschueller** [comment]
it was added after 1.15: #1400

**Comment by josephmure** [comment]
OK, good to know!

**Comment by josephmure** [comment]
@jschueller  Could you reopen please? The picture in 

http://openturns.github.io/openturns/latest/examples/meta_modeling/kriging_cantilever_beam.html

does not appear either in "master" either.

**Comment by josephmure** [comment]
The problem is still not fixed:

https://openturns.github.io/openturns/master/auto_meta_modeling/kriging_metamodel/plot_kriging_cantilever_beam.html

**Comment by josephmure** [comment]
The picture is now visible in the Use-case section. The reader simply has to follow the link at the top of the page.
