### ISSUE TITLE
There is no example to bootstrap the polynomial chaos

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1568]
The polynomial chaos produce sensitivity indices. However, there is no confidence interval of these sensitivity indices. This may, however, be computed from bootstrap, resampling within the training sample. This is not so easy, because the library does not currently provides a way to bootstrap both input and outputs. Once bootstrap sensitivity indices are computed, it is easy to estimate the distribution of the sensitivity from kernel smoothing. Confidence intervals can then be derived from the kernel smoothing bootstrap distribution.

The following example does exactly this on the cantilever beam example:

[Chaos-cantilever-beam-Bootstrap.ipynb.txt](https://github.com/openturns/openturns/files/5040542/Chaos-cantilever-beam-Bootstrap.ipynb.txt)

This example will be included within OT documentation by a contract which is currently being organized. It should be available within one or two months.

An interesting research topic would be to derive the asymptotic distribution of the sensitivity indices, based on the fact that a polynomial chaos is just a regression model. Since the asymptotic distribution of the coefficients of a regression model are known, we should be able to apply this theory to polynomial chaos. This would be a more accurate way to estimate the intervals than bootstrap, provided that the initial sample size is large enough to enter in the asymptotic regime.

**Comment by sofianehaddad** [comment]
@mbaudin47 thanks for sharing the notebook.
 
IMHO we should use **exactly** the same **sparse basis**, meaning the same **multivalve basis** & **same indices** with *LARS*. Otherwise we face two issues :

- Computational aspects : if we use again `LARS` it might take time with `bootstrap` (of course depending on data size, dimension & other elements)

- Interpretation. If we get several different **final basis**, it becomes complicated to make analysis and thus to compute mean of the various indices.

Using the same sparse basis is more complex in the library. I can share a script to perform it after some cleaning.

**Comment by mbaudin47** [comment]
Thank you very much for sharing this script. I totally agree : using the same basis was the next step in my roadmap. Your use of the DesignProxy is indeed more complicated and seems the efficient way to go. This will make an excellent and quite sophisticated example to be integrated in the examples section of the doc, isn'it @KieranDelamotte ?

**Comment by sofianehaddad** [comment]
We might think about using a `UserDefinedEnumerateFunction(list_selected_indices)` Then applying a **non sparse chaos** with this enumerate function + multivariate basis + FixedStrategy, we might derive an algo class/post processing without using the `DesignProxy`. Maybe we should keep this in mind @mbaudin47 for further discussions. What do you think? Do you have something else in mind ?

**Comment by mbaudin47** [comment]
So, once the first selection was done, the `list_selected_indices` could be retrieved with `FunctionnalChaosResult.getIndices()`, and used with the remaining bootstrap resamples. This allows to use the `FunctionalChaosAlgorithm` as is, without modification: all we do is to use a specific way of enumerating the polynomials on a specific basis, defined by the user. This sounds to be doable, simple and efficient. 
I read your NB into more detail: you did an impressive job of merging the NB I suggested with your mastering of the `DesignProxy`. The result is as short as can be with the current tech.
This reveals that the `DesignProxy` can be used in an applied example, not directly inside the C++ OT: may be an example of this class might be welcome in the doc, isn'it? I would have a purpose for this example: since the analytic asymptotic distribution of the regression coefficient would be retrieved with e.g. QRMethod.getGramInverse(), an example of creating a `DesignProxy` from scratch would be required. There is, however, an example of using getGramInverse in the calibration context:

https://github.com/openturns/openturns/blob/6cde44895358ade4033a74de0453f8131fe030ac/lib/src/Uncertainty/Bayesian/GaussianLinearCalibration.cxx#L163

Once done, the `Normal` instance of the distribution of the coefficients would be created directly, as in the `GaussianLinearCalibration` example (see L165).

**Comment by regislebrun** [comment]
In my opinion, as we know the list of basis functions to use (returned by FunctionalChaosResult::getReducedBasis()) for the subsequent runs, it would be more natural to use it to build a finite orthogonal basis. Unfortunately, OT allows to build a finite basis (thanks to the FiniteBasis class, accessible through the Basis interface) but not a finite orthogonal basis. It would be quite easy to create it with the following constructor:
```
FiniteOrthogonalBasis::FiniteOrthogonalBasis(const Collection<Function> & coll, const Distribution & measure)
```
but as we plan to redesign the whole Basis/OrthogonalBasis hierarchy I am not sure if it is a good idea to add a class to the current hierarchy.
