### ISSUE TITLE
ResourceMap reset

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1571]
Feature request: it would be nice if the ``ResourceMap`` had a ``reset()`` method that would restore all keys to their default values.

**Comment by jschueller** [comment]
http://openturns.github.io/openturns/master/user_manual/_generated/openturns.ResourceMap.html?highlight=resourcemap#openturns.ResourceMap.Reload ?

**Comment by josephmure** [comment]
Ah, ok. Did not know about this method. Thanks!
