### ISSUE TITLE
LogNormal::computeRange

### ISSUE THREAD

**Issue by GuiGag** [openturns/openturns#1577]
ComputeRange for LogNormal distributions seems to return inadequate values.
lowerBound is set to gamma, which may be overkill in case of of a large mu/sigma ratio
upperBound is evaluated using computeScalarQuantile which seems to truncate a non negligible part of the distribution

Example plot with mu=3e4, sigma = 3e3, gamma=0, X-axis has been resized to match values returned by computeRange
![distributionPDF](https://user-images.githubusercontent.com/66832525/90483215-ade16400-e134-11ea-9448-7e8db727e364.png)

**Comment by josephmure** [comment]
Here is a script that draws the PDF of your LogNormal distribution. The X interval is set using `getRange()`

```
import openturns as ot
from openturns.viewer import View
myParam = ot.LogNormalMuSigma(3e4, 3e3, 0.0)
myDist = ot.ParametrizedDistribution(myParam)
r = myDist.getRange()
lower = r.getLowerBound()[0]
upper = r.getUpperBound()[0]
box = ot.Interval([lower, 0.0], [upper, 1.4e-4])
graph = myDist.drawPDF()
graph.setBoundingBox(box)
View(graph)
```

![lognormal_range](https://user-images.githubusercontent.com/31989332/90611029-81961800-e206-11ea-8514-be081736f93c.png)

There may be overkill on both lower and upper bound, but I cannot reproduce the truncation issue.

**Comment by GuiGag** [comment]
Thanks for the heads up!
In fact, there is no truncation, I just rescaled the X-axis to point out the values returned by computeRange().
I guess I should use getRange() then
My bad...

**Comment by josephmure** [comment]
You're welcome! I don't understand how you were able to call [computeRange()](https://github.com/openturns/openturns/blob/ececf785cb174a261204229d74cc3165b45aafc3/lib/src/Uncertainty/Distribution/openturns/LogNormal.hxx#L165), though. It is supposed to be a private method and  `getRange()` is the public accessor to the `Interval` previously computed by `computeRange()`.
