### ISSUE TITLE
Option to suppressing and/or save warnings?

### ISSUE THREAD

**Issue by Aorus42** [openturns/openturns#1578]
Hello,

I have two questions regarding OpenTURNS warnings:

1. Is there an option to suppress warnings from displaying in the console, for example
`WRN - You are using a default implementation for the hessian. Be careful, your computation can be severely wrong!`
?

2. I believe I raised this several months ago (apologies if I am repeating myself, but I cannot find the answer), but is there a way to capture and save warnings from a reliability algorithm (FORM or SORM) in a Python variable? I the reason I ask is that I am calculating limit states for several thousand cases on a computing cluster and would like to identify which cases run into potential problems.

Thank you,
Phil

**Comment by josephmure** [comment]
Hi Phil, 

1. to suppress all warnings you only need to add `ot.Log.Show(ot.Log.NONE)` at the beginning of your script. Thanks to @regislebrun for [this tip](https://gitter.im/openturns/community?at=5f2426bf36563560f2b4fb7e).
2. you can save all warnings in a log file by adding `ot.Log.SetFile("Warnings.log")` at the beginning of your script. Obviously, this is not compatible with `ot.Log.Show(ot.Log.NONE)`.

For more information about warnings, check out [this doc page](http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Log.html#openturns.Log.Show) and [this test script](https://github.com/openturns/openturns/blob/12c832da852833d12a9a9a428641f5b82b624735/lib/test/t_Log_std.cxx#L88).
