### ISSUE TITLE
Documentation: description error in the API for the FittingTest_BestModelKolmogorov and FittingTest_BestModelChiSquaredclasses

### ISSUE THREAD

**Issue by EmmanuelArdillon** [openturns/openturns#1586]
For these 2 classes there is a mistake in the description of the return "Best model":
"The best distribution for the sample according to Bayesian information criterion. This may raise a warning if the best model does not perform well."

This sentence is relative to the BIC best model class, it has to be corrected for Kolmogorov and Chisquared classes.

[http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.FittingTest_BestModelKolmogorov.html?highlight=kolmogorov%20best%20model#openturns.FittingTest_BestModelKolmogorov](url)

**Comment by josephmure** [comment]
Thanks for letting us know that @EmmanuelArdillon. I've committed a fix and it is likely going to be included in 1.16.
