### ISSUE TITLE
The drawPDF method of the Triangular distribution is wrong

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1591]
The drawPDF of the `Triangular` method seems to be wrong is some cases.

The following script:

```
triangular = ot.Triangular(0.45, 0.95, 1.03)
truncated.drawPDF(0.95, 1.03, 100)
```

produces:

![image](https://user-images.githubusercontent.com/31351465/92446931-dd751080-f1b6-11ea-98d6-1ba15336b381.png)

The graphics presents a flat function. This is not correct, since we plot the function from its mode down to zero. The table of PDF values seems correct:

```
0.95 3.4482758620689653
0.9588888888888889 3.065134099616856
0.9677777777777777 2.6819923371647514
0.9766666666666667 2.2988505747126418
0.9855555555555555 1.9157088122605372
0.9944444444444445 1.532567049808428
1.0033333333333334 1.1494252873563184
1.0122222222222221 0.7662835249042188
1.021111111111111 0.3831417624521094
1.03 -0.0
```

Since the drawPDF cannot be wrong, I deduce that the `Triangular` distribution has a bug, that I cannot identify.

**Comment by jschueller** [comment]
works for me, looks like you're using the wrong variable (truncated instead of triangular)
![tri](https://user-images.githubusercontent.com/3832365/92448037-5b85e700-f1b8-11ea-9cb0-9a2f5b05854d.png)

**Comment by mbaudin47** [comment]
Oups! You are right, sorry.
