### ISSUE TITLE
The fieldfunction_metamodel example has a bug

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1600]
The example in:

https://openturns.github.io/openturns/master/examples/meta_modeling/fieldfunction_metamodel.html

has a bug. The cell #10:

![image](https://user-images.githubusercontent.com/31351465/94284820-35e83400-ff53-11ea-88f1-029254323359.png)

does not show the axes of the Graph.

**Comment by KieranDelamotte** [comment]
Regarding this issue, I made a similar change in the PR #1632 . However, I am not sure if it is really a bug in the example or if it is the `add` method of `Graph' having some funny behavior.
I will probably do some corrections similar to PR #1632 at first.

**Comment by regislebrun** [comment]
@KieranDelamotte By default, neither the axes or the grid are activated using the default constructor of Graph. Using the copy constructor, you get what was activated in the graph being copied. BTW I don't see why one should cast graph_ev_x into a Graph as it should already be one. Is it reused afterward?
The solution is to activate the axes using graph.setAxes(True), and IMO even add graph.setGrid(True) as it improves the reading of the results. As the eigenvalues are expected to be positive and rapidly decreasing, one should set a logarithmic scale on the Y axis: `graph.setLogScale(GraphImplementation.LOGY)` or `graph.setLogScale(2)` for short.

**Comment by KieranDelamotte** [comment]
Thanks for the clarification @regislebrun. I agree about the cast, I'll correct it as well.
