### ISSUE TITLE
MaximumLikelihoodFactory cannot be used with FittingTest.Kolmogorov

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1605]
Trying to check if a sample can be modeled using an Exponential distribution with known shift parameter results in an exception. 
The following code should work:
```
from openturns import *

n = 10
alpha = 0.05
data = Exponential(2.5).getSample(n)
factory = MaximumLikelihoodFactory(Exponential())
factory.setKnownParameter([0.0], [1])
# Here it works
print("Direct use of the factory", factory.build(data))
size = 100
ResourceMap.SetAsUnsignedInteger("FittingTest-KolmogorovSamplingSize", size)
# Here it doesn't
res = FittingTest.Kolmogorov(data, factory, alpha)
print("H=", int(not res[1].getBinaryQualityMeasure()), "pValue=", res[1].getPValue(), "KSstat=", res[1].getStatistic(), "crit=", float('nan'), "alpha=", res[1].getThreshold())
```
but it is not the case...

**Comment by jschueller** [comment]
I see, we can return the distribution passed to MaximumLikelihoodFactory with the known parameters.

**Comment by josephmure** [comment]
There is a typo in the title of the issue : "K**l**omogorov". It is not important by itself but it would be better to correct it in order not to defeat searches in the ChangeLog @jschueller.

**Comment by jschueller** [comment]
ok
