### ISSUE TITLE
(Normal|Exponential|...)Factory::build produces an object of the generic Distribution class

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1607]
Distribution factories build methods yield objects of the generic `Distribution` class, not of the relevant daughter class.

```
import openturns as ot
sample = ot.Sample([[0.0], [0.1], [0.2], [0.3], [0.4], [0.5]])

print("The type of a Normal distribution is {}".format(type(ot.Normal())))
normal = ot.NormalFactory().build(sample)
print("But the output of the NormalFactory build() is {}".format(type(normal)))

print("The type of an Exponential distribution is {}".format(type(ot.Exponential())))
exponential = ot.ExponentialFactory().build(sample)
print("But the output of the ExponentialFactory build() is {}".format(type(exponential)))
```

Output:

```
The type of a Normal distribution is <class 'openturns.dist_bundle2.Normal'>
But the output of the NormalFactory build() is <class 'openturns.model_copula.Distribution'>
The type of an Exponential distribution is <class 'openturns.dist_bundle1.Exponential'>
But the output of the ExponentialFactory build() is <class 'openturns.model_copula.Distribution'>
```

As a result, methods that are specific to a distribution are unavailable. For example, `normal.getSigma()` and `exponential.getLambda()` both produce errors.

**Comment by regislebrun** [comment]
It is a limitation or the C++ inheritance model. Use buildAsXXX method to cet an actual instance of the XXX distribution

**Comment by josephmure** [comment]
In that case, wouldn'it it be better to remove the `build` method altogether? Doesn't this create unnecessary confusion?

**Comment by regislebrun** [comment]
You need a generic build() method in order to call a factory regardless of the underlying model (eg in FittingTest.BestModelKolmogorov), and you appreciate to have a buildAsXXX() method when there is a unique factory involved and you want to get an actual XXX distribution.

**Comment by josephmure** [comment]
Yes, taking the example of the [ExponentialFactory](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.ExponentialFactory.html?highlight=buildasexponential#openturns.ExponentialFactory.build), it is true that both `build` and `buildAsExponential` are documented, and the return type of `build` is marked as `Distribution`. However, I did not really register this to mean that the returned type of `build` is the generic `Distribution`. I merely thought that the doc had been copy-pasted over all `Factory` classes... ;)
