### ISSUE TITLE
FittingTest::BIC returns MaxScalar when it should return Infinity

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1615]
As part of the compromise that was reacher a CT#16, the FittingTest::BIC was modified so that whenever it should return Infinity, it returns SpecFunc::MaxScalar instead.

A better solution should be found (whether through infinity or exception handling).

This is part of a more general discussion on how to handle nonstandard floating values.

**Comment by josephmure** [comment]
Here is a summary of the discussions (courtesy of @mbaudin47 on PR #1566).
There are two correct strategies

    generate exceptions,
    generate exceptional floating point numbers such as INFs and NANs.

There are wrong strategies.

    A wrong strategy is to produce warnings, because these rather silent message are unnoticed by most users.
    A wrong strategy is to produce MaxScalar when the result is INF. This is because using a finite floating point number is very different from using INF. For example, we may use the following code in order to produce the number 1 based on MaxScalar:

x =MaxScalar
for i in range(53):
    x /= 2.0

This is impossible when x is INF, which is good.

Here are the arguments against INF and NANs:

    A INF or a NAN is not a real number. Hence, this is not what most users expect as the return of a function. However, because we always perform computations with floating point numbers, indeed, nobody should expect a real number as the output of a C++ or a Python function returning a float.
    Using them slow down the computation, because the performance of the libraries are poor when dealing with exceptional floating point numbers. @regislebrun This assertion requires some factual proofs.
    We do not know how OT dependencies (e.g. NLOPT, etc…) react to these exceptional numbers. @regislebrun This assertion requires some factual proofs, with examples of poor management of floating point numbers.

Here are a few ways to constructively produce a correct code.

    Remplace -MaxScalar by Lowest.
    Create an alternate PR with exceptions in the logPDF methods of all distributions. I am against such an implementation, because this is useless if Joseph's PR is used.

The lowest field is provided in std::numeric_limits:

http://www.cplusplus.com/reference/limits/numeric_limits/

However, according to the previous page, "For floating-point types: implementation-dependent; generally, the negative of max().". Hence, the code in OT would be:

const Scalar Specfun::Lowest = -MaxScalar;

Then, we would use Lowest in place of -MaxScalar wherever appropriate.

An option would be to build the code with an option which raises an exception each time an INF number is produced.

Below is a reference which might be related:

    https://randomascii.wordpress.com/2012/04/21/exceptional-floating-point/
    https://stackoverflow.com/questions/9366215/why-does-gcc-report-a-floating-point-exception-when-i-execute-1-0

**Comment by regislebrun** [comment]
We all should definitely read the series of posts [here](https://randomascii.wordpress.com/category/floating-point/), in particular this one: https://randomascii.wordpress.com/2012/05/20/thats-not-normalthe-performance-of-odd-floats/
As I said during the CT, I learned from experience that exceptional floating point numbers have a huge performance penalty. But it was based on quite old experiment, when x87 was the norm and SSE2 was not so widespread. And you can read in the previous article that the performance penalty was up to a 900x slowdown. Now, it looks like NaNs and Infs are processed at full speed.
For those who are too much optimistic about the guarantees provided by a standard regarding eg the reproducibility of a computation, they should read [this article](https://randomascii.wordpress.com/2012/03/21/intermediate-floating-point-precision/), or at least have a look at the final flowchart https://randomascii.files.wordpress.com/2012/03/image6.png
Remember that the different rounding modes are not taken into account in this flowchart!
Concerning the added value of exceptions, read [this, already referenced by Joseph](https://randomascii.wordpress.com/2012/04/21/exceptional-floating-point/) **Note that the author underline the utility of letting inf sneak into the computation from time to time** so the use of inf is **not** a systematic devil, but its global propagation **is.**

**Comment by josephmure** [comment]
I suggest that from now on, we restrict ourselves to the particular issue concerning the BIC on this ticket. For the general discussion about using or not using INFs, we should move to the corresponding forum thread:

https://openturns.discourse.group/t/should-methods-be-allowed-to-output-infinity/44

**Comment by josephmure** [comment]
Closing because of the dedicated thread on Discourse.
