### ISSUE TITLE
The Search engine does not work

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1616]
I use the URL:

https://openturns.github.io/openturns/master/search.html

and i search for "symbolicfunction":

![image](https://user-images.githubusercontent.com/31351465/95902864-ae455680-0d95-11eb-8e6f-879ef21af3d5.png)

When I click on "Search", nothing appears:

![image](https://user-images.githubusercontent.com/31351465/95903003-dcc33180-0d95-11eb-9e46-86c720f6e6f3.png)

**Comment by jschueller** [comment]
_static dir is located into python/doc/usecases instead python/doc

**Comment by jschueller** [comment]
it still fails, seems some js files are misplaced now

**Comment by KieranDelamotte** [comment]
@jschueller 
What do you mean by misplaced ?

**Comment by jschueller** [comment]
I thought js files should go into /js 
https://github.com/openturns/openturns.github.io/tree/master/openturns/master/_static

**Comment by jschueller** [comment]
seems to work after all, maybe not everything was published, sorry
