### ISSUE TITLE
We cannot square a Distribution

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1617]
The following script:
```
import openturns as ot
X = ot.Normal()
Y = X^2
```
produces:
```
TypeError: unsupported operand type(s) for ^: 'Normal' and 'int'
```
However, the following script performs well:
```
import openturns as ot
X = ot.Normal()
Y = X * X
```
In the actual script, we raised X - Y to the power 4, where X and Y are univariate distributions.

(This is one error based on experiments with otbenchmark.)

**Comment by mbaudin47** [comment]
Below is another use case.
```
X = ot.Normal()
Y = ot.Normal()
Z = max(X, Y)
```
which produces:
```
TypeError: '>' not supported between instances of 'Normal' and 'Normal'
```

**Comment by regislebrun** [comment]
You can actually square a distribution, but not using your syntax:
```
Y=X.sqr()
```
By the way, `Y=X.sqr()` and `Y=X*X` are different distributions as shown in the following figure:
![Figure_1](https://user-images.githubusercontent.com/8220933/95916587-2d905580-0da9-11eb-9b03-6d146c558cf2.png)
You can see that `Y` is positive while `Z` can take negative values. The multiplication `X*X` means that you are defining the distribution of the product of two independent copies of X! What we call 'distribution arithmetic' is rather an 'independent random variables arithmetic' where each instance of `X` means 'an iid copy of `X`'

Concerning the `max` operator, it could easily be added as we already have the `MaximumDistribution` class. In the mean time you have to use:
```
Z=MaximumDistribution([X,Y])
```
but you can also use:
```
Z=MaximumDistribution([X,X])
```
to get the distribution of the maximum of two independent RV distributed according to `Normal()`!

**Comment by regislebrun** [comment]
... and it works like a charm!

**Comment by mbaudin47** [comment]
That is correct: I will use this.
Another user use-case:
```
X = ot.Normal()
Y = 32 / (X ** 3)
```
produces
```
TypeError: unsupported operand type(s) for /: 'int' and 'Distribution'
```

**Comment by regislebrun** [comment]
Right. You have to use `Y=32*(X**3).inverse()` or even `Z=32*X**(-3)`. The first one gives you a distribution whose PDF evaluates to inf regardless of the input (so perfectly fitted to your needs ;-)), the second one is much more reasonable:
![Figure_1](https://user-images.githubusercontent.com/8220933/95920383-a2ff2480-0daf-11eb-83c5-b6ef17b2af9d.png)
but unfortunately you have to provide the bounds by yourself for the plot, because the automatic computation of the bounds gives you... inf! And then you get:
```
TypeError: InvalidArgumentException : Error: cannot draw a PDF with xMax <= xMin, here xmin=inf and xmax=-inf
```

**Comment by jschueller** [comment]
- Distribution is missing the reverse div operator, I have a possible fix
- Python max operator is supposed to return a bool, I think we cannot expect to return a Distribution

**Comment by mbaudin47** [comment]
These issues were identified from using otbenchmark: https://github.com/mbaudin47/otbenchmark/pull/59
