### ISSUE TITLE
Overlarge yellow box at the top of doc pages

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1619]
The "Note" box at the top of all doc pages should be downsized or removed. Its size varies accross pages, but it is always too large.

![Fat_yellow_box](https://user-images.githubusercontent.com/31989332/96032293-c1702900-0e5e-11eb-8ef2-4c74dcd59022.JPG)

**Comment by KieranDelamotte** [comment]
I have seen it and should correct it tomorrow. It does not appear locally for me though.

**Comment by josephmure** [comment]
Theoretically, the linked PR should remove the box entirely.

**Comment by KieranDelamotte** [comment]
This is perfect !
