### ISSUE TITLE
ProcessSample.set_item(field) hangs

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/openturns#1627]
Hi
Before releasing [1.15](30da434f21be48ec3d53111c014479477db29cca) we update `ProcessSample` interface such as `{get, set}item` rely on a `Sample` instead of a `Field`.

If one has "oldest" scripts in which we feed `[i]` with fields, then code sometimes hangs...

```
import openturns as ot
mesh = ot.RegularGrid(0, 1, 100)
process_sample = ot.ProcessSample(mesh, 10, 1)
field = ot.Field(mesh, 1)
process_sample[0] = field
```

**Comment by jschueller** [comment]
hi, I cant replicate the issue, even with a for loop

**Comment by sofianehaddad** [comment]
Strange maybe it is only specific to my config? (osx)
Seems it is random a with (sometimes) a segfault msg.

**Comment by jschueller** [comment]
how often ?

**Comment by sofianehaddad** [comment]
very few. Got it twice I think
I reset everything. It is maybe related to another issue
