### ISSUE TITLE
bic yields maxscalar

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#1629]
with latest changes, BIC gives maxscalar for a case where the previous result was ~9.46:

```
import openturns as ot
N = 300
sample = ot.Normal(3).getSample(N)
sample.stack(ot.Gumbel().getSample(N))
sample.setDescription(['X0', 'X1', 'X2', 'X3'])
sample = sample.getMarginal([0, 3])
sample = sample.rank() / sample.getSize()
factories = [ot.NormalCopulaFactory(), ot.GumbelCopulaFactory()]
for factory in factories:
    distribution = factory.build(sample)
    bic = ot.FittingTest.BIC(sample, factory)
    print(bic)


# master:
[class=NormalCopula name=NormalCopula dimension=2 correlation=class=CorrelationMatrix dimension=2 implementation=class=MatrixImplementation name=Unnamed rows=2 columns=2 values=[1,0.0580361,0.0580361,1], 1.7976931348623157e+308]
[class=GumbelCopula name=GumbelCopula dimension=2 theta=1.03839, 1.7976931348623157e+308]

# 1.15:
[class=NormalCopula name=NormalCopula dimension=2 correlation=class=CorrelationMatrix dimension=2 implementation=class=MatrixImplementation name=Unnamed rows=2 columns=2 values=[1,0.0580361,0.0580361,1], 9.463136136270297]
[class=GumbelCopula name=GumbelCopula dimension=2 theta=1.03839, 9.465332479832988]
```

cc @josephmure

**Comment by jschueller** [comment]
its and independent sample, so ok it should be +inf I guess

**Comment by josephmure** [comment]
When I run your script, `sample` contains zeros, so there are points at the boundary of the domain. The probability of the boundary under any normal or Gumbel copula is null, which is why the BIC is theoretically infinite. This is basically the same issue as the one corrected in commit  https://github.com/regislebrun/openturns/commit/1dff007ecdddb6d96cbe9e1bcda83d688015743b by @regislebrun.

**Comment by jschueller** [comment]
ok

**Comment by regislebrun** [comment]
You should replace `sample.rank() / sample.getSize()` by either `(sample.rank()+1) / sample.getSize()` (classical empirical copula sample) or `(sample.rank()+0.5) / sample.getSize()` (unbiased empirical copula sample)

**Comment by jschueller** [comment]
thanks, that's much better
