### ISSUE TITLE
computeStandardDeviation exception

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1635]
I vagely remember we talked about this problem but I don't find the related issue. 
This code throws "RuntimeError: InternalException : Error: the matrix is not definite positive" :
```
sample = ot.Sample(3, [-2, 0.3, 0.1])
sample.computeStandardDeviation()
```
while the awaited result is [[0, 0] [0, 0]]

PS: as the name is misleading for newcomers who in fact are looking for ```sample.computeStandardDeviationPerComponent()```
we easily come through this issue.

**Comment by josephmure** [comment]
The [doc](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.Sample.html?highlight=computestandarddeviation#openturns.Sample.computeStandardDeviation) states that the output is the lower left Cholesky factor of the covariance matrix, so the exception raised in your example is no surprise. However, I agree that the name of the method is misleading. Shoudn't it be `computeCovarianceCholesky` or somesuch?

**Comment by regislebrun** [comment]
IMO we should simply drop this method, or make it point to computeStandardDeviationPerComponent, as we expected to have a neat multivariate extension of the standard deviation when we defined this method, but I don't know any actual use of it...
