### ISSUE TITLE
Search results do not recognize examples

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1636]
Examples are no more appearing in the Search results.

To my knowledge, the search tool analyzes the url (Regex) to distinguish between "API", "Theory" and "Examples"
I suspect that the directory structure has changed and there is no more a directory called "Example/" or something like that.

**Comment by jschueller** [comment]
I removed the _py suffix, my bad:
mysearchtools.js:29:      else if (result[0].includes("auto_py")){

**Comment by KieranDelamotte** [comment]
Thanks @jschueller

**Comment by Jean-A** [comment]
Examples do appear again in the results but are not prefixed.  Any commit missing?
They are supposed to appear on top of the results with prefix "Example:..." (vs "API: ..." or "Theory: ...")
