### ISSUE TITLE
ImportanceSampling doc page still accessible on master branch

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1640]
The doc page of the removed class `ImportanceSampling` is still accessible in *master* :

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.ImportanceSampling.html

It is even indexed by search engines: if you google "importance sampling openturns", it is the first link you see.

By the way, what is the current procedure to do what `ImportanceSampling` formerly did?

**Comment by jschueller** [comment]
see https://openturns.github.io/openturns/latest/theory/reliability_sensitivity/importance_simulation.html#importance-simulation

**Comment by jschueller** [comment]
should be ok when github refreshes
