### ISSUE TITLE
Big white space at the beginning of examples

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1642]
Here an example of the phenomenon: https://openturns.github.io/openturns/latest/auto_graphs/plot_graphs_basics.html?highlight=composeddistribution

The analysis of the html code shows that a css file "_Static/Basic.css" on the server is interfering.
More precisely, the line 697 in Basic.css "clear: both;" that should be replaced by "clear: left;"

My understanding is that "Basic.css" is added on the server side during the build of the doc. The phenomenon is not observed on local installation.
@jschueller : can you try to change this line at the source to see if it corrects the bug?

**Comment by Jean-A** [comment]
Yes @josephmure, it is probably the same bug.
I suggested a correction by changing a line in "Basic.css"
@KieranDelamotte doesn't have this file on his local install and as I understood, it no use to commit it for it will be overwritten by the build of the documentation on the server.
That's why I asked @jschueller if we can change it at the source.

**Comment by josephmure** [comment]
For some reason, although the fix in https://github.com/openturns/openturns/pull/1648 is merged, the published doc does not seem to take the [new custom.css rule](https://github.com/openturns/openturns/pull/1648/commits/f073f4798a90ba4b5d8d0dfa05f02671f5dafba3) into account.

**Comment by josephmure** [comment]
Is it because there is no newline at the end of the custom.css file?

**Comment by josephmure** [comment]
I don't think my local version of sphinx is the latest release but I doubt this is a sphinx issue: Firefox can display the custom.css file used and it looks like it is not the new but the old custom.css that is used by the1.16rc1 build.

![wrong_custom_css](https://user-images.githubusercontent.com/31989332/99117174-93187180-25f5-11eb-9e83-d6078ad40448.png)

When I write the new lines from the commit manually in Firefox's editor, it displays the page correctly, like on my local build.
![correct_custom_css](https://user-images.githubusercontent.com/31989332/99117479-120daa00-25f6-11eb-92f3-b204fc5a14fc.png)

**Comment by Jean-A** [comment]
The current version of custom.css accessed a this url: https://openturns.github.io/openturns/master/_static/css/custom.css is obviously the old one
@josephmure are you sure your commit has been tagged 1.16?

**Comment by josephmure** [comment]
I don't know what it means for my commit to be "tagged" 1.16. It was merged in the 1.16 branch: https://github.com/openturns/openturns/commits/1.16

Isn't that enough?

**Comment by jschueller** [comment]
seems fine: https://openturns.github.io/openturns/1.16/auto_graphs/plot_graphs_basics.html

**Comment by Jean-A** [comment]
In fact, you can see that:
https://openturns.github.io/openturns/1.16/_static/css/custom.css  : OK
but:
https://openturns.github.io/openturns/master/_static/css/custom.css  : NOK
https://openturns.github.io/openturns/latest/_static/css/custom.css  : NOK

**Comment by josephmure** [comment]
@jschueller Do you know why the new custom.css was suddenly taken into account in 1.16 and in master? It still is not taken into account by latest, however.
