### ISSUE TITLE
Problem in MaximumDistribution PDF

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1643]
coll = [ot.Uniform(), ot.Normal()]
distribution = ot.MaximumDistribution(coll)
distribution.computePDF([1.1])
gives >>> 0.0

It seems that: computePDF (x) = 0 for x > 1

**Comment by regislebrun** [comment]
Good catch! The problem is in MaximumDistribution::computePDF(), line 167:
```
if ((cdf == 0) || (cdf == 1.0)) return 0.0;
```
should be replaced by:
```
if (cdf == 0) return 0.0;
```
I will fix it in an upcoming PR

**Comment by Jean-A** [comment]
Thank you @regislebrun
