### ISSUE TITLE
2D drawCDF axes bounds values

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1644]
Not sure it is a bug.

When I plot the CDF of  ot.ComposedDistribution([U, U]  with U = ot.Uniform()
the grah limits are [-3, 3] and not [-1, 1]. Is it the desired behaviour ?
![image](https://user-images.githubusercontent.com/52526981/97627336-87408300-1a2b-11eb-92cc-ae4dc365f853.png)

By the way, drawPDF() cannot plot iso-lines for the density is constant in this case. 
![image](https://user-images.githubusercontent.com/52526981/97627888-4ac15700-1a2c-11eb-9bb0-a58870da71e1.png)

**Comment by regislebrun** [comment]
Yes, it is the expected behaviour to show that the CDF is defined everywhere and not only on the range of the distribution. For the constant densities it is not easy to draw something very meaningful using iso-lines. I don't have a better idea than the current solution...

**Comment by Jean-A** [comment]
Thank you @regislebrun 
For the PDF, I don't see a solution with iso-lines. Another solution would be to color a meshgrid but this is another story.
I will close the issue.
