### ISSUE TITLE
UserDefinedStationaryCovarianceModel needs a SymmetricMatrixCollection

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1649]
The matrices C_k do not need to be positive definite, only symmetric.
The global matrix for a whole sample needs to be positive semi-definite.

**Comment by josephmure** [comment]
@jschueller I think this is a bug, not a doc issue. The constructor requires a  `CovarianceMatrixCollection` when it should only require a `SymmetricMatrixCollection`. It is only when the covariance matrix of the design set has been build that we can check for positive definiteness.

**Comment by sofianehaddad** [comment]
Agreed with @josephmure it is not only a doc issue. Ctor should be changed (see [here](https://github.com/openturns/openturns/blob/master/lib/src/Base/Stat/UserDefinedStationaryCovarianceModel.cxx#L48) the ctor)

**Comment by sofianehaddad** [comment]
Seems this one is fixed. Isn't it?

**Comment by jschueller** [comment]
yes #1664
