### ISSUE TITLE
There is no example of a parametric StationaryFunctionalCovarianceModel

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1650]
The current example shows a covariance model with a correlation function which has no parameter. In order to estimate its hyper-parameters, we must create a `ParametricFunction` and use the `StationaryFunctionalCovarianceModel` afterwards. An second example should show this in the help of  `StationaryFunctionalCovarianceModel`.

**Comment by josephmure** [comment]
Do you have something like that in mind @mbaudin47? I was thinking about entrusting this fix to one of the trainees at EDF.

```
import openturns as ot
rho_param = ot.SymbolicFunction(['tau','n'], ['exp(-tau)*exp(n * log(cos(2*pi_*tau)))'])
rho = ot.ParametricFunction(rho_param, [1], [2.0])
covModel = ot.StationaryFunctionalCovarianceModel([1.0], [1.0], rho)
covModel.setActiveParameter([0, 1, 2])
print(covModel.getParameterDescription())
```
Output:
```
[scale_0,amplitude_0,n]
```

**Comment by mbaudin47** [comment]
Exactly: this is an interesting example of a parametrized stationary covariance model.
