### ISSUE TITLE
Cobyla freezes in 0T1.16rc1

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1651]
See https://stackoverflow.com/questions/64605271/meta-model-of-the-field-function-openturns-1-16rc1

**Comment by NikolaH1** [comment]
The error I get is >>WRN - Warning! TNC algorithm failed. The error message is Linear search failed<<

**Comment by regislebrun** [comment]
@NikolaH1 Ok so it is one of the factories which is unable to build something meaningful (StudentFactory, WeibullMinFactory or the generic MaximumLikelihoodFactory). Could you please share your learning samples in order for us to reproduce the bug?

**Comment by NikolaH1** [comment]
I attached the example

[GitHub.zip](https://github.com/openturns/openturns/files/5476986/GitHub.zip)

**Comment by regislebrun** [comment]
When cobyla meets a point with NaNs it freezes a few step after.
