### ISSUE TITLE
TimeSeries accessor

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1658]
This example shows a usage of "TimeSeries()[ i ]" or "TimeSeries()[ i , j ] https://openturns.github.io/openturns/latest/auto_probabilistic_modeling/stochastic_processes/plot_timeseries_manipulation.html#sphx-glr-auto-probabilistic-modeling-stochastic-processes-plot-timeseries-manipulation-py

But they do not correspond to what is awaited by the text (a kind of slicing).
Is it a accessor issue or a documentation issue?

example 1 :
````
#Get the time series at index i : (ti, Xi)
print('(ti, Xi) = ', myTimeSeries[i])
````
[Out] : (ti, Xi) =  [-0.330858,-1.40182,0.339849]
the output is a Point which does not include the timestamp
````myTimeSeries[i]```` becomes equivalent to ````myTimeSeries.getValueAtIndex(i))````

example 2:
````
# get the time stamp:
print('ti = ', myTimeSeries[i, 0])
# get the first component of the corresponding value :
print('Xi1 = ', myTimeSeries[i, 1])
````
They give the marginals 0 and 1 in fact.

**Comment by jschueller** [comment]
I guess we split up the mesh from values at some point, now getTimeGrid must be used
