### ISSUE TITLE
Examples not prefixed in the search engine

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1659]
In the search engine, examples should be prefixed by "Examples:". This is not the case and as a result:

1. examples appear at the bottom of the list whereas they should appear first;

![OT_search_api_top](https://user-images.githubusercontent.com/31989332/98217818-4bd21700-1f4b-11eb-96cb-e7d3071bedb2.png)

2. the "Examples" ticking box does not do anything: unticking it does not remove the examples from the list.

![OT_search_unprefixed_examples](https://user-images.githubusercontent.com/31989332/98217816-4b398080-1f4b-11eb-8ee3-4863c8361521.png)

**Comment by jschueller** [comment]
see #1636

**Comment by josephmure** [comment]
No  @jschueller this is a different bug: these screenshots were obtained after your fix was applied.

**Comment by jschueller** [comment]
sorry

**Comment by KieranDelamotte** [comment]
Locally @jschueller 's commit work for me. 

For the display confusion, I think the search.html page has not been update with the 1.16rc tag hence the display of 1.16dev.

**Comment by jschueller** [comment]
indeed: https://openturns.github.io/openturns/1.16/search.html?q=kriging
