### ISSUE TITLE
XMLH5StorageManager does not store IndicesCollection into HDF5 files

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1661]
When saving a large mesh into a Study, only the vertices are stored into an HDF5 file. If the storage of the simplices could be done using the same technology it would result into a significant gain both in terms of speed and size.

**Comment by jschueller** [comment]
indeed, our main concern was Sample so we worried only about the collections of Scalar, not UnsignedInteger, cc @YomGarcia
