### ISSUE TITLE
IntervalMesher segfault when diamond==true

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1670]
The following script leads to a segfault:
```
from openturns import *
mesh=IntervalMesher([20]*3).build(Interval(3), True)
```

**Comment by jschueller** [comment]
fails at IntervalMesher, line 402:
```
vertices(centerCDHGIndex, 0) = (vertices(c, 0) + vertices(d, 0) + vertices(g, 0) + vertices(h, 0)) * 0.25;
```

**Comment by regislebrun** [comment]
Indeed ;-)! Initially I had in mind to add only the center of each cube (m*n*p additional vertices) when diamond==True but as we are working with simplices I cant have pyramids with square bases. So I also had to add the centers of the faces, resulting into (m+1)*n*p+m*(n+1)*p+m*n*(p+1) more vertices. The correct formula should be to add 4*m*n*p+m*n+n*p+p*m vertices instead of only m*n*p.

**Comment by regislebrun** [comment]
and the way new simplices are added is just crazy! Everything has to be recoded...

**Comment by jschueller** [comment]
in the mean time we can throw instead of crashing, https://github.com/openturns/openturns/pull/1766
