### ISSUE TITLE
x-axis values of drawProbabilityConvergence()

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1671]
When using a "Compact" strategy to store values of a Monte-Carlo simulation, the final size of the sample could be lower than the original one due to the resampling strategy.
In this case, the x-axis values in the drawProbabilityConvergence() graph are misleading because they do not reflect the original number of iterations.

Shouldn't the numbering be readjusted at least for "Compact Strategy" using the compacting ratio or better shoudn't we store the iteration index (works for "Last" strategy) as x-axis ? 

You can see [in this example](https://openturns.github.io/openturns/master/auto_reliability_sensitivity/reliability/plot_axial_stressed_beam_quickstart.html#sphx-glr-auto-reliability-sensitivity-reliability-plot-axial-stressed-beam-quickstart-py) that number of **iterations** = **12692**  while x-axis upper limit ~**1600**
![image](https://user-images.githubusercontent.com/52526981/99385703-a7988a80-28d1-11eb-81f3-11c1ba52be09.png)

**Comment by regislebrun** [comment]
Right! I don't know if we should write the number of outer iterations (current choice with the error you found) or the number of evaluations (more standard, my preference). In any case, we should rely on result_ to get the exact number of iterations and on getEvaluationCallsNumber() for the number of evaluations (think about DirectionalSampling, where many calls are made even if blockSize==1).
