### ISSUE TITLE
Warning messages with kriging algorithm

### ISSUE THREAD

**Issue by chademay** [openturns/openturns#1673]
Hello,

When using the kriging algorithm of OpenTurns 1.15 (with Python 3.8 and Spyder 4.1.5), I always have a lot of warning messages such as :

"\x1b[0m\n\x1b[34m\x1b[1mWRN - Warning! For coherency we set scale upper bounds = [6.13868,7.05613"....

Is there a way not to display them ?

Thank you,

Charles.

**Comment by regislebrun** [comment]
Yes, add `Log.Show(Log.NONE)` at the point from where you don't want to see the messages. Adapt it according to the way you import openturns.
