### ISSUE TITLE
Source distribution not available on pypi

### ISSUE THREAD

**Issue by thebaptiste** [openturns/openturns#1676]
For some internal reasons, in my project we install all python packages from source distribution (pip install with option --no-binary)
It seems that you only provide wheels for openturns on pypi ?
It would be great if you could also provide source distribution.

**Comment by jschueller** [comment]
yes, source installation is not supported

**Comment by jschueller** [comment]
I can add that openturns is in c++ and we have no setup.py so that wont work

**Comment by thebaptiste** [comment]
Maybe you could provide on pypi a python binding of your C++ libraries requiring these libraries to be installed on the system, as it's done for instance for gdal.
But ok, I will deal with it and I will install the binary distribution or directly build openturns from github sources.
Thanks for your answer.
