### ISSUE TITLE
MinimumVolumeClassifier should build with a collection of levels

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1694]
The current constructor is:
```
algo = ot.MinimumVolumeClassifier(distribution, alpha)
```
where alpha is a float. 
It is possible to improve this constructor into:
```
algo = ot.MinimumVolumeClassifier(distribution, alphaCollection)
```
where alphaCollection is a collection of confidence levels. 
Hence, this leads to a classification with different classes. 
This is an enhancement request.

**Comment by jschueller** [comment]
cf #1681
