### ISSUE TITLE
LogNormalFactory

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#1696]
Hi,
I noticed that the estimation of a LogNormal on this data is wrong: the graph with the empirical CDF and the estimated one clearly shows that the LogNormal is not a correct model . But the result of the test contains a p-value = 0.999312!!!!
If we fix the range parameter gamma = 0 and if fit a Normal distribution on the log-data, then the test rejects the LogNormal distribution with a p-value =  1e-5.

Conclusion: I think the bug is due to the bad estimation of the range parameter gamma. 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

from openturns import *
from openturns.viewer import View

SampleDuree = Sample([[757],[140],[143],[6.5],[28.0333],[8889.03],[6594.28],[5434.9],[510.9],[10573.6],[6591],[72],[236.533],[947.367],[1997.42],[4700.33],[10171.6],[10752],[0.416667],[7190.33],[12459.9],[5541.5],[1595.58],[10364.5],[6228.5],[13025.5],[8187.73],[11221.2],[9795.22],[4433.78],[8147.37]])
ResourceMap.SetAsUnsignedInteger("FittingTest-KolmogorovSamplingSize",1000000)

####################"
# Case 1: we estimate the 3 parameters of the LogNormal (gamma, muLog, sigmaLog)
loiLN_Duree, resultLN = FittingTest.Kolmogorov(SampleDuree, LogNormalFactory(), 0.05) #Loi Lognormale
print(resultLN)

# Graph: empirical CDF + estimated CDF
empiricalCDF = UserDefined(SampleDuree)
graph = loiLN_Duree.drawCDF(0.0, 14000, 10001)
graph.add(empiricalCDF.drawCDF())
graph.setColors(["red", "black"])
graph.setLegends(["Log-Normal", "Durée"])
view = View(graph)
view.show()

loiLN_Duree, resultLN = FittingTest.Kolmogorov(SampleDuree, factory, 0.05) #Loi Lognormale
print(resultLN)

####################"
# Case 2: we transfome the data with the log function and we estimate a Normal distribution

from math import log
fct_log = SymbolicFunction('x', 'log(x)')
sample_log = fct_log(SampleDuree)

loiN, resultN = FittingTest.Kolmogorov(sample_log, NormalFactory(), 0.05)
print(resultN)

empiricalCDF = UserDefined(sample_log)
graph = loiN.drawCDF()
graph.add(empiricalCDF.drawCDF())
graph.setColors(["red", "black"])
graph.setLegends(["Normal", "s_log"])
view = View(graph)
view.show()

**Comment by sofianehaddad** [comment]
Hi @adutfoy 

I updated a bit the script as now the `Lilliefors` static method handles now this part (and no more `Kolmogorov)`

Here is the updated one:
```
import openturns as ot
from openturns.viewer import View
from math import log


SampleDuree = ot.Sample.BuildFromPoint([757, 140, 143, 6.5, 28.0333, 8889.03, 6594.28, 5434.9, 510.9,\
                                       10573.6, 6591, 72, 236.533, 947.367, 1997.42, 4700.33, 10171.6, 10752, 0.416667,\
                                       7190.33, 12459.9, 5541.5, 1595.58, 10364.5, 6228.5, 13025.5,\
                                       8187.73, 11221.2, 9795.22, 4433.78, 8147.37])

# 0: "buildMethodOfLocalLikelihoodMaximization"
# 1: "buildMethodOfModifiedMoments"
# 2: "buildMethodOfMoments"
# 3: "buildMethodOfLeastSquares"
ot.ResourceMap.SetAsUnsignedInteger("LogNormalFactory-EstimationMethod", 0)


#ot.ResourceMap.SetAsUnsignedInteger("FittingTest-KolmogorovSamplingSize", 1000000)
ot.ResourceMap.SetAsUnsignedInteger('FittingTest-LillieforsMaximumSamplingSize', 1000000)
ot.ResourceMap.SetAsUnsignedInteger('FittingTest-LillieforsMinimumSamplingSize', 100)

# Case 1: we estimate the 3 parameters of the LogNormal (gamma, muLog, sigmaLog)
loiLN_Duree, resultLN = ot.FittingTest.Lilliefors(SampleDuree, ot.LogNormalFactory(), 0.05) #Loi Lognormale
print("Lilliefors for LogNormal factory:", resultLN)

# Graph: empirical CDF + estimated CDF
empiricalCDF = ot.UserDefined(SampleDuree)
#empiricalCDF = ot.HistogramFactory().build(SampleDuree)
graph = loiLN_Duree.drawCDF(0.0, 14000, 10001)
graph.add(empiricalCDF.drawCDF())
graph.setColors(["red", "black"])
graph.setLegends(["Log-Normal", "Duree"])
view = View(graph)
view.show()

#loiLN_Duree, resultLN = ot.FittingTest.Lilliefors(SampleDuree, factory, 0.05) #Loi Lognormale
#print(resultLN)


#Case 2: we transfome the data with the log function and we estimate a Normal distribution
gamma = SampleDuree.getMin()[0] - SampleDuree.getMin()[0] / (2* len(SampleDuree))
fct_log = ot.SymbolicFunction('x', 'log(x - %s)'%gamma)
sample_log = fct_log(SampleDuree)

loiN, resultN = ot.FittingTest.Lilliefors(sample_log, ot.NormalFactory(), 0.05)
print("Lilliefors for Normal factory:", resultN)

empiricalCDF = ot.UserDefined(sample_log)
#empiricalCDF = ot.HistogramFactory().build(sample_log)
graph = loiN.drawCDF()
graph.add(empiricalCDF.drawCDF())
graph.setColors(["red", "black"])
graph.setLegends(["Normal", "s_log"])
view = View(graph)
view.show()
```

To complete I give the output figures:

![image](https://user-images.githubusercontent.com/1433220/108722199-29c4ca80-7523-11eb-8373-1735b1b8c68e.png)

![image](https://user-images.githubusercontent.com/1433220/108722152-1ca7db80-7523-11eb-987b-ecd149219dd6.png)

**Comment by sofianehaddad** [comment]
When moving from `buildMethodOfLocalLikelihoodMaximization`(which is the default method) to `buildMethodOfModifiedMoments` or `buildMethodOfMoments`, we  get more accurate `p-value` (meaning `0`).
We should set the `LogNormalFactory-EstimationMethod` resource map key for that purpose.

It fails with `least squares` with msg (`On entry to DGELSY, parameter number  4 had an illegal value`)
So I guess there is no bug but only the method which fail in some (specific/complex) use cases. 
Any idea @regislebrun ?

**Comment by sofianehaddad** [comment]
I close this because probably it is related to the used method (`buildMethodOfLocalLikelihoodMaximization`) and link with specific `LillieforsMaximumSamplingSize` 
Feel free to reopen it
