### ISSUE TITLE
The Search engine can be very slow

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1698]
We can now search in Example, API or Theory. 
http://openturns.github.io/openturns/master/search.html
If we search only in API, the search result can be awfully slow.
For example, if we unselect API and search for Sample:
![image](https://user-images.githubusercontent.com/31351465/102073208-4649d580-3e03-11eb-8c7e-3d3d5b094c8e.png)
the result is printed only after a relatively long time.

**Comment by KieranDelamotte** [comment]
Hi,

As already said during the last call meeting, this is not really an issue. We somehow have to fit into the Sphinx environment. What we do with the check boxes is filtering the results of Sphinx searching tool.

Sphinx provides a default Scorer which print the result according to relevance (keyword in the title of an example, API name, ...). This `Scorer` can be customized and that is exactly what is done in OT : each main category (Examples, API, Theory) has its own score (resp. 300, 200, 100) and we add the relevance. Then they are sorted in descending order. This Scorer is called locally and not on the server.

The check boxes only display/hide the results. Hence, if the result you want has a low score you have to wait a bit.

Last, do not generalize over the 'Sample' search as it is a very common term in OT. As a comparison try searching 'plot' in Matplotlib search bar (also Sphinx-based by the way). If your wanted result is among the last ones then you will have to wait a few minutes.

**Comment by josephmure** [comment]
With a few months of experience using the new search engine, I agree with @KieranDelamotte: this is not an issue. When searching names that are used everywhere like `Point` and `Sample` it needs about 10 seconds to display API results with my internet connection. For other classes (`MaternModel`, `Student`, `GaussianNonLinearCalibration`, ...) API results are almost instantaneously displayed.

**Comment by mbaudin47** [comment]
Searching "Sample" in the Search engine of 1.15 is instantaneous:

![image](https://user-images.githubusercontent.com/31351465/107858806-65caa200-6e36-11eb-8e70-cb8959a99022.png)

In this sense, the new engine is a regression in some cases.

A possible trick is to add "class" in front of the name:

![image](https://user-images.githubusercontent.com/31351465/107858790-4b90c400-6e36-11eb-9589-d6493f893c6c.png)

This restricts the number of pages which are filtered by the boxes, but is somewhat a workaround.

**Comment by josephmure** [comment]
@mbaudin47 Should this issue remain open? I don't think any solution is available within the current framework. There is a tradeoff between sorting the results and having them appear quickly. Note that in practice, users often use external search engines, which decreases the importance of the internal one.

**Comment by mbaudin47** [comment]
This issue was solved by @KieranDelamotte at some point in time. I do not remember exactly when. The current speed of the search engine is now OK in my opinion.
