### ISSUE TITLE
The number of files in python/src is too large

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1704]
The number of files in:

https://github.com/openturns/openturns/blob/master/python/src

is too large : there is currently almost 1500 files in the directory. 

This prevents from using github interactive features. Indeed, only the first files are printed, which prevents from accessing the files which first letter is greater than "P" in alphabetical order. 

![image](https://user-images.githubusercontent.com/31351465/103138185-52ba1200-46d0-11eb-9822-6c74d3dba541.png)

For example, 

https://github.com/openturns/openturns/blob/master/python/src/SobolIndicesExperiment_doc.i.in

is not printed. Hence, the only way of fixing an issue is to pull a git copy. This is a pity, since github allows to get interactive edits. As a consequence, only OpenTURNS with git can update the doc, which drastically reduce the number of potential doc bugfix suggestions.

**Comment by josephmure** [comment]
This is a late answer, but it is not quite true that GitHub's interactive features cannot be used when the file is omitted from the list. If you know its name, you can use the "Go to file" button to search for it:

![image](https://user-images.githubusercontent.com/31989332/185642527-788560c9-81e0-497a-9e4e-ff91cd2f5ce6.png)

**Comment by sofianehaddad** [comment]
@jschueller are we planning to do something here? 
IMHO it deals **only** with the dev team & no **major** issue is identified.
I propose to close the issue. Feel free to reopen it if you think it is important
