### ISSUE TITLE
Kriging metamodel throws segfault when evaluated on huge sample

### ISSUE THREAD

**Issue by Kramer84** [openturns/openturns#1709]
On a meta-model created through kriging, when evaluated on a relatively huge sample (300 000 points), a segfault is thrown.

When the sample is evaluated sequentially (50 000 by 50 000) the evaluation goes without a problem.

As this error occurs while using openturns through the python interface, I could not trace back the C++ part of the error.

I have included a [link to a google drive folder](https://drive.google.com/drive/folders/1hRQsQmbzYW2wwEhjIXM_xJs-hjfy7ofW?usp=sharing), containing a minimal working example, the X and Y samples used for the creation of the metamodel, as well as the huge sample on which this error occurs. (the minimal working example is a notebook and the samples are csv files) 

My machine has 16 Gb of RAM and the size in memory of the sample in .csv format is 85 Mb, so memory should not be the issue here.
My version of openturns is 1.16.

My guess was on the segfault, because when trying to debug with GDB i get this error message:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007f179e358c14 in dgemm_oncopy_HASWELL ()
   from /home/kramer84/anaconda3/envs/stochastic_field_env/lib/python3.7/site-packages/openturns/../../.././liblapack.so.3
```

**Comment by regislebrun** [comment]
Hi,
I tested your notebook on my laptop (linux). It runs like a charm with both OT 1.16 and master. As my laptop has a huge amount of memory I will test it on a more reasonable configuration tomorrow to see if it is a memory-related problem.

Cheers

Régis

**Comment by Kramer84** [comment]
Thank you very much for the fast reply! 

I really had thought that it shouldn't be memory-related as there were no noticeable spikes in memory with smaller samples, so I'm glad that it works on your machine. 
With a bit of luck it is only related to my hardware. 

Cheers

Kristof

**Comment by jschueller** [comment]
hello, it looks more like an openblas issue, maybe this one:
https://github.com/xianyi/OpenBLAS/issues/2728

**Comment by regislebrun** [comment]
@Kramer84 I ran your notebook on a standard HP laptop with no problem. You should upgrade your conda environment, or use the workaround proposed in https://github.com/xianyi/OpenBLAS/issues/2728:
```
import os

os.environ['OPENBLAS_NUM_THREADS'] = '1'
```
@jschueller It looks like you found the root cause, thks!
 Here are the specifications of the laptop and the OpenBLAS version I used for the test:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 78
model name      : Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
stepping        : 3
microcode       : 0xe2
cpu MHz         : 699.998
cache size      : 3072 KB
...
MemTotal:       16277308 kB
MemFree:         3955356 kB
MemAvailable:   12075404 kB
```
using OpenTURNS 1.16 shipped with conda, using the following version of OpenBLAS:
```
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
```

**Comment by jschueller** [comment]
the code path also depends on the cpu model, here i5-6300u is skylake, not haswell as in the bug report so you may not reproduce:
https://ark.intel.com/content/www/fr/fr/ark/products/88190/intel-core-i5-6300u-processor-3m-cache-up-to-3-00-ghz.html

**Comment by Kramer84** [comment]
This must be the issue, thanks! This would also explain why, when I ran the GDB debugger with a script where NumPy was imported before openTURNS the error pointed to the openBLAS library located in the numpy package.

I tried your workaround here, but the kernel still appears to be dying. My libopenblas version is also a bit older than yours.
```
libopenblas               0.3.10               h5a2b251_0  
```
I believe this is the case as I'm using a specific environment where I installed openturns with the Mayavi/Traits package, which has older dependencies.

Here is the one-liner to recreate my environment:
```
conda create --name ot_traits_env python=3 numpy scipy pandas scikit-learn scikit-image mayavi jupyter pyface joblib matplotlib conda-forge::openturns conda-forge::cython conda-forge::cyipopt 
```

I will check if updating conda and recreating a new virtual environment solves the issue, but the environment may be a bit too constrained.

My hardware configuration is also a bit older that yours:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
...
Vendor ID:           GenuineIntel
CPU family:          6
Model:               60
Model name:          Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
Stepping:            3
CPU MHz:             1465.384
CPU max MHz:         3200,0000
CPU min MHz:         800,0000
...
L2 cache:            256K
L3 cache:            3072K
```

**Comment by jschueller** [comment]
0.3.10 is the version in their bug report, maybe you can try to upgrade your conda stack, hopefully openblas will be updated

**Comment by Kramer84** [comment]
After updating conda and my environment, the libopenblas version was not affected, so with this specific hardware configuration and environment the only work-around is looping over the sample.

When using a clean environment that allows for the usage of the updated version of libopenblas, there is no more error. 

I will check if there is a way to force the update of libopenblas without interfering with other libraries, but anyways, this specific issue here is solved, thank you very much!

**Comment by Kramer84** [comment]
I tried to force the update of libopenblas using: 
```
conda update libopenblas --no-channel-priority --no-pin --no-deps
```
but conda just says that the package is already installed, as if 3.10 would be the latest version, would adding the " -force " flag be a solution?
