### ISSUE TITLE
The GridLayout always remove specific X/Y ticks labels

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1711]
In:
https://github.com/openturns/openturns/blob/3f67cff1d6593a15e16f53eea2d038b76cea4d52/python/src/viewer.py#L213
we see:
```
if i < graph.getNbRows() - 1:
    axes[0].set_xticklabels([])
if j > 0:
    axes[0].set_yticklabels([])
```
This disables the X/Y ticks labels for specific graphs in the grid.
In the case of the ot.VisualTest.DrawPairs, this produces:

![image](https://user-images.githubusercontent.com/31351465/103563247-bc9a9e80-4ebc-11eb-9bf1-67382baf8a1c.png)

This is correct, because all the graphs in the grid share the same data.

However, this is not correct in general, because the graphs of the grid may or may not share the X or Y data. In the example given in the doc, this is wrong, because the PDF from different variables may not have the same (vertical) PDF values:

![image](https://user-images.githubusercontent.com/31351465/103563560-42b6e500-4ebd-11eb-8e24-61725387d25a.png)

I guess that no code can be setup to cover all cases. This is why I suggest to remove it at this particular location, which is the general GridLayout. However, a specific setup might be set for specific graphics such as the Pairs.

**Comment by jschueller** [comment]
dup of #1710
