### ISSUE TITLE
The log-PDF of the Pareto is wrong

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1714]
The code for the LogPDF of the Pareto has a bug:
https://github.com/openturns/openturns/blob/bc1ba291d2377bdd2bbefce9009f1790e3443305/lib/src/Uncertainty/Distribution/Pareto.cxx#L146

The correct code would be:
```
std::log(alpha_) + alpha_ * std::log(beta_) + (-alpha_ - 1.0) * std::log(x)
```

**Comment by mbaudin47** [comment]
The method i used to find the bug is at:
https://openturns.discourse.group/t/automated-consistency-tests-of-a-distribution/82

**Comment by mbaudin47** [comment]
Hence, the `MaximumLikelihoodFactory` class cannot be used to estimate its parameters.

**Comment by regislebrun** [comment]
Correct. I found another bug thanks to your testing code: the computeDDF() method of the GeneralizedPareto distribution has a bug for small values of xi. The correct formula should be:
```
  if (std::abs(xi_) < 1.0e-8)
  {
    result[0] = -0.5 * std::exp(-z) * (2.0 + xi_ * (2.0 - z * (4.0 - z))) / (sigma_ * sigma_);
    return result;
  }
```
Do you have a branch for these bugs or do I start one?

**Comment by jschueller** [comment]
it's a good idea to have more generic tests: ie a t_Distribution_std.py file, like we do for covariance models

**Comment by mbaudin47** [comment]
> Correct. I found another bug thanks to your testing code: the computeDDF() method of the GeneralizedPareto distribution has a bug for small values of xi. The correct formula should be:
> 
> ```
>   if (std::abs(xi_) < 1.0e-8)
>   {
>     result[0] = -0.5 * std::exp(-z) * (2.0 + xi_ * (2.0 - z * (4.0 - z))) / (sigma_ * sigma_);
>     return result;
>   }
> ```
> 
> Do you have a branch for these bugs or do I start one?

I do not have any branch on this topic yet. Please go ahead and I might review afterwards.
