### ISSUE TITLE
A new constructor ConditionedGaussianProcess would be useful

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1716]
We would like to create a conditioned Gaussian process with a covariance model which parameters have already been estimated. That is, we do not want to use the estimation part of `KrigingAlgorithm`.

It would almost like `GaussianProcess` with inputSample and and outputSample:
```
ConditionedGaussianProcess(inputSample, outputSample, trend, covarianceModel, mesh)
```
This is a feature which would be useful for teaching purposes in training: it would allow to add new points sequentially @RomanSueur.
 @M2CI-ONERA Might this be useful for your probability estimation algorithms ?

**Comment by sofianehaddad** [comment]
Hmmm I am missing something. Using `krigingResult` is needed as we rely on `conditional covariance`.
What do you have in mind exactly?

**Comment by mbaudin47** [comment]
Looking at the current parameters of the `KrigingResult` class, some parameters are the same, but some are not:
 * inputSample, outputSample, covarianceModel : OK
 * metaModel, residuals, relativeErrors: these informations are unknown for the user. It is an output of the algorithm.
 * covarianceCoefficients: this information is already in the covarianceModel we have at our disposal.
 * basis, trendCoefficients: a TrendTransform would be more appropriate, since the basis and the coefficients are already known.

Perhaps, this could be better explained within a use-case: @RomanSueur or @josephmure , may you provide the script you prepare for the training?

**Comment by sofianehaddad** [comment]
Ok waiting for the use-case.
At least, a conditioning sample is missing and I don't think we can bypass the kriging step...

**Comment by regislebrun** [comment]
Hi @mbaudin47 ,

Do you have something like this in mind?
```
# This function allows to build a conditioned Gaussian process
# given a set of locations, the corresponding values, the trend
# function, the fully known covariance model and a mesh
def buildConditionedGaussianProcess(inputSample, outputSample, trend, covarianceModel, mesh):
    # First, build the detrend data
    centeredOutputSample = outputSample - trend(inputSample)
    # Second, build the conditioned covariance model
    covarianceModel.setActiveParameter([])
    basis = ot.Basis()
    krigingAlgo = ot.KrigingAlgorithm(inputSample, centeredOutputSample, covarianceModel, basis)
    krigingAlgo.run()
    centeredConditionedProcess = ot.ConditionedGaussianProcess(krigingAlgo.getResult(), mesh)
    return ot.CompositeProcess(ot.TrendTransform(trend, mesh), centeredConditionedProcess)
```
Here is an illustration:
```
trend = ot.SymbolicFunction("x", "x+1.43*x^3")

size = 4
a = -1.0
b = 0.75
inputSample = ot.Uniform(a, b).getSample(size)
deformation = ot.SymbolicFunction("x", "0.8*x+0.2*sin(pi_ * x)")
outputSample = trend(inputSample) + ot.Normal(0.0, 0.5).getSample(size)
covarianceModel = ot.SquaredExponential([0.25], [0.5])

N = 200
mesh = ot.IntervalMesher([N]).build(ot.Interval(a, b))

process = buildConditionedGaussianProcess(inputSample, outputSample, trend, covarianceModel, mesh)

g = trend.draw(a, b)
d = g.getDrawable(0)
d.setLineStyle("dashed")
d.setLineWidth(2)
d.setColor("black")
g.setDrawable(d, 0)
M = 5
g.add(process.getSample(M).drawMarginal(0, True))
points = ot.Cloud(inputSample, outputSample)
points.setColor("black")
points.setPointStyle("fcircle")
g.add(points)
g.setTitle("Conditioned Gaussian process")
g.setXTitle(r"$x$")
g.setYTitle(r"$y(x)$")
g.setLegends(["trend"] + ["traj. " + str(i) for i in range(M)] + ["obs."])
g.setLegendPosition("topleft")
view = otv.View(g)
view.ShowAll()
```
which produces the following figure:
![Figure_1](https://user-images.githubusercontent.com/8220933/104425272-c2f5de00-5580-11eb-8f0a-1027045ad8b9.png)

It cannot be introduced in OT through a constructor as it may involve a significant amount of computation due to the Kriging step, and we try to keep the instantiation time as short as possible. But a factory could be an option.

**Comment by sofianehaddad** [comment]
I see the point. I missed the `mesh` argument (vs `inputSample`). 
Agreed with @regislebrun : the key point here is the evaluation of `Kriging` !

**Comment by josephmure** [comment]
What does the `mesh` do exactly? Does is tell at which points realizations of the conditioned GP are to be discretized?

**Comment by regislebrun** [comment]
Exactly.

**Comment by mbaudin47** [comment]
Thank you very much @regislebrun , i guess that the function you designed fits the need (and seems to be more simple than i thought). @RomanSueur : does it match your requirements?

**Comment by RomanSueur** [comment]
Yes it does.
In fact it was not clear to me how to make possible to restrict the use of a KrigingAlgorithm to the sole estimation of the \lambda parameters.
It is done by removing the trend and using the setActiveParameter() method (which I didn't know).
Thank you all !

**Comment by regislebrun** [comment]
Looks like the issue is closed no?

**Comment by mbaudin47** [comment]
I agree. This is why I close this issue.
