### ISSUE TITLE
KarhunenLoeveReduction's example has a format issue

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1740]
The example at:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.KarhunenLoeveReduction.html

is wrong:

![image](https://user-images.githubusercontent.com/31351465/106157098-a5c92e00-6182-11eb-897b-8628b7731797.png)

**Comment by jschueller** [comment]
this is already fixed in my branch

**Comment by mbaudin47** [comment]
Which branch?

**Comment by jschueller** [comment]
misc, just merged ^^

**Comment by mbaudin47** [comment]
This commit: 4871d20c944d9516be07eb96831f59e269799e67
(Stupid bug!)
