### ISSUE TITLE
The example which shows how to set the figure size is wrong.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1742]
The example which shows how to set the figure size is wrong:

http://openturns.github.io/openturns/master/auto_graphs/plot_graphs_basics.html

![image](https://user-images.githubusercontent.com/31351465/106324211-105c9580-6279-11eb-8815-1eed62cd46de.png)

**Comment by KieranDelamotte** [comment]
The name of the variable in the `viewer.py` file is `plot_kw`. It is the same syntax for figures (`figure_kw`), axes (`axes_kw`), ...

**Comment by mbaudin47** [comment]
So the keyword argument was spelled `plot_kws` instead of `plot_kw`? Python does not check this? At least a warning should be generated, isn'it?
