### ISSUE TITLE
There is no example or feature to plot a (X,Y) sample.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1749]
When we analyze the link between the inputs and the outputs of a sample, it is convenient to plot the outputs versus the inputs. When there are several inputs (which is the most often encountered case) and several outputs (which is less often), the `GridLayout` class provides the perfect tool to plot the sample and see the correlations graphically. As the propagation of uncertainties is the core of the library, providing a way to see this would prove essential. 

The following provides an example.
```python
import openturns as ot
model = ot.SymbolicFunction(
    ["X0", "X1", "X2"],
    ["1.0 + 2.0 * X0 - 1.0 * X1 + 4.0 * X2", "-2.0 - 3.0 * X0 + 5.0 * X1 - 1.0 * X2"],
)
distribution = ot.Normal(3)
distribution.setDescription(model.getInputDescription())
sampleX = distribution.getSample(100)
sampleY = model(sampleX)
dimensionX = sampleX.getDimension()
dimensionY = sampleY.getDimension()
descriptionX = sampleX.getDescription()
descriptionY = sampleY.getDescription()

grid = ot.GridLayout(dimensionY, dimensionX)
for j in range(dimensionY):
    for i in range(dimensionX):
        graph = ot.Graph("", descriptionX[i], descriptionY[j], True, "",)
        cloud = ot.Cloud(sampleX[:, i], sampleY[:, j])
        graph.add(cloud)
        grid.setGraph(j, i, graph)
grid.setTitle("Each row is an output, each column is an input.")
```
The previous script produces the following figure.

![image](https://user-images.githubusercontent.com/31351465/132667007-afbe5246-ccc1-4460-8368-49f07be94e81.png)

As most of us systematically perform this task (or *should* perform it), my feeling is that a dedicated graphical function should provide it.

**Comment by m-balesdent** [comment]
@mbaudin47 Maybe this example that illustrates the method `DrawPairs`  method does the job and this issue could be closed?  [https://openturns.github.io/openturns/latest/auto_data_analysis/graphics/plot_visualize_clouds.html#sphx-glr-auto-data-analysis-graphics-plot-visualize-clouds-py](https://openturns.github.io/openturns/latest/auto_data_analysis/graphics/plot_visualize_clouds.html#sphx-glr-auto-data-analysis-graphics-plot-visualize-clouds-py)

**Comment by mbaudin47** [comment]
Indeed, `DrawPairs(sample)` can plot a single sample. But is does not plot a (X,Y) pair as I required in this issue. That could be done if we implement `DrawPairs(inputSample, outputSample)`.
