### ISSUE TITLE
Error while estimating the reduced log-likelihood when using a StationaryFunctionalCovarianceModel

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#1752]
Hello,
I think there is an error in the way the reduced log-likelihood is computed when using a user defined StationaryFunctionalCovarianceModel.

For illustrative purposes, in the code below I try to obtain the same results when using a ot.SquaredExponential() covariance model and a user defined StationaryFunctionalCovarianceModel:

```
import openturns as ot
import numpy as np

#Target function
def f(x):
    return x*np.sin(x)

#Sampling of target function
N = 12
sampleX = np.linspace(0,1,N).reshape((N,1))*8
sampleY = f(sampleX)

#Constant null trend
basis = ot.Basis(0)

#Definition of a squared exponential covariance by using the StationaryFunctionalCovarianceModel class
rho = ot.SymbolicFunction(['tau'], ['exp(- 1/2 * (tau)^2)'])
covModel = ot.StationaryFunctionalCovarianceModel([1.0], [1.0], rho)
covModel.setActiveParameter([0])
algo = ot.KrigingAlgorithm(sampleX, sampleY, covModel, basis)


#Definition of a squared exponential covarianceby using the pre-defined
covModel2 = ot.SquaredExponential()
covModel2.setActiveParameter([0])
algo2 = ot.KrigingAlgorithm(sampleX, sampleY, covModel2, basis)


#Definition and representation of the 2 log-likelihood functions
LL = algo.getReducedLogLikelihoodFunction()
LL2 = algo2.getReducedLogLikelihoodFunction()

LL.draw(1e-3,2.,100)
LL2.draw(1e-3,2.,100)
```

The resulting plots of the two log-likelihood functions w.r.t. to the scale parameters are presented below:

![image](https://user-images.githubusercontent.com/20241166/106782599-a06c5780-664a-11eb-9c91-fab0d6bca3c7.png)

![image](https://user-images.githubusercontent.com/20241166/106782055-07d5d780-664a-11eb-8f7b-54e4dc7cd083.png)

**Comment by sofianehaddad** [comment]
Hi,

Could you please test with the current `master`?  I made some changes and fixed various issues. Seems the problem vanishes as I can not reproduce the bug.

![image](https://user-images.githubusercontent.com/1433220/106784535-b713ae00-664c-11eb-8886-24f28b747801.png)

**Comment by JPelamatti** [comment]
Hello,
I can confirm that this issue does not seem to appear when using the current master branch, as is shown below. Thanks for the help.
![Figure](https://user-images.githubusercontent.com/20241166/106875925-7ca32300-66d7-11eb-9abd-145383303132.png)

**Comment by sofianehaddad** [comment]
Perfect
You are welcome.

**Comment by josephmure** [comment]
Perhaps we should add a unit test for this to prevent regressions in the future. After this is done, we can add this as a fixed bug in the ChangeLog. @sofianehaddad @mbaudin47

**Comment by sofianehaddad** [comment]
Useless to integrate it to the `Changelog` as the fix already exists. For the unit test, it is up to you!

**Comment by josephmure** [comment]
It doesn't exist in 1.16, though, which is the version that @chademay was using when he detected the bug. That is why I think it should be in the 1.17 ChangeLog.

**Comment by josephmure** [comment]
For the unit test, could you please review PR #1754 @sofianehaddad ?
