### ISSUE TITLE
The SRC function is a misnomer. 

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1753]
In the library, the `CorrelationAnalysis_SRC` static method actually computes the squared SRC. This corresponds to an importance factor of a linear model. 

More precisely, the definition for Standardized Regression Coefficient is:

![image](https://user-images.githubusercontent.com/31351465/106790420-d4984600-6653-11eb-9b2e-b75256abdc94.png)

(from https://www.sciencedirect.com/topics/mathematics/standardized-regression-coefficient) or:

![image](https://user-images.githubusercontent.com/31351465/106791358-1bd30680-6655-11eb-8e0e-e9dce964d335.png)

(from uqftp.ethz.ch/uqlab_doc_pdf/1.4.0/UserManual_Sensitivity.pdf, UQLab User Manual. Sensitivity Analysis, page 4).

However, the function `CorrelationAnalysis_SRC()` from:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.CorrelationAnalysis_SRC.html

computes :

![image](https://user-images.githubusercontent.com/31351465/106790525-fbef1300-6653-11eb-8ce8-f482fbc653f6.png)

which is the squared SRC coefficient.

The `CorrelationAnalysis_SignedSRC` function computes the SRC:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.CorrelationAnalysis_SignedSRC.html

And this is why the `SignedSRC` was asked by users: it provides the classical feature that most users know about. I admit that the current feature returns an importance factor which, in some situations, is more interesting. But the content does not match the name, and this is a bug. (In practice, we should consider both indices).  

Changing the content of the method without changing its name would break backward compatibility and lead to silent bugs in users' scripts.

Here is why I suggest the following update:
*  `CorrelationAnalysis_SRC` is tagged deprecated and removed in a future release
* `CorrelationAnalysis_SignedSRC` is tagged deprecated and removed in a future release
* a new `CorrelationAnalysis_StandardizedRegressionCoefficient` is created, which maps to `CorrelationAnalysis_SignedSRC`
* a new `CorrelationAnalysis_LinearImportanceFactor` is created, which maps to `CorrelationAnalysis_SRC`
* Both new pages would define their equations, so that the update content would be clear-cut.

@sofianehaddad : would you agree?

**Comment by sofianehaddad** [comment]
Hi @mbaudin47 agreed! Maybe we can go further and move the methods into a non-static class. What do you think?

**Comment by mbaudin47** [comment]
> Hi @mbaudin47 agreed! Maybe we can go further and move the methods into a non-static class. What do you think?

What for? Is there an issue with the current implementation?

**Comment by mbaudin47** [comment]
The doc of `CorrelationAnalysis_SignedSRC` is wrong: it mentions the rank, but not rank is involved in this computation.

**Comment by mbaudin47** [comment]
I have a use-case for a change of API. The `StandardizedRegressionCoefficient` class could provide two constructors:
* `StandardizedRegressionCoefficient(sample_X, sample_Y)` would estimate the coefficients based on the sample and a linear regression,
* `StandardizedRegressionCoefficient(distribution_X, linear_function)` would compute the coefficients based on the distribution and linear function.

Moreover, it could be extended to multidimensional output (the current implementation is restricted to single output dimension).

Below is an implementation of the second use-case:
```
import openturns as ot
import numpy as np

distribution = ot.ComposedDistribution([ot.Uniform(), ot.Normal()])
center = [0.0] * 2
constant = [3.0]
linear = ot.Matrix([[2.0, -3.0]])
g = ot.LinearFunction(center, constant, linear)

# Sample SRC
sample_size = 100000
sample_X = distribution.getSample(sample_size)
sample_Y = g(sample_X)
SSRC = ot.CorrelationAnalysis_SignedSRC(sample_X, sample_Y)
print("Sample SRC=", SSRC)

# Exact SRC
# Output variance
dimension_X = g.getInputDimension()
dimension_Y = g.getOutputDimension()
variance_Y = ot.Point(dimension_Y)
for j in range(dimension_Y):
    for i in range(dimension_X):
        marginal = distribution.getMarginal(i)
        marginal_sd = marginal.getStandardDeviation()
        variance_Y[j] += linear[j, i] ** 2 * marginal_sd[0] ** 2
standard_deviation_Y = ot.Point(dimension_X)
for j in range(dimension_Y):
    standard_deviation_Y[j] = np.sqrt(variance_Y[j])
# SRC
SRC = ot.Sample(dimension_Y, dimension_X)
for j in range(dimension_Y):
    for i in range(dimension_X):
        marginal = distribution.getMarginal(i)
        marginal_sd = marginal.getStandardDeviation()
        SRC[j, i] = linear[0, i] * marginal_sd[0] / standard_deviation_Y[j]

print("Exact SRC=", SRC)
```

**Comment by mbaudin47** [comment]
Final decision:
- the content of `SRC` is moved to `SquaredSRC`,
- the modified `SRC` computes the correct formula.
