### ISSUE TITLE
BestModelLilliefors returns p-value = 0

### ISSUE THREAD

**Issue by Tangzl922** [openturns/openturns#1755]
Hi,

I'm using FittingTest.BestModelLilliefors() to fit distribution from sample, but for some samples, sometimes it returns p-value = 0, sometimes doesn't. And a wrong distribution can be obtained.
How could this problem be explained and solved?

Regards

**Comment by jschueller** [comment]
I think this is already answered by https://github.com/openturns/openturns/issues/1585
