### ISSUE TITLE
GridLayout hides the titles in the graph

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1771]
When we create a grid, each graph in the grid may (or may not) have its own title. However, it seems that the class hides them by default. Moreover, it seems that it cannot be shown.

The following script, for example, 
```
import openturns as ot

sample_array = [100, 200, 400, 1000]
grid = ot.GridLayout(1, len(sample_array))
for i in range(len(sample_array)):
    sample = ot.Normal().getSample(sample_array[i])
    distribution = ot.KernelSmoothing().build(sample)
    graph = distribution.drawPDF()
    graph.setTitle("n=%d" % (sample_array[i]))
    graph.setLegends([""])
    grid.setGraph(0, i, graph)
```
produces:

![image](https://user-images.githubusercontent.com/31351465/107847985-70fadf00-6df0-11eb-930a-11d8f17dfc20.png)

We see that the titles in the graphs are not shown.

**Comment by mbaudin47** [comment]
I think that this is a choice in:

https://github.com/openturns/openturns/blob/4fa7756a99b09a4f1b3d3e735a206ca6ecc88ad2/python/src/viewer.py#L217

which is correct for pairplots, but this might not be universal.

**Comment by mbaudin47** [comment]
This is an invalid bug, as matplotlib performs the same.
The following code implements the viewer part in Python.
```
def grid_plot(grid, figure_size=(6.0, 6.0)):
    """
    Plot a grid of graphics.
    
    Parameters
    ----------
    grid : ot.GridLayout
        The grid.
    figure_size : a sequence(2)
        The width and height of the figure.
    """
    figure = pl.figure(figsize=figure_size)
    nbrows = grid.getNbRows()
    nbcolumns = grid.getNbColumns()
    for i in range(nbrows):
        for j in range(nbcolumns):
            k = 1 + i + j * nbrows
            graph = grid.getGraph(i, j)
            ax = figure.add_subplot(nbrows, nbcolumns, k)
            _ = otv.View(graph, figure=figure, axes=[ax])
    _ = figure.suptitle(grid.getTitle())
    return figure
import pylab as pl
_ = grid_plot(grid, figure_size = (16.0, 4.0))
pl.subplots_adjust(wspace=0.3)
```

produces:

![image](https://user-images.githubusercontent.com/31351465/107855561-71609d80-6e23-11eb-82f5-c70755c68fa1.png)

We see that the graph titles are not shown. 

This is why I close this issue.

**Comment by sofianehaddad** [comment]
I think there is a small bug [here](https://github.com/openturns/openturns/blob/master/python/src/viewer.py#L219)
IMO when handling with a `GridLayout`, we should use `self._ax[i]` for `graph(i,j).getTitle()`

Here a pure `matplotlib` example :
```
import matplotlib.pylab as plt
fig, ax = plt.subplots(2, 2)
c = 1
for i in range(2):
    for j in range(2):
         ax[i, j].plot(plt.np.arange(10), c * plt.np.arange(10))
         ax[i, j].set_title("c=%d"%c)
         c*=2
plt.show()
```
which produces
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1433220/107917595-767b3500-6f68-11eb-8c64-f95b84902645.png">

Then `GridLayout.getTitle()` should be handled by `self.fig_.suptitle`
Thus there is a small bug ;-)

**Comment by sofianehaddad** [comment]
@mbaudin47 in https://github.com/openturns/openturns/pull/1773 I proposed a solution.
I slightly updated your example (adding a title to the `GridLayout)

Here are script used and output:
```
import openturns as ot

sample_array = [100, 200, 400, 1000]
grid = ot.GridLayout(1, len(sample_array))
for i in range(len(sample_array)):
    sample = ot.Normal().getSample(sample_array[i])
    distribution = ot.KernelSmoothing().build(sample)
    graph = distribution.drawPDF()
    graph.setTitle("n=%d" % (sample_array[i]))
    graph.setLegends([""])
    grid.setGraph(0, i, graph)

grid.setTitle("ks comparison")
from openturns.viewer import View
view = View(grid)
view.show()
```
![image](https://user-images.githubusercontent.com/1433220/107954056-4483c600-6f9c-11eb-82c8-f8bc2fe9ef91.png)

**Comment by mbaudin47** [comment]
Thank you!
