### ISSUE TITLE
The GeneralizedParetoFactory has undocumented constructor

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1782]
The API doc of `GeneralizedParetoFactory`:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.GeneralizedParetoFactory.html?highlight=generalizedparetofactory

provides the constructor:

```
ot.GeneralizedParetoFactory(solver)
```

where `solver` is an `ot.OptimizationSolver()`. 

Moreover, there is no API example, so that a user cannot know that the following is possible (and, actually, necessary):
```
solver = ot.Cobyla()  # TNC is default, but fails
factory = ot.GeneralizedParetoFactory(solver)
dist, result = ot.FittingTest.Lilliefors(sample, factory, 0.01)
```

**Comment by josephmure** [comment]
The doc only mentions [one constructor](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.GeneralizedParetoFactory.html#openturns.GeneralizedParetoFactory):
```
GeneralizedParetoFactory()
```
So what must be done is:

1. mention the `GeneralizedParetoFactory(solver)` constructor,
2. create an adequate sample (do you have one to propose @mbaudin47?),
3. Add your code snippet as an example.

Is that right @mbaudin47?

**Comment by mbaudin47** [comment]
Yes, exactly.

**Comment by adutfoy** [comment]
I think it does not work like that. In the C++, there is indeed only one constructor. The solver is indicated in the ResourceMap with the key "GeneralizedParetoFactory-DefaultOptimizationAlgorithm" which is 'TNC' by default. 
I will add an example via the PR#2574.

**Comment by adutfoy** [comment]
ok: the keys are already mentioned. Nothing to do.
