### ISSUE TITLE
LinearModelResult.getFormula() method is not updated by Stepwise regression

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#1790]
Hello,
As the title says, I think that there's a small issue with the LinearModelResult which is obtained when using the LinearModelStepwiseAlgorithm class.  It seems that the regression formula provided by the getFormula method takes into account the entire functional basis onto which the stepwise algorithm is called, rather than the subset of functions selected by said algorithm.

A brief example is provided below:

```
import openturns as ot

'''Definition of the data set'''
ot.RandomGenerator.SetSeed(0)
distribution = ot.Normal()
func = ot.SymbolicFunction(['x1','x2', 'x3'], ['x1 + x2 + sin(x2 * 2 * pi_)/5 + 1e-3 * x3^2'])
dimension = 3
distribution = ot.ComposedDistribution([ot.Normal()]*dimension)
input_sample = distribution.getSample(20)
output_sample = func(input_sample)

'''Creation of a basis'''
functions = []
input_description = ['x1','x2', 'x3']
functions.append(ot.SymbolicFunction(input_description, ['1.0'])) #Constant term
for i in range(dimension): #Linear terms
    functions.append(ot.SymbolicFunction(input_description, [input_description[i]])) 
basis = ot.Basis(functions)

'''Stepwise regression'''
minimalIndices = [0]
isForward = True
penalty = 2.0 #Akaike information criterion 
maximumIterationNumber = 10
algo_forward = ot.LinearModelStepwiseAlgorithm(input_sample, basis, 
output_sample, minimalIndices, isForward, penalty, maximumIterationNumber)
algo_forward.run()
result_forward = algo_forward.getResult()
print('Selected coefficients: ', result_forward.getCoefficientsNames())
print('Formula: ', result_forward.getFormula())

```

Best regards

**Comment by jschueller** [comment]
yes, it's just the entire basis
also LinearModelStepwiseAlgorithm::getFormula is useless

**Comment by jschueller** [comment]
should the formula also contain the coefficients ?

**Comment by JPelamatti** [comment]
Personally, I think that the formula without coefficients makes for a clearer and more understandable visual output, especially given the fact that there is the getCoefficients method.

**Comment by jschueller** [comment]
ok

**Comment by sofianehaddad** [comment]
When we implemented `getFormula` feature, the description of `SymbolicFunction` was more readable and thus it makes sense to have both `coefficients` and `description`.  As an example, `[x1, x2] -> [x1]` description was initially `[x1]`.
For sure the work was not finalised as we don't have the coefficients inside the formula. (Some `R` inspirations ;-)) but it is never late.

However as we may provide any kind of function (symbolic, linear, python,...), we can not handle the `basis.__str__()` output of each function and it becomes difficult to read the corresponding formula.  
IMHO we should rely on other services (`getDescription`) for example to make a good balance between having a readable output / not dropping this method. The purpose is that user might define the description of the function.
Any (other) idea?
