### ISSUE TITLE
EGO getResult().getOutputSample() yields wrong sample

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1795]
When you run the EGO example `plot_ego.py` with the current master and append it with the following line:

```
print(result.getOutputSample())
```

you get:

```
 0 : [ 0 0 ]
 1 : [ 0 0 ]
 2 : [ 0 0 ]
 3 : [ 0 0 ]
 4 : [ 0 0 ]
 5 : [ 0 0 ]
 6 : [ 0 0 ]
 7 : [ 0 0 ]
 8 : [ 0 0 ]
 9 : [ 0 0 ]
10 : [ 0 0 ]
11 : [ 0 0 ]
12 : [ 0 0 ]
13 : [ 0 0 ]
14 : [ 0 0 ]
15 : [ 0 0 ]
16 : [ 0 0 ]
17 : [ 0 0 ]
18 : [ 0 0 ]
19 : [ 0 0 ]
```

When you run it with OT 1.16, you get something like this instead :

```
 0 : [ -0.874903 ]
 1 : [ -0.960459 ]
 2 : [ -0.960623 ]
 3 : [ -0.787077 ]
 4 : [ -0.956606 ]
 5 : [ -0.942971 ]
 6 : [ -0.740798 ]
 7 : [ -0.961812 ]
 8 : [ -0.966798 ]
 9 : [ -0.957343 ]
10 : [ -0.970366 ]
11 : [ -0.962785 ]
12 : [ -0.967757 ]
13 : [ -0.9772   ]
14 : [ -0.968444 ]
15 : [ -0.892943 ]
16 : [ -0.958074 ]
17 : [ -0.965214 ]
18 : [ -0.972462 ]
19 : [ -0.971796 ]
```

This explains why `result.drawOptimalValueHistory()` does not work in the [master doc](https://openturns.github.io/openturns/master/auto_numerical_methods/optimization/plot_ego.html#create-and-solve-the-problem) but does in the [1.16 doc](https://openturns.github.io/openturns/1.16/auto_numerical_methods/optimization/plot_ego.html#create-and-solve-the-problem)

It looks like in master, the output sample is simply initialized. What is really curious is that the dimension of the output sample has changed: 2 in master, 1 in 1.16.

**Comment by josephmure** [comment]
I don't think this issue needs to be mentioned in the ChangeLog since the problem does not affect any released version of OpenTURNS.

**Comment by jschueller** [comment]
ok

**Comment by josephmure** [comment]
Does your commit fix it or is it simply a step towards a fix?

**Comment by jschueller** [comment]
it fixes it, it was broken when I squared the OptimResult api, but now it makes EGO weird because it uses a 2-d objective function, I wonder if I should change the API of EGO to provide the noise from a separate function instead of the objective 2nd marginal

**Comment by sofianehaddad** [comment]
IMHO we should postpone changes in `EGO` as we are planning to drop the current `KrigingAlgorithm::setNoise` and move it into a specific `CovarianceModel`

**Comment by josephmure** [comment]
On the other hand, since @jschueller has already fixed it, we might as well use the fix. And something needed to be done to make the example work.

**Comment by jschueller** [comment]
sofiane probably meant changes on the ego api, not revoking this fix

**Comment by sofianehaddad** [comment]
exact @jschueller
