### ISSUE TITLE
Brent's implementation has a stability issue

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1805]
The conditions to bracket the root:

https://github.com/openturns/openturns/blob/bc1ba291d2377bdd2bbefce9009f1790e3443305/lib/src/Base/Solver/Brent.cxx#L80

and

https://github.com/openturns/openturns/blob/bc1ba291d2377bdd2bbefce9009f1790e3443305/lib/src/Base/Solver/Brent.cxx#L156

should use the sign of fa and fb to check the condition instead of performing the product. 
Indeed, this may produce unnecessary overflows / underflows.
See:

https://github.com/scipy/scipy/issues/13737

for a similar discussion, bibliographical references and a test case.
The remaining of the code seems to be impeccable: the use of ratios e.g. f(a)/f(b) seems to be the correct way to do.

**Comment by jschueller** [comment]
```
import openturns as ot
f = ot.SymbolicFunction(['x'], ['exp(x)-1.9151695967140057e-174'])
solver = ot.Brent()
a = -450.0
b = -350.0
root = solver.solve(f, 0.0, a, b)
print(root) 
```
gives -450

**Comment by regislebrun** [comment]
I fixed it (and also Bisection & Secant) in an upcoming PR
