### ISSUE TITLE
Problem with wilksNumber 

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1818]
This code

````
import openturns as ot
import numpy as np

sample = ot.Normal(0,10).getSample(10000)
alpha = 0.995
confidence_level = np.linspace(0.001,0.999, 10000)
plt.plot(confidence_level, [ot.Wilks.ComputeSampleSize(alpha, beta) for beta in confidence_level])
````
shows the evolution of wilksNumber according to the confidence level. The function is expected to be monotonous but it isn't.

![image](https://user-images.githubusercontent.com/52526981/114847146-ae262200-9ddd-11eb-8adb-9467ae193900.png)

**Comment by regislebrun** [comment]
I fixed it, now I get:
![Wilks](https://user-images.githubusercontent.com/8220933/114849745-5806ae00-9de0-11eb-835d-1e0d63d6d93c.png)
