### ISSUE TITLE
SimulatedAnnealingLHS accepts SpaceFillingMinDist but minimizes the criterion

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1826]
A possible way to solve the issue is to no longer let `SimulatedAnnealingLHS` accept `SpaceFillingMinDist`. This could be achieved by calling `spaceFilling_.isMinimization()` and throwing when the result is `false`.

See the [Gitter discussion](https://gitter.im/openturns/community?at=60743c2ca9dd556843d2dda8) for details.

@efekhari27 @jschueller @mbaudin47 @JPelamatti @sofianehaddad

**Comment by JPelamatti** [comment]
It  might be an ingenuous question, but why not simply minimize the opposite of the maximization objective function (i.e., min -f(x) ) when dealing with a false `isMinimization()` attribute?
Indeed, as stated in the gitter discussion, for this specific problem, maximizing `SpaceFillingMinDist` is equivalent to minimizing `SpaceFillingPhiP`, and therefore we could simply not allow the user to use this particular space filling class. However, an alternative minimization based solution might not always be available in future developments, and we would be back dealing with the same issue.

**Comment by sofianehaddad** [comment]
I will try a fix
