### ISSUE TITLE
Incompatible documentation for CauchyModel

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/openturns#1833]
On the [theory side](http://openturns.github.io/openturns/master/theory/probabilistic_modeling/parametric_spectral_model.html?highlight=spectral%20model) and [API side](http://openturns.github.io/openturns/master/user_manual/_generated/openturns.CauchyModel.html#openturns.CauchyModel) definitions of the Cauchy model differ.
And both are wrong (missing a factor two for the API one). This should be fixed before the release

**Comment by jschueller** [comment]
the two formula have common terms, but I really dont know what to fix here, do you think you can adress this before wednesday ?

**Comment by sofianehaddad** [comment]
Sorry I was on leave.
It will be done for next release ;-)

**Comment by jschueller** [comment]
hi @sofianehaddad any news on this ?

**Comment by sofianehaddad** [comment]
I will fix this in the next couple of days
