### ISSUE TITLE
libOT.so.0.0.0 doesn't have a SONAME

### ISSUE THREAD

**Issue by yurivict** [openturns/openturns#1842]
```
Warning: /disk-samsung/freebsd-ports/math/openturns/work/stage/usr/local/lib/libOT.so.0.0.0 doesn't have a SONAME.
Warning: pkg(8) will not register it as being provided by the port.
Warning: If another port depend on it, pkg will not be able to know where it comes from.
```

Version 1.17
OS: FreeBSD 12.2

**Comment by jschueller** [comment]
Does it go away with: ```cmake -DLIB_SOVERSION=0.17 -DLIB_VERSION=0.18.0``` ?

**Comment by yurivict** [comment]
I didn't try this. Setting SONAME should be done inside of cmake scripts and shouldn't be user-visible.

**Comment by jschueller** [comment]
could you test this so we can make it the default for the next release ?

**Comment by yurivict** [comment]
It works, except it should be:
```
cmake -DLIB_SOVERSION=0 -DLIB_VERSION=0.18.0
```

ldconfig(8) manpage says:
```
Filenames must conform to the lib*.so.[0-9] pattern in order to be added to the hints file.
```
and therefore SONAME can only have one number in it.

**Comment by yurivict** [comment]
I take back my previous comments.

No, ```-DLIB_SOVERSION=0.18 -DLIB_VERSION=0.18.0``` doesn't work.
It creates symlinks but doesn't set the SONAME.

You needs to add something like this:
```
SET_TARGET_PROPERTIES(
  libOT
  PROPERTIES
  VERSION 0.18.0
  SOVERSION 0.18
)
```

Multiple numbers in SOVERSION are ok.
