### ISSUE TITLE
Ali-Mikhail-Haq copula parameter value

### ISSUE THREAD

**Issue by MLasserre** [openturns/openturns#1843]
When I define an Ali-Mikhail-Haq copula with theta=1:
```
import openturns as ot  
amh_copula = ot.AliMikhailHaqCopula(1)
```
I have the following error:
`
InvalidArgumentException : Theta MUST be in (-1, 1), here theta=1
`
According to documentation it is 1 by default and theta is in [-1;1].

**Comment by MLasserre** [comment]
I just checked the file `AliMikhailHaqCopula.cxx` and it is set to 0.5 by default.

**Comment by MLasserre** [comment]
There is also the same problem with the Farlie-Gumbel-Morgenstern copula.
The parameter theta is said (according to documentation) to be set to 1 by default while it is set to 0.5.

**Comment by regislebrun** [comment]
@MLasserre You are right. I checked all the copula and found other discrepancies between the documentation and the code:
  * in EmpiricalBernsteinCopula, the default sample is *[[0.0],[0.0]]* and not *[[0.0]]*
  * in FarlieGumbelMorgensternCopula, the default theta is 0.5 and not 1
  * in NormalCopula, the default dimension is 2 (was not in the doc)
