### ISSUE TITLE
Sample indexing does not work on np.int64 type

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#1854]
Hello,
I have noticed that the indexing of ot.Sample objects (in the sense of accessing specific elements of a Sample) only works with int indices, and not with np.int64 indices. This issue can be problematic when we are given the indices in the form a numpy array, as is briefly shown in the example below.

```
import openturns as ot
import numpy as np

sample = ot.Uniform().getSample(5)

index_list = [1,3,4] #Indices to be accessed under the form of list
print(type(index_list))  # <class 'list'>
print(type(index_list[0])) # <class 'int'>
print(sample[index_list])

index_array = np.array([1,3,4])  #Indices to be accessed under the form of a numpy array
print(type(index_array))
print(sample[index_array]) #This does not work

index_array2list = list(index_array)  #The array is transformed into a list in order to access the sample elements
print(type(index_array2list)) # <class 'list'> , as expected
print(type(index_array2list[0])) # <class 'numpy.int64'> , this is different than the working example above
print(sample[index_array2list]) # This does not work either
```

The solution I found would be to build the list of indices from an array in a sequential manner in order to be able to call the int() command, as follows:
```
index_fromarray = [int(i) for i in index_array]
print(type(index_fromarray)) #<class 'list'>
print(type(index_fromarray[0])) # <class 'int'>
print(sample[index_fromarray]) #This second workaround works
```
Given the good compatibility between openturns and numpy objects, I think it might be worth extending the indexing of openturns objects to np.int64 indices, especially as the difference between the two types of values is not particularly easy to spot and users might get stuck.

EDIT: the np.array().tolist() command also seems to be a viable solution
EDIT2 : This issue is also acknowledged in issue #1427

**Comment by jschueller** [comment]
Sample.__getitem__ should check for an `__int__()` method, unfortunately its only wired when asking a single Point

**Comment by sofianehaddad** [comment]
@jschueller I am lost. how to solve this issue?
