### ISSUE TITLE
Speed up Normal computeSurvivalFunction

### ISSUE THREAD

**Issue by jaronowitz** [openturns/openturns#1856]
I have some code that needs to call `computeSurvivalFunction` function around 100,000 times for a 20-dimensional multivariate normal. Is there any way to do this in a reasonable amount of time? I've been trying to parallelize the function calls but they still are very time intensive. Below is the function that needs to be sped up.

```
def Phi(x, sig, mu=None):
    """Computes survival function of MVN at point x"""
    if mu is None:
        mu = np.zeros(sig.shape[0])

    assert sig.shape[0] == mu.shape[0]

    mvn = ot.Normal(mu, ot.CovarianceMatrix(sig))
    prob = mvn.computeSurvivalFunction(x)

    return prob

```

Thank you so much in advance for any guidance.

**Comment by regislebrun** [comment]
Hi,
First of all your problem is hard if the covariance matrix is general, i.e. if there is no structure allowing to reduce the problem to a lower dimensional one. If you track the calls you see that Normal::computeSurvivalFunction() is implemented as EllipticalDistribution::computeSurvivalFunction(), which uses the symmetry of the elliptical distributions to make a call to computeCDF(). So the only way you can speed-up the computation is by tweaking the numerical parameters of Norma::computeCDF(). In ResourceMap.cxx, you have the following keys:
```
  // Normal parameters //
  addAsScalar("Normal-MaximumCDFEpsilon", 5.0e-6);
  addAsScalar("Normal-MinimumCDFEpsilon", 5.0e-2);
  addAsUnsignedInteger("Normal-MarginalIntegrationNodesNumber", 16);
  addAsUnsignedInteger("Normal-MaximumNumberOfPoints", 10000000);
  addAsUnsignedInteger("Normal-MinimumNumberOfPoints", 100000);
  addAsUnsignedInteger("Normal-SmallDimension", 6);
```
If you want to try quadrature rules on your 20 dim problem you can set `Normal-SmallDimension` to any value not less than 20, but you also will have to reduce `Normal-MarginalIntegrationNodesNumber` to 2 or 3 in order to keep the number of integration nodes to something reasonable. The best option is to reduce the number of Monte Carlo sample: set `Normal-MaximumNumberOfPoints` to 1000000 in order to get values correct with an absolute precision of order a few 1e-3. Depending on your case, you will get a speed-up as large as 10x. Otherwise you will have to use more complex constructs. If you send me an example of the covariance matrices and the range of arguments you plan to use I can give post a more efficient python implementation than the default one.

Cheers

Régis

**Comment by jaronowitz** [comment]
Hi Régis,

Thank you so much for the prompt response and detailed answer. Below are a few examples of the covariance matrices (`sig`) and the corresponding point `x` for which `Phi` is evaluated. The mean `mu` is always zero so the gaussians are centered. For the purpose of legibility I reduced the size from 20 dimensions to 5.

If you need a more detailed explanation of how these arguments are created, I can post the full code that generates `sig` and `mu` but it is a bit more complex. 

The context of the problem is to calculate the expected value of the maximum component of a 20 dimensional multivariate gaussian. The formula for this can be found as Corollary 2 in [this paper](https://www.jstor.org/stable/2985184). The explicit formula for a single 20 dimensional mvn involves 20 calls to `computeSurvivalFunction` of a 19 dimensional mvn and 19*20/2 calls to `computeSurvivalFunction` of an 18 dimensional mvn.

The above mentioned expected value is an objective function for an optimization problem so the objective function itself gets called many many times. 



```
#############################################
x:
[ 0.36536493 -0.18729894  0.01196479  0.29317741  0.02313473]
sig: 
[[1.         0.60464906 0.55677696 0.56099316 0.56333635]
 [0.60464906 1.         0.53028679 0.47451481 0.60313954]
 [0.55677696 0.53028679 1.         0.56620479 0.50331222]
 [0.56099316 0.47451481 0.56620479 1.         0.56976393]
 [0.56333635 0.60313954 0.50331222 0.56976393 1.        ]]
####################################################
x:
[-0.36536493 -0.62642604 -0.37524169 -0.07778601 -0.36515493]
sig: 
[[1.         0.49842976 0.47029487 0.4702817  0.4630271 ]
 [0.49842976 1.         0.45831974 0.39141041 0.53731128]
 [0.47029487 0.45831974 1.         0.50869251 0.43391773]
 [0.4702817  0.39141041 0.50869251 1.         0.50793587]
 [0.4630271  0.53731128 0.43391773 0.50793587 1.        ]]
####################################################
x:
[0.18729894 0.62642604 0.19974362 0.471138   0.22964425]
sig: 
[[1.         0.3891278  0.43561069 0.4699065  0.38547485]
 [0.3891278  1.         0.45946852 0.50072818 0.41577447]
 [0.43561069 0.45946852 1.         0.53962054 0.39326153]
 [0.4699065  0.50072818 0.53962054 1.         0.51009019]
 [0.38547485 0.41577447 0.39326153 0.51009019 1.        ]]
####################################################
x:
[-0.01196479  0.37524169 -0.19974362  0.30146934  0.0112862 ]
sig: 
[[1.         0.47121766 0.53215251 0.46797763 0.49494658]
 [0.47121766 1.         0.57883218 0.5002837  0.53551026]
 [0.53215251 0.57883218 1.         0.43561577 0.60103533]
 [0.46797763 0.5002837  0.43561577 1.         0.53866186]
 [0.49494658 0.53551026 0.60103533 0.53866186 1.        ]]
####################################################
x:
[-0.29317741  0.07778601 -0.471138   -0.30146934 -0.28988363]
sig: 
[[1.         0.46674026 0.55403114 0.46346469 0.45772222]
 [0.46674026 1.         0.60055316 0.49097143 0.49531211]
 [0.55403114 0.60055316 1.         0.52276203 0.59408661]
 [0.46346469 0.49097143 0.52276203 1.         0.4223133 ]
 [0.45772222 0.49531211 0.59408661 0.4223133  1.        ]]
####################################################
```

Regards,
Julian

**Comment by regislebrun** [comment]
Hi Julian,

The best I got so far is the following:
```
class PhiSample:
    def __init__(self, sig, mu=None, sampling_size = ot.ResourceMap.GetAsUnsignedInteger("Normal-MaximumNumberOfPoints")):
        """Computes survival function of MVN at point x"""
        if mu is None:
            mu = np.zeros(sig.shape[0])
        assert sig.shape[0] == mu.shape[0]
        self.sample = ot.Normal(mu, ot.CovarianceMatrix(sig)).getSample(sampling_size)

    def computeSurvivalFunction(self, x):
        prob = self.sample.computeEmpiricalCDF(x, True)
        return prob
```
As both `Normal.getSample()` and `Sample.computeEmpiricalCDF` are parallelized, the speed is somewhat correct. Unfortunately, for a 20-d normal distribution most of the space is empty so you will spend a lot of time computing a value of... zero! For example, if your components are independent, the survival function at [1.0]*20 is equal to 1.0211491264457884e-16, so mostly unreachable with any sampling algorithm.
You should have a look at `MaximumDistribution`. I tested it on your 5d case and... it takes a very long time to compute anything. But if you try:
```
import openturns as ot
from time import time

ot.ResourceMap.SetAsUnsignedInteger("Normal-MaximumNumberOfPoints", 100000000)

R = ot.CovarianceMatrix(5, [1.,         0.60464906, 0.55677696, 0.56099316, 0.56333635, 0.60464906, 1.,         0.53028679, 0.47451481, 0.60313954, 0.55677696, 0.53028679, 1.,         0.56620479, 0.50331222, 0.56099316, 0.47451481, 0.56620479, 1.,      0.56976393, 0.56333635, 0.60313954, 0.50331222, 0.56976393, 1.])
# Will take forever
d = ot.MaximumDistribution(ot.Normal([0.0]*5, R))
#print("d mean    =", d.getMean())
t0 = time()
mu = d.getSample(ot.ResourceMap.GetAsUnsignedInteger("Normal-MaximumNumberOfPoints")).computeMean()[0]
t1 = time()
print("d mean(MC)=%.4f" % mu, "t=%.2f" % (t1 - t0), "s")
```
you get:
```
d mean(MC)=0.7757 t=30.97 s
```
on my laptop. Sadly, the computation is purely sequential. You can reduce the sampling size to get something faster. The main point is to control the seed of the random generator if you want to get something smooth enough for your optimization algorithm to be happy. If you are interested in robust optimization you should have a look here http://openturns.github.io/otrobopt/master/index.html.
Unfortunately I have no access to the full paper you mentioned. If the relevant formulas are available elsewhere I will be happy to have a look at them and to try one or two ideas on them.

Cheers

Régis

**Comment by jaronowitz** [comment]
Hi Régis,

Your class `PhiSample` works perfectly! The expectation calculation is essentially a linear combination of the `SurvivalFunction` evaluations. So the high dimensional concentration issue you mentioned of 1.0211491264457884e-16 being approximated as 0 is not too big of a problem for me.

I took a look at `MaximumDistribution` and as you mentioned it runs very slow. For my problem I think explicitly computing the expected value is significantly faster than approximating the entire extreme value distribution then taking its mean. It is very cool that this is a feature of openturns though and implementing it was so much easier than translating the unwieldy formula from the cited paper!

One final question- I experimented running my code on virtual machines with 8 CPUs and 16 CPUs (GCP c2-standard-8 and GCP c2-standard-16) and the runtime was more or less identical. You mentioned that  `Normal.getSample()` and `Sample.computeEmpiricalCDF` are parallelized so shouldn't there be some speedup without any other explicit parallelization in my code?

Thanks again for all your help and insightful answers,
Julian

**Comment by regislebrun** [comment]
Hi Julian,

Regarding the parallelization, it all depends on your environment. On a native linux box and the OT conda package, you have both TBB and parallel blas so the computation is fully parallel. TBB is used for the parallelization of the native OT algorithms (here: `computeEmpiricalCDF`) , and we rely on parallel BLAS for the parallelization of the dense linear algebra (here: `getSample`), most of the time through OpenBLAS, based on OpenMP. Sometimes you have to deactivate either OpenMP or TBB in order to avoid the creation of too many threads (see https://gitter.im/openturns/community?at=5f2426bf36563560f2b4fb7e). So to further help you:
  * give me the description of your environment (OS+cores in the guest+cores in the host)
  * give me a description of your OT package (pip, conda etc.)
I will check on my side that there is no bad interaction between TBB and OpenMP.

I would love to read the reference you pointed ;-).

Cheers

Régis

**Comment by regislebrun** [comment]
Here are the results of this benchmark on my laptop (Linux 64 8 cores/16threads, OpenBLAS+TBB):
```
import sys

use_OMP = sys.argv[1] == "True"
use_TBB = sys.argv[2] == "True"
size = 100

print("use_OMP=", use_OMP, "use_TBB=", use_TBB)

# Must be set before to load OT module
import os
if not use_OMP:
    os.environ["OPENBLAS_NUM_THREADS"] = "1"
    os.environ["OMP_NUM_THREADS"] = "1"

import openturns as ot
if not use_TBB:
    ot.TBB.Disable()

import numpy as np

ot.ResourceMap.SetAsUnsignedInteger("Normal-MaximumNumberOfPoints", 1000000)
  
class PhiSample:
    def __init__(self, sig, mu=None, sampling_size = ot.ResourceMap.GetAsUnsignedInteger("Normal-MaximumNumberOfPoints")):
        """Computes survival function of MVN at point x"""
        if mu is None:
            mu = np.zeros(sig.shape[0])
        assert sig.shape[0] == mu.shape[0]
        self.sample = ot.Normal(mu, ot.CovarianceMatrix(sig)).getSample(sampling_size)

    def computeSurvivalFunction(self, x):
        prob = self.sample.computeEmpiricalCDF(x, True)
        return prob

dim = 20
d_ref = ot.Normal(dim)
sigma = np.array(d_ref.getSample(2*dim).computeCovariance())
points = d_ref.getSample(size)
from time import time

print("Unique normal,", size, "points")
t0 = time()
phi = PhiSample(sigma)
for x in points:
    res = phi.computeSurvivalFunction(x)
    #print("x=", x, "->%.4e" % res)
t1 = time()
print("(PhiSample) Speed=", size / (t1 - t0), "evals/s")

print("#"*10)
print(size, "normal + point")
t0 = time()
for x in points:
    phi = PhiSample(sigma)
    res = phi.computeSurvivalFunction(x)
    #print("x=", x, "->%.4e" % res)
t1 = time()
print("(PhiSample) Speed=", size / (t1 - t0), "evals/s")
```
I get:
```
use_OMP= True use_TBB= True
Unique normal, 100 points
(PhiSample) Speed= 101.53356864626637 evals/s
##########
100 normal + point
(PhiSample) Speed= 1.7632828477246016 evals/s
real    0m58,011s
user    3m16,242s
sys     2m29,481s

use_OMP= True use_TBB= False
Unique normal, 100 points
(PhiSample) Speed= 42.523076018429386 evals/s
##########
100 normal + point
(PhiSample) Speed= 1.6559602357355832 evals/s
real    1m3,122s
user    3m10,693s
sys     2m32,066s

use_OMP= False use_TBB= True
Unique normal, 100 points
(PhiSample) Speed= 112.01191288807419 evals/s
##########
100 normal + point
(PhiSample) Speed= 2.2030691539927325 evals/s
real    0m46,576s
user    0m52,648s
sys     0m7,754s

use_OMP= False use_TBB= False
Unique normal, 100 points
(PhiSample) Speed= 43.53756862067741 evals/s
##########
100 normal + point
(PhiSample) Speed= 2.0607193879377905 evals/s
real    0m51,073s
user    0m43,214s
sys     0m7,859s
```
As you see, I get the best performance with OMP off and TBB on, and the speed-up is not impressive because the parallel part is only a small fraction of the total work. IMO there is room for huge improvements if you implement a dedicated function for the mean of the maximum of correlated Gaussian by generating a unique large sample of iid standard Gaussian then reuse it through the whole computation, using parallel algebra to induce correlation when needed during your iterations and using computeEmpiricalCDF() on these correlated samples. This way you will avoid the significant cost of generating each time a large amount of standard Gaussian random deviates.

Cheers

Régis

**Comment by jaronowitz** [comment]
Hi Régis,

Thank you again for your excellent insights and suggestions! I believe I've more than satisfactorily solved the problem with your help.

> IMO there is room for huge improvements if you implement a dedicated function for the mean of the maximum of correlated Gaussian by generating a unique large sample of iid standard Gaussian then reuse it through the whole computation, using parallel algebra to induce correlation when needed during your iterations and using computeEmpiricalCDF() on these correlated samples.

I realized that if I'm sampling anyways to compute the explicit mean function, a more efficient technique for reusing the samples would be to instead sample directly from the correlated normal and approximate the expected value of the maximum component by monte carlo without the explicit formula. The explicit formula required many unrelated mc approximations so why not just the one mc sample to compute the whole thing?

Also my optimization problem is to find the matrix in a class of matrices that after premultiplying the correlated normal results in the largest expected value of the maximum component. Thus the following code only needs to sample once for the whole optimization procedure!

```
class NormalSampler:
    def __init__(self, mu, sig, sampling_size=1000000):
        if mu is None:
            mu = np.zeros(sig.shape[0])
        assert sig.shape[0] == mu.shape[0]
        self.sample = ot.Normal(mu, ot.CovarianceMatrix(sig)).getSample(sampling_size)
        self.sample = np.array(self.sample).T
        self.dim = sig.shape[0]
        self.sampling_size = sampling_size

    def computeAfanja_mean(self, b):
        samples_transformed = b @ self.sample
        samples_max = samples_transformed.max(axis=0)

        return np.mean(samples_max)

    def get_Afanja_samples(self, b):
        samples_transformed = b @ self.sample
        samples_max = samples_transformed.max(axis=0)

        return samples_max
```

The solution no longer involves "speeding up normal computeSurvivalFunction" as the title of this issue suggests, but nonetheless I am extremely grateful for your help solving the central problem. Below I've attached the paper as you requested, the relevant part is corollary 2 in section 3.1. If you happen to have any more thoughts or insights please let me know!

[The Moments of the Maximum of Correlated Normal.pdf](https://github.com/openturns/openturns/files/6658921/The.Moments.of.the.Maximum.of.Correlated.Normal.pdf)

Thanks again,
Julian
