### ISSUE TITLE
ProductCovarianceModel fails when constructed with DiracCovarianceModel

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1857]
The following script:
```
import openturns as ot
c = ot.ProductCovarianceModel([ot.DiracCovarianceModel(1)])
```
enters an (almost) infinite loop. It is due to the way extra parameters are computed in `ProductCovarianceModel.cxx`:
https://github.com/openturns/openturns/blob/master/lib/src/Base/Stat/ProductCovarianceModel.cxx#L115
For a DiracCovarianceModel it is not true that the number of parameters is greater than the input dimension as the scale parameter has been removed (and not simply deactivated) from the list of parameters.

**Comment by sofianehaddad** [comment]
ah my bad! Probably the same issue for `IsotropicCovarianceModel`, `KroneckerCovarianceModel`...
I will check

**Comment by regislebrun** [comment]
I already have a PR to fix it and other little glitches (e.g. one of the constructors of MaternModel was missing an isStationary_ = true instruction). I will push it in a few minutes.

**Comment by sofianehaddad** [comment]
ok 
thanks
