### ISSUE TITLE
FORM - IMPORTANCE FACTOR

### ISSUE THREAD

**Issue by HAFID-Anas** [openturns/openturns#1864]
Hi, 

I do not understand why deterministic variable modelled with Dirac distribution, have high importance factor values.

Example Bellow : 

```
from __future__ import print_function
import openturns as ot
import numpy as np
import openturns.viewer as viewer
from matplotlib import pylab as plt
#ot.Log.Show(ot.Log.NONE)
```

#X = [Hs, Delta, Dn, Kd, cot_a, A]
```
def Hudson(X):
    Hs, Delta, Dn, Kd, cot_a, A = X
    Z = A*Delta*Dn*np.power(Kd*cot_a,1.0/3.0)-Hs
    return [Z]
```
```
ot_Hudson = ot.PythonFunction(6, 1, Hudson)
dist_Hs = ot.Gumbel(1/1.164,2.74/1.164)
dist_Delta = ot.Normal(1.233, 0.047)
dist_Dn = ot.Normal(2.06, 0.113)
dist_Kd = ot.Dirac(8) # Deterministic parameter
dist_cot_a = ot.Normal(2,0.10)
dist_A = ot.Normal(1,0.18)
```

```
distribution = ot.ComposedDistribution([dist_Hs, dist_Delta, dist_Dn, dist_Kd, dist_cot_a, dist_A])
vect = ot.RandomVector(distribution)
output = ot.CompositeRandomVector(ot_Hudson, vect)
Faillure_Hudson = ot.ThresholdEvent(output, ot.Less(), 0.0)
```

# Estimate the probability with FORM - Define a solver.
```
optimAlgo = ot.Cobyla()
optimAlgo.setMaximumEvaluationNumber(1000)
optimAlgo.setMaximumAbsoluteError(1.0e-10)
optimAlgo.setMaximumRelativeError(1.0e-10)
optimAlgo.setMaximumResidualError(1.0e-10)
optimAlgo.setMaximumConstraintError(1.0e-10)
```

# Run  FORM
```
startingPoint = distribution.getMean()
algo = ot.FORM(optimAlgo, Faillure_Hudson, startingPoint)
algo.run()
result = algo.getResult()
ImportanceFactors = result.getImportanceFactors()
print('ImportanceFactors =', ImportanceFactors)
```

# Results : 
ImportanceFactors = [Hs : 0.0483065, Delta : 0.000518936, Dn : 0.00109101, Kd : 0.932697, cot_a : 9.86208e-05, A : 0.0172874]

**Comment by HAFID-Anas** [comment]
Is this a bug ?, I do not think determenistic parameters should have an importance factor.

**Comment by HAFID-Anas** [comment]
Is this a bug ?, I do not think determenistic parameters should have an importance factor.

**Comment by regislebrun** [comment]
Hi,
Thank you for recalling us this bug! It is a long-standing bug in OpenTURNS: FORM/SORM analyses should not be allowed for discrete distributions as the associated isoprobabilistic distribution is **not** a diffeomorphism. It would be miraculous to be able to transform a constant into a Gaussian distribution ;-)!
I remember a discussion we (the dev team) had many years ago about an extension of the FORM/SORM algorithm to the case of discrete distributions using this approach:
  * extract the full support of the discrete part of the input distribution
  * conditioned to the possible values of this discrete part, compute the probability of the (conditioned) event involving only continuous distributions
  * aggregate all these contributions using the total decomposition formula

The algorithm can be made efficient in several ways, for example:
  * by pruning conditional events whose conditional probability is so small that the contribution would be negligible wrt the already computed contributions. It leads to a strategy for the exploration of the discrete support: select the discrete points in the reverse order of their probabilities
  * by taking the design point of the closest discrete point already computed as a starting point for the current optimization

but we didn't found the time to implement it, and then we forgot it. But things may change thanks to your reminder!

Another approach, much easier to implement but much less numerically robust is to replace each discrete distribution by a convolution with a very narrow kernel, such as ot.Normal(0.0, 1e-6) or ot.Uniform(-1e-6, 1e-6). Waiting for a better implementation of FORM, replace the `ot.Dirac(8)` distribution by **any** approximation of it, e.g. `ot.Normal(8, 1e-6)`, which is equivalent to `ot.Dirac(8)+ot.Normal(0.0, 1e-6)`, or `ot.Uniform(8.0-1e-6, 8.0+1e-6)`, which is equivalent to `ot.Dirac(8)+ot.Uniform(-1e-6, 1e-6)`, and then you will get much more meaningful results:
```
from __future__ import print_function
import openturns as ot
import numpy as np

def Hudson(X):
    Hs, Delta, Dn, Kd, cot_a, A = X
    Z = A*Delta*Dn*np.power(Kd*cot_a,1.0/3.0)-Hs
    return [Z]

ot_Hudson = ot.PythonFunction(6, 1, Hudson)
dist_Hs = ot.Gumbel(1/1.164,2.74/1.164)
dist_Delta = ot.Normal(1.233, 0.047)
dist_Dn = ot.Normal(2.06, 0.113)
#dist_Kd = ot.Dirac(8) # Deterministic parameter
dist_Kd = ot.Dirac(8) + ot.Normal(0.0, 1e-6) # Use a Normal based Dirac approximation
#dist_Kd = ot.Dirac(8) + ot.Uniform(-1e-6, 1e-6) # Use a Uniform based Dirac approximation
dist_cot_a = ot.Normal(2,0.10)
dist_A = ot.Normal(1,0.18)

distribution = ot.ComposedDistribution([dist_Hs, dist_Delta, dist_Dn, dist_Kd, dist_cot_a, dist_A])
distribution.setDescription(["Hs", "Delta", "Dn", "Kd", "cot_a", "A"])
vect = ot.RandomVector(distribution)
output = ot.CompositeRandomVector(ot_Hudson, vect)
Faillure_Hudson = ot.ThresholdEvent(output, ot.Less(), 0.0)

# Estimate the probability with FORM - Define a solver.

optimAlgo = ot.Cobyla()
optimAlgo.setMaximumEvaluationNumber(1000)
optimAlgo.setMaximumAbsoluteError(1.0e-10)
optimAlgo.setMaximumRelativeError(1.0e-10)
optimAlgo.setMaximumResidualError(1.0e-10)
optimAlgo.setMaximumConstraintError(1.0e-10)

# Run FORM

startingPoint = distribution.getMean()
algo = ot.FORM(optimAlgo, Faillure_Hudson, startingPoint)
algo.run()
result = algo.getResult()
ImportanceFactors = result.getImportanceFactors()
print('ImportanceFactors =', ImportanceFactors)
```
gives you, using the ot.Normal approximation:
```
ImportanceFactors = [Hs : 0.717752, Delta : 0.0077105, Dn : 0.0162105, Kd : 1.05796e-14, cot_a : 0.00146534, A : 0.256861]
```
and, using the ot.Uniform approximation:
```
ImportanceFactors = [Hs : 0.717752, Delta : 0.0077105, Dn : 0.0162105, Kd : 6.823e-15, cot_a : 0.00146534, A : 0.256861]
```
and the importance factor of Kd is essentially zero, as expected!

Cheers

Régis

**Comment by HAFID-Anas** [comment]
Thanks a lot regislebrun.

**Comment by jschueller** [comment]
short-t

**Comment by josephmure** [comment]
Regis' method will be documented as an example.

**Comment by mbaudin47** [comment]
In general, this might a difficult problem. In this particular case, it seems to me that a simple workaround would be to reduce the dimension of the problem using a `ParametricFunction` where the parameter Kd is set to a constant.
```Python
indices = [3]
ref_point = [8.0]
g_reduced = ot.ParametricFunction(ot_Hudson, indices, ref_point)

distribution = ot.ComposedDistribution([dist_Hs, dist_Delta, dist_Dn, dist_cot_a, dist_A])
vect = ot.RandomVector(distribution)
output = ot.CompositeRandomVector(g_reduced, vect)
Faillure_Hudson = ot.ThresholdEvent(output, ot.Less(), 0.0)

optimAlgo = ot.Cobyla()
optimAlgo.setMaximumEvaluationNumber(1000)
optimAlgo.setMaximumAbsoluteError(1.0e-10)
optimAlgo.setMaximumRelativeError(1.0e-10)
optimAlgo.setMaximumResidualError(1.0e-10)
optimAlgo.setMaximumConstraintError(1.0e-10)

# Run FORM

startingPoint = distribution.getMean()
algo = ot.FORM(optimAlgo, Faillure_Hudson, startingPoint)
algo.run()
result = algo.getResult()
ImportanceFactors = result.getImportanceFactors()
print('ImportanceFactors =', ImportanceFactors)
```
This produces:
```
ImportanceFactors = [X0 : 0.717752, X1 : 0.0077105, X2 : 0.0162105, X3 : 0.00146534, X4 : 0.256861]
```
This might be useful for @HAFID-Anas in the meantime.

**Comment by jschueller** [comment]
using a ParametricFunction only works for Dirac, else you need to sum every contributions
