### ISSUE TITLE
Fails to find chaospy

### ISSUE THREAD

**Issue by yurivict** [openturns/openturns#1869]
```
-- Could NOT find chaospy (missing: CHAOSPY_LOCATION _CHAOSPY_VERSION_MATCH) 
```
despite it is being installed:
```
$ pkg info | grep chaospy
py38-chaospy-4.3.2             Toolbox for performing uncertainty quantification
```

Version: 1.17
FreeBSD 13

**Comment by jschueller** [comment]
can the module be imported ?
```
python -c "import chaopy; print(chaospy.__version__)"
```

**Comment by yurivict** [comment]
It can't be imported because numpoly requires a higher version of numpy.

Thank you for your help.

**Comment by jschueller** [comment]
note that chaospy is not a dependency of openturns, neither are numpy/scipy/pandas
