### ISSUE TITLE
Improvement of COBYLA

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#1876]
For some optimization problems, default value of "rhobeg" parameter seems not to be relevant. 

Improvements of COBYLA could be done by adapting the initial value of this parameter depending on the characteristics of the optimization problem, as it has been done in NLOPT : 

https://github.com/stevengj/nlopt/blob/master/src/algs/cobyla/cobyla.c

--> lines 202 to 225

Mathieu

**Comment by jschueller** [comment]
the initialization of the initial step dx is here:
https://github.com/stevengj/nlopt/blob/master/src/api/options.c#L920
we can just use rhobeg=abs(dx[0]) if we dont want to implement scaling like nlopt does

also its clever to set rhoend using rhobeg like nlopt does

key cobyla-defaultrhobeg could default to 0, that would mean use the nlopt initialization, else if set to non-zero it could mean no initialization

**Comment by jschueller** [comment]
I have a first implementation but the number of evals is worse on the quadratic example, can you give your script ?
[rhobeg.txt](https://github.com/openturns/openturns/files/6790386/rhobeg.txt)

**Comment by m-balesdent** [comment]
You can find my experimentations there : 

[cobyla_experimentations.txt](https://github.com/openturns/openturns/files/6790598/cobyla_experimentations.txt)

**Comment by jschueller** [comment]
@m-balesdent do you have an example where it enhances the kriging hyperparameters estimation ?

**Comment by m-balesdent** [comment]
This PR is not relevant anymore since COBYLA has been improved
