### ISSUE TITLE
Rename Hanning filtering window

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/openturns#1878]
The `Hanning` filtering function should be renamed onto [Hann](https://en.wikipedia.org/wiki/Hann_function) because it is the correct name of the window.
`Hanning` is a term used in this [report](http://web.mit.edu/xiphmont/Public/windows.pdf) and should be fixed for next release.

**Comment by regislebrun** [comment]
True. It was the name used in `Random Data Analysis`, the book on which the initial work on filtering windows was based. The confusion was also present in matlab at this time, hence the Hann (Hanning) mention in its documentation (https://www.mathworks.com/help/signal/ref/hann.html)
