### ISSUE TITLE
Adaptive Directional Sampling Algorithm: the drawProbabilityConvergence graph may be wrong

### ISSUE THREAD

**Issue by EmmanuelArdillon** [openturns/openturns#1879]
First, let us mention that we appreciate that an example for the use of the ADS method is recently available.
We used it and changed various times the number of simulations and variation coefficient fixed by the user.
ANd we noticed that the Probability convergence graph remains unchanged in log scale, showing only iterations 1 and 2...
You can see it in the attached PNG file. The example is just the original example in the doc, complemented with 3 usual lines to draw the probability convergence graph.

![plot_SDA](https://user-images.githubusercontent.com/64831693/126354539-0462e701-580c-4d76-8612-83b3b0d246fe.png)
[plot_estimate_probability_adaptive_directional_sampling Probconv.txt](https://github.com/openturns/openturns/files/6849683/plot_estimate_probability_adaptive_directional_sampling.Probconv.txt)

**Comment by jschueller** [comment]
the graph probably cannot be interpreted in that way since it give the probability of each step x subdivision,
and that only depend on the number of dimension, not the sampling size

**Comment by EmmanuelArdillon** [comment]
If so, the suggestion would be to provide a graph corresponding to the general expectation of the user, as it is the case for other simulation methods. Why this specificity for ADS?

**Comment by EmmanuelArdillon** [comment]
Do you mean these 2 figures correspond to the 2 steps of the method ?

**Comment by EmmanuelArdillon** [comment]
Anyway, this specificity may be considered as surprising and at least it would be great for users to mention it in the API for instance.

**Comment by jschueller** [comment]
we could also concatenate the whole convergence graphs of each simulation at each step but unlike subset they are independent so it wont be continuous
