### ISSUE TITLE
Adaptive Directional Sampling: some enhancements proposed

### ISSUE THREAD

**Issue by EmmanuelArdillon** [openturns/openturns#1880]
First, the original algorithm is in fact Adaptive Directional Stratification, which reflects better the method (it is a stratification method) without changing the initials. A first suggestion would be to restore the appropriate name.

Second, there is apparently no possibility to access to the effective number of simulations (iterations) actually performed during the simulation, neither to the effective variation coefficient at the end of the simulation: no "get" method seems to get these results. If you confirm this issue, it would be interesting for the user to add such methods.

**Comment by jschueller** [comment]
yes, subset too, but I think it's better to stick to what's in the papers

all these results can be obtained through getResult

**Comment by EmmanuelArdillon** [comment]
Let us stick to the papers: ADS is clearly referenced as Adaptive Directional Stratification in the pHD thesis manuscript or other reference papers of Miguel Munoz-Zuniga, its "father"; "Stratification" and "Sampling" are not equivalent. Restoring "Stratification" would be preferable.
For subset, "subset simulation" is more common than "subset sampling", but "simulation" and "sampling" are equivalent.

**Comment by regislebrun** [comment]
BTW simulation is much less explicit than sampling. The name Sampling was chosen as a common suffix to many algorithms and to match with the existing DirectionalSampling algorithm when ADS has been introduced into OT. I agree that we should stick to the official names in order not to confuse the user.
@EmmanuelArdillon could you edit the title of the issue and add the missing "l" in Sampling?
