### ISSUE TITLE
Strange behavior of FORM ?

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#1883]
Hello,

I have found a strange behavior of FORM with Normal law as input distribution.

When one tries to perform it twice, the second FORM result is different from the first one. It seems to appear when the value of sigma is different to 1. It has been tested with other distributions (Gumbel, LogNormal) and the problem did not appear.

```
import openturns as ot

myFunction = ot.SymbolicFunction(['x'], ['x-1.25'])

myDistribution = ot.Normal(2,0.5)
vect = ot.RandomVector(myDistribution)
output = ot.CompositeRandomVector(myFunction, vect)
event = ot.ThresholdEvent(output, ot.Less(), 0)
solver = ot.Cobyla()

# -------------------------------------------------------
algo = ot.FORM(solver, event, myDistribution.getMean())
algo.run()
result = algo.getResult()
print('first estimate:',result.getEventProbability())

# -------------------------------------------------------
algo_2 = ot.FORM(solver, event, myDistribution.getMean())
algo_2.run()
result_2 = algo_2.getResult()
print('second estimate:',result_2.getEventProbability())
```

It returned : 
```
first estimate: 0.06680979165962676
second estimate: 0.22663036376248244
```
In this case, the second FORM seems to be performed with a Normal distribution with sigma equal to 1.

Moreover, one try with an input distribution with sigma equal to one, both calls give same results : 

```
import openturns as ot

myFunction = ot.SymbolicFunction(['x'], ['x-1.25'])

myDistribution = ot.Normal(2,1)
vect = ot.RandomVector(myDistribution)
output = ot.CompositeRandomVector(myFunction, vect)
event = ot.ThresholdEvent(output, ot.Less(), 0)
solver = ot.Cobyla()

# -------------------------------------------------------
algo = ot.FORM(solver, event, myDistribution.getMean())
algo.run()
result = algo.getResult()
print('first estimate:',result.getEventProbability())

# -------------------------------------------------------
algo_2 = ot.FORM(solver, event, myDistribution.getMean())
algo_2.run()
result_2 = algo_2.getResult()
print('second estimate:',result_2.getEventProbability())
```
with results 
```
first estimate: 0.22663036376248244
second estimate: 0.22663036376248244
```

**Comment by HAFID-Anas** [comment]
For your first example (standard deviation = 0.5) the analytical probability of faillure is equal to 0.06681
For your second example (standard deviation = 1) the analytical probability of faillure is equal to 0.22663

The result from the first simulation are correct, i guess you have to clean old data and variables.

**Comment by HAFID-Anas** [comment]
you need to redefine myDistribution , vect, output and event before each simulation. I believe they are somehow modified by the algorithm.

**Comment by m-balesdent** [comment]
Yes, that is the potential bug. If you try to do it  with another distribution (e.g.  Gumbel), everything is OK.

**Comment by jschueller** [comment]
the cholesky factor is not updated properly due to a missing copyOnWrite in TriangularMatrix
