### ISSUE TITLE
Case insensitive keys in ResourceMap?

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1901]
Hi,
In order to ease the use of ResourceMap, I propose to automatically convert the String entries into upper-case (done in ResourceMap::SetAsString/ResourceMap::addAsString) and to modify the C++ code accordingly. It should impact 34 files according to `grep -rl GetAsString ./lib/src/ | wc -l` (a little bit more if we want to reflect the internal values of these keys in the Python doc&examples) and should be mostly transparent for the user.

Your opinion?

**Comment by regislebrun** [comment]
Ok so I remove the conversion to upper case in HaltonSequence::setScrambling()?

**Comment by jschueller** [comment]
lets close
