### ISSUE TITLE
Cobyla & NLopt should accept LeastSquaresProblem

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#1914]
LeastSquaresProblem defines a special case of OptimizationProblem and as such, it should be accepted by all the general purpose optimization algorithms. It has been deactivated the 5th of August, 2019:
https://github.com/openturns/openturns/commit/8d514bae846acb75900c88b46abead78c3594c4a#diff-a4b24cabd6712a1e3619e411e56f7901a95ac9002ab0405e82680df6627ac62b

Is there any hidden reason why it has been deactivated at this time?

**Comment by jschueller** [comment]
It was part of a PR that worked on distribution estimation, I dont remember but I guess it gaved poor results for the LSQ factories (like Pareto ?) compared to the dedicated algorithms in ceres & cminpack.

**Comment by jschueller** [comment]
Maybe a way to solve that would be a priority index that would push ceres & cminpack in first position for LSQ problems.

**Comment by regislebrun** [comment]
So it was a dubious fix for an actual problem ;-)! It looks like the priority is almost already hard-coded into OptimizationAlgorithm::GetAlgorithmNames() as the algorithms coming from Bonmin, Ipopt, Ceres and CMinpack are added to the list of algorithms names before Cobyla, TNC and NLopt. IMO the correct order should be:
CMinpack, Ceres, Dlib, Cobyla, TNC, Ipopt, NLopt, Bonmin to push the best least-squares algorithm in first places and the most exotic Bonmin in last place. BTW the checkProblem() method of these algorithms  should be reviewed thoroughly. I can do that if you don't have time for it.

**Comment by jschueller** [comment]
checkProblem is already quite good are we're using that extensively in persalys, you'll see in git history that I fixed these a lot of times

**Comment by regislebrun** [comment]
The problem I see is that LeastSquaresProblem is rejected by TNC, Cobyla, Ipopt, NLopt even if these libraries provide algorithms to solve general optimization problems, and the check made in Dlib::checkProblem() is too restrictive. There are two separate issues:
  * a LeastSquaresProblem with or without bounds is an OptimizationProblem with or without bounds so it should be accepted by *any* algorithm able to solve an OptimizationProblem
  * some algorithms work poorly on some instances of LeastSquaresProblem, so an automatic selection of algorithm should be informed of that. But unless you have a proof that such algorithm (e.g. TNC) performs *systematically* poorly on least-squares problems you cannot simply block their use.

**Comment by jschueller** [comment]
There may also be problems with TNC not yielding exact same results for calibration, I dont remember if I fixed those tests or not.

**Comment by jschueller** [comment]
actually TNC is allowed to solve LS problems, cobyla is not.
if I allow cobyla, it often runs out of evaluations and when it succeeds the approximation is sometimes poorer, but much quicker
