### ISSUE TITLE
1.18: 10 tests fail

### ISSUE THREAD

**Issue by yurivict** [openturns/openturns#1919]
```
The following tests FAILED:
	205 - cppcheck_Chi_std (Failed)
	207 - cppcheck_ChiSquare_std (Failed)
	228 - cppcheck_Gamma_std (Failed)
	240 - cppcheck_InverseChiSquare_std (Failed)
	241 - cppcheck_InverseGamma_std (Failed)
	268 - cppcheck_NonCentralChiSquare_std (Failed)
	281 - cppcheck_RandomMixture_std (Failed)
	288 - cppcheck_Rice_std (Failed)
	383 - cppcheck_IsoProbabilisticTransformation_EllipticalCopula (Failed)
	445 - cppcheck_GeneralLinearModelAlgorithm_std (Failed)
Errors while running CTest
Output from these tests are in: /disk-samsung/freebsd-ports/math/openturns/work/.build/lib/test/Testing/Temporary/LastTest.log
```

[LastTest.log](https://people.freebsd.org/~yuri/openturns-tests-LastTest.log)

OS: FreeBSD 13

**Comment by jschueller** [comment]
in the logs we see some kolmogorov tests of a few distributions fail
these distributions have in common the usage of DistFunc::rGamma in their getRealization
we can also see that t_DistFunc_gamma succeeds

It doesnt look like this part of the code have changed because distfunc.cxx was not touched.
Could it be due to a compiler update or different optimization flags ? (the cmake log could be useful in that regard)
Maybe running the python tests in the same manner will give us more clues ?

**Comment by yurivict** [comment]
1.17 has same or similar failures:
```
The following tests FAILED:
	203 - cppcheck_Chi_std (Failed)
	205 - cppcheck_ChiSquare_std (Failed)
	226 - cppcheck_Gamma_std (Failed)
	238 - cppcheck_InverseChiSquare_std (Failed)
	239 - cppcheck_InverseGamma_std (Failed)
	266 - cppcheck_NonCentralChiSquare_std (Failed)
	279 - cppcheck_RandomMixture_std (Failed)
	286 - cppcheck_Rice_std (Failed)
	292 - cppcheck_StudentFactory_std (Failed)
	381 - cppcheck_IsoProbabilisticTransformation_EllipticalCopula (Failed)
	443 - cppcheck_GeneralLinearModelAlgorithm_std (Failed)
Errors while running CTest
Output from these tests are in: /disk-samsung/freebsd-ports/math/openturns/work/.build/lib/test/Testing/Temporary/LastTest.log
```

**Comment by yurivict** [comment]
The compiler is clang-12 if this matters.

**Comment by jschueller** [comment]
I cannot reproduce. On a fresh bsd13 (x86_64), installed llvm12, boost etc, and these tests pass.

**Comment by jschueller** [comment]
Seems it doesnt happen with boost 1.77, so it looks like a boost bug

**Comment by jschueller** [comment]
@yurivict it doesnt happen if I rebuild the same version bsd has (1.72), could it be from the way it is built in bsd ?

**Comment by yurivict** [comment]
Same failures with openturns-1.20, boost-1.80.0

What is wrong with the Boost build?

**Comment by jschueller** [comment]
it may be due to boost not being configured to be thread-safe, does it have the "threading=multi" option ?

**Comment by yurivict** [comment]
There is no "threading=xx" setting during Boost build. Does it default to single-threaded?

**Comment by jschueller** [comment]
I did not find any clear documentation on that.

**Comment by yurivict** [comment]
I've rebuilt Boost with ```threading=multi```. The complete config line:
> --layout=system  --prefix=/usr/local  -d2 cxxflags="-pipe -fno-omit-frame-pointer -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer -DLIBICONV_PLUG -std=gnu++17" cflags="-pipe -fno-omit-frame-pointer -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing" --toolset=clang  -j6 threading=multi  link=shared,static optimization=speed pch=off --without-python  release -sICONV_PATH=/usr -sICU_PATH=/usr/local threading=multi inlining=full DESTDIR=/disk-samsung/freebsd-ports/devel/boost-libs/work/stage

The same 10 cases still fail with Boost built this way.

**Comment by jschueller** [comment]
then it might be a boost bug on freebsd, maybe the reproducer above can help

**Comment by yurivict** [comment]
@jschueller Boost claims that there is jo bug in Boost: https://github.com/boostorg/math/issues/870#issuecomment-1312445959
