### ISSUE TITLE
Adaptive Directional Stratification: the coefficient of variation of the probability is inconsistent with repeated probability results

### ISSUE THREAD

**Issue by EmmanuelArdillon** [openturns/openturns#1921]
When running various times the included script on the cantilever beam example, we obtain inconsistent results in terms of coefficient of variation: the obtained variation coefficients are very low (even with only 1000 samples: about 10-2), whereas the scatter of the probability values is high, as reported below:
Run       Pf                                                   CV
1            5.645635453580792e-07              1.19e-02
2           4.0596904230031335e-07             1.82e-02
3           4.402915497922379e-07               9.44e-03

One limitation of this method (with its current implementation) occurs when multiple roots have to be identified (multiple intersections with the limit state surface), but I don't think it is the explanation here (cantilever beam example).
Could you check if this is an implementation problem? 
[plot_estimate_probability_adaptive_directional_sampling wrong CV.txt](https://github.com/openturns/openturns/files/7515513/plot_estimate_probability_adaptive_directional_sampling.wrong.CV.txt)

**Comment by jschueller** [comment]
I cannot reproduce, what version is this ? which OS ? how was it installed (conda/pip/other) ?

**Comment by EmmanuelArdillon** [comment]
OT V 1.17, LINUX (poste Calibre), installation with conda

**Comment by jschueller** [comment]
I still cannot reproduce on linux/conda/1.17, are you sure this is the right script ?

**Comment by jschueller** [comment]
I know what you did: you made a loop without resetting the random generator seed

**Comment by josephmure** [comment]
@jschueller I believe that @EmmanuelArdillon's point is that the spread of the Pf values obtained with various random seeds is too large to be consistent with the computed coefficient of variation.

**Comment by EmmanuelArdillon** [comment]
Thank you Joseph for comment. That is exactly what I meant. The purpose was not to obtain identical results with a fixed seed. It was to run a first example. The script that I sent is in fact the OT reference example script for ADS (with different simulation number).
https://openturns.github.io/openturns/latest/auto_reliability_sensitivity/reliability/plot_estimate_probability_adaptive_directional_sampling.html#sphx-glr-auto-reliability-sensitivity-reliability-plot-estimate-probability-adaptive-directional-sampling-py
And the results that I obtain show that the Pf confidence intervals derived from independant runs are disjoint (inconsistent).
What if you also perform independant runs? Do you notice this inconsistency, or not?
Could you investigate the implementation of this cv?

**Comment by EmmanuelArdillon** [comment]
Thanks for reopening the ticket

**Comment by josephmure** [comment]
I think there is a mistake  in the computation of `sigma[i]` :

https://github.com/openturns/openturns/blob/07ba0debc4b41b44c7858b685039562ab36a7187/lib/src/Uncertainty/Algorithm/Simulation/AdaptiveDirectionalStratification.cxx#L129

According to Equations (33) and (34) of [Munoz2011](https://josselin-garnier.org/wp-content/uploads/2013/12/munoz_ress.pdf), `sigma[i]` is supposed to be estimate the standard deviation of the probability of failure conditionally to a particular direction (when said direction varies randomly over the stratum). Instead, in OT it estimates the standard deviation of the *estimator* of the probability of failure conditionally to the stratum.

I think that we should apply a corrective factor, e.g. 

``
sigma[i] = result.getStandardDeviation() * sqrt(ni); 
``

**Comment by josephmure** [comment]
I have made a test script based on the cantilever beam example: 
[test_adaptive_directional_stratification.txt](https://github.com/openturns/openturns/files/7561527/test_adaptive_directional_stratification.txt)

Here are the results with version 1.18. Confidence interval bounds are given for the confidence level 0.95.

```
MC probability =  4.6207680083473107e-07
MC standard deviation =  1.1580753513605385e-07
Median estimated standard deviation =  3.1948146340559214e-08
```

![image](https://user-images.githubusercontent.com/31989332/142387200-6e274ae9-3b64-464b-b97c-25f87a4a033c.png)

And with the change I suggested in the post above:

```
MC probability =  4.694902894431845e-07
MC standard deviation =  3.916753604370548e-08
Median estimated standard deviation =  3.830863979422656e-08
```

![image](https://user-images.githubusercontent.com/31989332/142387292-c7c774e1-2848-47a1-8e1e-79205f737a57.png)

**Comment by jschueller** [comment]
thanks for the analysis, I'll commit the fix then
