### ISSUE TITLE
Adaptive Directional Stratification: the coefficient of variation cannot be used as a stopping criterion

### ISSUE THREAD

**Issue by EmmanuelArdillon** [openturns/openturns#1922]
All is in the title.
You may use the script of the previous issue relative to ADS.
We also noticed this during the current development of Persalys-Penstock.

It would be highly appreciated to give this possibility to the user, as it is of great interest when performing simulations.

**Comment by jschueller** [comment]
yes, the attribute is not forwarded to DS but as a woraround you can set the resourcemap key "SimulationAlgorithm-DefaultMaximumCoefficientOfVariation"
