### ISSUE TITLE
Estimator of the Kurtosis

### ISSUE THREAD

**Issue by KieranDelamotte** [openturns/openturns#1929]
Hi,

I see in the code the following factor in the Kurtosis estimator:
`const Scalar factor2 = -3.0 * (3.0 * size_ - 5.0) / ((size_ - 2.0) * (size_ - 3.0));`

According to [Wikipedia's article](https://en.wikipedia.org/wiki/Kurtosis#Standard_unbiased_estimator) it should be:
`const Scalar factor2 = -3.0 * (size_ - 1.0) * (size_ - 1.0) / ((size_ - 2.0) * (size_ - 3.0));`

Am I missing something?

**Comment by sofianehaddad** [comment]
Indeed. 
Same remark for `factor1`. In the [code](https://github.com/openturns/openturns/blob/master/lib/src/Base/Stat/SampleImplementation.cxx#L1742), we have :
`const Scalar factor1 = (size_ + 1.0) * size_ * (size_ - 1.0) / ((size_ - 2.0) * (size_ - 3.0));`
Whereas in the literature :
`const Scalar factor1 = (size_ + 1.0) * size_ / ((size_ - 1.0) * (size_ - 2.0) * (size_ - 3.0));`

**Comment by KieranDelamotte** [comment]
`factor1` is good there is a hidden simplification.

**Comment by sofianehaddad** [comment]
hmmm can not see it

**Comment by KieranDelamotte** [comment]
Now I understand.

[Scipy's kurtosis](https://github.com/scipy/scipy/blob/master/scipy/stats/_stats_py.py#L1173) does use the unbiased estimator described in the [Wikipedia page](https://en.wikipedia.org/wiki/Kurtosis#Standard_unbiased_estimator). 
OpenTURNS always uses the `-3` factor to correct bias. 
So, 
`-3.0 * (size_ - 1.0) * (size_ - 1.0) / ((size_ - 2.0) * (size_ - 3.0)) - 3 ` 

is indeed the 

`-3.0 * (3.0 * size_ - 5.0) / ((size_ - 2.0) * (size_ - 3.0))` 

factor in OT.


`

**Comment by mbaudin47** [comment]
I realise that this is the answer for the question asked by Kieran, but not the one asked by Sofiane. The equations for the unbiased estimator of the kurtosis (and the skewness) are given in:

Joanes, Derrick N.; Gill, Christine A. (1998), "Comparing measures of sample skewness and kurtosis", _[Journal of the Royal Statistical Society, Series D](https://en.wikipedia.org/wiki/Journal_of_the_Royal_Statistical_Society,_Series_D "Journal of the Royal Statistical Society, Series D")_, **47** (1): 183–189, [doi](https://en.wikipedia.org/wiki/Doi_(identifier) "Doi (identifier)"):[10.1111/1467-9884.00122](https://doi.org/10.1111%2F1467-9884.00122), [JSTOR](https://en.wikipedia.org/wiki/JSTOR_(identifier) "JSTOR (identifier)") [2988433](https://www.jstor.org/stable/2988433)

I derive below the equations which are required to obtain the formulas used in OpenTURNS in `computeSkewness`:
https://github.com/mbaudin47/openturns/blob/43b3cad808c12939d72fc9cb94ca70de0c5cd322/lib/src/Base/Stat/SampleImplementation.cxx#L1692
and `computeKurtosis`:
https://github.com/mbaudin47/openturns/blob/43b3cad808c12939d72fc9cb94ca70de0c5cd322/lib/src/Base/Stat/SampleImplementation.cxx#L1723


![image](https://user-images.githubusercontent.com/31351465/156651725-9c4639a3-d797-420f-8754-555f78e18c40.png)

![image](https://user-images.githubusercontent.com/31351465/156651830-446f2725-0c83-4caa-a67a-29c17347ce5b.png)

![image](https://user-images.githubusercontent.com/31351465/156651906-c176859c-070d-4c91-b549-eeff816b211f.png)

I hope that this definitely clarifies the equations used in the `Sample` class.
