### ISSUE TITLE
Interface class getImplementation methods are useless in Python

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1931]
Suppose I get a `KrigingResult` and want to access the underlying covariance kernel. The method `KrigingResult::getCovarianceModel` yields an object of the interface class `CovarianceModel`. Let us call this object `cov`.

Even if the implementation is actually a `MaternModel`, I will not be able to call `cov.getNu()`, since that method is specific to the `MaternModel` class. Now, I could access it indirectly through the generic `getParameter` method, but this is impractical.

In C++, `cov.getImplementation()` yields a pointer and I could write `cov.getImplementation()->getNu()`.
In Python however `cov.getImplementation()` yields a useless `CovarianceModelImplementationPointer` object, but that "pointer" cannot access `getNu`.

Would it be possible to make the Python version of `getImplementation` yield a reference to the actual implementation instead of a pointer?

EDIT: This problem is not limited to the case of `CovarianceModel` objects. Here is a (probably not exhaustive) list of situations where the lack of Python `dynamic_cast` is an issue.

## CovarianceModel

See above. I recently coded a Python class with @efekhari27 that relied on OT covariance kernels. We were able to derive analytical formulas for a specific kernel (Matérn with nu=5/2), so the class needed to inspect the `CovarianceModel` object in order to see whether analytical formulas were available or not. It went like this: with `kernel` being some `CovarianceModel`:

```python
 if kernel.getImplementation().getClassName()=="MaternModel"
    if kernel.getParameter()[-1]==2.5
        _analytical = True
```
Of course, what I would have liked to write is:
```python
 if kernel.getImplementation().getClassName()=="MaternModel"
    if kernel.getNu()==2.5
        _analytical = True
```
However, whenever `kernel` is obtained from a `KrigingResult`, its type is `CovarianceModel` so Matérn-specific methods are unavailable.

## Distribution

Many classes have `getDistribution` methods, and all return... objects of type `Distribution`. As Sofiane pointed out below, factories often provide `buildAsXXX` methods to circumvent the issue, but non-factory classes do not have such methods. @mbaudin47 may be able to provide more specific examples.

## RandomVector

The `RandomVector` interface class has many methods that can only used by one or some of the classes derived from `RandomVectorImplementation`. Here is a list:
Method | Description
-- | --
getAntecedent() | Accessor to the antecedent RandomVector in case of a composite RandomVector.
getCovariance() | Accessor to the covariance of the RandomVector.
getDescription() | Accessor to the description of the RandomVector.
getDistribution() | Accessor to the distribution of the RandomVector.
getDomain() | Accessor to the domain of the Event.
getFunction() | Accessor to the Function in case of a composite RandomVector.
getId() | Accessor to the object's id.
getMarginal(*args) | Get the random vector corresponding to the  marginal component(s).
getMean() | Accessor to the mean of the RandomVector.
getOperator() | Accessor to the comparaison operator of the Event.
getParameter() | Accessor to the parameter of the distribution.
getParameterDescription() | Accessor to the parameter description of the distribution.
getThreshold() | Accessor to the threshold of the Event.
intersect(other) | Intersection of two events.
isComposite() | Accessor to know if the RandomVector is a composite one.
isEvent() | Whether the random vector is an event.
join(other) | Union of two events.
setName(name) | Accessor to the object's name.
setParameter(parameters) | Accessor to the parameter of the distribution.

These methods exist in the interface but are implemented as throwing `NotYetImplementedException` in `RandomVectorImplementation`. As a result, they clutter both the API and the doc of all `RandomVectorImplementation` derived classes that do not implement them. If we could dynamic-cast in Python, we probably would not need to do this.

## Conclusion

Several strategies exist to circumvent the lack of dynamic-cast (or some substitute) in Python:

- The `CovarianceModel` strategy: since all derived classes are similar, we can get away with losing some model-specific methods because they are just more convenient accessors, but it can be a hassle for users.
- The `Factory` strategy: write as many `buildAsXXX` methods as necessary. This is more convenient for users, but is a lot of work for developers.
- The `RandomVector` strategy: put everything in the interface. Users can access everything but must understand that most methods available are dummy methods, this makes the API harder to understand.

I believe we need to come up with some way of achieving in Python what is done with dynamic cast in C++. Maybe there are SWIG tools that could be helpful?

**Comment by sofianehaddad** [comment]
You can get the `CovarianceModelImplementation` using `cov.getImplementation().get()` but you will never get the implementation. I think it is not easy (or just not possible). 
For example `UniformFactory` (and all other distribution factories) have the generic `build` method that provide a `Distribution`. But we had to implement a specific `buildAsXXX` method for each of them because we need sometimes the real implementation in `python`. It probably means we need to work a lot on the `C++` side to finally get the model as `Matern` for examplle

**Comment by josephmure** [comment]
Apparently, we are not the only ones who have this kind of problem.  In [this discussion](https://sourceforge.net/p/swig/mailman/swig-user/thread/op.t67gy7ebz3pzfc%40nitrogenycs2/#msg18697032), there was a recommendation to search for `factory.i` in the SWIG [CHANGES](https://raw.githubusercontent.com/swig/swig/master/CHANGES) file.

Here is the relevant part:

```
02/22/2006: mmatus
	    Add the factory.i library for languages using the UTL (python,tcl,ruby,perl).
	    
            factory.i implements a more natural wrap for factory methods. 

	    For example, if you have:							    
	    								    
  	    ----  geometry.h --------					    
  	         struct Geometry {                          		    
  	           enum GeomType{			     			    
  	             POINT,				     		    
  	             CIRCLE				     		    
  	           };					     		    
  	           					     		    
  	           virtual ~Geometry() {}    		     		    
  	           virtual int draw() = 0;				    
  	    	 							    
  	    	 //							    
  	    	 // Factory method for all the Geometry objects		    
  	    	 //							    
  	           static Geometry *create(GeomType i);     		    
  	         };					     		    
  	         					     			    
  	         struct Point : Geometry  {		     		    
  	           int draw() { return 1; }		     		    
  	           double width() { return 1.0; }    	     		    
  	         };					     		    
  	         					     			    
  	         struct Circle : Geometry  {		     		    
  	           int draw() { return 2; }		     		    
  	           double radius() { return 1.5; }          		    
  	         }; 					     		    
  	         								    
  	         //							    
  	         // Factory method for all the Geometry objects		    
  	         //							    
  	         Geometry *Geometry::create(GeomType type) {		    
  	           switch (type) {			     		    
  	           case POINT: return new Point();	     		    
  	           case CIRCLE: return new Circle(); 	     		    
  	           default: return 0;			     		    
  	           }					     		    
  	         }					    		    
  	    ----  geometry.h --------					    
	    								    
	    								    
	    You can use the %factory with the Geometry::create method as follows:
	    								    
  	      %newobject Geometry::create;				    
  	      %factory(Geometry *Geometry::create, Point, Circle);	    
  	      %include "geometry.h"					    
	    								    
  	    and Geometry::create will return a 'Point' or 'Circle' instance   
  	    instead of the plain 'Geometry' type. For example, in python:	    
	    								    
  	      circle = Geometry.create(Geometry.CIRCLE)			    
  	      r = circle.radius()						    
	    								    
  	    where 'circle' now is a Circle proxy instance.	   
```

I also found these issues in the `GammaLib` bug tracker:
- [Perform automatic dynamic typecasting in Python interface
](https://cta-redmine.irap.omp.eu/issues/119)
- [Investigate possible solutions for type casting in SWIG](https://cta-redmine.irap.omp.eu/issues/287)

Apparently, they were able to find a satisfactory solution, but I do not really understand it.
