### ISSUE TITLE
Contour curves outside graph window

### ISSUE THREAD

**Issue by Jean-A** [openturns/openturns#1939]
I noticed a strange behavior on the top right corner of the graph when I execute this code
```
import openturns as ot
d = ot.ComposedDistribution([ot.Normal(0,1), ot.Normal(0, 1)])
d.drawPDF()

```
![image](https://user-images.githubusercontent.com/52526981/151178725-b4d6a189-5272-4f07-b2c6-bc2fbde2f6ca.png)

**Comment by regislebrun** [comment]
It looks like your matplotlib version or your jupyter-notebook version has a bug...

**Comment by Jean-A** [comment]
Yet I executed "conda install matplotlib" a few minutes ago.
I didn't see this behavior with other draw methods so far. 

Note that if I use openturns.viewer the behavior is almost invisible (small green triangle on the top right)
![image](https://user-images.githubusercontent.com/52526981/151181991-cd008c7d-3675-43cc-aaad-0d571f4bc0d0.png)

If it is only visible on my installation I can close the issue

**Comment by Jean-A** [comment]
I will close the issue for the time being as I am the only one to have the issue.
FYI, my OS is Windows 10

**Comment by Jean-A** [comment]
The problem is visible now on master http://openturns.github.io/openturns/master/auto_data_analysis/estimate_dependency_and_copulas/plot_estimate_non_parametric_copula.html?highlight=copula

**Comment by jschueller** [comment]
https://github.com/matplotlib/matplotlib/issues/22661

**Comment by mbaudin47** [comment]
I can reproduce this bug with my OT 1.18 that I use for some study. Notice that the legends of the contour plot are not shown, as on your own figure.

![image](https://github.com/openturns/openturns/assets/31351465/6a6a95fb-74bf-4031-9977-5941f5469c00)

The bug is fixed in the current version.
