### ISSUE TITLE
pip install not available on mac/arm64

### ISSUE THREAD

**Issue by syam5g** [openturns/openturns#1980]
python 3.10 versions via pip for Windows and Linux, but not for Mac

**Comment by jschueller** [comment]
it should be: https://pypi.org/project/openturns/1.18/#files
try downloading openturns-1.18-cp310-cp310-macosx_10_9_x86_64.whl manually maybe ?

**Comment by syam5g** [comment]
I have this error: 
ERROR: openturns-1.18-cp310-cp310-macosx_10_9_x86_64.whl is not a supported wheel on this platform.

**Comment by jschueller** [comment]
what's your cpu arch ? arm ?

**Comment by syam5g** [comment]
Puce Apple M1 ARM 64 bits

**Comment by jschueller** [comment]
ah, in that case that's not available because conda-forge has not migrated all the packages yet

**Comment by syam5g** [comment]
too bad, thanks anyway for your help

**Comment by jschueller** [comment]
@syam5g we have arm binaries via conda-forge now, could you test it ?

**Comment by syam5g** [comment]
Yes it works, thank you. I used the command : conda install --channel=conda-forge openturns in miniconda3 environment.

**Comment by josephmure** [comment]
@jschueller Is pip install now available for osx/arm ?

**Comment by jschueller** [comment]
no solution yet

**Comment by jschueller** [comment]
should be okay now, thanks to the new cirrus job: https://github.com/openturns/build-wheels/commit/acf1169e982e2f7de07fe3ea768cdf5af711b1c6
new files: https://pypi.org/project/openturns/#files
@syam5g can you test it ?
