### ISSUE TITLE
CircleCI-build doc no longer accessible

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1998]
Until very recently, we could access the CircleCI-built doc by clicking on the *Details* link of the  *build_linux artifact* "check", but this is apparently no longer possible. I noticed a recent URL change which broke the link:

https://output.circle-artifacts.com/output/job/1f8a728b-f407-41ec-9f17-040152cec3ad/artifacts/0/html/auto_calibration/bayesian_calibration/plot_gibbs_simus.html#updating-theta

whereas before URLs were rather like this:

https://1549-40968898-gh.circle-artifacts.com/0/html/user_manual/_generated/openturns.HMatrixParameters.html#openturns.HMatrixParameters.getCompressionMethod

Although the direct link was broken, it was still possible to access the HTML pages through the *Artifacts* tab of the *build_linux* CircleCI interface. For builds that were made today (march 25th 2022), even this is no longer possible because the *Artifacts* tab is empty, like here:

https://app.circleci.com/pipelines/github/openturns/openturns/1863/workflows/9db4051c-8fe8-4184-8386-cf2c36028d9d/jobs/9092/artifacts

I saw this discussion in the CircleCI Discourse forum: 

https://discuss.circleci.com/t/artifact-urls-now-private/43282

Perhaps it is related?

**Comment by jschueller** [comment]
fixed upstream, see pagmo pr is ok

**Comment by josephmure** [comment]
Good to know!
