### ISSUE TITLE
Precision issue with the Python KrigingAlgorithm test

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2014]
Hello,

While building version 1.18 on an amd64 computer, with tbb activated, I meet a precision issue:

---

Traceback (most recent call last):
  File "/build/openturns-1.18/python/test/t_KrigingAlgorithm_std.py", line 186, in <module>
    test_two_outputs()
  File "/build/openturns-1.18/python/test/t_KrigingAlgorithm_std.py", line 164, in test_two_outputs
    ott.assert_almost_equal(result([[9.5], [10.0]]).getCovariance(
  File "/build/openturns-1.18/debian/tmp/usr/lib/python3.10/site-packages/openturns/testing.py", line 194, in assert_almost_equal
    return _testing.assert_almost_equal(*args)
RuntimeError: Value 0.0111101 is not close enough to 0

---

Changing line 165 of python/test/t_KrigingAlgorithm_std.py to
    ) - reference_covariance, ot.Matrix(4, 4), 0.0, 2e-2) fixes the issue for me. 

Maybe you would be interested in reworking this criterion if the same issue shows up on other machines.

Best,

Pierre

**Comment by pgrt** [comment]
Hi Julien,

The build was done in an unstable chroot: so the packages of unstable, and the hmat-oss package which is currently in experimental.

**Comment by jschueller** [comment]
I cannot seem to reproduce the issue on my side yet.
It should not be because of hmat as this test does not involve hmat.
Maybe the lapack variant ? I used netlib (liblapack-dev) as in the debian package.
Or compilation flags (I'm using defaults + warnings/assertions) ?
Here is the docker image I used:
```
FROM debian:unstable
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get -y install curl gnupg apt-transport-https ca-certificates cmake python3-dev swig libcminpack-dev libxml2-dev libboost-math-dev bison flex liblapack-dev libmpc-dev libhdf5-dev libnlopt-cxx-dev libceres-dev libmpc-dev libprimesieve-dev libblas-dev libtbb-dev coinor-libipopt-dev libdlib-dev libpng-dev libsqlite3-dev git g++

WORKDIR /tmp
RUN curl -fO http://deb.debian.org/debian/pool/main/h/hmat-oss/libhmat-oss2_1.7.1-1_amd64.deb
RUN curl -fO http://deb.debian.org/debian/pool/main/h/hmat-oss/libhmat-oss-dev_1.7.1-1_amd64.deb
RUN dpkg -i libhmat-oss2_1.7.1-1_amd64.deb libhmat-oss-dev_1.7.1-1_amd64.deb

ENV MAKEFLAGS="-j20"
RUN git clone --depth 1 -b v1.18 https://github.com/openturns/openturns.git && cd openturns && cmake -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=32 -DSWIG_COMPILE_FLAGS="-O0" -DCMAKE_CXX_FLAGS="-Wall -D_GLIBCXX_ASSERTIONS" . && make install
RUN cd openturns && ctest -E cppcheck -R KrigingAlgorithm_std --output-on-failure --timeout 500 --repeat-until-fail 100 ${MAKEFLAGS}
```

**Comment by pgrt** [comment]
Hi,

Thanks for attempting to reproduce the issue and providing the details. I admit I have no real clue to explain the diffs.

Concerning flags, I fiddled a bit the arguments that are passed to CMake in debian/rules, so certainly there are differences between your build and mine.

I just uploaded openturns to Debian experimental, through the NEW queue. We should wait a few days before it gets built, but you can see my packaging changes at:
    https://salsa.debian.org/science-team/openturns/

Thanks for the reference to #1950. Yet I guess the latter seems very innocuous, given the numerical accuracy of double?
In the current issue, we get 0.0111101 where a tolerance of 0.01 is okay, so I guess there should be more than a numerical accuracy issue.
Yet again, I admit I am not able to make a more educated guess about it.

Best,
Pierre
