### ISSUE TITLE
Suggestion: spelling errors in the source

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2016]
Hello,

The Debian linter, Lintian, is able to spot many spelling errors in the source code. For OpenTURNS, all of them are gathered in the enclosed patch.

[spelling.txt](https://github.com/openturns/openturns/files/8450046/spelling.txt)

Admittedly, although this file is huge, the improvement brought to OpenTURNS is quite minor. Additionally, a review is needed as some changes concern the names of variables.

If you would be interested in a pull request instead, please tell me.

Best regards,

Pierre

**Comment by jschueller** [comment]
thanks, applied
