### ISSUE TITLE
HSIC examples

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/openturns#2017]
Hi

Having a look at an [HSIC example](https://openturns.github.io/openturns/master/auto_reliability_sensitivity/sensitivity_analysis/plot_hsic_estimators_ishigami.html?highlight=hsic), let us focus on covariance models definition. 
The corresponding blocks write:
```
for i in range(3):
    Xi = X.getMarginal(i)
    inputCovariance = ot.SquaredExponential(1)
    inputCovariance.setScale(Xi.computeStandardDeviation())
    covarianceModelCollection.append(inputCovariance)

outputCovariance = ot.SquaredExponential(1)
outputCovariance.setScale(Y.computeStandardDeviation())
covarianceModelCollection.append(outputCovariance)
```
I find strange the way we fill the covariance models. Indeed my understanding (and my early experience) was that scale parameter is usually set to 1/sigma_i, sigma_i being the marginal standard deviation. This seems confirmed when having a look at [R sensitivity documentation](https://github.com/cran/sensitivity/blob/master/man/sensiHSIC.Rd#L62), and the corresponding applied code [for rbf kernel](https://github.com/cran/sensitivity/blob/master/R/sensiHSIC.R#L15)

What is/are the best practices?

Cheers

**Comment by sofianehaddad** [comment]
@vchabri any idea also?

**Comment by sofianehaddad** [comment]
To complete, even in the [doc](https://openturns.github.io/openturns/master/theory/reliability_sensitivity/sensitivity_hsic.html), we have the follwing block
```
For instance, the squared exponential (or Gaussian) kernel can be parameterized as a function of the sample empirical variance. In this case, we obtain :

\kappa_i(x_i^j,x_i^k) = \exp (\theta_i (x_i^j - x_i^k)^2)

with \theta_i = 1/\sigma_i^2, where \sigma_i^2 is the empirical variance of the sample X_i.```
I guess it is a mistake/bug in documentation example, isn't it?

**Comment by josephmure** [comment]
Unless I missed something, the R documentation only says how to define the scale parameter(s) of the covariance kernel, it does not tell which value should be chosen.

The standard deviation is a scale parameter for the Xi variable, so having it also be the scale parameter for the corresponding covariance kernel seems reasonable to me, and I will try to show why. (I am no HSIC expert but I think the following is true.)

Assume that Xi follows a standard normal distribution, let k be the covariance kernel we pick for Xi.

Then, for any sigma>0, define k_sigma as the covariance kernel such that for any x, k_sigma(x) = k(x / sigma): with OT, we would have written:

```
k_sigma = deepcopy(k)
k_sigma.setScale(sigma * k.getScale())
```

Then, all else being equal, the HSIC index of (sigma Xi, Y) obtained with the kernel k_sigma is equal to the HSIC index of (Xi, Y) obtained with the kernel k.

**Comment by josephmure** [comment]
Excuse me, I replied before seeing your last message:



> To complete, even in the [doc](https://openturns.github.io/openturns/master/theory/reliability_sensitivity/sensitivity_hsic.html), we have the follwing block
> 
> ```
> For instance, the squared exponential (or Gaussian) kernel can be parameterized as a function of the sample empirical variance. In this case, we obtain :
> 
> \kappa_i(x_i^j,x_i^k) = \exp (\theta_i (x_i^j - x_i^k)^2)
> 
> with \theta_i = 1/\sigma_i^2, where \sigma_i^2 is the empirical variance of the sample X_i.
> ```
> 
> I guess it is a mistake/bug in documentation example, isn't it?

No, it simply means they parametrize the covariance kernel differently in R. Their parameter is the inverse of our scale parameter.

**Comment by sofianehaddad** [comment]
Hmmm
in fact, I am wrong, sorry. `cov.setScale(sigma)` allows to compute K(x/scale). Thus it is exactly the same thing.
Thanks for your feedback.
