### ISSUE TITLE
Probleme with the UserDefined distribution

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#2020]
I created a UserDefined distribution on 8 discrete values. 
```
from openturns import *
from openturns.viewer import View

sample = Sample([[350],[358],[360],[353],[364],[355],[349],[351],[358]])
nMax = int(sample.getMax()[0]) #364
nMin = int(sample.getMin()[0]) #349
```

Here, I verify that the support is good: from 349 until 364
```
loi_UD = UserDefinedFactory().build(sample)
print(loi_UD)
```

When I draw the CDF, the tail CDF value changes with the upper bound of the graph: for exemple, look at 366
```
g = loi_UD.drawCDF(nMin, nMax+2)
view = View(g)
view.show()
g = loi_UD.drawCDF(nMin, nMax+10)
view = View(g)
view.show()
```

Here, I do not understand why loi_UD.computeCDF(nMax) is not equal to 1
```
print('CDF(nMax) = ',  loi_UD.computeCDF(nMax)) #0.8888888888888888
print('CDF(nMax+1) = ',  loi_UD.computeCDF(nMax+1)) #1.0
```

**Comment by Jean-A** [comment]
<= was replaced by < in the empirical distribution function? 
![image](https://user-images.githubusercontent.com/52526981/162924533-f9f3e9a9-351c-4f64-b0cf-7efb7240d53a.png)

**Comment by jschueller** [comment]
> <= was replaced by < in the empirical distribution function? ![image](https://user-images.githubusercontent.com/52526981/162924533-f9f3e9a9-351c-4f64-b0cf-7efb7240d53a.png)

yep!

**Comment by adutfoy** [comment]
Ok: this modification corrects the problem of the CDF compuytation. But the problem with the graph still remains. 
```
from openturns import *
from openturns.viewer import View

sample = Sample([[350],[358],[360],[353],[364],[355],[349],[351],[358]])
nMax = int(sample.getMax()[0]) #364
nMin = int(sample.getMin()[0]) #349

loi_UD = UserDefinedFactory().build(sample)

g = loi_UD.drawCDF(nMin, nMax+2)
view = View(g)
view.show()
g = loi_UD.drawCDF(nMin, nMax+10)
view = View(g)
view.show()

```

**Comment by jschueller** [comment]
I dont understand, the graph seem fine to me:
![g1](https://user-images.githubusercontent.com/3832365/163199045-16cb7753-6905-45d3-a7be-aac129b05b32.png)
![g2](https://user-images.githubusercontent.com/3832365/163199090-c72f2a5a-b8d7-4ee1-a2f9-5573036742c5.png)

**Comment by adutfoy** [comment]
Ok! your graphs are correct!
I join the ones I had ....

[bug_graph_g1.pdf](https://github.com/openturns/openturns/files/8482807/bug_graph_g1.pdf)
[bug_graph_g2.pdf](https://github.com/openturns/openturns/files/8482808/bug_graph_g2.pdf)
