### ISSUE TITLE
module 'openturns' has no attribute 'Pagmo'

### ISSUE THREAD

**Issue by jacktang** [openturns/openturns#2029]
Hello,

I run the demo from the page 

```
import openturns as ot
from openturns.viewer import View

ot.Log.Show(ot.Log.NONE)
ot.RandomGenerator.SetSeed(0)

for algo in ot.Pagmo.GetAlgorithmNames():
    print(algo)
```

And it throws error

```
module 'openturns' has no attribute 'Pagmo'
```

the installed openturns version is `1.18`, and os is macos. How can I fix the error

**Comment by sofianehaddad** [comment]
Hi `pagmo` is not available in `1.18`. You should update to `1.19rc1`  to get the feature

**Comment by jacktang** [comment]
@sofianehaddad 

I've tried to install nightly build package, but still version `1.18` 

```
pip3 install --pre --extra-index-url https://pypi.anaconda.org/openturns-wheels-nightly/simple --upgrade --force-reinstall openturns
```

How can I install `1.19rc1`?

**Comment by jacktang** [comment]
@sofianehaddad thanks!
