### ISSUE TITLE
Multi-objective optimization example question

### ISSUE THREAD

**Issue by jacktang** [openturns/openturns#2031]
Hello, I am learning MOO question by openturns example: https://openturns.github.io/openturns/latest/auto_numerical_methods/optimization/plot_optimization_pagmo.html, And I plot front sets into the graph using the code

```
for i in range(front.getSize()):
    data[2*i] = front[i]
    if i != front.getSize()-1:
        data[2*i+1, 0] = front[i, 0]
        data[2*i+1, 1] = front[i+1, 1]

print("Data:", data)        
curve = ot.Curve(data)
curve.setColor('blue')
curve.setLegend(f"front {0}")

front_points = ot.Cloud(front)
front_points.setColor('red')

graph.add(curve)
graph.add(front_points)
```
And the final graph:

<img width="383" alt="middle_img_v2_39aabbfd-fc42-4710-be4b-2f658280b5dg" src="https://user-images.githubusercontent.com/44341/164188151-dad4c9d6-839c-4704-a012-36b3d234509e.png">

my question is why choose blue line to show Pareto front, but not the yellow line or green dash line (see below graph)? 
 
![image](https://user-images.githubusercontent.com/44341/164189446-dd573747-d795-43de-958d-1ce8b7987e1f.png)

**Comment by jschueller** [comment]
You're right, the plot is incorrect and it should be the green line:
```
for i in range(front.getSize()):
    data[2*i] = front[i]
    if i != front.getSize()-1:
        data[2*i+1, 0] = front[i+1, 0]
        data[2*i+1, 1] = front[i, 1]
```
we know that points in the upper-right quarter planes from front points in red (defined by the green line) are all worse, but that doesnt apply to other points defined by the blue line

if you want something line the yellow line you can increase the number of points in the populations, but any interpolation between the front points is your responsability
