### ISSUE TITLE
[Debian] pythoninstallcheck_DistributionFactory_std issues on arm64, armel, armhf, mips64el

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2047]
Hello,

During the Debian packaging of version 1.18, I noticed the following test failure on the 4 architectures arm64, armel, armhf, mips64el:

287/550 Test  #776: pyinstallcheck_DistributionFactory_std .................................***Failed    4.40 sec
[34m[1mWRN - The first and third quartiles are equal, which means that many values are repeated in the given sample. Switch to the standard deviation-based bandwidth.[0m
[34m[1mWRN - Error: cannot estimate a LogNormal distribution based on a constant sample using the method of local maximum likelihood.[0m
[34m[1mWRN - Error: cannot estimate a LogNormal distribution based on a constant sample using the method of modified moments.[0m
[34m[1mWRN - Error: cannot build a LogNormal distribution if data contains NaN or Inf[0m
[34m[1mWRN - (previous message repeated 3 times)[0m
[34m[1mWRN - TNC went to an abnormal point=[501][0m
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/python/test/t_DistributionFactory_std.py", line 43, in <module>
    assert ok, str(factory)+' vs ' + weird
AssertionError: BernoulliFactory vs nan

It seems there is a strange behaviour of the factory on these architectures when a vector of integers (not floating point numbers) is provided, which is the case for Bernoulli. Indeed, writing

try:
        dist = factory.build(sample + 1.E-12)

in python/test/t_DistributionFactory_std.py instead of

try:
        dist = factory.build(sample)

fixes the issue.

Best,
Pierre

**Comment by jschueller** [comment]
same as #2046
