### ISSUE TITLE
[Debian] Dlib issues on tests on mips64el, ppc64el architectures

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2050]
Hello,

While packaging version 1.18 for Debian, I noticed failures of the Dlib_std and Dlib_global tests, in their C++ and Python flavours, on mips64el and ppc64el. A gdb session lead to:

Program received signal SIGSEGV, Segmentation fault.
0x000000fff6f0f934 in dlib::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > (this=0xfffffd4848, A=...) at /usr/include/dlib/matrix/matrix_lu.h:130
130                 if (piv(piv_temp(i)-1) != piv(i))
(gdb) bt
#0  0x000000fff6f0f934 in dlib::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> >::lu_decomposition<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > (this=0xfffffd4848, A=...) at /usr/include/dlib/matrix/matrix_lu.h:130
#1  0x000000fff6f11e9c in dlib::inv_helper<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout>, 0l>::inv (m=...)
    at /usr/include/dlib/matrix/matrix_la.h:848
#2  dlib::inv<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > (m=...) at /usr/include/dlib/matrix/matrix_la.h:1021
#3  dlib::newton_search_strategy_obj<OT::DlibHessian>::get_next_direction<dlib::matrix<double, 0l, 0l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > (funct_derivative=..., 
    x=..., this=0xfffffd47d8) at /usr/include/dlib/optimization/optimization_search_strategies.h:307
#4  OT::DlibNewtonSearchStrategy::get_next_direction (this=<optimized out>, x=..., f_value=<optimized out>, funct_derivative=...) at ./lib/src/Base/Optim/Dlib.cxx:264
#5  0x000000fff6f144f8 in OT::DlibSearchStrategy::get_next_direction (funct_derivative=..., f_value=11029, x=..., this=0xfffffd5150) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#6  dlib::find_min<OT::DlibSearchStrategy, OT::DlibStopStrategy, OT::DlibFunction, OT::DlibGradient, dlib::matrix<double, 0l, 1l, dlib::memory_manager_stateless_kernel_1<char>, dlib::row_major_layout> > (search_strategy=..., stop_strategy=..., f=..., der=..., x=..., min_f=-1.7976931348623157e+308) at /usr/include/dlib/optimization/optimization.h:186
#7  0x000000fff6f02b8c in OT::Dlib::run (this=<optimized out>) at ./lib/src/Base/Optim/Dlib.cxx:650
#8  0x000000aaaaacd328 in main () at t_Dlib_std.cxx:273

The version of dlib which is used is 19.23.

If you have any idea how to fix it, this would be really great for me!

Best,

Pierre

**Comment by jschueller** [comment]
it rather looks like a dlib bug

**Comment by pgrt** [comment]
Hi,

Probably, as it stopped showing up after I upgraded the dlib version. Closing the issue thus.

Best,
Pierre

**Comment by pgrt** [comment]
Hi,

It seems I closed this issue too quickly, even with dlib 19.24 the issue is in fact still showing up on the two aforementioned architectures.
I am hereby reopening it for tracking, until we can determine if we should fill a report against dlib -- and which one -- if that's ok for you.

Thanks,
Pierre

**Comment by jschueller** [comment]
goto https://github.com/davisking/dlib/pull/2689

**Comment by pgrt** [comment]
> goto [davisking/dlib#2689](https://github.com/davisking/dlib/pull/2689) closing since there little I can do on our side (hairy to add a test for specific archs)

Thanks for the pointer!
Arguably, adding tests for tricky yet innocuous issues is probably not worth our time!

Cheers,
Pierre
