### ISSUE TITLE
[Debian] Many test failures and freezes on the i386 architecture

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2051]
Hello,

While packaging version 1.18 for Debian, I got many freezes during the tests. The following tests seem stuck and I stopped them after 150 minutes of inactivity:

- C++ tests Cobyla_std, FORM_sensitivity, WhittleFactory_std, ARMALikelihoodFactory_std, PostAnalyticalControlledImportanceSampling_std, PostAnalyticalImportanceSampling_std
- Python tests EfficientGlobalOptimization_std, InverseRosenblattEvaluation_form, FORM_interval, MultiFORM_std, Waarts_25_quadratic_terms, Waarts_system_series, Waarts_saddle

My guess would be to incriminate Cobyla, as for Cobyla_std, FORM_sensitivity and WhittleFactory_std, it seems the program gets stuck in the trstlp function in lib/src/Base/Optim/algocobyla.c. I made no check for the other frozen tests.

Also I got many test failures, which are all in the enclosed file.

[i386failures.txt](https://github.com/openturns/openturns/files/8693817/i386failures.txt)

I would be glad if you had any idea to fix either the freezes or some test failures.

Thanks for your help in any case!

Best,
Pierre

**Comment by jschueller** [comment]
I had troubles with Cobyla in the past on i386 with gcc that were fixed, at the time the solution was to reduce the optimization level

**Comment by pgrt** [comment]
Hi,

I investigated a bit more but eventually removed the openturns package from the i386 architecture, as the maintainance burden has become too overwhelming. Everything is fine on the other arches.

Best,
Pierre
