### ISSUE TITLE
TruncatedNormal failure

### ISSUE THREAD

**Issue by manongeorget** [openturns/openturns#2058]
The following code fails : 

```python
import openturns as ot
ot.TruncatedNormal(50.0,1.0,3.0,4.0)
```

Error message:

```python
TypeError: InvalidArgumentException : Error: the truncation interval has a too small measure. Here, measure=0
```

Scipy manages to do it with:

```python
import scipy.stats as st
import numpy as np

np.random.seed(seed=233423)
mean = 50.0
std = 1.0
a = 3.0
b = 4.0

standard_lower_bound = (a - mean) / std
standard_upper_bound = (b - mean) / std

realization = st.truncnorm.rvs(standard_lower_bound, standard_upper_bound, loc=mean, scale=std)
print(realization)
```
output : 3.9970118404450403

**Comment by regislebrun** [comment]
It is due to the (naive) way we compute the Gaussian probability of the truncation interval. For the extreme cases we should use a log scale for the PDF, CDF and so on, based on the erfcx function in Faddeeva.cc. Good catch.

**Comment by regislebrun** [comment]
Th only remaining issue is with computeLogCharacteristicFunction(), which requires to compute the logarithm of the difference between two values of the Faddeeva function very close one to the other. The Faddeeva implementation we use is not well-suited for this computation. A quick workaround may be to use the algorithm described [here](https://arxiv.org/abs/2010.05659), coupled to the use of boost::multiprecision. I will give it a try tomorrow if I find an hour or two...

**Comment by mbaudin47** [comment]
It seems to me that the bug is not fixed. The next script:
```
import openturns as ot
t = ot.TruncatedNormal(0.0, 1.0, 10.0, 39.0)
print(t.computePDF(10.1))
```
prints:
```
inf
```
