### ISSUE TITLE
Double colons :: in API doc

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#2075]
For some reason, in the current master version of the doc, "Parameters:" and "Returns:"  are respectively replaced with "Parameters::" and "Returns::"

See for example

https://openturns.github.io/openturns/master/user_manual/_generated/openturns.AggregatedProcess.html#openturns.AggregatedProcess.getFuture

![image](https://user-images.githubusercontent.com/31989332/174819869-0363b6b8-c81d-4bf6-adbe-a39a210a0f3f.png)

In the 1.19 doc everything is normal:

https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.AggregatedProcess.html#openturns.AggregatedProcess.getFuture

![image](https://user-images.githubusercontent.com/31989332/174819790-4c0b586a-e7b1-4ae6-8252-3a4a36a69552.png)

**Comment by jschueller** [comment]
https://github.com/sphinx-doc/sphinx/issues/10594
