### ISSUE TITLE
The sum of two Normal is not necessarily a Normal

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2086]
The sum of two `Normal` is not necessarily a `Normal`. In general, this should be a `RandomMixture`. If the two means are equal, then the variances should be summed. 

In the following script, the two means are different:
```
In [17]: x = ot.Normal(-10.0, 1.0)
In [18]: y = ot.Normal(10.0, 1.0)
In [19]: z = x + y
In [20]: z
Out[20]: class=Normal name=Normal dimension=1 mean=class=Point name=Unnamed dimension=1 values=[0] sigma=class=Point name=Unnamed dimension=1 values=[1.41421] correlationMatrix=class=CorrelationMatrix dimension=1 implementation=class=MatrixImplementation name=Unnamed rows=1 columns=1 values=[1]
```
The mean of the sum of two gaussian distribution is wrong in this case. This should be a multi-modal distribution with two peaks: one at -10 and another one at +10.

**Comment by sofianehaddad** [comment]
you are confusing `Mixture` and `RandomMixture`

Mixture = distribution density writes as sum of density (with corresponding weights)
RandomMixture = sum of random variables!

**Comment by mbaudin47** [comment]
There is a confusion in my bug, which is invalid.
