### ISSUE TITLE
Why is this library overriding the SIGINT handler?

### ISSUE THREAD

**Issue by zplizzi** [openturns/openturns#2088]
In the code [here](https://github.com/openturns/openturns/blob/master/python/src/__init__.py#L57), the standard SIGINT handler is replaced (removed, really): `signal.signal(signal.SIGINT, signal.SIG_DFL)`.

This interferes with any code that imports this library and causes SIGINT to not be handled properly. Why is this necessary?

Eg this code will not clean up properly if you press CTRL-C:
```
import openturns as ot
import time

if __name__ == "__main__":
    try:
        print("starting")
        time.sleep(100)
    finally:
        print("calling shutdown")
        # do_shutdown()
```

**Comment by jschueller** [comment]
It is so to allow to interrupt the swig layer (openturns is mostly a c++ library), else we cannot stop for example a long simulation:
```
import openturns as ot
import time

print(ot.__file__)
if __name__ == "__main__":
    try:
        print("starting")
        f = ot.SymbolicFunction(['E', 'F', 'L', 'I'], ['-F*L^3/(3*E*I)'])
        d = ot.Normal([50.0, 1.0, 10.0, 5.0], [1.0]*4, ot.IdentityMatrix(4))
        vect = ot.RandomVector(d)
        output = ot.CompositeRandomVector(f, vect)
        event = ot.ThresholdEvent(output, ot.Less(), -3.0)
        experiment = ot.MonteCarloExperiment()
        algo = ot.ProbabilitySimulationAlgorithm(event, experiment)
        algo.setMaximumOuterSampling(150000000)
        algo.setBlockSize(4)
        algo.setMaximumCoefficientOfVariation(-0.1)
        algo.run()
    finally:
        print("calling shutdown")
        # do_shutdown()
```

**Comment by jschueller** [comment]
This method seems to work:
https://stackoverflow.com/questions/12145494/how-to-abort-python-script-calling-c-function-using-swig
