### ISSUE TITLE
Compute gradient of a PythonFunction with respect to a Sample

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2090]
Hello,

I've taken a look on the current implementation of the gradient of a PythonFunction. While it is possible to evaluate the value of a PythonFunction on a given sample, it seems impossible to compute its gradient on this object. It seems that only Points are accepted. 

``` 
import openturns as ot

def a_exec(X):
    Y = [3.0 * X[0] - X[1]]
    return Y

f = ot.PythonFunction(2, 1, a_exec)

X =ot.Sample([[100.0, 100.0],[50.,50.]])

Y = f(X)
print(Y)

dY_0 = f.gradient(X[0])
print(dY_0) 

dY = f.gradient(X)
print(dY) 
```

Is it the expected behavior?

**Comment by jschueller** [comment]
yes, as the gradient is always a matrix, we would have to return a 3-d matrix (tensor)

**Comment by m-balesdent** [comment]
Thanks!
