### ISSUE TITLE
Compressed H5 files?

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2091]
I have a huge meta-model to store into a Study. If I use an XMLH5StorageManager with compression level=9, I get a compressed XML file of size 8.5Ko and an uncompressed h5 file of size 1.9Go. If I compress this file using gzip, I get a file of size 85Mo (22.4x smaller). Could it be possible to compress the h5 file automatically?

**Comment by jschueller** [comment]
cc @YomGarcia
