### ISSUE TITLE
getSampleAtVertex() is not robust

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2094]
It seems to me that the method `getSampleAtVertex(nodeIndex)` does not check its input. Hence, any integer `nodeIndex` can be used, which may produce memory errors.
With OT1.19, the following script:
```python
import openturns as ot
scale = [1.0]
amplitude = [1.0]
covarianceModel = ot.SquaredExponential(scale, amplitude)
grid_min = 0.0
grid_max = 2.0
grid_size = 2
grid_step = (grid_max - grid_min) / (grid_size - 1)
mesh = ot.RegularGrid(0.0, grid_step, grid_size)
gaussianProcess = ot.GaussianProcess(covarianceModel, mesh)
sample_size = 10
sample = gaussianProcess.getSample(sample_size)
print("getSampleAtVertex(2) = ")
print(sample.getSampleAtVertex(2))
```
produce:
```
getSampleAtVertex(2) = 
0 : [ 4.65653e-310 ]
1 : [ 1.03978e-312 ]
2 : [ 1.58101e-322 ]
3 : [ 4.65653e-310 ]
4 : [ 8.37404e+242 ]
5 : [ 4.65653e-310 ]
6 : [ 1.58101e-322 ]
7 : [ 6.93594e-310 ]
8 : [ 1.58101e-322 ]
9 : [ 1.58101e-322 ]
```
But this cannot be correct, since there are only two nodes, with indices 0 and 1. Hence, there is no node with index equal to 2. According to the code:

https://github.com/openturns/openturns/blob/8584beb36c7f3282147b10e83acb327da234c3e5/lib/src/Base/Stat/ProcessSampleImplementation.cxx#L518

there does not seem to be a check that the node index is valid, i.e. between 0 and `verticesNumber - 1` where:
```
const UnsignedInteger verticesNumber = mesh_.getVerticesNumber();
```

**Comment by regislebrun** [comment]
This method was primarily developed as a private method, used in a controlled context by other methods. We forgot to add the argument check when its status changed...
