### ISSUE TITLE
LinearModelStepwiseAlgorithm ctor order

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2097]
the LinearModelStepwiseAlgorithm X,Y arguments are not consecutive as advertised in the doc
(https://openturns.github.io/openturns/latest/user_manual/response_surface/_generated/openturns.LinearModelStepwiseAlgorithm.html?highlight=linearmodelstepwisealgorithm)
maybe its better to put the basis argument after, for consistency with eg kriging ?
```
  LinearModelStepwiseAlgorithm(const Sample & inputSample,
                               const Basis & basis,
                               const Sample & outputSample,
                               const Indices & minimalIndices,
                               const Direction direction = FORWARD,
                               const Indices & startIndices = Indices());
```
cc @sofianehaddad

**Comment by sofianehaddad** [comment]
you are right

**Comment by sofianehaddad** [comment]
@jschueller same for `LinearModelAlgorithm`, isn't it?
