### ISSUE TITLE
Problem in documentation of getCorrelation() method

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2102]
Hello,

Description of `getCorrelation()` method of all the distributions and copulas returns "**(ditch me?)**".

See for example : [https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Exponential.html?highlight=ditch#openturns.Exponential.getCorrelation](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Exponential.html?highlight=ditch#openturns.Exponential.getCorrelation)

Mathieu

**Comment by adutfoy** [comment]
This problem has benn resolved in the 1.22 version.
