### ISSUE TITLE
The theory doc of the autocorrelation function of a stochastic process is wrong

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2104]
The theory [doc](https://openturns.github.io/openturns/latest/theory/probabilistic_modeling/process_definitions.html) of the autocorrelation function of a stochastic process is wrong:

![image](https://user-images.githubusercontent.com/31351465/180426418-f520fab3-61bc-4c41-b049-0301bb0839a8.png)

What is wrong is that, in the square root, we should have the product of the variance at point s (indices ij) and the variance at point t (index ij).

In [Wikipedia](https://en.wikipedia.org/wiki/Autocorrelation), the definition is:

![image](https://user-images.githubusercontent.com/31351465/180426554-e497429f-e1a9-49d6-8bca-9cfc274c418e.png)

In [^Papoulis2002] page 384, I read:

![image](https://user-images.githubusercontent.com/31351465/180426800-28269310-4535-4b20-91f8-edd029aeb479.png)

So the correct equation should be:

![image](https://user-images.githubusercontent.com/31351465/180427380-4444621e-59f9-4dfd-8764-76ad7f41a14d.png)

Is this correct @adutfoy ?

[^Papoulis2002]: A. Papoulis, S. U. Pillai (2002). Probability, Random Variables, And Stochastic Processes. Fourth Edition.

**Comment by jschueller** [comment]
ping @adutfoy
