### ISSUE TITLE
HSIC draw indices method does not handle input sample descritption names

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2110]
Hello,

In order to be consistent with other sensitivity indices draw functions, it could be nice to by default to display the input sample name descriptions in the graph instead of default names "X0", "X1", "X2", etc., or to provide a method to change these names.

Regards,

Loïc and Mathieu

**Comment by jschueller** [comment]
This should be adressed by https://github.com/openturns/openturns/pull/2085
