### ISSUE TITLE
Add mini-galleries of examples on the API pages

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2115]
Since several releases, the OpenTURNS web documentation starts with a page of examples which is really nice! Attractive to people who are not comfortable with mathematics, convenient for users looking for a standard use of some objects, ... 

As the technology used to generate the example galleries seems to be [sphinx-gallery](https://github.com/sphinx-gallery/sphinx-gallery), why not adding a section **Examples** at the bottom of the API pages as [scikit-learn does](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html#examples-using-sklearn-gaussian-process-gaussianprocessregressor) It can be really useful, when you arrive on an API page for x or y reason, to find examples associated to the corresponding class.  Note that it is possible to automate this [with sphinx gallery](https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation).

**Comment by mbaudin47** [comment]
It seems to me that the second link to "as scikit-learn does" is wrong. It points to the same link as under "sphinx-gallery".

**Comment by mdelozzo** [comment]
Oops. I repaired the link. This is a exactly this example I had in mine!
