### ISSUE TITLE
GaussianProcess Gibbs sampling method issues

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#2121]
There are several issues related to the way Gibbs sampling works in the [GaussianProcess](https://openturns.github.io/openturns/1.19/user_manual/_generated/openturns.GaussianProcess.html) class.

- [x] Using `setSamplingMethod(ot.GaussianProcess.GIBBS)` results in a wrong result.

Here is an example where we construct a "Gaussian process" discretized on a singleton and sample from it.
We take 10 as the amplitude of the covariance model, so the sample from the "Gaussian process" (actually a simple normal random variable) should have empirical standard deviation approximately 10. Instead, it is about 100.

```python
import openturns as ot
ot.RandomGenerator.SetSeed(0)

standard_deviation = 10.0

mesh = ot.Mesh([[0.0]]) # singleton
cov_matrix = ot.CovarianceMatrix(1, [standard_deviation**2]) # associated "covariance matrix"
covModel = ot.UserDefinedCovarianceModel(mesh, cov_matrix)

# Create the "Gaussian Process" discretized on a singleton
myProcess = ot.GaussianProcess(covModel, mesh)
myProcess.setSamplingMethod(ot.GaussianProcess.GIBBS) # the result is correct if this line is commented

size = 1000
sample = ot.Sample(size, 1)
for i in range(size):
    sample[i] = myProcess.getRealization().getValues()[0]

print(sample.computeStandardDeviation())
# [102.017]
```

- [x] This line of code should be changed:

https://github.com/openturns/openturns/blob/82c89cd7e5e92aade1b6d216167453508aaa4684/lib/src/Uncertainty/Process/GaussianProcess.cxx#L252

As it stands, if `ot.GaussianProcess.GIBBS` is selected but the output dimension is >1, sampling silently falls back to Cholesky. An exception would be better.

- [x] `GaussianProcess` needs a `getSamplingMethod` to match its `setSamplingMethod`.

~The name `ot.GaussianProcess.GIBBS` is confusing, because this is not a traditional Gibbs sampler of a Gaussian vector Y with mean 0 and covariance matrix C. It implements the idea, proposed by [Galli and Gao (2001)](https://link.springer.com/article/10.1023/A:1011094131273) of using a Gibbs sampler to sample from an auxiliary Gaussian vector X with mean 0 and covariance matrix C^{-1}, and then setting Y = C X. What we do is use a smart implementation of that idea given in [Ayano and Emery (2020)](https://www.researchgate.net/publication/345206244_Iterative_algorithms_for_non-conditional_and_conditional_simulation_of_Gaussian_random_vectors) (thanks for the ref @regislebrun) - see my [post below](https://github.com/openturns/openturns/issues/2121#issuecomment-1209074621). So maybe we could rename this `ot.GaussianProcess.GALLIGAOGIBBS`? The [doc](https://openturns.github.io/openturns/1.19/user_manual/_generated/openturns.GaussianProcess.html#openturns.GaussianProcess.setSamplingMethod) should also be updated to explain what the method does, or at least provide a reference.~

EDIT: fourth task was moved by @jschueller to #2130.

**Comment by sofianehaddad** [comment]
Good catch!
Probably a missing `std::sqrt` [here](https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Process/GaussianProcess.cxx#L289)

**Comment by josephmure** [comment]
I would rather bet on a missing `std::sqrt` there:
https://github.com/openturns/openturns/blob/82c89cd7e5e92aade1b6d216167453508aaa4684/lib/src/Uncertainty/Process/GaussianProcess.cxx#L295

But I do not know this algorithm. It is strange that it is called "Gibbs" because it does not do what I would expect a Gibbs algorithm to do.

**Comment by sofianehaddad** [comment]
There is a scaling [here](https://github.com/openturns/openturns/blob/82c89cd7e5e92aade1b6d216167453508aaa4684/lib/src/Uncertainty/Process/GaussianProcess.cxx#L290). That is why I suggested the previous fix

**Comment by josephmure** [comment]
With your fix, `delta` would be homogeneous to the inverse of a standard deviation.
But the [next line](https://github.com/openturns/openturns/blob/82c89cd7e5e92aade1b6d216167453508aaa4684/lib/src/Uncertainty/Process/GaussianProcess.cxx#L291) multiplies delta by a covariance, making the product `covarianceRow * delta` homogeneous to a standard deviation.  The same line adds this product to `values`, which is supposed to be adimensional, so there would be a problem.

**Comment by regislebrun** [comment]
If I remember well, this algorithm was presented 10 years ago during a workshop at IHP. I am pretty sure that this article would be of interest https://www.researchgate.net/publication/345206244_Iterative_algorithms_for_non-conditional_and_conditional_simulation_of_Gaussian_random_vectors but unfortunately I cannot find the full version online...

**Comment by josephmure** [comment]
So I have taken a screenshot (sorry for the weird gap, it should be on a single line) of the updating formula  (equation 6 in the paper @regislebrun linked to) :

![image](https://user-images.githubusercontent.com/31989332/183599164-8881f6e7-7ab2-4801-bdc2-72635d221de7.png)
![image](https://user-images.githubusercontent.com/31989332/183596711-f6f09efd-dbdb-4d04-a75d-1857def9edd4.png)

I think we are implementing the "simple" version of the algorithm, where ![image](https://user-images.githubusercontent.com/31989332/183598638-2e276d20-5241-4426-bf6a-0d64b94b472b.png)

The other notations are given in the following screenshots: 

![image](https://user-images.githubusercontent.com/31989332/183597604-87e77134-0eec-434d-97f2-fb33f87d59cc.png)

-----------------

![image](https://user-images.githubusercontent.com/31989332/183597848-c6b75323-47d9-4081-8782-bc042060e314.png)

-----------------

![image](https://user-images.githubusercontent.com/31989332/183598334-66ce6d97-f4e2-4bbf-b729-8e0575565d36.png)

-----------------

![image](https://user-images.githubusercontent.com/31989332/183598078-c0a17e0d-c9e9-429c-811e-b8f4b1347771.png)

-----------------

In our implementation, in addition to ![image](https://user-images.githubusercontent.com/31989332/183598638-2e276d20-5241-4426-bf6a-0d64b94b472b.png) we have p=1 and therefore J is a singleton {j}, so the updating formula simplifies to:

![image](https://user-images.githubusercontent.com/31989332/183601686-a2e72533-ca23-4360-99a2-c73c00f92b72.png)

**Comment by josephmure** [comment]
So neither @sofianehaddad's nor my suggestions were enough. To implement this, I think we should replace the current code block:

```c++
  for (UnsignedInteger n = 0; n < nMax; ++n)
  {
    LOGINFO(OSS() << "Gibbs sampler - start iteration " << n + 1 << " over " << nMax);
    const Point permutation(permutationDistribution.getRealization());
    for (UnsignedInteger i = 0; i < size; ++i)
    {
      const UnsignedInteger index = static_cast< UnsignedInteger >(permutation[i]);
      LOGDEBUG(OSS() << "Gibbs sampler - update " << i << " -> component " << index << " over " << size - 1);
      // Here we work on the normalized covariance, ie the correlation
      Sample covarianceRow(covarianceModel_.discretizeRow(vertices, index));
      diagonal[index] = covarianceRow[index][0];
      const Point delta(1, (DistFunc::rNormal() - values(index, 0)) / diagonal[index]);
      values += covarianceRow * delta;
    }
  }
  // We have to rescale the realization
  for (UnsignedInteger i = 0; i < size; ++i) values[i] *= diagonal[i];
  return values;
```

with:

```c++
  for (UnsignedInteger n = 0; n < nMax; ++n)
  {
    LOGINFO(OSS() << "Gibbs sampler - start iteration " << n + 1 << " over " << nMax);
    const Point permutation(permutationDistribution.getRealization());
    for (UnsignedInteger i = 0; i < size; ++i)
    {
      const UnsignedInteger index = static_cast< UnsignedInteger >(permutation[i]);
      LOGDEBUG(OSS() << "Gibbs sampler - update " << i << " -> component " << index << " over " << size - 1);
      // Here we implement equation (6) of Arroyo, Daisy & Emery, Xavier (2020) with rho=0 and J={j}
      Sample covarianceRow(covarianceModel_.discretizeRow(vertices, index));
      diagonal[index] = covarianceRow[index][0];
      const Point delta(1, (std::sqrt(diagonal[index]) * DistFunc::rNormal() - values(index, 0)) / diagonal[index]);
      values += covarianceRow * delta;
    }
  }
  return values;
```

**Comment by jschueller** [comment]
no relation with #1873 ?
