### ISSUE TITLE
MixtureClassifier 'grade' method does not work with a Sample input

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#2123]
Hello,
There seems to be an issue with the 'grade' method of the of the MixtureClassifier class. There are two different sets of inputs it can be called with: 

- Point and Integer,
- Sample and List of Integers

However, the second usage does not seem to work. A short example: 
``` 
import openturns as ot
mixt =  ot.Mixture([ot.Uniform(0,1),ot.Uniform(0.5,1.5)],[0.4,0.6])
classif = ot.MixtureClassifier(mixt)
sample = ot.Uniform(0,1).getSample(3)
classif.grade(sample,[0,1,1])
```

However, if I do the following, it works normally: 
``` 
[...]
classif = ot.Classifier(classif)
classif.grade(sample,[0,1,1])
```

I guess there might be an issue within the heritage of the grade(Sample, IntegerCollection) method between ClassifierImplementation and MixtureClassifier, but I can't seem to find it.

**Comment by sofianehaddad** [comment]
Probably missing a `using ClassifierImplementation::grade;` in `MixtureClassifier.hxx`. I will check
Thanks for catching it
