### ISSUE TITLE
GaussianProcess.GIBBS

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2130]
The name `ot.GaussianProcess.GIBBS` is confusing, because this is not a traditional Gibbs sampler of a Gaussian vector Y with mean 0 and covariance matrix C. It implements the idea, proposed by [Galli and Gao (2001)](https://link.springer.com/article/10.1023/A:1011094131273) of using a Gibbs sampler to sample from an auxiliary Gaussian vector X with mean 0 and covariance matrix C^{-1}, and then setting Y = C X. What we do is use a smart implementation of that idea given in [Ayano and Emery (2020)](https://www.researchgate.net/publication/345206244_Iterative_algorithms_for_non-conditional_and_conditional_simulation_of_Gaussian_random_vectors) (thanks for the ref @regislebrun) - see my [post below](https://github.com/openturns/openturns/issues/2121#issuecomment-1209074621). So maybe we could rename this `ot.GaussianProcess.GALLIGAOGIBBS`? The [doc](https://openturns.github.io/openturns/1.19/user_manual/_generated/openturns.GaussianProcess.html#openturns.GaussianProcess.setSamplingMethod) should also be updated to explain what the method does, or at least provide a reference.

from #2121

**Comment by regislebrun** [comment]
@jschueller Good idea, let's adopt 'ot.GaussianProcess.GALLIGAOGIBBS'
