### ISSUE TITLE
KarhunenLoeveSVDAlgorithm seems to truncate the expansion from v1.19

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2139]
Hello,

I'm upgrading openturns to 1.19 in [gemseo](https://gitlab.com/gemseo/dev/gemseo/-/merge_requests/409) and unfortunately [a test](https://gitlab.com/gemseo/dev/gemseo/-/blob/develop/tests/mlearning/transform/dimension_reduction/test_klsvd.py#L68) fails due to a change in `KarhunenLoeveSVDAlgorithm` (maybe something in [this PR](https://github.com/openturns/openturns/pull/1995/files#diff-576252cb6c35b58aae503aaccb50a47707afa5c51de9d6e5fab8fef01dae7bed)).

The test relies on the following code  (I removed the gemseo part and kept the openturns + numpy one). It considers a 100-length process sample over a 10-length 1D mesh. The number of eigenvalues was equal to 10 up to the version 1.18 and is equal to 3 with the version 1.19. As it uses `KarhunenLoeveSVDAlgorithm` without thresholding, the value 10 seems to me correct.

Does the v.1.19 truncate the expansion by default?

```python
from numpy import array
from numpy import linspace
from numpy import pi
from numpy import sin
from numpy.random import rand
from openturns import Field
from openturns import KarhunenLoeveSVDAlgorithm
from openturns import Mesh
from openturns import ProcessSample
from openturns import Sample


def func(tau, theta):
    return sin(2 * pi * (tau - theta)) + 1


mesh_size = 10
mesh = [[t_i] for t_i in linspace(0, 1, mesh_size)]
data = array([func(array(mesh).flatten(), theta) for theta in rand(1000)])
mesh = Mesh(Sample(mesh))

datum = [[x_i] for x_i in data[0, :]]
samples = ProcessSample(1, Field(mesh, datum))
for datum in data[1:, :]:
    samples.add(Field(mesh, [[x_i] for x_i in datum]))

algo = KarhunenLoeveSVDAlgorithm(
    samples,
    [1] * mesh.getVerticesNumber(),
    0.0,
    True,
)
algo.run()

result = algo.getResult()
print(len(result.getEigenvalues()))
# 10 for version <= 1.18
# 3 for version == 1.19
```

**Comment by jschueller** [comment]
on this example eigenvalues decrease very fast, and when we compute the cumulated sum for the criteria the sum stays the same as we add a big value (~15) with a tiny one (9e-30):
eigenValues=[10.0389,2.68,2.25552,9.01814e-30,4.53074e-30,9.3953e-31,2.10531e-31,3.53615e-32,3.18668e-32,2.42483e-32]

**Comment by mdelozzo** [comment]
Yes, you're right. But I think it is up to the user to remove the 7 non-significant eigenvalues.

**Comment by regislebrun** [comment]
It should be enough to replace '<' by '<=' [here](https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Process/KarhunenLoeveSVDAlgorithm.cxx#L323)

**Comment by mdelozzo** [comment]
Your proposed fix seems to be good. Thanks.
