### ISSUE TITLE
GeneralizedParetoFactory.buildMethodOfMoments estimating wrong parameter

### ISSUE THREAD

**Issue by shiokoala** [openturns/openturns#2140]
Hello,

I have just started using openTURNS for extreme value analysis and found that the GeneralizedParetoFactory.buildMethodOfMoments() method of estimating the genpar parameters (xi, sigma, mu) results in the shape parameter(xi) being the negative of the expected parameter.
(It's also my first time posting any kind of issues on a public repo, so my apologies if I've broken any rules)

I think this is due to a confusing convention of having two different ways of representing the generalized Pareto distribution, where some people use 'k' and others use 'xi' for the shape parameter, where the only difference is k=-xi. I'm not sure, so if anyone could point me to a source for the origin of the equation that would be helpful.

Here I've demonstrated the problem by comparing the bootstrap estimations from multiple methods of estimation.
![image](https://user-images.githubusercontent.com/63235669/191654758-96093b65-47a1-4044-89de-800e1e58838a.png)

**Comment by jschueller** [comment]
indeed, it looks like we estimate k and pass it as xi in GeneralizedParetoFactory::buildMethodOfMoments

**Comment by shiokoala** [comment]
Thank you for the quick response!
