### ISSUE TITLE
Using semantic versioning for defining the version numbers of OpenTURNS

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2141]
Hello,

Why not use [semantic versioning](https://semver.org/) for defining the version numbers of OpenTURNS?

Given a version number MAJOR.MINOR.PATCH, we increment the:

- MAJOR version when we make incompatible API changes,

- MINOR version when we add functionality in a backwards compatible manner, and

- PATCH version when we make backwards compatible bug fixes.

It would facilitate the integration of _openturns_ into software depending on many packages:
- PATCH versions could be released more often to solve the bugs introduced in the previous releases,
- MINOR versions could improve the software depending on _openturns_ without complicating the integration of the new version because of API changes,
- When a developer would like to upgrade _openturns_ and see that the new version is a MAJOR, he would known that he will have to roll up his sleeves because of the changes of API and will look for the right timing to do so.

As an integrator, it would help me and my colleagues :)

**Comment by jschueller** [comment]
currently we may break api at each minor version, and if we do there is at least one version overlap where we declare obsolete symbols as deprecated before actually removing them
maintainers can refer to the changelog when upgrading

**Comment by jschueller** [comment]
a cool thing to read: https://hynek.me/articles/semver-will-not-save-you/

**Comment by mdelozzo** [comment]
Thanks for your explanation and the shared article.
