### ISSUE TITLE
Table of Contents issue in API doc pages

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#2144]
The current master has very ugly API TOCs:

https://openturns.github.io/openturns/master/user_manual/_generated/openturns.ConditionalDistribution.html

![image](https://user-images.githubusercontent.com/31989332/192529317-e73535ac-1955-427a-b9fa-e6bdfcdf7a98.png)

This bug was not introduced by PR #2136, as the CircleCI-compiled doc of that PR shows:

https://output.circle-artifacts.com/output/job/994fb343-d924-4b6d-9fc9-c0186f62f674/artifacts/0/html/user_manual/_generated/openturns.ConditionalDistribution.html

![image](https://user-images.githubusercontent.com/31989332/192530466-e0dfd191-e5bc-4f66-8945-95043d6f4a90.png)

Did something change with Sphinx?

**Comment by jschueller** [comment]
yes, the version: 5.2.x

**Comment by josephmure** [comment]
Can you fix this before the RC or should we freeze the Sphinx version for now?

**Comment by jschueller** [comment]
at least open an issue at sphinx with the same report

**Comment by jschueller** [comment]
looks it comes from https://github.com/sphinx-doc/sphinx/pull/10807
a bit better with toc_object_entries_show_parents = hide

**Comment by josephmure** [comment]
I have raised the issue in the discussion of the request that prompted the creation of the feature that is causing the problem: https://github.com/sphinx-doc/sphinx/issues/6316#issuecomment-1261408551

**Comment by josephmure** [comment]
The option to disable the feature is implemented in PR https://github.com/sphinx-doc/sphinx/pull/10886. I have tested it locally: it works fine.

**Comment by josephmure** [comment]
We might want to think about updating the "openturns" theme, however.
