### ISSUE TITLE
P1LagrangeInterpolation can make Python fail

### ISSUE THREAD

**Issue by RomanSueur** [openturns/openturns#2152]
Here is what I get in my console when I try to use the P1LagrangeInterpolation constructor :

_______________________________________________________
A61372@dsp1021827:~$ python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>> import numpy as np
>> import openturns as ot
>> 
>> tps_max    = 2500
>> mesher     = ot.IntervalMesher([50])
>> interval   = ot.Interval([0.0], [tps_max])
>> outputMesh = mesher.build(interval)
>> 
>> output_dimension = 1
>> 
>> nodes            = ot.Sample(1, np.arange(0,2500,0.8))
>> nombrePasDeTemps = nodes.getDimension()
>> simplices        = [[nodeIndex, nodeIndex + 1] for nodeIndex in range(nombrePasDeTemps - 1)]
>> inputMesh        = ot.Mesh(nodes, simplices)
>> interpolationTf  = ot.P1LagrangeInterpolation(inputMesh, outputMesh, output_dimension)

Erreur de segmentation
A61372@dsp1021827:~$
___________________________________________________________

Is there any workaround for this or another class allowing to interpolate (even roughly) ?

Thank you

**Comment by sofianehaddad** [comment]
Your `inputMesh` is incorrect. It has a `size=1` and `dimension=3125`.

You should define your nodes as follow:
```
nodes = ot.Sample.BuildFromPoint(np.arange(0, 2500, 0.8))
```
Otherwise, in case of regular grid (1d), the simplest way is to have your mesh easily using:
```
 inputMesh = ot.RegularGrid(0, 0.8, 2500)
```

@jschueller it should however raise an exception in this case, no?

Cheers.
