### ISSUE TITLE
HSIC computation cost

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2153]
the wingweight example that use HSIC takes much longer to run when the doe size is set from 200 to 800 (see #2150)
is there something that explains the computing cost ? is it usable on "medium" DOEs (10k) ?
seems #2053 helps gain a few percents, but its not radical
@JPelamatti @josephmure

**Comment by mdelozzo** [comment]
The computing cost is identified as a limitation of HSIC for practitioners. One should take a look at the recent literature on the subject, e.g. https://link.springer.com/article/10.1007/s11222-016-9721-7.

**Comment by jschueller** [comment]
I suggest to mention this in the doc then

**Comment by JPelamatti** [comment]
@jschueller  As mentioned in the #2053 , the main computational cost come from the permutation-based p-values. Standard HSIC and R2-HSIC should have an acceptable cost when dealing with a DoE containing 10k elements (I would guess a few seconds per dimension). However, in this case you could/should use the asymptotic p-values estimator without much worry, as you are providing a considerable amount of data.
@mdelozzo  Thanks for the reference!

**Comment by sofianehaddad** [comment]
see #2251
