### ISSUE TITLE
Slow creation of mixtures when the atom distributions are costly to copy

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2157]
When creating a mixture of costly to create & copy atoms takes way too long time:
```
import openturns as ot
from time import time

ot.Log.Show(ot.Log.NONE)

ot.ResourceMap.SetAsUnsignedInteger("Mixture-LargeSize", 0)

class ModifiedKernel(ot.PythonDistribution):

    def __init__(self, kernel, F, Xk, h):
        super(ModifiedKernel, self).__init__(1)
        self.kernel_ = kernel
        self.F_ = F
        self.Ftrunc_ = ot.TruncatedDistribution(F, 0.0, ot.TruncatedDistribution.UPPER)
        self.Xk_ = Xk
        self.h_ = h

    def getRange(self):
        lb = self.kernel_.getRange().getLowerBound()[0]
        ub = self.kernel_.getRange().getUpperBound()[0]
        Xk = self.Xk_
        h = self.h_
        return ot.Interval((lb - Xk) / h, (ub - Xk) / h)

    def computeCDF(self, X):
        x = X[0]
        K = self.kernel_
        F = self.F_
        Ftrunc = self.Ftrunc_
        Xk = self.Xk_
        h = self.h_
        y = F.computeQuantile(Ftrunc.computeCDF(x))[0]
        return K.computeCDF((y - Xk) / h)

    def isCopula(self):
        return False

class ConditionalKernelMixture(ot.PythonDistribution):

    def __init__(self, distribution, x_1):
        super(ConditionalKernelMixture, self).__init__(1)
        kernel = distribution.getKernel()
        bw = distribution.getBandwidth()
        inSample = distribution.getInternalSample()
        size = inSample.getSize()
        sample1 = inSample.getMarginal(1)
        weights = kernel.computePDF((sample1 - x_1) / bw[1]).asPoint()
        F = distribution.getMarginal(0)
        all_data = [(kernel, F, inSample[i, 0], bw[0]) for i in range(size)]
        atoms = [ot.Distribution(ModifiedKernel(data[0], data[1], data[2], data[3])) for data in all_data]
        self.actualDistribution_ = ot.Mixture(atoms, weights)

    def getRange(self):
        return self.actualDistribution_.getRange()

    def computeCDF(self, X):
        return self.actualDistribution_.computeCDF(X)

size = 2000
sample = ot.Normal(2).getSample(size)
x_1 = sample.getMarginal(1).computeMedian()[0]
ks = ot.KernelSmoothing()
bw = ks.computeSilvermanBandwidth(sample)
distribution = ks.buildAsKernelMixture(sample, bw)
t0 = time()
dPy = ConditionalKernelMixture(distribution, x_1)
d = ot.Distribution(dPy)
t1 = time()
print("t=", t1 - t0, "s")
```
gives on my computer, with the current master:
```
##################################################
size= 2000
Create atoms
t= 5.280026912689209 s
Create mixture
t= 146.09880709648132 s
```
The following flame graph shows the problems:
![perf_master](https://user-images.githubusercontent.com/8220933/195300871-842d0108-3a15-4ab3-a772-7e41ec05d2e8.svg)

We see that a large amount of time is spent in creating Study objects, due to the way the copy constructor of Python objects is implemented, using the persistence mechanism. The problem is mainly located [here](https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Distribution/Mixture.cxx#L237), where we use the weight_ attribute of the distributions to store the weights of the mixture, triggering a copy of each atom. A solution should be to improve the copy of Python objects, but a quick fix could be to avoid such a copy by using the p_ attribute of the Mixture to implement all its methods. Doing so, I get:
```
size= 2000
Create atoms
t= 5.260856628417969 s
Create mixture
Second loop, keep only the atoms with a significant weight and update the sum
t= 0.016857147216796875 s
```
The creation of the atoms still takes too much time. Unfortunately I lost the flame graph obtained after this modification, but the main point was the time spent in the computeRange() method of the TruncatedDistribution, partly due to a call to ResourceMap and mainly due to the call to the computeProbability() method of the underlying distribution. For an 1D Normal kernel, 80% of the time is spent creating Interval, Point and destroying them. A solution is to implement a generic computeProbability() method dedicated to the 1D case, with the two (scalar) bounds of the interval, and to propagate their use to the KernelMixture class. Doing so, I get:
```
##################################################
size= 2000
Create atoms
t= 0.684654712677002 s
Create mixture
Second loop, keep only the atoms with a significant weight and update the sum
t= 0.005232095718383789 s
```
and the following flame graph shows that, now, the time is spent in the actual computation of probabilities instead of the management of intermediate objects:
![perf_apres_modification_mixture_proba](https://user-images.githubusercontent.com/8220933/195304080-de61de5e-f0f1-426d-81c4-72b37120f285.svg)

Unfortunately I am still struggling with a bug related to the reorganization of the different variants of the computeProbability() method to propose a PR...

**Comment by jschueller** [comment]
fixed in #2159
