### ISSUE TITLE
Drop Normal SPD check

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2161]
https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Distribution/Normal.cxx#L110

**Comment by regislebrun** [comment]
@jschueller Without this check we should reorganize the computations a little bit:
* First, extract the diagonal part of the covariance matrix and check that its elements are strictly positive. Throw an exception if it is not the case
* Second, compute the correlation matrix
* Third, call the constructor based on mean, standard deviation and correlation: it will perform the regularization loop and check the positiveness of the matrix

**Comment by jschueller** [comment]
thanks, applied
