### ISSUE TITLE
Curious indents on doc

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2166]
Hello, 

All the pages of doc  [example 1](https://openturns.github.io/openturns/latest/user_manual/probabilistic_modelling.html ), [example2](https://openturns.github.io/openturns/latest/user_manual/orthogonal_basis.html) have curious indents.

Mathieu

**Comment by jschueller** [comment]
https://github.com/sphinx-doc/sphinx/issues/10918

**Comment by m-balesdent** [comment]
Won't it be possible to wait for the solving of this bug by sphinx and consequently not to use the latest version of sphinx for ot. 1.20 ?
