### ISSUE TITLE
Testing equality of distribution parameters with type Scalar (aka double) should not be done with the == operator

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2179]
Hello,

While investigating the issue
    https://github.com/persalys/persalys/issues/748
on Persalys, I found that many classes in lib/src/Uncertainty/Distribution/
define the == operator by comparing the parameters of the distributions one by one using ==. If you look at the above mentioned issue, especially at
    https://github.com/persalys/persalys/issues/748#issuecomment-1279437959
you will see this can lead to unexpected errors due to the precision of the double type. For instance, the examplified distribution is Gamma, which has three Scalar (ie double) parameters.

It would be safer to check the differences between parameters are small, e.g. with the enclosed patch. Also I guess it would be worth looking at the other distributions for the same issue, e.g. Rayleigh.cxx, LogUniform.cxx... have the same problem.

[scalar_comparison_in_Gamma_distribution.txt](https://github.com/openturns/openturns/files/9895914/scalar_comparison_in_Gamma_distribution.txt)

Best,
Pierre

**Comment by jschueller** [comment]
this mainly concerns the automated tests, I'd say we rather make sure to compare parameters with assert_almost_equal in new tests, unfortunately there are still a lot of tests that we compare using diffs

**Comment by pgrt** [comment]
Hi @jschueller and thanks for looking at my report!

I understand and agree new tests should certainly do so, and I can imagine reviewing and revising all existing tests can be a considerable burden.

Yet my point was more focused on the class definitions of the distributions themselves, as the assessment of distributions being the same or not can happen to be unreliable: be it in a test of anywhere else, distributions that would be compared using their == operator could be seen as different because of numerical accuracy, although they would be associated to the same real values of parameters. E.g. in the Persalys issue 748 we had
    Gamma(k = 100, lambda = 50, gamma = -1.11022e-16)
and
    Gamma(k = 100, lambda = 50)
which were considered as different using Gamma.operator== .

Thanks again,
Pierre

**Comment by josephmure** [comment]
> this mainly concerns the automated tests, I'd say we rather make sure to compare parameters with assert_almost_equal in new tests, unfortunately there are still a lot of tests that we compare using diffs

An alternative would be to develop an assert_almost_equal method for distributions: it would call the scalar assert_almost_equal method on all parameters of the distribution, using the same absolute and relative tolerances for all parameters. If we need to fine-tune the test by having different absolute and relative tolerances for the parameters, we can always fall back on the current way of doing it parameter by parameter.

**Comment by regislebrun** [comment]
Hi all,
I am dubious on the interest of making distribution comparisons approximate. IMO the values of the parameters rarely depends on two different computations, so if the comparison returns false where it should return true it is most of the case the sign of another bug, which would be hidden if we hide it through approximate comparisons.
Is the bug found via Persalys an actual roundoff error or a conversion between types through the GUI? From where comes the -1.11022e-16 value for gamma in Persalys?

**Comment by pgrt** [comment]
Hi everyone,

@regislebrun I am unsure of the exact reason for the bug found via Persalys but I can say it shows up in the assertion on line 124 in lib/test/t_ProbabilisticModelWindow_std.cxx (in the Persalys source tree) and it depends on the architecture: on amd64 for instance there is no problem.

I understand the idea @josephmure explains, yet I tend to agree with @regislebrun there is a bug hidden somewhere. In my opinion we /should/ be able to rely on the == operator in lib/src/Uncertainty/Distribution/Gamma.cxx (and for other distributions as well) to handle exact comparison.
For instance would we say that OT::Gamma(100., 50., 0.) and OT::Gamma(100., 50., 1.11022e-16) are equal, the latter number being the machine epsilon? If yes, then == should return true when comparing these two distributions and something in the spirit of the above submitted patch should be implemented.
If not, then we can indeed test approximate equality of distributions but the == operators of the distributions are unreliable and we should acknowledge it.

Cheers,
Pierre

**Comment by jschueller** [comment]
lets close this since we have https://github.com/openturns/openturns/pull/2183
