### ISSUE TITLE
out of bound probas

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2200]
running torque_model.py:
```
/usr/lib/python3.10/site-packages/pyAgrum/lib/explain.py:219: UserWarning: For A, entropy is NaN.
  warnings.warn(f"For {bn.variable(n).name()}, entropy is NaN.")
/usr/lib/python3.10/site-packages/pyAgrum/lib/explain.py:227: UserWarning: For T->A, mutual information is Nan.
  warnings.warn(f"For {bn.variable(x).name()}->{bn.variable(y).name()}, mutual information is Nan.")
```
this is because some probabilities computed in otagrum are slightly negative out of bounds [0,1]
cc @MLasserre

**Comment by jschueller** [comment]
oh, it comes from the poincarre sum in DistributionImplementation::computeProbabilityGeneral where we sum with alternating signs:
```
// P(\bigcap_i ai < Xi \leq bi) = \sum_c (−1)^n(c) F(c_1,c_2,...,c_n)
    // with c = (c_i, i =1, ..., n), c_i \in [a_i, b_i]
    // and n(c) = Card({c_i == a_i, i = 1, ..., n})
    probability = 0.0;
    const UnsignedInteger iMax = 1 << dimension_;
    for( UnsignedInteger i = 0; i < iMax; ++i )
    {
      Bool evenLower = true;
      Point c(b);
      for( UnsignedInteger j = 0; j < dimension_; ++j )
      {
        const UnsignedInteger mask = 1 << j;
        if (i & mask)
        {
          c[j] = a[j];
          evenLower = (!evenLower);
        }
      } // j
      const Scalar cdf = computeCDF(c);
      if (cdf < 0.0)
        std::cout << "DistributionImplementation::computeProbabilityGeneral cdf="<<cdf<<std::endl;
      probability += (evenLower ? cdf : -cdf);
    } // i
```

@regislebrun does it make sense to clip the proba to [0,1] ?

**Comment by regislebrun** [comment]
Ok I found it. The chain is: `ComposedDistribution::computeProbability` calls `NormalCopula::computeProbability` after an interval adaptation, then it calls `Normal::computeProbability` and as we are in a small dimension setting, it calls `ContinuousDistribution::computeProbability`. In OT1.19, this method was implemented as a numerical integration of the PDF using a Gauss Legendre quadrature, but in OT1.20 it is redirected to `DistributionImplementation::computeProbability`, which should use the exact same algorithm. I have been stupid enough to forget to trigger a call to `DistributionImplementation::computeProbabilityContinuous` (I had in mind to do it at the ContinuousDistribution level but changed my mind in the way) and use `DistributionImplementation::computeProbabilityGeneral` instead. It is implemented as an alternating sum of CFD evaluations, which can lead to (slightly) negative values.

As a summary:
* `DistributionImplementation::computeProbability()` should call `DistributionImplementation::computeProbabilityContinuous()` when `isContinuous()` is true
* All the calls to `ContinuousDistribution::computeProbability()` should be replaced by calls to `DistributionImplementation::computeProbability()`

The `ContinuousDistribution` class should probably be removed...

**Comment by jschueller** [comment]
ok, computeProbabilityContinuous works on our testcase
it's fine to call ContinuousDistribution::computeProbability as it's the mother class even when not implemented

do we still want to clip the poincarre formulas though ?

**Comment by regislebrun** [comment]
@jschueller I found many references to Poincarre in the source code... but it is Poincare (with a unique 'r')!

**Comment by jschueller** [comment]
ok, done
