### ISSUE TITLE
Edges of a PolygonArray

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2205]
A `PolygonArray` can be useful to plot confidence bounds using fill color with some transparency. But when we create a `PolygonArray` with a alpha fill color, unwanted edges are shown.
In the following script, I create three functions : the sine function and the sine function +/- a delta value representing the lower and upper bounds. Then I fill the area with some transparent color. 

```python
import openturns as ot
import numpy as np
import openturns.viewer as otv

# Create a transparent color
palette = ot.Drawable.BuildDefaultPalette(2)
fillColor = palette[1]
r, g, b = ot.Drawable.ConvertToRGB(fillColor)
alpha_channel = 64
transparentFillColor = ot.Drawable.ConvertFromRGBA(r, g, b, alpha_channel)

# Create three functions
function_1 = ot.SymbolicFunction(["x"], ["sin(x) - 0.5"])
function_2 = ot.SymbolicFunction(["x"], ["sin(x)"])
function_3 = ot.SymbolicFunction(["x"], ["sin(x) + 0.5"])

# Create plot
n_points = 20
sample_grid = ot.Sample.BuildFromPoint(np.linspace(-np.pi, np.pi, n_points))
lower_bound = function_1(sample_grid)
upper_bound = function_3(sample_grid)
# Plot (fill)
graph = function_2.draw(-np.pi, np.pi, n_points)
verticesLowerBound = ot.Sample(
    [[sample_grid[i, 0], lower_bound[i, 0]] for i in range(n_points)]
)
verticesUpperBound = ot.Sample(
    [[sample_grid[i, 0], upper_bound[i, 0]] for i in range(n_points)]
)
n_test = verticesLowerBound.getSize()
polyData = [
    [
        verticesLowerBound[i],
        verticesLowerBound[i + 1],
        verticesUpperBound[i + 1],
        verticesUpperBound[i],
    ]
    for i in range(n_points - 1)
]
polygonList = [
    ot.Polygon(polyData[i], transparentFillColor, transparentFillColor)
    for i in range(n_points - 1)
]
boundsPoly = ot.PolygonArray(polygonList)
graph.add(boundsPoly)
view = otv.View(graph)
```

Here is the result.
![image](https://user-images.githubusercontent.com/31351465/207408581-be704826-6102-49c2-9ac0-145939a065c5.png)

We see that the edges of each of the 20 polygons are printed. Since these edges get crossed over, there are unwanted lines in the plot. When I save the file into a PDF with:
```python
view.getFigure().savefig("filename.pdf", bbox_inches="tight")
```
and open the file using Inkscape, I can see the "Contour" of each Polygon:

![image](https://user-images.githubusercontent.com/31351465/207409835-75412a70-f212-4b72-a65d-0667ddda1da5.png)

When I disable the edges with Inkscape, I get the expected rendering.
In the API of the `PolygonArray` I do not see any method which configure the width of the edges. This seems like a useful evolution to me because that would allow to print nice confidence intervals.

**Comment by regislebrun** [comment]
You can get what you want by passing the relevant kwargs to the viewer. Replace the last line of your script by:
```
otv.View(graph, polygoncollection_kw={'edgecolor':"none"})
```
and you get:

![Figure_1](https://user-images.githubusercontent.com/8220933/207459322-b4864960-42b0-405c-a24e-11de04f1d6b2.png)

IMO this behavior should be triggered by setting the line width to zero, which is unfortunately rejected by `DrawableImplementation::setLineWidth()`...

**Comment by mbaudin47** [comment]
Thank you Régis for the trick: it works perfectly. Actually, I tried to use `setLineWidth()`, but this failed as you pointed:
```python
boundsPoly.setLineWidth(0.0)
```
produces:
```
TypeError: InvalidArgumentException : Given line width=0 is incorrect
```

**Comment by mbaudin47** [comment]
It seems that the keyword has no effect within a `GridLayout`. For example, consider the following script which creates a `GridLayout` containing the same graph twice. 
```python
#
grid = ot.GridLayout(1, 2)
grid.setGraph(0, 0, graph)
grid.setGraph(0, 1, graph)
view = otv.View(
    grid,
    figure_kw={"figsize": (10.0, 3.0)}, 
    polygoncollection_kw={'edgecolor':'none', 'linewidth':0}
)
```
It produces:

![image](https://user-images.githubusercontent.com/31351465/209447447-dac7b95a-80ce-4864-87a0-648ab221b737.png)

We see that the edges are here, again.
