### ISSUE TITLE
Switching to primesieve 11

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2207]
Hello,

Recently, the version of primesieve in Debian suddenly rose to 11, and there are changes in the interface that affect openturns (well, in fact, just one).

The attached patch makes the needed correction, hopefully it will help you a bit when you switch to primesieve 11 to build OT.

Best,
Pierre

[primesieve11.txt](https://github.com/openturns/openturns/files/10249942/primesieve11.txt)

**Comment by jschueller** [comment]
see https://github.com/openturns/openturns/issues/2204

**Comment by pgrt** [comment]
Hi Julien,

Oops, sorry for the duplicate issue!

Cheers,
Pierre
