### ISSUE TITLE
Missing 1.19.post1 package for python 3.7 on windows

### ISSUE THREAD

**Issue by AntoineD** [openturns/openturns#2214]
Hello,

we automatically pin the dependencies of our projects to have the most reproducible environments, and we do it for each version of python we support.
We define those pinned dependencies on linux because windows brings dependencies that do not exist on other platforms.

For python 3.7, openturns provides the version 1.19.post1 on linux but not on windows, this forces us to hand change the requirements.

Would it be possible to provide the 1.19.post1 version for python 3.7 also on windows?

**Comment by jschueller** [comment]
cant you just pin to 1.19* with: "openturns>=1.19,<1.20" ?

**Comment by AntoineD** [comment]
We support `openturns >=1.16,<1.21`.

**Comment by jschueller** [comment]
no I mean on pypi openturns "1.19" does provide 3.7 for windows, unlike "1.19.post1", so pinning to 1.19* your ci env should make linux and windows resolve a compatible version

**Comment by AntoineD** [comment]
We use [`pip-compile`](https://pip-tools.readthedocs.io/en/latest/) to automatically create the requirement files with the pinned dependencies, we have only one package that depends on openturns but this one package is a dependency of a bunch of other packages which do not directly depend on openturns so fixing this can only be done manually for about 20 packages. That would be very kind if you could just provide the missing build.

**Comment by jschueller** [comment]
sorry, that wont be possible, we dont store the exact same build environment of past releases

**Comment by AntoineD** [comment]
Thank you, I understand. For the future releases it would be awesome if you could provide the builds of a version for all the platforms.
