### ISSUE TITLE
Missing HAVE_CSTDDEF definition in order to build against coinor-bonmin

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2215]
Hello,

I tried to build openturns against coinor-bonmin which is now in Debian, and got

```
In file included from /usr/include/coin/IpJournalist.hpp:15,
                 from /usr/include/coin/IpException.hpp:13,
                 from /usr/include/coin/BonTMINLP.hpp:19, 
                 from /<<PKGBUILDDIR>>/lib/src/Base/Optim/openturns/BonminProblem.hxx:29,
                 from /<<PKGBUILDDIR>>/lib/src/Base/Optim/Bonmin.cxx:28:
/usr/include/coin/IpSmartPtr.hpp:18:4: error: #error "don't have header file for stddef"
   18 | #  error "don't have header file for stddef"
      |    ^~~~~
```

so that I adopted the enclosed patch to do the same thing as in
    lib/src/Base/Optim/openturns/IpoptProblem.hxx
in the current  OpenTURNS source.

[ipopt_preprocessor_macro.txt](https://github.com/openturns/openturns/files/10416782/ipopt_preprocessor_macro.txt)

Now the build runs well.

Best,
Pierre

**Comment by jschueller** [comment]
hi Pierre,
I believe you need
https://github.com/openturns/openturns/commit/b09028adec3aff942e601e0a894669c3d833e3dc

**Comment by pgrt** [comment]
Hi Julien,

I am late on this, like for primesieve a few weeks ago, seeing only the last tagged version... thanks for drawing my attention on this commit then! :-D

Best,
Pierre
