### ISSUE TITLE
C++ Bonmin test failed

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2223]
I compiled and installed the latest version of Bonmin (1.8.8, found [here](https://www.coin-or.org/download/source/Bonmin/). The configuration and compilation generate no error, but the C++ test fails with the following output:
```
class=Bonmin
algorithm=B-BB
options=
mu_oracle=loqo

terminate called after throwing an instance of 'OT::InternalException'
  what():  Bonmin solver exited with status MINLP_ERROR
Abandon (core dumped)
```
Any clue on how to fix it?

**Comment by jschueller** [comment]
do you have the required metis/mumps/ipopt dependencies ?
if not, you can refer to this script:
https://github.com/openturns/docker-images/blob/master/manylinux2014_x86_64/Dockerfile#L23

**Comment by regislebrun** [comment]
@jschueller thanks, it works, but unfortunately OpenBlas is not included in the list so some of the computations take much longer to execute when I am in the validation step... But at least I can generate the documentation, thanks!
