### ISSUE TITLE
Unary minus for distribution

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2229]
It seems that the unary minus does not exist for a distribution. The following script:
```Python
u = ot.WeibullMax()
s = u ** 2
n = -s
```
produces:
```
TypeError: bad operand type for unary -: 'Distribution'
```
If I replace `-s` with `0 - s`, then the codes works.

**Comment by jschueller** [comment]
see https://github.com/openturns/openturns/pull/1157
