### ISSUE TITLE
KrigingAlgorithm with 2 outputs

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2241]
From openturns 1.20, I am no longer able to instantiate a `KrigingAlgorithm` with 2 outputs with the code below, inspired [from the doc](https://openturns.github.io/openturns/latest/user_manual/response_surface/_generated/openturns.KrigingAlgorithm.html). I get the message error:
```
Traceback (most recent call last):
  File "...\my_script.py", line 12, in <module>
    algo = ot.KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
  File "...\lib\site-packages\openturns\metamodel.py", line 5119, in __init__
    _metamodel.KrigingAlgorithm_swiginit(self, _metamodel.new_KrigingAlgorithm(*args))
TypeError: InvalidArgumentException : Covariance model output dimension is 1, expected 2
```

This code worked with openturns 1.19 (I could run the `KrigingAlgorithm`, get the metamodel and evaluate the latter). Has the API changed? Is there a new way to set a covariance model shared by the different outputs? Something similar to [this example](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_multioutput_firesatellite.html#sphx-glr-auto-meta-modeling-kriging-metamodel-plot-kriging-multioutput-firesatellite-py) using `TensorizedCovarianceModel` (the reason of this choice in this example is to have separate covariance models, which is not the case in my reproducer)?

# Reproducer

```python
import openturns as ot

f = ot.SymbolicFunction(["x"], ["x * sin(x)", "sin(x)"])
sampleX = [[1.0], [2.0], [3.0], [4.0], [5.0], [6.0], [7.0], [8.0]]
sampleY = f(sampleX)

basis = ot.Basis(
    [ot.SymbolicFunction(["x"], ["x"]), ot.SymbolicFunction(["x"], ["x^2"])]
)
covarianceModel = ot.SquaredExponential([1.0])
covarianceModel.setActiveParameter([])
algo = ot.KrigingAlgorithm(sampleX, sampleY, covarianceModel, basis)
```

**Comment by jschueller** [comment]
yes, now input/output dimension of the cov model must explicitely match the sample dimensions
(this logic was previously hidden to the user)
in your case that is a TensorizedCovarianceModel indeed

**Comment by mdelozzo** [comment]
Thanks for your quick reply! I will modify my code. Regarding `covarianceModel.setActiveParameter([])`, I couldn't find a clear explanation of what it does. Could you give me the meaning of this method please? And what is an active parameter?

**Comment by jschueller** [comment]
it allows to choose which (hyper) parameters are optimized

**Comment by jschueller** [comment]
that's a bug: maybe GLM assumes the scale must be of size dimension, but in TensorizedCovarianceModel that's a scalar

**Comment by sofianehaddad** [comment]
Strange, seems that setting `ot.ResourceMap.SetAsBool("GeneralLinearModelAlgorithm-UseAnalyticalAmplitudeEstimate", False)` fixes the issue.

However I am convinced (or pretty sure) that the problem is we assume the collection's size to be > 1.

As an example, have a look at [this](https://github.com/openturns/openturns/blob/master/lib/src/Base/Stat/TensorizedCovarianceModel.cxx#L240)
