### ISSUE TITLE
HSIC Target sensitivity bad filtering

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/openturns#2250]
As we have no distinction between `filtered` and `unfiltered` samples (see [the corresponding code](https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorTargetSensitivity.cxx#L44)) in `HSICEstimatorTargetSensitivity`, then applying the `setFilterFunction` method (see [the corresponding code](https://github.com/openturns/openturns/blob/master/lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorTargetSensitivity.cxx#L83) consists in applying `newFilter o oldFilter (originalData)`

**Comment by sofianehaddad** [comment]
@JPelamatti @regislebrun @jschueller see 1b7dc10d1d6758b58fd271fa0ae0f3e0f4ef4695 for fixes

**Comment by JPelamatti** [comment]
Oh you are right, nice catch !
