### ISSUE TITLE
Viewer() raises error keyword grid_b is not recognized

### ISSUE THREAD

**Issue by Not-a-Penguin** [openturns/openturns#2269]
Trying to instantiate the  Viewer() with a sample raises an error in line 299 of viewer.py: `ValueError: keyword grid_b is not recognized; `

Commenting the line seems to solve the issue.

**Comment by jschueller** [comment]
yes, this was already fixed in https://github.com/openturns/openturns/issues/2240, the solution was to drop the keyword
