### ISSUE TITLE
Legend location with grid layout

### ISSUE THREAD

**Issue by Gatienn** [openturns/openturns#2297]
I'm having difficulties setting the legend location with the grid layout.
What I want to do is to use a different legend location for each graph , such as "topright" for graph1 and "bottomright" for graph2.

The issue is that plotting these graphs within a grid layout will force all the legend locations to be "topright" : as a result the legend locations defined with each graph are ignored.

![image](https://user-images.githubusercontent.com/82940508/236488841-21d080f0-e10f-420f-a32d-e2d1b800dc13.png)

I think that the legend location (defined explicitly or by default) of the grid layout prevails on those of the subgraphs.

Thank you in advance,
Gatien

**Comment by Gatienn** [comment]
![image](https://user-images.githubusercontent.com/82940508/236492348-67cb0a07-31b7-4720-8aff-6519d205cffe.png)

Here is the same script except that I set the legend location of the grid layout to "upper left" explicitly. 
It highlights that the grid layout legend location comes before the others.

**Comment by jschueller** [comment]
hi, could you post the code as plain text instead of images ?

**Comment by Gatienn** [comment]
Here's the code : 

import openturns as ot
import openturns.viewer as otv

x = [1,2,3,4,5]
y = [3,1,4,1,5]
y1 = [6,0,2,2,1]

grid = ot.GridLayout(1,2)

graph = ot.Graph("titre", "x", "y", True, "topright")
cloud = ot.Cloud(x,y)
cloud.setLegend("test")
graph.add(cloud)
grid.setGraph(0, 0, graph)

graph = ot.Graph("titre1", "x", "y1", True, "bottomright")
cloud = ot.Cloud(x,y)
cloud.setLegend("test")
graph.add(cloud)
grid.setGraph(0, 1, graph)

otv.View(grid)
