### ISSUE TITLE
Negative value given by computeProbability 

### ISSUE THREAD

**Issue by IBM86** [openturns/openturns#2304]
import numpy as np
import openturns as ot

mean=np.array([2,3])

cov=np.array([[4,-1],[-1,2]])

distrib = ot.Normal(mean, ot.CovarianceMatrix(cov))

prob=distrib.computeProbability(ot.Interval([-1,94.2], [4.85,1],[False,True],[True,False]))

print(prob)

**Comment by jschueller** [comment]
ok in master, maybe fixed by #2159
