### ISSUE TITLE
1.20 & python 36 windows

### ISSUE THREAD

**Issue by nitawa** [openturns/openturns#2308]
Dear developers, 
I  can see that openturns 1.20 (pip wheel) is not supporting python 3.6.
I can of course, starting from the  run_docker_build.sh script shipped with the sources archives, try to build it with mingw, but I am wondering whether you already tried to build it natively on windows with cmake + msbuild. 
If so do you have some uptodate documentation, I can try to follow ?

Thanks for your valuable feedback.
PS: I raise this question, because some dependencies  like openBLAS can already be built with visual c++ 2017 out of the box.

**Comment by jschueller** [comment]
yes it should work, look at the developer doc:
http://openturns.github.io/openturns/latest/developer_guide/windows_native_port.html
