### ISSUE TITLE
v1.21rc1 doesn't find IpOpt headers

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#2310]
On my box (Linux Mageia 8), IpOpt is detected using the library location:
```
//Details about finding Ipopt
FIND_PACKAGE_MESSAGE_DETAILS_Ipopt:INTERNAL=[/home/maison/local/lib/libipopt.so][/home/maison/local][v()]
```
but the path for the headers `/home/maison/local/include/coin` is not set. I have to change `#include <IpTNLP.hpp>` into `#include <coin/IpTNLP.hpp>` in IpoptProblem.hxx and `#include <IpIpoptApplication.hpp>` into `#include <coin/IpIpoptApplication.hpp>` to fix it.

**Comment by jschueller** [comment]
I dont think you need that as IPOPT_INCLUDE_DIR can be set to "/home/maison/local/include/coin" if needed

**Comment by jschueller** [comment]
I need more infos, so you installed ipopt in a non-sytem directory, but then what options did you  you pass to cmake ?

**Comment by mbaudin47** [comment]
Any news on this topic?
