### ISSUE TITLE
Minor wording issues in the cross entropy importance sampling example

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#2323]
Some minor wording issues / typos I noticed in this [example](http://openturns.github.io/openturns/master/auto_reliability_sensitivity/reliability/plot_crossentropy.html)

- margin(s) should be marginal distribution(s) or marginal(s) 
- standard space is missing an article 'the' at a few locations in the text
- For more advanced use -> For a more advanced usage

I might have missed other stuff.
Cheers

**Comment by jschueller** [comment]
cc @m-balesdent @l-brevault
