### ISSUE TITLE
Sobol sensitivity analysis for field output

### ISSUE THREAD

**Issue by jacktang** [openturns/openturns#2324]
Hello there

I want to do some (global) sensitivity analysis using sobol index. The problem contains 4 parameters and output is one field (2d space and 1134 points). I've tried Sobol, and it thrown the error:

```
----> [2] sensitivityAnalysis = ot.SaltelliSensitivityAlgorithm(inputDesign, outputDesign, size)

File (~/miniconda3/envs/dev/lib/python3.10/site-packages/openturns/simulation.py:2058), in SaltelliSensitivityAlgorithm.__init__(self, *args)
   2057 def __init__(self, *args):
-> 2058     _simulation.SaltelliSensitivityAlgorithm_swiginit(self, _simulation.new_SaltelliSensitivityAlgorithm(*args))

TypeError: InvalidArgumentException : Sobol experiment is too small (500 vs 600)
```
How can I fix it?

**Comment by jschueller** [comment]
it looks that the inputDesign/outputDesign samples sizes does not match the original Sobol size
did you use SobolIndicesExperiment ?
if not, refer to:
https://openturns.github.io/openturns/latest/auto_reliability_sensitivity/sensitivity_analysis/plot_sensitivity_sobol.html
