### ISSUE TITLE
A sign mistake in FGM document

### ISSUE THREAD

**Issue by WissenY** [openturns/openturns#2327]
I found that the FGM implementation is different from the conventional form that

>  $C(u_1, u_2) = u_1 u_2 (1- \theta (1 - u_1)(1 - u_2))$

This appears on the [website](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.FarlieGumbelMorgensternCopula.html#openturns.FarlieGumbelMorgensternCopula.computePDF:~:text=The%20FarlieGumbelMorgenstern%20copula%20is%20defined%20by%20%3A) and [openturns](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23)/[python](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23/python)/[src](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23/python/src)/FarlieGumbelMorgensternCopula_doc.i.in. But I found that the code implementation is using form 

> $C(u_1, u_2) = u_1 u_2 (1 +  \theta (1 - u_1)(1 - u_2))$

The sign before  $\theta$ is $+$ in [openturns](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23)/[lib](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23/lib)/[src](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23/lib/src)/[Uncertainty](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23/lib/src/Uncertainty)/[Distribution](https://github.com/openturns/openturns/tree/c7214fc78ad44300d37eb37ed6f28a64387efc23/lib/src/Uncertainty/Distribution)/FarlieGumbelMorgensternCopula.cxx. I think it would be better that the doc is revised as the form used in code.

**Comment by jschueller** [comment]
indeed, thanks
