### ISSUE TITLE
HSIC with large amount of data makes crash

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2338]
Hi folks, 

I would like to try HSIC on a dimensional problem. To do so, I tried to use the reliability problem 202 of the reliability benchmark [RPrepo ](https://rprepo.readthedocs.io/en/latest/reliability_problems.html#rp202). 

This problem has an input dimension of 225 and a scalar output.

I generated 10 000 samples of input / output data. These data can be downloaded [here](https://github.com/m-balesdent/openturns_debug_files/blob/main/data_beam.p).

When I tried to perform HSIC with a sample of size 1000 (`n_samples` in the following code), the code works fine. 

When the sample size is set to a number lower than the input dimension, the python kernel crashes and the error is : 
`/usr/x86_64-w64-mingw32/include/c++/12.2.0/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = OT::CovarianceMatrix; _Alloc = std::allocator<OT::CovarianceMatrix>; reference = OT::CovarianceMatrix&; size_type = long long unsigned int]: Assertion '__n < this->size()' failed.`

Furthermore, when the number of samples is quite large (e.g. 2000), I have `File "...\Python39\site-packages\openturns\uncertainty.py", line 1969, in __init__
    _uncertainty.HSICEstimatorGlobalSensitivity_swiginit(self, _uncertainty.new_HSICEstimatorGlobalSensitivity(*args))
RuntimeError: std::bad_alloc`

This is the code that reproduces the errors.

```
import openturns as ot
import pickle
data = pickle.load(open('data_beam.p','rb'))
n_samples = 1000
sampleX = data['sampleX'][0:n_samples]
sampleY = data['sampleY'][0:n_samples]
dim = sampleX.getDimension()

covarianceModelCollection = []
for i in range(dim):
    Xi = sampleX.getMarginal(i)
    inputCovariance = ot.SquaredExponential(1)
    inputCovariance.setScale(Xi.computeStandardDeviation())
    covarianceModelCollection.append(inputCovariance)
   
outputCovariance = ot.SquaredExponential(1)
outputCovariance.setScale(sampleY.computeStandardDeviation())
covarianceModelCollection.append(outputCovariance)    
estimatorType = ot.HSICUStat()
globHSIC = ot.HSICEstimatorGlobalSensitivity(covarianceModelCollection, sampleX, sampleY, estimatorType)
```

**Comment by jschueller** [comment]
now you can set HSICEstimator-InputCovarianceMatrixCacheSizeMb in the resource map with 2000 for a 2gb limit
