### ISSUE TITLE
4th order iterative moment (Kurtosis) not matching Scipy

### ISSUE THREAD

**Issue by robcaulk** [openturns/openturns#2345]
Hello, 

I tested your IterativeMoments library against non-iterative calculations in Scipy, and found a discrepancy for the 4th order (Kurtosis):

```python
import openturns as ot
import scipy.stats as stats
import numpy as np

np.random.seed(1234)
# generate 100 random numbers from normal distribution
sample = np.random.normal(0, 1, 500)
mean = np.mean(sample)
variance = np.var(sample,ddof=1)
skewness = stats.skew(sample, bias=False)
kurtosis = stats.kurtosis(sample, bias=False)

ot_iter = ot.IterativeMoments(4, 1)
for x in sample :
    ot_iter.increment(ot.Point([x]))

print(f"Scipy: {kurtosis}, OpenTurns: {ot_iter.getKurtosis()[0]}")
```

Which prints 

```
Scipy: 0.16621066135050455, OpenTurns: 3.1662106613504966
```

I have also implemented the same iterative higher moments method following https://arxiv.org/pdf/1510.04923.pdf, which is apparently the same reference shown in the OpenTurns source [here](https://github.com/openturns/openturns/blob/8e2b86c7ec741b152b5629a9e98d160295bb8031/lib/src/Base/IterativeStat/IterativeMoments.cxx#L183), you can find our custom implementation [here](https://github.com/IterativeStatistics/BasicIterativeStatistics/pull/21).

Our implementation yields identical results as OpenTurns (equally wrong :-) ).

**Comment by KieranDelamotte** [comment]
Maybe #1929 is relevant. 
cc @mbaudin47

**Comment by KieranDelamotte** [comment]
With `kurtosis = stats.kurtosis(sample, bias=False, fisher=False)` you get the same result as OT.

**Comment by robcaulk** [comment]
Thanks for looking into this, that is great news!

**Comment by jschueller** [comment]
scipy computes the kurtosis excess and OT the "regular" kurtosis
