### ISSUE TITLE
dsfmt 2.x ?

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2350]
it seems we use dsfmt 1.x from 2008

there is a much newer version at https://github.com/MersenneTwister-Lab/dSFMT, but the algo changes and we would have to modify most test outputs as the realizations change too
[dsfmt2.txt](https://github.com/openturns/openturns/files/11905583/dsfmt2.txt)
this version supports to give samples in batches

if speed is not a concern there is also a mersenne twister in the c++ standard library:
https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine

note: currently dsfmt sse2 is disabled (but the speedup is very small) in simd.h
https://github.com/openturns/openturns/blob/master/lib/src/Base/Stat/simd.h#L7

**Comment by regislebrun** [comment]
Is the new version worse the change? Is it significantly faster than the current one or does it solve a bug?
The two main advantages of dsfmt wrt the standard implementation are the speed  and the different cycles (not used by OT, a shame ;-)). If the version in the C++ library is essentially as fast as dsfmt, it may be a good thing to switch to this version.

**Comment by jschueller** [comment]
it's not as fast as I remember: STL<DSFMT1<DSFMT2 in terms of speed

**Comment by jschueller** [comment]
another aspect I didnt think of is that dsfmt 1.x generates 32 bit ints, and then we convert that to double, maybe we should use a proper 64 bits generator

**Comment by jschueller** [comment]
nowaday the standard seems to be PGC64, also used by numpy

**Comment by jschueller** [comment]
see #1765
