### ISSUE TITLE
IterativeThresholdExceedance

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2354]
Hello,
I'm estimating probabilities with `IterativeThresholdExceedance` and I have question: would it be possible to add an option, e.g. `includeThreshold`, to count the number of times the threshold is reached or exceeded (and not only exceeded)? In order to estimate $\mathbb{P}[X\geq t]$, and not only $\mathbb{P}[X > t]$. Or is there another technique I haven't seen?

**Comment by jschueller** [comment]
hi @mdelozzo, indeed it computes $\mathbb{P}[X > t]$
maybe a ComparisonOperator could be used in this class to get the desired behavior
but maybe you can work around with a well chosen $\mathbb{P}[X > t - \epsilon]$ ?

**Comment by mdelozzo** [comment]
yes, clearly, I'm doing very well with this workaround at the moment.

Another question: would it be possible to add a class `IterativeProbability ` instead of letting the user calculate it by hand with `getThresholdExceedance` and `getIterationNumber`?

**Comment by jschueller** [comment]
It can be a new method in that same class
