### ISSUE TITLE
GPU Acceleration for large datasets?

### ISSUE THREAD

**Issue by kevindarby** [openturns/openturns#2356]
Hi, 

Is there a plan for this project to include GPU acceleration for marginal / copula fitting on large data sets?

Thanks,

Kevin

**Comment by jschueller** [comment]
hi, we have nothing planned specifically about inference performance right now, but feedback/improvements are always welcome

**Comment by jschueller** [comment]
please use our forums for questions like this in the future

**Comment by mbaudin47** [comment]
Is there any specific use case that is too slow in your opinion? Can you share some minimal code that reveals the issue?
