### ISSUE TITLE
The Sample help page does not show how to set a column

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2359]
In the help page:
https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Sample.html
there is no example which shows how to set a column of a Sample:
```python
import openturns as ot
sample[:, 0] = column  # where column is a Sample or a Point
```

In [the example](https://openturns.github.io/openturns/latest/auto_data_analysis/manage_data_and_samples/plot_quick_start_point_and_sample.html#the-sample-class), this is not shown.

**Comment by mdelozzo** [comment]
In [the example you mention](https://openturns.github.io/openturns/latest/auto_data_analysis/manage_data_and_samples/plot_quick_start_point_and_sample.html#the-sample-class), this is shown in the section [Get a row or a column of a Sample](https://openturns.github.io/openturns/latest/auto_data_analysis/manage_data_and_samples/plot_quick_start_point_and_sample.html#get-a-row-or-a-column-of-a-sample) with the sentence _Slicing can also be used to set..._. This section could stop just before this sentence and new section could start with the title _Set a row or a column of a Sample_.

**Comment by mbaudin47** [comment]
You are right: thank you for pointing this.

There is, however, a subtle point which is not presented in this example: to set a column from a list of floats, we can use `BuildFromPoint`. I also add this.
