### ISSUE TITLE
Conda install on Windows: cannot import OpenTURNS

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#2360]
Hi! A Windows user sent me the following error:

```
import openturns as ot

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\AppData\Local\miniforge3\lib\site-packages\openturns\__init__.py", line 49, in <module>
    from .common import *
  File "C:\Users\...\AppData\Local\miniforge3\lib\site-packages\openturns\common.py", line 12, in <module>
    from . import _common
ImportError: DLL load failed while importing _common: La procédure spécifiée est introuvable.
```

This user did a fresh install of Miniforge3 for Windows: https://github.com/conda-forge/miniforge/releases/download/23.1.0-3/Miniforge3-23.1.0-3-Windows-x86_64.exe

On this fresh install, he ran the command to install openturns and pandas:

```
conda install openturns pandas
```

After the install (which reported no error), Pandas could be imported, but OpenTURNS could not (see error message above).

**Comment by josephmure** [comment]
Note that this user was in the end able to install and import OpenTURNS, but had to use pip.

**Comment by amole-arup** [comment]
I have also had this problem with openturns in a micromamba environment. I installed everything using micromamba from conda-forge channel (including openturns). It only occurs when importing in a Spyder console. I haven't had any problem when using VS Code.

![image](https://github.com/openturns/openturns/assets/77268469/4b7d7a5a-a18d-4d77-9473-3ce21a8de3bf)

**Comment by jschueller** [comment]
yep, this is due to a conflict with numpy (and scipy) mingw runtime

a workaround is to use numpy binary from pip:
`pip install numpy scipy --force-reinstall --no-deps`

**Comment by amole-arup** [comment]
Are you saying that it is a conflict between Spyder and NumPy? If you are talking about a direct conflict, then it does not make sense to me because I didn't have any errors when I imported when using VS Code (see screen capture). The environment is exactly the same as the one where I had an import error above.

![image](https://github.com/openturns/openturns/assets/77268469/bfb35e1d-a7a6-46d3-9146-fe52bcfd296d)

**Comment by jschueller** [comment]
no between openturns and numpy/scipy

**Comment by amole-arup** [comment]
That seems to be a strange behaviour by Spyder. Why would it pull in a different version of NumPy than the one provided in the Environment?

**Comment by antonio-canavate** [comment]
Hi @jschueller, I have just tried and it works perfectly.

Thanks a lot

Best

Toni

**Comment by jschueller** [comment]
cf https://github.com/conda-forge/openturns-feedstock/issues/186
