### ISSUE TITLE
Inconsistency in the documentation of KrigingAlgorithm

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2361]
- The documentation of `KrigingAlgorithm.setOptimizationAlgorithm` uses the name `solver` in the signature and `algorithm` in the docstring, which is inconsistent.
- The documentation of `KrigingAlgorithm.setMaximumEvaluationNumber` uses the name `maximumEvaluationNumber` in the signature and `N` in the docstring, which is inconsistent. `KrigingAlgorithm.getMaximumEvaluationNumber` uses `N`.
- The documentation of `KrigingAlgorithm.setMaximumIterationNumber` uses the name `maximumIterationNumber` in the signature and `N` in the docstring, which is inconsistent. `KrigingAlgorithm.getMaximumIterationNumber` uses `N`.
- The documentation of `KrigingAlgorithm.setOptimizationBounds` uses the name `optimizationBounds` in the signature and `bounds` in the docstring, which is inconsistent. `KrigingAlgorithm.getMaximumIterationNumber` uses `N`.
- The docstring of `KrigingAlgorithm.setMaximumIterationNumber` has a rendering bug.
- In the docstring of the object returned by `KrigingAlgorithm.getOptimizationBounds`, the name is `problem` instead of `bounds` of `optimization_bounds`.

**Comment by mbaudin47** [comment]
I read [KrigingAlgorithm](http://openturns.github.io/openturns/latest/user_manual/response_surface/_generated/openturns.KrigingAlgorithm.html) and i try to spot the issues.

![image](https://github.com/openturns/openturns/assets/31351465/ec1481a0-3b14-41e8-bce9-8f923511790d)

- You write: "_The documentation of KrigingAlgorithm.setMaximumEvaluationNumber uses the name maximumEvaluationNumber in the signature and N in the docstring, which is inconsistent. KrigingAlgorithm.getMaximumEvaluationNumber uses N._" I cannot see that method. But it is a method of optimization algorithms such as `MultiStart` for example. Can you point the issue more precisely please?
- You write: "_The documentation of KrigingAlgorithm.setMaximumIterationNumber uses the name maximumIterationNumber in the signature and N in the docstring, which is inconsistent. KrigingAlgorithm.getMaximumIterationNumber uses N._". Idem.

**Comment by mbaudin47** [comment]
After bug fix:

![image](https://github.com/openturns/openturns/assets/31351465/23133b4c-8305-484d-97fe-b7a71dc2b9e5)

![image](https://github.com/openturns/openturns/assets/31351465/3fd185ed-e225-4f36-99ca-7cfa1aa2e64f)

![image](https://github.com/openturns/openturns/assets/31351465/23286ace-9546-4ff5-b3df-c3ff2b4dd770)

**Comment by mbaudin47** [comment]
I see:

![image](https://github.com/openturns/openturns/assets/31351465/972864d2-516e-4e80-94d5-1babb55471ed)

**Comment by mbaudin47** [comment]
**After** bug fix:

![image](https://github.com/openturns/openturns/assets/31351465/f1c49864-c7e9-4d6f-83db-65f525dd54bb)

![image](https://github.com/openturns/openturns/assets/31351465/cb15efa0-509e-41d3-997c-22129b9f5484)

**Comment by mdelozzo** [comment]
Thanks, @mbaudin47, for these fixes!
