### ISSUE TITLE
The optimizers are subclasses of OptimizationAlgorithmImplementation

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2362]
In the documentation of `KrigingAlgorithm.setOptimizationAlgorithm`, we can read that the type of `algorithm` is `OptimizationAlgorithm` instead of `OptimizationAlgorithmImplementation`:

```python
from openturns import TNC
from openturns import OptimizationAlgorithmImplementation
from openturns import OptimizationAlgorithm

assert issubclass(TNC, OptimizationAlgorithm)
# False

assert issubclass(TNC, OptimizationAlgorithmImplementation)
# True
```

The same problem appears in the documentation of `OptimizationAlgorithm`, with the class docstring _"Base class for optimization wrappers."_ and the note _"Class [OptimizationAlgorithm](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.OptimizationAlgorithm.html#openturns.OptimizationAlgorithm) is an abstract class, which has several implementations. The default implementation is [Cobyla](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Cobyla.html#openturns.Cobyla)"_

What is the link between `OptimizationAlgorithm` and `OptimizationAlgorithmImplementation`?

Other remark: the constructor `OptimizationAlgorithm()` seems to be available, e.g. `KrigingAlgorithm.setOptimizationAlgorithm(TNC())`.

**Comment by sofianehaddad** [comment]
Let us say that from a `python` interface and for `users`, they are the same!

There is a mechanism that make the `OptimizationAlgorithm` (called `interface` class) a kind of `smart pointer` to the implementations. So algorithms (`TNC`, `Cobyla` & others) inherit from `implementation` (`OptimizationAlgorithm`) with all specifics/generics methods. The algorithms in `openturns` usually require the `interface` class. There is a mechanism that internally makes a transfo when we provide implementations such as `TNC` (or we could provide `ot.OptimizationAlgorithm(ot.TNC())`)
You have this pattern `implementation/interface` in mainly all classes (`Distribution` for example ) --> `Distribution()` provides a `Uniform()`

**Comment by mdelozzo** [comment]
Oh yes, I see... The famous _bridge_ pattern. I read about it few months ago. Thanks for your explanation, and maybe it's time for me to read again about design patterns :-)

My problem is that I have a function 
```python
def f(implementation_name: str):
    # instantiate implementation and do something with
```
and I would like to easily instantiate the implementation. In the case of optimizers, I had in mind to create a dictionary `d = {cls.__name__: cls for cls in OptimizationAlgorithmImplementation.__subclasses__}` and then get `cls = d[implementation_name]`. Is there a better way to do that (from `OptilizationAlgorithm` typically) or do you think that it's good?

Other point: when using the type annotation `def f(algorithm: OptimizationAlgorithm = TNC())`, I think that the type checkers will raise an error because `TNC` does not inherit from `OptimizationAlgorithm`. This is a case where the use of `OptimizationAlgorithmImplementation` can be important.

**Comment by jschueller** [comment]
look at the `OptimizationAlgorithm.Build` method that instanciates each solver by its name:
https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.OptimizationAlgorithm.html#openturns.OptimizationAlgorithm.Build

**Comment by mdelozzo** [comment]
Thanks, @jschueller and @sofianehaddad, for your answers. I didn't know this method and will try to used it. I close this issue for the moment.
