### ISSUE TITLE
KrigingAlgorithm: examples set bounds before disabling optimization

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2364]
Several examples of `KrigingAlgorithm` ([here](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_hyperparameters_optimization.html) and [there](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_multioutput_firesatellite.html#sphx-glr-auto-meta-modeling-kriging-metamodel-plot-kriging-multioutput-firesatellite-py), and perhaps elsewhere) set the optimization bounds of the covariance model parameters with `setOptimizationBounds` but disables their optimization with `setOptimizeParameters(False)`. Is it on purpose? If so, what is the meaning of this?

**Comment by sofianehaddad** [comment]
Thanks for reporting. 
The second example ([this one](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_multioutput_firesatellite.html#sphx-glr-auto-meta-modeling-kriging-metamodel-plot-kriging-multioutput-firesatellite-py)) should be updated. I think the issue has been introduced by... me when trying to debug the multivariate kriging. I will fix it
For the first one, it illustrates many situations (optim on with user defined bounds, optim off..) Maybe the example is too much complex and should/might be reworked. @mbaudin47 could you have a look on that please? many thanks again

**Comment by mbaudin47** [comment]
Now I can see your point in [this one](https://openturns.github.io/openturns/latest/auto_meta_modeling/kriging_metamodel/plot_kriging_hyperparameters_optimization.html):

![image](https://github.com/openturns/openturns/assets/31351465/3cbbe2c6-cb03-4f77-ac9d-1b59ea24da76)

**Comment by mdelozzo** [comment]
Thanks, @mbaudin47 and @sofianehaddad, for your fixes.
