### ISSUE TITLE
which version of otsvm to use with openturns 1.21

### ISSUE THREAD

**Issue by nitawa** [openturns/openturns#2393]
### What happened?

Dear developers,
At this link: [openturns 1.21](https://github.com/openturns/otconda/releases), one can read that one should use otsvm 0.11 with openturns 1.21. Is this really this tag which was used ?

I'm raising this question, because in `lib/src/LibSVMRegression.cxx `(line 47), the `MetaModelResult` is missing some arguments.
`   result_ = MetaModelResult(Function(), metaModel, residuals, relativeErrors);`

But the declaration says:
```
  MetaModelResult(const Sample & inputSample,
                  const Sample & outputSample,
                  const Function & metaModel,
                  const Point & residuals,
                  const Point & relativeErrors);
```
Thanks for your valuable feedback.

### How to reproduce the issue?

```shell
compile ot
```

### Version

1.21

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
its a mistake: it should be 0.12

**Comment by jschueller** [comment]
others ok except otmorris which should be 0.14

**Comment by jschueller** [comment]
yes, this one I did not update for a while
