### ISSUE TITLE
KrigingAlgorithm fails if basis is empty

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/openturns#2403]
### What happened?

If we provide an empty basis to the kriging algorithm, it fails!

We also need to have a ctor without he `basis` argument

### How to reproduce the issue?

```shell
ot.RandomGenerator.SetSeed(0)
model = ot.AbsoluteExponential()
size = 15
x = ot.Normal().getSample(size)
y = x + ot.Normal(0, 0.01).getSample(size)
algo = ot.KrigingAlgorithm(x, y, model, ot.Basis())
algo.run()
```

### Version

1.21

### Operating System

all

### Additional Context

The bug is recent (`1.21`) and not appearing in oldest versions

**Comment by jschueller** [comment]
I dont understand: this was not allowed in older versions either because there was never a ctor with 3 arguments (only 4 with basis/basiscollection)

**Comment by jschueller** [comment]
is your snippet missing a 4th argument with ot.Basis() ?

```algo = ot.KrigingAlgorithm(x, y, model, ot.Basis())```

**Comment by sofianehaddad** [comment]
Indeed, that's what happen when you provide a solution before defining the problem
thanks you are right - it is fixed
