### ISSUE TITLE
Student does not give access to all its parameters

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#2406]
### What happened?

When the Student is created from the (nu, mu, sigma, R) API: 

- the getMu() method is implemented only when the dimension is 1.
- the setMu() method is implemented only when the dimension is 1.

It should be implemented for any dimensions. 

### How to reproduce the issue?

```shell
from openturns import *
s = Student(1.5, [1.0, 2.0], [3.0, 4.0], CorrelationMatrix(2))
s.getMu()
s.setMu([3.0, 4.0])
```
```


### Version

1.22dev

### Operating System

Linux

### Installation media

from source

### Additional Context

_No response_

**Comment by jschueller** [comment]
it returns a Scalar, so we cannot change this without breaking api

**Comment by adutfoy** [comment]
Yes I saw that it was returning a scalar. But I don't understand why we did not implement the accessor of the parameter in the other dimensions.

**Comment by jschueller** [comment]
indeed, that's a problem

**Comment by jschueller** [comment]
there is also getMean which gives what you want

**Comment by mbaudin47** [comment]
The `getMu()` method should be changed and return a `Point`, whatever the dimension. The doc should be changed accordingly.
