### ISSUE TITLE
Uniform: document the default values of a and b

### ISSUE THREAD

**Issue by mdelozzo** [openturns/openturns#2416]
The default values of the parameters `a` and `b` of the uniform distribution (respectively -1 and 1) [are not documented](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Uniform.html).

<img width="360" alt="image" src="https://github.com/openturns/openturns/assets/53711375/9e588059-43a9-4c24-943e-d9f778a321d9">

**Comment by adutfoy** [comment]
Hi,
In this PR#2405, I completed the default values of all the distributions, copulas and parametrizations of distributions.

**Comment by mdelozzo** [comment]
Thanks for this action :)
