### ISSUE TITLE
The MethodOfMomentsFactory class is not documented properly

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2419]
### What happened?

This issue is related to the API help page of MethodOfMomentsFactory :

https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.MethodOfMomentsFactory.html

The API doc currently documents how the problem is solved based on the solvers we have in the library. It should first document the non linear system of equation associated with the moments. 

### How to reproduce the issue?

```shell
Use your eyes!
```

### Version

1.21

### Operating System

other

### Installation media

other

**Comment by mbaudin47** [comment]
I mean that the problem is primarily to solve a system of nonlinear equations. This system of equations is the same for all distributions. The specific way to solve the system of equations in the library is to solve an optimization problem, because we do not have any algorithm to directly solve the system of nonlinear equations.

In the doc, the system of nonlinear equations associated to the generic method of moments must be written. This is not written anywhere else in the doc. I can paste it below from my lecture notes as soon as I can access my computer.

**Comment by mbaudin47** [comment]
![Screenshot_20240320_183325.jpg](https://github.com/openturns/openturns/assets/31351465/7f2a0980-7c70-4a1f-9e92-7e69df742f15)

![Screenshot_20240320_183308.jpg](https://github.com/openturns/openturns/assets/31351465/32bc0ae2-a30e-46d6-9446-5445649f9f41)

**Comment by adutfoy** [comment]
I added the non linear system in the method. See PR##2585
