### ISSUE TITLE
Deprecate Os::GetEndOfLine()

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2420]
### What is the idea?

This method has been introduced at a time where it was unclear if we had to specify a single carriage return or a carriage return+a null character to mark the end of a line, depending on the OS.
As "\n" is always correct, it should be used instead of  Os::GetEndOfLine()

### Why is this needed?

"\n" is more compact and more readable

**Comment by jschueller** [comment]
agreed, lets stop using it in the new repr methods @mbaudin47

**Comment by mbaudin47** [comment]
Ok.
