### ISSUE TITLE
The LHSExperiment does not manage a non-independent copula

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2452]
### What is the idea?

The LHSExperiment does not manage a non-independent copula.

The script:
```python
import openturns as ot
dimension = 3
mu = ot.Point(dimension)
sigma = ot.CovarianceMatrix(dimension)
sigma[0, 2] = -0.5
distribution = ot.Normal(mu, sigma)
sampleSize = 5
experiment = ot.LHSExperiment(distribution, sampleSize)
```
produces:
```
TypeError: InvalidArgumentException : Error: cannot use the LHS experiment with a non-independent copula.
```

This is not consistent with the low discrepancy experiments, where a transformation into a standard space with independent copula is performed if required. Hence the next script works.

```python
import openturns as ot
dimension = 3
mu = ot.Point(dimension)
sigma = ot.CovarianceMatrix(dimension)
sigma[0, 2] = -0.5
distribution = ot.Normal(mu, sigma)
ldSequence = ot.SobolSequence()
sampleSize = 5
experiment = ot.LowDiscrepancyExperiment(ldSequence, distribution, sampleSize)
sample = experiment.generate()
```

This suggestion was born in the discussion with @efekhari27  on this [openturns.discourse thread](https://openturns.discourse.group/t/why-does-the-lhs-class-exist/309/3).

### Why is this needed?

The feature will allow to increase the convergence rate of many algorithms, including estimating the probability of observing an event in the case where the input has a non-independent copula.

**Comment by jschueller** [comment]
see the cambou2017 paper

**Comment by jschueller** [comment]
we could do the same thing done in LowDiscrpancyExperiment, but I dont know if that's correct:
[0001-LHSExperiment-Allow-dependent-copula.patch.txt](https://github.com/openturns/openturns/files/13256263/0001-LHSExperiment-Allow-dependent-copula.patch.txt)
maybe I should revert it (misc2)
