### ISSUE TITLE
Should the doc use Matplotlib or OpenTURNS graphical features?

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2454]
### What happened?

During the review of the PR #2219, graphical features were used to plot a covariance model. We are not sure of which choice to make: either use only Matplotlib features or OpenTURNS graphical features, when possible.

- In the script [python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_categorical.py](https://github.com/openturns/openturns/pull/2219/files/6774b9ba943365ac02a4136a5d01cb614cd0ddc8#diff-0dc7c84f015784eb25eee591b663fa2add12b423276c7965bbde60b04022b4a9), the `subplot` function from Matplotlib was used. Another way to get the same result is to use `GridLayout`.
- In the script [python/doc/examples/meta_modeling/kriging_metamodel/plot_kriging_categorical.py](https://github.com/openturns/openturns/pull/2219/files/6774b9ba943365ac02a4136a5d01cb614cd0ddc8#diff-0dc7c84f015784eb25eee591b663fa2add12b423276c7965bbde60b04022b4a9), the code uses `fill_between` which can be implemented using [this example](http://openturns.github.io/openturns/latest/auto_graphs/plot_graphs_fill_area.html).
- Matplotlib's `plot` function can be replaced with `Cloud`.

Here is an attempt to provide a table of pros/cons.

| Matplotlib | OpenTURNS |
|---|---|
| Pro: Well known by users | Pro: if we do not show how to use these features, who will ?|
| Pro: Often easy to use | Pro: sometimes, the equivalent OT feature exists |
| Pro: Powerful | Con: Some feature do not exist in OT (example : Matplotlib's `fill_in_between`) |
| Con: When Matplotlib's API changes, the examples must be updated (otherwise, bugs like #2269 can appear) | Pro: any change in the Graphics API are updated at each release |
| | Provides examples that can can consider as candidates for inclusion in the C++ lib (example : Matplotlib's `fill_in_between` for kriging bounds)|

### How to reproduce the issue?

```shell
Read the doc.
```

### Version

1.21

### Operating System

unknown

### Installation media

unknown

**Comment by jschueller** [comment]
lets recall that OT graphical objects goal is to visualize OT results, not to become a graphing library on its own
now the question only arises when we want to plot something for which there is no dedicated "draw" method

I dont think we want to enforce one or the other because either one can be more practical depending on the context
imho it should be "whatever is practical/shorter"

**Comment by JPelamatti** [comment]
I agree with jschueller

**Comment by josephmure** [comment]
Conclusion: use whichever is more practical or shorter in the context of the example.

**Comment by josephmure** [comment]
Conclusion: use whichever is more practical or shorter in the context of the example.
