### ISSUE TITLE
configure fails to find bonmin

### ISSUE THREAD

**Issue by yurivict** [openturns/openturns#2456]
### What happened?

```
CMake Warning at CMakeLists.txt:378 (find_package):
  By not providing "FindBonmin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Bonmin", but
  CMake did not find one.

  Could not find a package configuration file provided by "Bonmin" with any
  of the following names:

    BonminConfig.cmake
    bonmin-config.cmake

  Add the installation prefix of "Bonmin" to CMAKE_PREFIX_PATH or set
  "Bonmin_DIR" to a directory containing one of the above files.  If "Bonmin"
  provides a separate development package or SDK, be sure it has been
  installed.

```

### How to reproduce the issue?

```shell
regular build
```

### Version

1.21

### Operating System

other

### Installation media

from source

### Additional Context

The latest coin-or-bonmin-1.8.9 is installed.

clang-16
FreeBSD 13.2

**Comment by jschueller** [comment]
we do have FindBonmin.cmake/FindIpopt.cmake scripts, they are located in the cmake folder:
https://github.com/openturns/openturns/tree/master/cmake

the cmake folder should be found according to CMAKE_MODULE_PATH:
[list (APPEND CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)`](https://github.com/openturns/openturns/blob/master/CMakeLists.txt#L41)

please provide the full arguments passed to cmake cli

**Comment by jschueller** [comment]
but maybe ceres is missing a dependency on freebsd,
can you show the logs ?
