### ISSUE TITLE
Problems while configuring OpenTURNS for Visual Studio 2019

### ISSUE THREAD

**Issue by ariste-sarl** [openturns/openturns#2459]
### What happened?

When managing OpenTURNS with Visual Studio 2019 several difficulties are encountered:
- The "OT" project for building the OT.dll library does not include header files, which does not allow intellisens to be used. It would be possible to include them by adding ${HEADERFILES} to the add_library command.
- When running C++ tests (cppcheck project) all tests fail because the launch path for the t_TestName.exe executables is not correct. The path does not include the directory corresponding to the configuration used during the build (Debug, RelWithDebInfo, Release...)
- When launching python tests (pyinstallcheck project) a large number of tests are ignored because the -C DEBUG option was not placed in the ctest launch command.

### How to reproduce the issue?

```shell
Build the Visual Studio solution with CMake by choosing "Visual Studio 16 2019" as generator and "x64" as optional platform.
```

### Version

1.22dev

### Operating System

Windows

### Installation media

from source

**Comment by jschueller** [comment]
please check #2402
