### ISSUE TITLE
Cobyla returns an internal exception when maximum number of evaluations is reached

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2460]
### What is the idea?

Hi Folks,

Cobyla's version of openTURNS retrieves an internal exception (`InternalException : Solving problem by cobyla method failed (Maximum number of function evaluations reached)`) when the maximum number of evaluations is reached. This induces a python fail.  It could be better to indicate a warning instead of an exception. Sometimes, one has very small simulation budget for the optimization and considering a stopping criterion with the maximum evaluation budget is wanted.

One can note that the NLopt version of Cobyla in the library does not present this issue.

Best,

Mathieu

**Comment by jschueller** [comment]
actually it seems to be a problem in NLopt's LN_COBYLA which only stops for the MaximumEvaluationNumber criterion:
```
import openturns as ot

linear = ot.SymbolicFunction(["x1", "x2", "x3", "x4"], ["x1+2*x2-3*x3+4*x4"])
dim = 4
startingPoint = [0.0] * dim
bounds = ot.Interval([-3.0] * dim, [5.0] * dim)
problem = ot.OptimizationProblem(linear)
problem.setBounds(bounds)
for name in ["LN_COBYLA", "LN_NELDERMEAD", "LN_AUGLAG", "LD_LBFGS", "LD_SLSQP"]:
    algo = ot.OptimizationAlgorithm.Build(name)
    algo.setProblem(problem)
    algo.setMaximumEvaluationNumber(10000)
    algo.setStartingPoint(startingPoint)
    #print("algo=", algo)
    algo.run()
    result = algo.getResult()
    print("result=", result.getEvaluationNumber())

result= 10000
result= 267
result= 5
result= 6
result= 5
```

and with `algo.setMaximumEvaluationNumber(2)` they all stop silently:
```
result= 2
result= 2
result= 3
result= 2
result= 2
```

**Comment by m-balesdent** [comment]
It could be nice to also have a silently stop for openturns' Cobyla instead of a failure.

**Comment by jschueller** [comment]
we have a private setIgnoreFailure that allows to ignore all convergence criteria
also both NLopt & Ceres default to a loose convergence mode: the optimization runs without exception but you have to check a flag to see if convergence was achieved

**Comment by josephmure** [comment]
The `setIgnoreFailure` method of `Cobyla` and `TNC` should be documented in an example.

**Comment by m-balesdent** [comment]
> * [ ]  The `setIgnoreFailure` method of `Cobyla` and `TNC` should be documented in an example.

This is closed by PR #2490 
> 
>     * [ ]  In the C++ code, the exception should be thrown after the result structure has been set.
> 
>     * [ ]  `OptimizationResult` should have a new string attribute "status"
> 
>     * [ ]  These mechanisms should be illustrated in the doc

**Comment by jschueller** [comment]
maybe it could be modified after #2472 is merged because I add a new method to replace setIgnoreFailure and implement the status attribute

**Comment by jschueller** [comment]
this is done now, with the new setCheckStatus method
