### ISSUE TITLE
Some 'General methods' examples are in the wrong category

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#2473]
### What happened?

Some examples listes in the 'General method' category should probably be moved to different categories.

Compute leave-one-out error of a polynomial chaos expansion -> Meta modeling
Compute confidence intervals of a regression model from data -> Meta modeling
Compute confidence intervals of a univariate noisy function -> Meta modeling or functional modeling
 

### How to reproduce the issue?

```shell
https://openturns.github.io/openturns/latest/auto_numerical_methods/index.html
```

### Version

1.21

### Operating System

all

### Installation media

conda

**Comment by josephmure** [comment]
This has been discussed during the technical committee meeting (20/11/2023).

The 3 examples you mention illustrate low-level methods which should not be documented within the "meta model" section, which is reserved for high level methods.

**Comment by mbaudin47** [comment]
These examples were created from #2336.
