### ISSUE TITLE
Coupling tools replace method is not robust to inputs larger than 10

### ISSUE THREAD

**Issue by JPelamatti** [openturns/openturns#2474]
### What happened?

If we follow the example on the usage of CouplingTools (https://openturns.github.io/openturns/latest/auto_functional_modeling/link_to_an_external_code/plot_link_computer_code_coupling_tools.html) but have a number of inputs larger than 10, we would end-up using a list of tokens of the sort:
[@X1, ...,  @X10, @X11]

However, this does not work as the current token replacement will see 3 times the token '@X1' and replace them all. Do you think there is a way to make the implementation more robust?

Indeed, this issue forces the user to hard code some tokens, which makes for a much less automatable scripting

### How to reproduce the issue?

```shell
import openturns as ot
import openturns.coupling_tools as ct

infile = "template.txt"
outfile = "input.txt"
tokens = ["@X1", "@X2" "@X3", "@X4", "@X5", "@X6", "@X7", "@X8", "@X9", "@X10", "@X11", '@X12']
X = ot.Normal(12).getSample(1)[0]
ct.replace(infile, outfile, tokens, X)

# template.txt would look like this :
"
@X1
@X2
@X3
@X4
@X5
@X6
@X7
@X8
@X9
@X10
@X11
@X12
"
```

### Version

1.21.1

### Operating System

Linux

### Installation media

conda

**Comment by jschueller** [comment]
you can add "@" on both sides: @X1@ or use non-overlaping tokens: @X0001, etc, but yes the doc could be improved
