### ISSUE TITLE
Number of calls to objective function due to gradient approximation not always counted in OptimizationResult.getEvaluationNumber()

### ISSUE THREAD

**Issue by pierre-haessig** [openturns/openturns#2479]
### What happened?

There is either a bug (or at least an ambiguity, depending on a convention choice, see below) about the number returned `OptimizationResult.getEvaluationNumber()` in the case of an optimization problem solved by a gradient-based solver (such as [TNC](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.TNC.html)). I notice that (at least in v1.21), the number of evaluation number returned by the `OptimizationResult` result of `TNC` is only the number of call to the objective function, but *not counting* the many extra calls done for gradient approximation (using some finite differencing I guess. The difference can be huge (the actual total number of objective calls can be retrieved e.g.  by `OptimizationProblem.getObjective().getCallsNumber()`.

Now, it may be fine to state that `OptimizationResult.getEvaluationNumber()` only returns the number of objective calls *except those due to gradient approx*. However, if this is judged to be the normal behavior:
- I believe this should be documented in the accessor docstring of [getEvaluationNumber()](https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.OptimizationResult.html#openturns.OptimizationResult.getEvaluationNumber)
- Also, choosing this convention this would create an *inconsistency* with the behavior of `MultiStart` solver. At present, it is counting EvaluationNumber based on `OptimizationProblem.getObjective().getCallsNumber()`, thus counting *all calls*, see [MultiStart.cxx#L129](https://github.com/openturns/openturns/blob/master/lib/src/Base/Optim/MultiStart.cxx#L129).

### How to reproduce the issue?

```shell
from openturns.usecases import ackley_function
import openturns as ot

# Test function to be optimized
am = ackley_function.AckleyModel()
model = am.model # OT's Function object

dim = am.dim
lowerbound = [-4.0] * dim
upperbound = [4.0] * dim

# Optimization problem object:

problem = ot.OptimizationProblem(model)
bounds = ot.Interval(lowerbound, upperbound)
problem.setBounds(bounds)

# Optimization solver definition
algo = ot.TNC(problem)
algo.setStartingPoint([3.5,3.5])

# Run optimization
initialCallsNumber = problem.getObjective().getCallsNumber() # save initial nb of calls
algo.run()
result = algo.getResult()
print('x* =', result.getOptimalPoint()) 


# Effective number of calls to the objective function:
print('getCallsNumber() →', problem.getObjective().getCallsNumber() - initialCallsNumber)

# number of calls to the objective function, as declared in the `OptimizationResult`: much less!
print('getEvaluationNumber() →', result.getEvaluationNumber())
```

and the output is, starting from x0=(3.5, 3.5)
- 28 objective calls counted by `getEvaluationNumber()`
- 140 calls counted by `getObjective().getCallsNumber()` (substracting possible preexisting calls)

Since 140 == 28*(1+4) → this suggests that each calls to gradient takes 4 objective calls because it uses central difference?

### Version

1.21.1

### Operating System

Linux

### Installation media

conda

**Comment by mbaudin47** [comment]
See also #1252

**Comment by pierre-haessig** [comment]
OK. Thanks for the feedback. The difference mentioned in #1252 is subtle but fine once it's documented.
