### ISSUE TITLE
Cannot save large datasets using XMLH5StorageManager

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2487]
### What happened?

When I try to save a complex OT/Python class embedding large datasets, I get the following error:
```
Traceback (most recent call last):
  File "/data/Projets/2022/Skyreal/Cas_tests/ADEN/Psyche/ADEN_Build_PCE_Meta_Model.py", line 287, in <module>
    study_out.save()
  File "/home/regis/openturns-adm/build/install/lib64/python3.10/site-packages/openturns/common.py", line 615, in save
    return _common.Study_save(self)
IndexError: stoi
```
It sounds like the size of the dataset exceeds the range of int if I understand well the explanation given here:

https://stackoverflow.com/questions/29931827/stoi-causes-out-of-range-error

A way to solve it is to replace std::stoi by std::stol here
https://github.com/openturns/openturns/blob/4e02123b94c67f930958b15febc1884c89946e2b/lib/src/Base/Common/XMLH5StorageManager.cxx#L110

### How to reproduce the issue?

```shell
Unfortunately the script producing the bug relies on a large external dataset (8.5Go) so I cannot join it
```

### Version

1.23dev

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
I tried saving a large sample into an h5 but it blows up my memory:
```
import openturns as ot

fileName = "pyxmlh5.xml"
study = ot.Study()
study.setStorageManager(ot.XMLH5StorageManager(fileName))
sample = ot.Normal(1000).getSample(1000000)
study.add("sample", sample)
study.save()
```

/cc @YomGarcia
