### ISSUE TITLE
The computeComplementaryCDF and computeSurvivalFunction methods are unclear

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2507]
### What happened?

The computeComplementaryCDF and computeSurvivalFunction methods are unclear. 

Their meaning is different, but the documentation does not state clearly the difference in the multivariate case.

I share below an Inkscape vector image which shows the difference.

![diff_survival_CCDF](https://github.com/openturns/openturns/assets/31351465/65136de1-8391-4ba8-a00f-48a0d5d24e8e)

Furthermore, the equations are wrong. The API doc of `computeSurvivalFunction` is confusing because there are missing curly braces in the intersection :

![image](https://github.com/openturns/openturns/assets/31351465/016c151b-c257-4d73-be8b-cfb0a7958ff1)

The problem is that the equation refers to an event which has no meaning here. Moreover, the support is not necessarily equal to $\mathbb{R}^d$.

The correct equation is:

![image](https://github.com/openturns/openturns/assets/31351465/cd526a1d-da16-465e-9010-84c02c9ae017)

where $\mathcal{X}$ is the support of the random vector $\boldsymbol{X}$. Here is the LaTeX code (github fails to render it):
```latex
$$
S_{\boldsymbol{X}}(\boldsymbol{x}) = \mathbb{P}\left(\bigcap_{i = 1}^d \left\{X_i > x_i \right\}\right), \qquad \boldsymbol{x} \in \mathcal{X}
$$
```

The API help page of `computeComplementaryCDF` is confusing because there are missing curly braces within the intersection:

![image](https://github.com/openturns/openturns/assets/31351465/ffb48f2c-711a-47fa-bd3f-1604fa0486ff)

The correct equation is:

![image](https://github.com/openturns/openturns/assets/31351465/3857f6e9-fee1-4f26-949a-72f733ec88e5)

where $\mathcal{X}$ is the support of the random vector $\boldsymbol{X}$. Here is the LaTeX code (github fails to render it):
```latex
$$
1 - F_{\boldsymbol{X}}(\boldsymbol{x}) = 1 - \mathbb{P}\left(\bigcap_{i = 1}^d \left\{X_i \leq x_i \right\}\right), \qquad \boldsymbol{x} \in \mathcal{X}
$$
```

@adutfoy : This topic was clarified at the previous meeting on the topic of quantiles.

### How to reproduce the issue?

```shell
Read the doc.
```

### Version

1.21

**Comment by adutfoy** [comment]
I took into account your remarks in the PR#2553.
Except the one concerning the input of the cdf:  the inputs of the cdf and pdf and other related functions are in R^d and not only in the support of the distribution. For ex, you can compute the cdf of a Uniform(0,1) at any x in R! and not only in [0,1].

**Comment by mbaudin47** [comment]
Here is the SVG that generated the PNG:

![diff_complementary_CDF_survival](https://github.com/openturns/openturns/assets/31351465/28df1ca6-54c9-4125-acce-19a92ea52f0c)

This is a vector XML file that can be edited with Inkscape. This can be useful if we want to modify the PNG later.

**Comment by mbaudin47** [comment]
The SVG of the picture is already in the issue: you just have to save the file.
