### ISSUE TITLE
Cobyla claim to support bounds, but does not

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2508]
### What happened?

In the next script, I create a cost function that i want to minimize in the interval [0,1]. This is why I create an `OptimizationProblem` and set the bounds. Then I use the `Cobyla` class and `run()`. An exception is produced because the algorithm evaluates the function at the point $x = 1.0125$, which does not belong to [0,1].

### How to reproduce the issue?

The code:
```python
# %%
import openturns as ot

# %%
class Cost(ot.OpenTURNSPythonFunction):
    def __init__(self):
        super(Cost, self).__init__(1, 1)
        self.setInputDescription(["x"])
        self.setOutputDescription(["c"])

    def _exec(self, x):
        print(f"x = {ot.Point(x)}")
        if x[0] < 0.0 or x[0] > 1.0:
            raise ValueError("Point x not in bounds.")
        c = 1.0 - x[0] ** 2
        return [c]

# %%
costFunctionObj = Cost()
costFunction = ot.Function(costFunctionObj)
costFunction([0.5])

# %%
problem = ot.OptimizationProblem(costFunction)
bounds = ot.Interval([0.0], [1.0])
problem.setBounds(bounds)
algo = ot.Cobyla()  # Fails
# Workaround: algo = ot.NLopt("LN_COBYLA")
algo.setProblem(problem)
startingPoint = [0.5]
algo.setStartingPoint(startingPoint)
algo.run()
```
produces:
```
WRN - Cobyla went to an abnormal point x=[1.0125] y=[] msg=Python exception: 
ValueError: Point x not in bounds.
```

### Version

1.21

### Operating System

Linux

### Installation media

conda

**Comment by jschueller** [comment]
yes some algorithms do not enforce bounds strictly but penalize the corresponding constraint error so it can go a bit out of bounds sometimes (but it will never return an optimal point out of bounds) and the next few points will be likely inside the bounds

**Comment by YuDe95** [comment]
which commit fix this bug,Can you tell me?thanks!!!!!!!!!!

**Comment by jschueller** [comment]
should be dd68a2767e7cf8b1c5f275b8ae1aa4afe6864f45

**Comment by YuDe95** [comment]
have no effect

**Comment by jschueller** [comment]
it does, see the associated test-case that is added by this commit

**Comment by YuDe95** [comment]
I may not be able to test version 1.23 until later. If you have time, try changing setMaximumCallsNumber (100) to setMaximumCallsNumber (10000), and this issue may will occur

**Comment by YuDe95** [comment]
i use https://github.com/openturns/openturns/issues/2508#issue-2056402503 test in version 1.23,and it also have this error

  raise ValueError("Point x not in bounds.")
ValueError: Point x not in bounds.
WRN - Cobyla went to an abnormal point x=[1.0125] y=[] msg=Python exception: ValueError: Point x not in bounds.

**Comment by YuDe95** [comment]
`# %%
import openturns as ot
print(ot.__version__)
# %%
class Cost(ot.OpenTURNSPythonFunction):
    def __init__(self):
        super(Cost, self).__init__(1, 1)
        self.setInputDescription(["x"])
        self.setOutputDescription(["c"])

    def _exec(self, x):
        # print(f"x = {ot.Point(x)}")
        # if x[0] < 0.0 or x[0] > 1.0:
        #     raise ValueError("Point x not in bounds.")
        # c = 1.0 - x[0] ** 2
        c = x[0]
        return [c]

# %%
costFunctionObj = Cost()
costFunction = ot.Function(costFunctionObj)
costFunction([0.5])

# %%
problem = ot.OptimizationProblem(costFunction)
bounds = ot.Interval([-1e-9], [1.0e-9])
problem.setBounds(bounds)
problem.setMinimization(True)
algo = ot.Cobyla()  # Fails
# Workaround: algo = ot.NLopt("LN_COBYLA")
algo.setProblem(problem)
startingPoint = [0.0]
algo.setStartingPoint(startingPoint)
algo.setMaximumCallsNumber(10000)
algo.setMaximumAbsoluteError(1.0e-20)
algo.setMaximumRelativeError(1.0e-20)
algo.setMaximumResidualError(1.0e-20)
algo.setMaximumConstraintError(1.0e-20)

algo.run()`

result 
`
x = [0]
x = [1e-09]
x = [-0.0125]
x = [-0.0015625]
x = [-0.000195313]
x = [-2.44141e-05]
x = [-3.05176e-06]
x = [-3.8147e-07]
x = [-4.76837e-08]
x = [-5.96046e-09]
x = [-1e-09]
x = [-1.18626e-09]
x = [-1.02328e-09]
x = [-1.00291e-09]
x = [-1.00036e-09]
x = [-1.00005e-09]
x = [-1.00001e-09]
x = [-1e-09]
x = [-1e-09]
x = [-1e-09]
x = [-1e-09]
x = [-1e-09]
x = [-1e-09]
x = [-1e-09]
`

**Comment by jschueller** [comment]
you're right, lets reopen
