### ISSUE TITLE
Strange probabilistic model for the fire satellite use-case

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2527]
### What happened?

The probabilistic model of the fire satellite use-case (https://openturns.github.io/openturns/latest/usecases/use_case_fireSatellite.html) is made of independent normal distributions. It allows to produce negative values for quantities which are physically constrained to be positive. Many of these normal distributions have a standard deviation much lower than their mean value, resulting into a numerical truncation to positive values, but others like the reflectance factor or the drag coefficient can take negative values with significant probabilities.

### How to reproduce the issue?

```shell
Read the use-case description
```

### Version

1.23dev

### Operating System

Linux

### Installation media

from source

**Comment by m-balesdent** [comment]
We use the description given in :
Sankararaman, S. and Mahadevan, S. Likelihood-based approach to multidisciplinary analysis under uncertainty. Journal of Mechanical Design, 134(3):031008, 2012

It will be more consistent to truncate these distributions.
