### ISSUE TITLE
No wheel available for python 3.12

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2538]
### What happened?

Trying to install openturns using pip results into an error with python 3.12

### How to reproduce the issue?

```shell
pip install openturns
```

### Version

1.22

### Operating System

Linux

### Installation media

pip

### Additional Context

Many students faced the same issue on Linux, Windows and MacOS

**Comment by jschueller** [comment]
weird, we have 3.12 wheel files for all 3 OS:
https://pypi.org/project/openturns/#files

**Comment by jschueller** [comment]
I just re-checked, it works fine on linux+windows, maybe pypi servers are blocked by the firewall ?

**Comment by jschueller** [comment]
need more info
