### ISSUE TITLE
The computeQuantile() method of a Mixture can fail

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2541]
### What happened?

I created a `Mixture` and computed its quantile of level 0.5. 
- The script produces the value 1.5.
- The correct value is 1.

![image](https://github.com/openturns/openturns/assets/31351465/a922796b-a279-40a2-a349-14af08dadad6)

This is a trap: the distribution is specifically chosen so that its CDF is flat on the nonempty interval [1,2].

### How to reproduce the issue?

The script:

```python
distribution = ot.Mixture([ot.Uniform(0.0, 1.0), ot.Uniform(2.0, 3.0)], [0.5, 0.5])
alpha = 0.5
z = distribution.computeQuantile(alpha)[0]
print("z = ", z)
```

prints:
```
z = 1.5
```

### Version

1.21

### Operating System

Linux

### Installation media

conda

**Comment by jschueller** [comment]
isnt any value in [1,2] correct ?

**Comment by mbaudin47** [comment]
Here is the PDF:

![output](https://github.com/openturns/openturns/assets/31351465/a7af9271-346d-4a0d-9cd5-72fea4b57f97)

It is true, indeed, that the value x = 1.5 is so that f(0) = 0. But why should this be related to the definition of the quantile?

By definition, we have:

$$
x_\alpha = \textrm{inf} \set{x \in \mathbb{R}  |  \alpha \leq F(x)}
$$

Taking $x = 0.5$, we get:

$$
x_{0.5} = \textrm{inf} \set{x \in \mathbb{R}  | 0.5 \leq F(x)}
$$

Since $F(x) = 0.5$ for any $x in [1,2]$, it seems to me that the solution is:

$$
x_{0.5} = \textrm{inf} \set{[1,2]} = 1.
$$

**Comment by jschueller** [comment]
indeed sometimes its not defined with the inf, the english wp page states thats its more a convention:
https://en.wikipedia.org/wiki/Quantile_function

but the french page has the inf:
https://fr.wikipedia.org/wiki/Fonction_quantile

**Comment by mbaudin47** [comment]
You are right. This is done at:

https://github.com/openturns/openturns/blob/4fc2024d0cbccb92b4c5f70df8fd36598c903eb5/lib/src/Uncertainty/Model/DistributionImplementation.cxx#L2307

Actually, we do not have the required information in the `Distribution`: is the CDF continuous and strictly increasing? If yes, then `Brent` is the right method. Otherwise, then the problem is an `OptimizationProblem` with a non linear constraint.

**Comment by regislebrun** [comment]
There are several tricks to solve this issue:
1) Add a Uniform distribution over the range of the mixture with a weight of order a few CDFEpsilon_. This way, the flat parts are removed without modifying a lot the CDF
2) Or check if CDF(x_p-quantileEpsilon_)=p. In this case, solve CDF(x_p)=p-CDFEpsilon_, then return either this x_p or its first order correction x_p+CDFEpsilon_/PDF(x_p)

**Comment by jschueller** [comment]
I prefer 2.
