### ISSUE TITLE
New default colors are visually broking examples

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2543]
### What happened?

The PR #2422 changes the way the colors are managed. When no color is set, the first color in the current palette is used.

Although this has a positive impact on many examples, it has a negative impact on some. For example, in [plot_compare_unconditional_conditional_histograms.html](http://openturns.github.io/openturns/master/auto_data_analysis/sample_analysis/plot_compare_unconditional_conditional_histograms.html), the new plot is:

![image](https://github.com/openturns/openturns/assets/31351465/67acf9ee-cbab-417a-92f1-bf5aa7dc7fd9)

We see that the new plot uses two different blue: the default tableau blue and the blue. There is nothing that we can do to automatically update this kind of plot: the script must be updated. The simplest way to fix the colors in this particular case is to remove the statement `setColors(["blue"])` code in the script: the default colors will then do their job.

The goal of this PR is to gather in a single place the list of all the examples that should be updated.

- [ ] [plot_compare_unconditional_conditional_histograms.html](http://openturns.github.io/openturns/master/auto_data_analysis/sample_analysis/plot_compare_unconditional_conditional_histograms.html)
- [ ] [plot_draw_survival.html](http://openturns.github.io/openturns/master/auto_data_analysis/sample_analysis/plot_draw_survival.html)
- [ ] [plot_estimate_non_parametric_distribution.html](http://openturns.github.io/openturns/master/auto_data_analysis/distribution_fitting/plot_estimate_non_parametric_distribution.html) Managed in #2491.
- [ ] [plot_generate_by_inversion.html](http://openturns.github.io/openturns/master/auto_probabilistic_modeling/distributions/plot_generate_by_inversion.html)
- [ ] [plot_graphs_basics.html](http://openturns.github.io/openturns/master/auto_graphs/plot_graphs_basics.html)

### Version

1.22

### Operating System

other

### Installation media

other

**Comment by jschueller** [comment]
sometimes graphs from the api are affected too:
https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.VisualTest.DrawQQplot.html#openturns.VisualTest.DrawQQplot
also checkout distribution plots, simulation& sobol plots, etc

**Comment by josephmure** [comment]
@jschueller In the example you link to the desired behavior occurs: blue is selected, and then orange.
