### ISSUE TITLE
SpecFunc.MaxScalar is undocumented

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2549]
### What happened?

The constant `SpecFunc.MaxScalar` is undocumented.

![image](https://github.com/openturns/openturns/assets/31351465/7b580ec2-6584-4b76-8c1f-18dcbe3d20c9)

This is an issue because this constant is used in the doc e.g. [CompositeDistribution](https://openturns.github.io/openturns/master/user_manual/_generated/openturns.CompositeDistribution.html):

![image](https://github.com/openturns/openturns/assets/31351465/05ded7b5-e58c-4dc2-8557-3e1f14e8e6bc)

### How to reproduce the issue?

```shell
Read the doc.
```

### Version

1.22

### Operating System

other

### Installation media

other

**Comment by jschueller** [comment]
unfortunately we cannot add docstring to simple types, we must write something manually in rst

**Comment by adutfoy** [comment]
This PR is treated in #2749
