### ISSUE TITLE
FORM / SORM needs modification to avoid bad estimation of probability in case of non convergence of optimization

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2559]
### What is the idea?

Hi,

With the new feature of setting ignoreFailure of the optimization algorithm to `True` inside FORM / SORM, there is a possibility that the optimization algorithm does not converge in the most probable failure point estimation process embedded in FORM / SORM. 

In case of bad convergence, the equality constraint satisfaction about being on the limit state function is not ensured. In this case, the failure probability estimation is not possible.

One test should be included in FORM / SORM algorithms to check the constraint satisfaction after the optimization algorithm run and retrieve an exception if the constraint is not satisfied.

### Additional Context

To solve this issue, one may add a `limitStateTolerance` attribute to let the user choose the tolerance on the constraint satisfaction, and implement a test after the optimization algorithm run to check the validity of the results.

**Comment by regislebrun** [comment]
@m-balesdent I am not sure that there is a bug here. The ignoreFailures flag is set to false by default, and its name tells everything: ignore the failures. Not only some failures, but all failures. It is up to the user to decide if it fits his/her needs or not. You cannot get something wrong excepted if you deliberately ask for possible wrong results!

**Comment by m-balesdent** [comment]
@regislebrun I understand your remark based on COBYLA. The issue is maybe more general that in the context of ignoreFailure flag. Indeed, exceptions in case on non-convergence of optimization algorithms are not implemented for all the proposed algorithms, especially for algorithms coming from other libraries (NLopt, Pagmo, etc.). For example, if you run this code : 

```
import openturns as ot
from openturns.usecases import cantilever_beam

cb = cantilever_beam.CantileverBeam()
distribution = cb.distribution
model = cb.model

vect = ot.RandomVector(distribution)
G = ot.CompositeRandomVector(model, vect)
event = ot.ThresholdEvent(G, ot.Greater(), 0.3)

solver = ot.NLopt('LN_COBYLA')
solver.setMaximumEvaluationNumber(100)

algoFORM = ot.FORM(solver, event, distribution.getMean())

algoFORM.run()

result = algoFORM.getResult()

# failure probability
print(result.getEventProbability())

# value of limit state function at the design point 
print(cb.model(result.getPhysicalSpaceDesignPoint()))
```

> 0.4344180620967769
> 0.173183

you will have a wrong failure probability (0.43xx) instead f 1.1e-6 without any error message. Furthermore, if you check the value of limit state function for the design point, you will find 0.173xx that is not 0.3 (true value for cantilever beam problem) ! 

So I think the check on FORM / SORM is mandatory to ensure validity of results.

**Comment by regislebrun** [comment]
@m-balesdent You are right! Either we make the optimization algorithms more robust regarding convergence (and we generalize setIgnoreFailure) or we make FORM/SORM more cautious about the optimization result, and we should probably do both.

**Comment by mbaudin47** [comment]
Scary bug! For my own information, I tuned the algorithm so as to get the correct result:
```python
import openturns as ot
from openturns.usecases import cantilever_beam

cb = cantilever_beam.CantileverBeam()
vect = ot.RandomVector(cb.distribution)
G = ot.CompositeRandomVector(cb.model, vect)
event = ot.ThresholdEvent(G, ot.Greater(), 0.3)

solver = ot.NLopt('LN_COBYLA')
solver.setMaximumAbsoluteError(0.0)  # Sensitive point: remove it: you lose!

algoFORM = ot.FORM(solver, event, cb.distribution.getMean())
algoFORM.run()
result = algoFORM.getResult()

# failure probability
print(result.getEventProbability())  # True Pf = 1.1e-6
```
prints:
```
1.8464765502282925e-07
```

PS
To get colorful Python scripts, just use "```python" (see e.g. [here](https://aeturrell.github.io/python4DS/markdown.html#text-block-syntax)).
