### ISSUE TITLE
SimulatedAnnealingLHS.generate does not terminate for LHS of size 1

### ISSUE THREAD

**Issue by BenoitPauwels** [openturns/openturns#2563]
### What happened?

When executing code from [this page](https://openturns.github.io/openturns/latest/auto_reliability_sensitivity/design_of_experiments/plot_optimal_lhs.html#sphx-glr-auto-reliability-sensitivity-design-of-experiments-plot-optimal-lhs-py) with `N=1`, `SimulatedAnnealingLHS.generate` does not terminate.
(Could it be an infinite loop?)

### How to reproduce the issue?

```shell
import openturns as ot

N = 1

# Considering independent Uniform distributions of dimension 3
# Bounds are (-1,1), (0,2) and (0, 0.5)
distribution = ot.ComposedDistribution([
    ot.Uniform(-1.0, 1.0),
    ot.Uniform(0.0, 2.0),
    ot.Uniform(0.0, 0.5),
])
# Random LHS
lhs = ot.LHSExperiment(distribution, N)
lhs.setAlwaysShuffle(True)  # randomized
# Fixing C2 crit
space_filling = ot.SpaceFillingC2()
# Defining a temperature profile
# A geometric profile seems accurate with default parameters
# e.g. T0=10, c=0.95, iMax=2000
temperatureProfile = ot.GeometricProfile()
algo = ot.SimulatedAnnealingLHS(lhs, space_filling, temperatureProfile)
# optimal design
design = algo.generate()
```

### Version

1.22

### Operating System

Windows

### Installation media

pip

### Additional Context

This bug may seem inconsequential as few users may require an LHS of size 1 (!)
However I ran into it several times when testing elaborate code (that includes DOEs) : I run my code with minimal input values to check that it terminates correctly, before running it with meaningful values which require a signification execution time.

**Comment by jschueller** [comment]
indeed it needs at least 2 different points
