### ISSUE TITLE
Does openturns support cross-compilation of arm64-windows on the windows platform?

### ISSUE THREAD

**Issue by jimwang118** [openturns/openturns#2575]
### What happened?

When I used the following command to install openturns in vcpkg, an error occurred.
./vcpkg install openturns:arm64-windows

### How to reproduce the issue?

```shell
git clone vcpkg
.\bootstrap-vcpkg.bat
./vcpkg install openturns:arm64-windows
```

### Version

1.20

### Operating System

Windows

### Installation media

other

### Additional Context

CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   _NLOPT_STOGO_RUNS (advanced)
For details see F:/vcpkg/buildtrees/openturns/arm64-windows-rel/TryRunResults.cmake
-- nlopt::GD_STOGO: fails to run
CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
   _NLOPT_AGS_RUNS (advanced)
For details see F:/vcpkg/buildtrees/openturns/arm64-windows-rel/TryRunResults.cmake

**Comment by jschueller** [comment]
no bug here, you can try passing "-D_NLOPT_STOGO_RUNS=1 -D_NLOPT_AGS_RUNS=1" to cmake
you can also try 1.22 as it doesnt require these runtime checks anymore

**Comment by jimwang118** [comment]
Thank you very much, by adding the compile option it can now compile normally. I will also test whether the latest version compiles properly.
