### ISSUE TITLE
The legends of the drawPDF() graph have a wrong order

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2596]
### What happened?

The [plot_estimate_non_parametric_copula.html](http://openturns.github.io/openturns/latest/auto_data_analysis/estimate_dependency_and_copulas/plot_estimate_non_parametric_copula.html) plots the contours of a 2 dimensions distribution. The `drawPDF()` method plots:

![image](https://github.com/openturns/openturns/assets/31351465/41faf26e-22f5-4d79-b552-54116f9210eb)

We see that the order of the legends in the plot do not correspond to the order of the values: the values should be sorted in increasing order, but the legends are sorted so that the lowest value is the last, instead of being the first. In other words, the order of the legends is correct, except for the first one.

### How to reproduce the issue?

```python
import openturns as ot
import openturns.viewer as viewer
from matplotlib import pylab as plt

R = ot.CorrelationMatrix(2)
R[1, 0] = 0.4
copula = ot.NormalCopula(R)
sample = copula.getSample(30)
distribution = ot.BernsteinCopulaFactory().build(sample)
graph = distribution.drawPDF()
view = viewer.View(graph)
```

### Version

1.22

### Operating System

unknown

### Installation media

unknown

### Additional Context

@ariste-sarl : Did you notice that?
_No response_

**Comment by jschueller** [comment]
I dont think so

**Comment by mbaudin47** [comment]
Can you elaborate on this?

**Comment by jschueller** [comment]
its about the order of the legend, not the z-axis order
