### ISSUE TITLE
HSICEstimatorImplementation : cannot save with pickle

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#2624]
### What happened?

Everything is in the title.
The code below produces the following error:

```
TypeError: InvalidArgumentException : No object with label 'instance' in study
```

### How to reproduce the issue?

```shell
import pickle
import openturns as ot

with open("study.pkl", "wb") as f:
    pickle.dump(ot.HSICEstimatorGlobalSensitivity(), f)

with open("study.pkl", "rb") as f:
    loaded_hsic = pickle.load(f)
```

### Version

master

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
it has no factory: `static const Factory<HSIC...`

**Comment by josephmure** [comment]
I don't understand your message. There is a line with a factory:

https://github.com/openturns/openturns/blob/ee5b184d5a526932885fc4216cde66a72ee9aa4b/lib/src/Uncertainty/Algorithm/Sensitivity/HSICEstimatorImplementation.cxx#L38

@mbaudin47 says the same issue occurs with ExperimentIntegration.

**Comment by mbaudin47** [comment]
The commit d4108b2 fixes the issue for HSIC, but not for `ExperimentIntegration` isn'it?

**Comment by jschueller** [comment]
see 204744148b2c2fa62814724a181af630cc9081c7
