### ISSUE TITLE
Weird window for NormalGamma plot in API page

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#2627]
### What happened?

On the current master version of the NormalGamma API page the plot has a weird window:

https://openturns.github.io/openturns/master/user_manual/_generated/openturns.NormalGamma.html

![image](https://github.com/openturns/openturns/assets/31989332/100d1e9f-3ce7-4238-8950-35e14b71a25b)

Compare with the 1.22 (at the time of the writing of this message "latest") version:

https://openturns.github.io/openturns/1.22/user_manual/_generated/openturns.NormalGamma.html

![image](https://github.com/openturns/openturns/assets/31989332/b5a4a271-7149-4724-afae-436336b755ae)

### How to reproduce the issue?

```shell
import openturns as ot
from matplotlib import pyplot as plt
from openturns.viewer import View

distribution = ot.NormalGamma()

distribution.setDescription(["$X$", "$Y$"])
pdf_graph = distribution.drawPDF()
pdf_graph.setTitle(str(distribution))
fig = plt.figure(figsize=(10, 5))
pdf_axis = fig.add_subplot(111)
View(pdf_graph, figure=fig, axes=[pdf_axis], add_legend=False)
pdf_axis.set_ylim(top=5.0)
```

### Version

1.23dev (master)

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
The log-pdf maybe be wrong since my latest commit
