### ISSUE TITLE
Multi Start have incoherent behavior if the max eval has been reached

### ISSUE THREAD

**Issue by adumasphi** [openturns/openturns#2628]
### What happened?

Using the multi start algorithm, if the maximum evaluation has been reached, the behavior is not the same depending on the used algorithm.
With TNC or Cobyla, for a unit resolution the algo throws an exception if the max evaluation has been reached so the remaining evaluation is not computed in MultiStart. The next point can start with the same initial evaluation number. 
With Nlopt algorithm, the algorithm does not throw an exception if the max evaluation has been reached. So the remaining evaluation is computed and it is equal to 0, which is given to the algorithm as the new maximum evaluation number. With Nlopt there are 2 issues : the algorithm is still launched and seems to have no stopping criterion regarding the number of evaluation. And the report progress is also return infinity as it is divided by 0.

### How to reproduce the issue?

```shell
import openturns as ot
ot.Log.Show(ot.Log.DBG)

dim = 2

model = ot.SymbolicFunction(['x', 'y'], ['x^2+y^2*(1-x)^3'])
bounds = ot.Interval([-2.0] * dim, [3.0] * dim)
problem = ot.OptimizationProblem(model)
problem.setBounds(bounds)
solver = ot.TNC(problem)
# solver = ot.NLopt(problem, 'LN_COBYLA')
uniform = ot.ComposedDistribution([ot.Uniform(-2.0, 3.0)] * dim)
ot.RandomGenerator.SetSeed(0)
startingSample = uniform.getSample(5)


def report_progress(progress):
    print(f'\n-- progress={progress:0.0f}% --')


solver.setProgressCallback(report_progress)
algo = ot.MultiStart(solver, startingSample)
algo.setMaximumEvaluationNumber(5)
algo.run()
```

### Version

1.22

### Operating System

Linux

### Installation media

conda

### Additional Context

The behavior we have with TNC or Cobyla seems better to me, even if it was not expected this way. I would prefer give the same maximum number of evaluations for each single optimization. For the user it is obvious that the overall maximum evaluation will be n_start_points x max_evaluation. 
With the current strategy, we need to provide a large number of evaluations to be sure all starting points will be tested but we might have some starting points that will failed to converge and use all the available evaluations for nothing.
It is still possible to have for the multi start a maximum evaluation number for the whole optimization but I think it should be another parameter.

**Comment by jschueller** [comment]
1. NLopt should throw on MAXEVAL error code
2. MultiStart did not handle errors correctly and just continued to next point
