### ISSUE TITLE
There are duplicate and inconsistent mathematical notations

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2629]
### What is the idea?

New mathematical notations were successfully introduced in #2574.

These changes were introduced in [math_notations.sty](https://github.com/openturns/openturns/blob/master/python/doc/math_notations.sty]. But these notations are not entirely consistent.

- The input distribution is defined by:

https://github.com/openturns/openturns/blob/7481e77f5c3f36d6a055cf75142bf560c1dcf751/python/doc/math_notations.sty#L29

or:

https://github.com/openturns/openturns/blob/7481e77f5c3f36d6a055cf75142bf560c1dcf751/python/doc/math_notations.sty#L55

or:

https://github.com/openturns/openturns/blob/7481e77f5c3f36d6a055cf75142bf560c1dcf751/python/doc/math_notations.sty#L71

- The input domain does not use the `\set` macro:

https://github.com/openturns/openturns/blob/7481e77f5c3f36d6a055cf75142bf560c1dcf751/python/doc/math_notations.sty#L23

It is not consistent with the physical input space:

https://github.com/openturns/openturns/blob/7481e77f5c3f36d6a055cf75142bf560c1dcf751/python/doc/math_notations.sty#L50

- The output domain is defined as:

https://github.com/openturns/openturns/blob/7481e77f5c3f36d6a055cf75142bf560c1dcf751/python/doc/math_notations.sty#L52

but this could altenatively be named `outputDomain`.

### Why is this needed?

Update math_notations.sty and the file that use these macros.

**Comment by mbaudin47** [comment]
@adutfoy : Do you have any opinion on this topic?

**Comment by adutfoy** [comment]
The PR is treated in #2749
