### ISSUE TITLE
PCE on discrete input values

### ISSUE THREAD

**Issue by mtahtouh** [openturns/openturns#2643]
### What is the idea?

Hi, 
I would like to create a metamodel based on the coupling of two different models. The inputs of the first model are discrete values (6 parameters taking 3 different values each) and the final output is a time series. Is it possible to perform a PCE in this case ?

**Comment by regislebrun** [comment]
Hi,
It is possible using several ways. As it is neither an issue nor an enhancement, could you please post your question either on gitter (https://app.gitter.im/#/room/#openturns_community:gitter.im) or on discourse (https://openturns.discourse.group/) and I will be happy to help!

Cheers
