### ISSUE TITLE
The Faure sequence is wrong

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2653]
### What happened?

The Faure sequence generates wrong points in any dimension.

Here are the proofs of this.
- In dimension 2, we see that a set of 4 points does not correctly fill the 4 base-2 elementary volumes.
- In dimension 3, we see that 9 first points generated are wrong. The basis is obviously equal to 2 instead of 3. The third dimension is a copy of the first dimension.
- The estimated value of the mean of the GSobol' function does not converge to its true value.

Many thanks to Félix Husson (EDF & Institut Galilée) for pointing that bug.

One of the reasons of the bug is undetected is the way the unit test [t_FaureSequence_std.cxx](https://github.com/openturns/openturns/blob/master/lib/test/t_FaureSequence_std.cxx) is implemented. Since the algorithm produces a set of points, the simplest and most efficient way to implement the unit test is to check the coordinates of the set of points against a pre-defined reference `Sample`. This reference sample can be computed from another library, e.g. Matlab, Scilab, Mathematica, etc. Several dimensions e.g. 2, 3, and 4 should be checked. Instead, the first part of the current unit test checks the library against itself, which prevents from detecting any bug. The second part of the unit test estimates the number $\pi$. Unfortunately, the algorithm seems to converge with relative accuracy equal to $10^{-4}$. Actually, this unit test is still of poor value. Indeed, the fact that the estimate converges is a weak proof that the method is OK. Indeed, we may expect that the _rate_ of convergence is OK (which is not). Finally, the sample size is equal to 1000, instead of being equal to a power of the basis, i.e. 2 in this particular case.

#### Proof #1: In dimension 2

```python
import openturns as ot
import openturns.usecases.ishigami_function as ishigami
import openturns.viewer as viewer
import matplotlib.pyplot as plt

basis = 2
dimension = 2
taille = basis**dimension
distribution = ot.ComposedDistribution([ot.Uniform(0.0, 1.0)] * dimension)
sequence = ot.FaureSequence()
experiment_QMC = ot.LowDiscrepancyExperiment(sequence, distribution, taille, False)
sample = experiment_QMC.generate()
fig = viewer.PlotDesign(
    sample,
    subdivisions=[basis] * dimension,
    bounds=ot.Interval([0.0] * dimension, [1.0] * dimension),
)
plt.title(f"n = {taille}")
fig.set_figwidth(3.0)
fig.set_figheight(3.0)
```

![image](https://github.com/openturns/openturns/assets/31351465/aa43e023-6f1f-4f86-86d5-9c3dfde86169)
**Figure 1.** The first 4 points of the Faure sequence in dimension 2. There should be one single point for each elementary volume, but the upper left cell contain 2 points.

#### Proof #2: In dimension 3

The script below defines the first 9 points of the Faure sequence in dimension 3. This is from [^Baudin2013].
```python
# First 9 points of Faure sequence in dimension 3
expected = ot.Sample([
    [1 / 3, 1 / 3, 1 / 3],
    [2 / 3, 2 / 3, 2 / 3],
    [1 / 9, 4 / 9, 7 / 9],
    [4 / 9, 7 / 9, 1 / 9],
    [7 / 9, 1 / 9, 4 / 9],
    [2 / 9, 8 / 9, 5 / 9],
    [5 / 9, 2 / 9, 8 / 9],
    [8 / 9, 5 / 9, 2 / 9],
])
```

Now compare to the result from OpenTURNS.
```
dimension = 3
taille = 9
distribution = ot.ComposedDistribution([ot.Uniform(0.0, 1.0)] * dimension)
sequence = ot.FaureSequence()
experiment_QMC = ot.LowDiscrepancyExperiment(sequence, distribution, taille, False)
sample = experiment_QMC.generate()
sample
```
which prints:

<table>
  <tr><td></td><th>y0</th><th>y1</th><th>y2</th></tr>
  <tr><th>0</th><td>0.5</td><td>0.5</td><td>0.5</td></tr>
  <tr><th>1</th><td>0.25</td><td>0.75</td><td>0.25</td></tr>
  <tr><th>2</th><td>0.75</td><td>0.25</td><td>0.75</td></tr>
  <tr><th>3</th><td>0.125</td><td>0.625</td><td>0.125</td></tr>
  <tr><th>4</th><td>0.625</td><td>0.125</td><td>0.625</td></tr>
  <tr><th>5</th><td>0.375</td><td>0.375</td><td>0.375</td></tr>
  <tr><th>6</th><td>0.875</td><td>0.875</td><td>0.875</td></tr>
  <tr><th>7</th><td>0.0625</td><td>0.9375</td><td>0.0625</td></tr>
  <tr><th>8</th><td>0.5625</td><td>0.4375</td><td>0.5625</td></tr>
</table>

We see that the basis is equal to 2 instead of 3. We see that the third dimension is a copy of the first one.

[^Baudin2013]: "Low Discrepancy Toolbox Manual", Michael Baudin. Version 0.1. May 2013. https://gitlab.com/scilab/forge/lowdisc

#### Proof #3: Convergence on GSobol'

Notice that the lack of convergence of the faulty Faure sequence is not so obvious on the Ishigami function, because the third input variable is no so influential. Only the speed of convergence is affected here.

We consider the GSobol' test function and compute its mean.

```python
a=[0.0, 9.0, 99.0]
def GSobolModel(X):
    X = ot.Point(X)
    d = X.getDimension()
    Y = 1.0
    for i in range(d):
        Y *= (abs(4.0 * X[i] - 2.0) + a[i]) / (1.0 + a[i])
    return ot.Point([Y])

gSobolFunction = ot.PythonFunction(dimension, 1, GSobolModel)
gSobolFunction.setOutputDescription(["Y"])

# Define the distribution
distributionList = [ot.Uniform(0.0, 1.0) for i in range(dimension)]
distribution = ot.ComposedDistribution(distributionList)

name = "GSobol"

# Compute Mean
gSobolMean = 1.0


dimension = 3
basis = 3  # ie the smallest prime number greater or equal to the dimension
sampleSize = basis ** 7  # This is significant!
sequence = ot.FaureSequence()
experiment_QMC = ot.LowDiscrepancyExperiment(sequence, im.distributionX, sampleSize, False)
inputSample = experiment_QMC.generate()
outputSample = gSobolFunction(inputSample)
print(f"n = {sampleSize} , estimate = {outputSample.computeMean()[0]}")
print(f"Expected = {gSobolMean}")
```
We get:
```
n = 2187 , estimate = 10.722134899604974
Expected = 1.0
```

### Version

1.22

### Operating System

unknown

### Installation media

unknown

**Comment by regislebrun** [comment]
@mbaudin47 Nice catch, and thanks for the detailed analysis. The faulty part seems to be in `LowDiscrepancySequence::GetNextPrimeNumber(n)`, which was suppose to return the first prime number strictly greater than n and return the first prime number greater or equal to n-1 if primesieve is used (see https://github.com/kimwalisch/primesieve/blob/master/doc/CPP_API.md#primesieveiteratorjump_to-since-primesieve-110).

**Comment by mbaudin47** [comment]
I try to improve some of the low discrepancy unit tests in #2654. I was not able to reproduce the bug based on my Linux-build of the lib: do you know why?

**Comment by mbaudin47** [comment]
Is there a workaround?

**Comment by mbaudin47** [comment]
What if the installation is based on Conda: is there a way to remove that package/module, or is this integrated within the OT binary?

**Comment by jschueller** [comment]
its not possible to change it at runtime

**Comment by mbaudin47** [comment]
@regislebrun states that the dimension 2 works perfectly, which is the contrary of what @mbaudin47 . Burkardt (C++ and Matlab) and Dimitry Shvorob (Mathworks.com, 15373, "Generate a Faure sequence").

**Comment by mbaudin47** [comment]
@regislebrun I found the issue.

Here are the first 4 points of the Faure sequence in the current's master:

| | y0 |	y1 |
|---|---|---|
|0	| 0.5	| 0.5|
|1	| 0.25	| 0.75|
|2	| 0.75	| 0.25|
|3	| 0.125	| 0.625|

This is wrong. The 3d point is in base 8, not in base 4 as expected. The reason behind this is because we removed the first point, the infamous $(0, 0)$. This destroys the (t,m,s)-net property of the Faure sequence. When we use the script:

```python
import openturns as ot
import openturns.viewer as viewer
import matplotlib.pyplot as plt

basis = 2
dimension = 2
sample_size = basis**dimension
distribution = ot.ComposedDistribution([ot.Uniform(0.0, 1.0)] * dimension)
sequence = ot.FaureSequence()
experiment_QMC = ot.LowDiscrepancyExperiment(sequence, distribution, sample_size, False)
sample = experiment_QMC.generate()
fig = viewer.PlotDesign(
    sample,
    subdivisions=[basis] * dimension,
    bounds=ot.Interval([0.0] * dimension, [1.0] * dimension),
)
plt.title(f"n = {sample_size}")
plt.xlim(-0.1, 1.1)
plt.ylim(-0.1, 1.1)
fig.set_figwidth(3.0)
fig.set_figheight(3.0)
```

this produces:

![image](https://github.com/openturns/openturns/assets/31351465/9e5ed8ea-7550-4983-b983-e1b8d3541a61)

**Figure 1.** The faulty Faure sequence in OpenTURNS 1.23.

The correct 4 points are :

| | y0 |	y1 |
|---|---|---|
| 0 |0 | 0 |
|1	| 0.5	| 0.5|
|2	| 0.25	| 0.75|
|3	| 0.75	| 0.25|

This produces:

![image](https://github.com/openturns/openturns/assets/31351465/cacbd37c-caca-435c-98bf-8a21065ff873)

**Figure 2.** The correct Faure sequence.

A. Owen explained this in [^Owen2021]. The significant contribution of this paper is that Owen presents examples where removing the first point in the sequence reduces the convergence speed of the method. Please have a look at the figure 2 page 9. In the paper, $\hat{\mu}_{x,1}$ is the average of the first $n$ points where the first point was skipped and $\hat{\mu}_{x,2}$ is the average of the first $n$ points including zero. Removing the first point changes the expected convergence rate from $n^{-1}$ down to $n^{-3/2}$. One of the tricks to find a good example is to carefully select a function which is not symmetric about $(1/2, ..., 1/2)$.

![image](https://github.com/openturns/openturns/assets/31351465/a2157107-6d20-4c7a-aaac-60cff5258f9f)

One solution is: put the 0 back (which restores the convergence rate) and scramble the sequence by default (which solves the 0 issue). Quoting [^Owen2021]: "With digital nets as with antibiotics, one should take the whole sequence."

[^Owen2021]: On dropping the first Sobol' point. Art B. Owen. 2021 https://arxiv.org/abs/2008.08051

I will create a new issue on the topic with title: "_The zero should be included in some low discrepancy sequences_". This issue will impact Sobol', Faure and perhaps other sequences as well.
