### ISSUE TITLE
FunctionImplementation::draw forces the location of the color bar in 2D

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2658]
### What happened?

The value associated to the "Contour-DefaultColorBarPosition" key in ResourceMap is ignored by FunctionImplementation::draw(), see https://github.com/openturns/openturns/blob/b5fd8338850d1255233f64a0e0c27d963d6f7daf/lib/src/Base/Func/EvaluationImplementation.cxx#L465

This problem is triggered either when drawing a Function or the PDF/CDF of a bivariate distribution

### How to reproduce the issue?

```shell
import openturns as ot

ot.ResourceMap.SetAsString("Contour-DefaultColorBarPosition", "")
g = Normal(2).drawPDF()
ot.Show(g) # The colorbar is there!
```

### Version

1.24dev

### Operating System

all

### Installation media

from source

**Comment by mbaudin47** [comment]
@jschueller : This should be fixed for 1.23: it is easy to fix and it is related to a new feature of this release.
