### ISSUE TITLE
How to modify a Contour once it has been put into a Graph?

### ISSUE THREAD

**Issue by regislebrun** [openturns/openturns#2669]
### What happened?

If I want to modify the colorbar location of a Contour once it has been put into a Graph, I don't have access to the Contour interface but only the interface of Drawable:
```python
import openturns as ot

g = ot.Normal(2).drawPDF()
contour = g.getDrawable(0)
# Impossible to change the colorbar location
contour.setColorBarPosition("") # fails
```

### How to reproduce the issue?

```shell
Use the given script
```

### Version

1.24dev

### Operating System

all

### Installation media

from source

**Comment by josephmure** [comment]
You can do it this way;
```python
import openturns as ot

g = ot.Normal(2).drawPDF()
contour = g.getDrawable(0).getImplementation()
contour.setColorBarPosition("")
```

**Comment by mbaudin47** [comment]
@regislebrun : I suggest to update the title to "How to remove the colorbar of a contour plot?". I also suggest to close this issue, since the answer was given by @josephmure

**Comment by regislebrun** [comment]
@mbaudin47: The problem is not bound to the colorbar location but for all the methods of Contour not accessible from the Drawable interface. BTW many of these methods are poorly documented, such as isVminUsed()/isVmaxUsed(). It is stated that they are accessors to the related flag, but one has no clue on why it is usefull to get this information, in particular we don't know for what this value is used.

**Comment by josephmure** [comment]
Vmin and vmax are documented in https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.contour.html so I guess the answer is to link to this page.
