### ISSUE TITLE
t_Bonmin_std.py fails on arm64, ppc64, ppc64el

### ISSUE THREAD

**Issue by pgrt** [openturns/openturns#2689]
### What happened?

I built openturns 1.23 on a Debian autobuilder equipped with debian/experimental, and on arm64, ppc64, ppc64el, the test t_Bonmin_std.py fails, see
https://buildd.debian.org/status/fetch.php?pkg=openturns&arch=arm64&ver=1.23-1&stamp=1718137756&raw=0

We get an error with "LIMIT_EXCEEDED" with the B-BB algorithm. Surprisingly:
- this issue does not show up with the C++ test ;
- with the other algorithms the test passes (e.g. by setting line 61 of t_Bonmin_std.py to `for algo in ot.Bonmin.GetAlgorithmNames()[1:]:`.

The issue does not show up with amd64, armhf, ...

### How to reproduce the issue?

```shell
Build OT on a machine with one of the above architectures and debian/experimental.
```

### Version

1.23

### Operating System

Linux

### Installation media

from source

**Comment by jschueller** [comment]
one difference I can see is that the c++ test has this line that the python test doesnt have, maybe try remove it ?
bonminAlgorithm.setMaximumIterationNumber(1000);

**Comment by pgrt** [comment]
Hi Julien,

Thanks, good catch! By removing this line, the C++ test fails.
By adding it as you suggest, the Python test passes.
