### ISSUE TITLE
allow finish optimization wo feasible points

### ISSUE THREAD

**Issue by m-balesdent** [openturns/openturns#2690]
### What happened?

The `setIgnoreFailure()` method of optimization algorithms is not documented. Consequently, when openTURNS algorithms fail to optimize, the user has not the possibility to understand how to disable this test.

The `getIgnoreFailure()` is not documented as well.

### How to reproduce the issue?

```shell
see : https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Cobyla.html

for example
```

### Version

1.23

### Operating System

all

### Installation media

pip

**Comment by jschueller** [comment]
this method is deprecated and its documentation was removed

**Comment by m-balesdent** [comment]
The getIgnoreFailure is still is the doc

**Comment by jschueller** [comment]
yes, and already removed for 1.24

**Comment by m-balesdent** [comment]
So, if the user wants to have a result if the algorithm has not converged, is it still possible?

**Comment by jschueller** [comment]
yes, we should use setCheckStatus instead from now on

**Comment by m-balesdent** [comment]
I think there is a bug, when a I run the following with setCheckStatus(False),   the exception `InvalidArgumentException : no feasible point found during optimization` is thrown.
```
import openturns as ot
import openturns.viewer as viewer
from matplotlib import pylab as plt

ot.Log.Show(ot.Log.NONE)

objective = ot.SymbolicFunction(
    ["x1", "x2", "x3", "x4"], ["x1 + 2 * x2 - 3 * x3 + 4 * x4"]
)

inequality_constraint = ot.SymbolicFunction(["x1", "x2", "x3", "x4"], ["-1.0"])

dim = objective.getInputDimension()
bounds = ot.Interval([-3.0] * dim, [5.0] * dim)

problem = ot.OptimizationProblem(objective)
problem.setMinimization(True)
problem.setInequalityConstraint(inequality_constraint)
problem.setBounds(bounds)

algo = ot.Cobyla()
algo.setCheckStatus(False)

algo.setProblem(problem)
startingPoint = [0.0] * dim
algo.setStartingPoint(startingPoint)
algo.run()
````

**Comment by jschueller** [comment]
the inequality constraint is constant and negative so your problem is not feasible

**Comment by m-balesdent** [comment]
Yes it was just a short example to address the point. I think in this case, even if one the user puts `algo.setCheckStatus(False)`, the algorithm will not have to throw an exception.
