### ISSUE TITLE
The current Contour has linear color map, but rank-based levels

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2693]
### What happened?

The next script produces three plots from the iso-values of the PDF of a bi-dimensional Gaussian:
- the first one, with default parameters, uses a linear color map and rank-based levels, which is highly surprising,
- the second one uses default levels and rank-based color map,
- the third one uses linear color map and linear levels.

The default graph is quite surprising. It is even more surprising because the color map is cyclic, as already mentioned in #2626. It seems to me that the method to compute the levels should match the method to compute the colors. The linear scale is the most obvious one.

![image](https://github.com/openturns/openturns/assets/31351465/abf898c9-5fc7-42c4-a632-e93d6581bfea)
**Figure 1.** Iso-values of the PDF of a Normal(2) distribution with default settings.

![image](https://github.com/openturns/openturns/assets/31351465/50046272-973b-46f9-bf33-858b0e19f281)
**Figure 2.** Iso-values of the PDF of a Normal(2) distribution with rank-based color map.

![image](https://github.com/openturns/openturns/assets/31351465/7e0187cf-8905-4092-9325-8d6364c84845)
**Figure 3.** Iso-values of the PDF of a Normal(2) distribution with linear levels.

### How to reproduce the issue?

```python
#%%
import openturns as ot
import numpy as np

print(ot.__version__)

# %%
numberOfLevels = 10
ot.ResourceMap.SetAsUnsignedInteger("Contour-DefaultLevelsNumber", numberOfLevels)

# %%
graph = ot.Normal(2).drawPDF()
graph

# %%
# Use ranks for colors
graph = ot.Normal(2).drawPDF()
contour = graph.getDrawable(0).getImplementation()
contour.setColorMapNorm("rank")
graph.setDrawable(contour, 0)
graph

# %%
# Use linear for levels
graph = ot.Normal(2).drawPDF()
contour = graph.getDrawable(0).getImplementation()
contour.setLevels(np.linspace(6.35e-6, 0.2, numberOfLevels))
graph.setDrawable(contour, 0)
graph

# %%
```

### Version

1.23

### Operating System

Linux

### Installation media

conda

**Comment by mbaudin47** [comment]
@josephmure : Do you have an opinion on this topic?

**Comment by josephmure** [comment]
IMO the only issue here is the HSV color map because of the cycling issue. Otherwise the current behavior was decided at the technical committee meeting. It is never bad, so it is a good choice IMO. In the normal case however I think the best behavior would be log-based color and log-based levels.

**Comment by mbaudin47** [comment]
Here is the result with log-based levels and log-based colors.
```python
import openturns as ot

numberOfLevels = 10
ot.ResourceMap.SetAsUnsignedInteger("Contour-DefaultLevelsNumber", numberOfLevels)

graph = ot.Normal(2).drawPDF()
contour = graph.getDrawable(0).getImplementation()
contour.setLevels(np.logspace(-6.0, -1.0, numberOfLevels))
contour.setColorMapNorm("log")
graph.setDrawable(contour, 0)
```

![image](https://github.com/openturns/openturns/assets/31351465/c53a397a-9763-4838-aedc-8f0a3a01063c)
**Figure 4.** Iso-values of the PDF of a Normal(2) distribution with log-based levels and log-based color map.

The current API makes this easy. This is why I close this issue and tag it as a question.

**Comment by josephmure** [comment]
If you are lazier, you can even let matplotlib decide the levels when using the log normalization:

```python
import openturns as ot

numberOfLevels = 10
ot.ResourceMap.SetAsUnsignedInteger("Contour-DefaultLevelsNumber", numberOfLevels)

graph = ot.Normal(2).drawPDF()
contour = graph.getDrawable(0).getImplementation()
contour.setLevels([])
contour.setColorMapNorm("log")
contour.setColorMap("viridis")
graph.setDrawable(contour, 0)
```

![image](https://github.com/openturns/openturns/assets/31989332/f6448f71-e8cf-405a-9400-b9dccfaf900e)
