### ISSUE TITLE
errors in Wilks doc

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2707]
### What happened?

WIlks documentation has many errors

### How to reproduce the issue?

https://openturns.github.io/openturns/latest/theory/data_analysis/quantile_estimation_wilks.html

### Version

1.23

### Operating System

all

### Installation media

other

**Comment by mbaudin47** [comment]
- Exemple : https://openturns.github.io/openturns/latest/auto_data_analysis/manage_data_and_samples/plot_quantile_estimation_wilks.html
- Doc API : https://openturns.github.io/openturns/latest/user_manual/_generated/openturns.Wilks.html
- Théorie : https://openturns.github.io/openturns/latest/theory/data_analysis/quantile_estimation_wilks.html

**Comment by mbaudin47** [comment]
In the next equation:
- E is the integer part (and not the expectation),
- $a_\alpha$ is $a_\beta$,
- the second $i_n$ is $j_n$.

![image](https://github.com/openturns/openturns/assets/31351465/447ecc91-b4e8-4540-9e25-2648ab4a658b)

**Comment by adutfoy** [comment]
Michaël,

We get the asymptotic confidence interval thanks to this theorem.
![Int_1](https://github.com/openturns/openturns/assets/13952415/4a6e8f03-0866-4739-bb1b-a59aaced4ad1)
![Int_2](https://github.com/openturns/openturns/assets/13952415/4acefb1e-b7e4-4872-8970-3e08a51059f0)
