### ISSUE TITLE
when i use openturns cobyla to calaulate optimization

### ISSUE THREAD

**Issue by YuDe95** [openturns/openturns#2735]
### What happened?

cobyla error opt value  output and input .when use probelm type :maximization.

### How to reproduce the issue?

```shell
i use python code is
"""
def _exec(X0):
"""Main function: must be present"""
Y0 = X0
return Y0
"""
start point is 0
lower bound is -1e-8
upper bound is 1e-8
constrains is Y0>1
ALG is cobyla
probelm type is maximization
num of evaluation is 10000
error all is 1e-50



output is 1e-8
input is 0.1
so i think it maybe the cobyla error.
and when i change the end bound is 10,the value is
output is 10
input is 10
```

### Version

1.23

### Operating System

Windows

### Installation media

other

### Additional Context

![image](https://github.com/user-attachments/assets/304d9486-58ee-402f-8fde-d32198ad1e3f)
![image](https://github.com/user-attachments/assets/647624b3-7c61-4193-ae7b-722930de09f6)
![image](https://github.com/user-attachments/assets/303e8176-8960-47a0-acd6-16a1f8ad6510)
![image](https://github.com/user-attachments/assets/ebceaf79-dd2e-434b-b3ac-1206e9d97698)

**Comment by jschueller** [comment]
the new 16.1 version reports that problem is not feasible as it should, so I close the issue
note that you're reporting a bug for persalys, next time it should go to https://github.com/persalys/persalys
