### ISSUE TITLE
Rational behind Interval operations?

### ISSUE THREAD

**Issue by sofianehaddad** [openturns/openturns#2756]
### What happened?

The implementation of some operators (-, -=) seems bugous 

See the definition of the implemented [operator -](https://github.com/openturns/openturns/blob/master/lib/src/Base/Geom/Interval.cxx#L314) and [operator -=](https://github.com/openturns/openturns/blob/master/lib/src/Base/Geom/Interval.cxx#L329) for more details

### How to reproduce the issue?

```shell
import openturns as ot
a = ot.Interval(0.2, 0.5)
b = ot.Interval(0.01, 0.05)
print(a - b)
```
which returns
`[0.15, 0.49]`

The impact is that this operator is used in many places such as `Distribution::computeProbability`

Thanks @josephmure  for highlighting it

**Comment by mbaudin47** [comment]
The `+` operator has the same issue for me: if the `+` operator means the union of the two sets, then the union of two intervals is not necessarily an interval. This is why the + operator is questionable in my opinion.

**Comment by josephmure** [comment]
Apparently, both + and - operators were designed with sums and differences of random variables in mind: they give the range of the resulting random variable.

**Comment by mbaudin47** [comment]
Here is a picture which explains what is the current code:
 
![image](https://github.com/user-attachments/assets/42380770-7117-4236-8939-6510bc971f11)

**Comment by regislebrun** [comment]
It is an implementation of the interval arithmetic, see https://en.wikipedia.org/wiki/Interval_arithmetic. It has been a long standing way to model and propagate uncertainties, despite its pitfalls: the intervals tend to grow exponentially fast while the actual uncertainties grow at a much lower rate. But it was needed for applications where only a few number of intervals are combined, for which it gives useful bounds.
