### ISSUE TITLE
The draw() method requires the same number of points in the X and Y directions

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2785]
### What happened?

When we plot the iso-values of a 2D function, it seems that the number of points in the X direction must be equal to the number of points in the Y direction. Otherwise, an exception is generated.

The next script produces:
```
TypeError: Shapes of x (20, 30) and z (30, 20) do not match
```

### How to reproduce the issue?

```python
import openturns as ot
import openturns.viewer as otv

cost = ot.SymbolicFunction(['x0', 'x1'], ['x0^2 + x1^2'])

graph = cost.draw([-1.0] * 2, [1.0] * 2, [30, 20])
view = otv.View(graph)
```

### Version

1.23

**Comment by jschueller** [comment]
works for me, whats your matplotlib version ?

**Comment by jschueller** [comment]
see https://github.com/openturns/openturns/pull/2721

**Comment by regislebrun** [comment]
This is a bug in the viewer, not the library. Fixed in the current master.
