### ISSUE TITLE
The colors of some examples are broken

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#2786]
### What happened?

It seems that some examples now have broken colors.

For example, [plot_functional_chaos_graphs.html](https://openturns.github.io/openturns/latest/auto_meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_graphs.html) was as follows in latest.

![image](https://github.com/user-attachments/assets/5f79f074-3e07-4c77-82b8-a945db92b8c3)

**Figure 1.** The Laguerre polynomials in [latest/plot_functional_chaos_graphs.html](https://openturns.github.io/openturns/latest/auto_meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_graphs.html).

![image](https://github.com/user-attachments/assets/61a5a8e1-e0ab-48e9-a4e7-ca22ed38958b)

**Figure 2.** Laguerre polynomials in [master/plot_functional_chaos_graphs](https://openturns.github.io/openturns/master/auto_meta_modeling/polynomial_chaos_metamodel/plot_functional_chaos_graphs.html).

It seems to me that the faulty PR is [commit 2b85507e1c63e62e4aaf3d94e63d48709d393928](https://github.com/openturns/openturns/commit/2b85507e1c63e62e4aaf3d94e63d48709d393928#diff-84a7321b8c1468bbb9fada83b9dc00c86a91db28c4e5aa882c7b2c34bea8b2d7).

The same is true for [master/plot_subset_sampling.html](https://openturns.github.io/openturns/master/auto_reliability_sensitivity/reliability/plot_subset_sampling.html).

![image](https://github.com/user-attachments/assets/046f204a-e53a-4478-a59d-8702354a2389)
**Figure 3.** Thresholds in subset sampling in [latest/plot_subset_sampling.html](https://openturns.github.io/openturns/latest/auto_reliability_sensitivity/reliability/plot_subset_sampling.html).

![image](https://github.com/user-attachments/assets/d72af067-d299-418c-8186-6e4fb81e5fbe)
**Figure 4.** Thresholds in subset sampling in [master/plot_subset_sampling.html](https://openturns.github.io/openturns/master/auto_reliability_sensitivity/reliability/plot_subset_sampling.html).

### How to reproduce the issue?

```shell
Read the doc
```

### Version

1.23

### Operating System

unknown

### Installation media

unknown

**Comment by mbaudin47** [comment]
The root cause is [UniVariateFunctionImplementation.cxx#L94](https://github.com/openturns/openturns/blob/414b0908346a84a60f86abcdcfe81e74beba4618/lib/src/Base/Func/UniVariateFunctionImplementation.cxx#L94) where the `Curve` is created using `Curve curve(data, "red", "solid", 2, getName());`. Since the color is "explicitly set", then the default color setting does not kick in.

**Comment by jschueller** [comment]
was it supposed to change the subset example red lines ?

**Comment by mbaudin47** [comment]
I think that the Subset example was not fixed:

![image](https://github.com/user-attachments/assets/a0bd0ef3-3d33-4f64-8961-49830dabc88e)

I do not know exactly why the bug occurs, but it is unrelated to the polynomials issue which is now solved.
