### ISSUE TITLE
Log.hxx ERROR issue

### ISSUE THREAD

**Issue by nitawa** [openturns/openturns#2796]
### What happened?

Hi,
When using `Openturns` compiled with Visual c++ 2017 , one gets an error due to the definition of `ERROR`, implemented [here](https://github.com/openturns/openturns/blob/master/lib/src/Base/Common/openturns/Log.hxx#L81)

A quick fix is implemented in a patch that I attach to this artifact.

regards.

[openturns.Log.hxx.patch.txt](https://github.com/user-attachments/files/17572012/openturns.Log.hxx.patch.txt)

### How to reproduce the issue?

```shell
compile openturns and compile openturns_salome.
```

### Version

1.23

### Operating System

Windows

### Installation media

from source

**Comment by jschueller** [comment]
how is OpenTURNS used in your case, just with "include <openturns/Log.hxx>" ?
could you give the actual includes that are used in you case ?
as a workaround I think including OTwindows.h first should fix the error

**Comment by jschueller** [comment]
maybe its pulled by Qt as neither persalys nor openturns include windows headers in their public interface
