### ISSUE TITLE
Linear-QuadraticFunction and Linear-QuadraticEvaluation are not coherent

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#2837]
### What happened?

The two classes LinearFunction and LinearEvaluation are note coherent.
**LinearEvaluation**: this class implements the evaluation of the function: $f :  \mathbb{R}^d  \rightarrow \mathbb{R}^p$ such that:

$$
f(X) = A^t (X-b) + c
$$

The input arguments are: $b,c,A$.
The method *getLinear()* returns $A$.

**LinearFunction**: this class implements the evaluation of the function: $f :  \mathbb{R}^d  \rightarrow \mathbb{R}^p$ such that:

$$
f(X) = A (X-b) + c
$$

The input arguments are: $b,c,A$.
There is no method *getLinear, getConstant, getCenter*. If we want to access to the matix $A$, we have to write:

$$
f = LinearFunction(center, constant, linear)
$$
$$
f.getEvaluation().getImplementation().getLinear()
$$

which return $A^t$...

I propose: 

1. to make coherent both functions: the input arguments are : $b,c,A$ and the function is

$$
f(X) = A (X-b) + c
$$

2. to add the methods *getLinear, getConstant, getCenter* to the *LinearFunction*

### How to reproduce the issue?

```shell
import openturns as ot
A = ot.Matrix(2,1)
A[0,0] = 1
A[1,0] = 2
b = [2.0, 3.0]
c = [4.0]
f = ot.LinearEvaluation(b,c,A)

center = [0.0, 0.0]
constant = [-1.0]
linear = ot.Matrix(1,2)
linear[0,0] = 2.0
linear[0,1] = 3.0
f = ot.LinearFunction(center, constant, linear)
```

### Version

1.25dev

### Operating System

Linux

### Installation media

from source

### Additional Context

-

**Comment by jschueller** [comment]
dup of #2833
