### ISSUE TITLE
Pip does not recognize conda install of openturns

### ISSUE THREAD

**Issue by NolwenHuet** [openturns/openturns#995]
When installing a python package with conda, it is usually recognized by the pip installator, so that if a `pip install openturns` is called afterwards, it is simply answered `Requirement already satisfied.`.

However this is not the case with openturns, so that pip download openturns even if already installed via conda.

This could be problematic if openturns is a dependency of another pip python package as 
- it will potentially override the choice by the user of the openturns version,
- it leads to pip install crashing for mac user as corresponding wheel does not exist yet on pypi.org (see #994), even if openturns has been installed via conda.

It seems that this is due to a lacking directory in `site-packages/` when installing openturns.
Usually a package install creates 2 directories named something like `mypackage/` and `mypackage-1.0.0.dist-info/` or `mypackage-1.0.0.egg-info/`. The latter is lacking for openturns.

Steps to reproduce issue:
```
conda create -n ot openturns -y
conda activate ot
pip install openturns
```
Which leads to 

> Collecting openturns

Instead of 
> Requirement already satisfied.

**Comment by jschueller** [comment]
Yes, it turns out it only requires mypackage-1.0.0.egg-info/ with an existing METADATA file in it, I should these files from openturns/build-wheels
