### ISSUE TITLE
The computeMinimumVolumeLevelSet method has doc issues

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#997]
See the computeMinimumVolumeInterval method of the Beta:

http://openturns.github.io/openturns/master/user_manual/_generated/openturns.Beta.html?highlight=computeminimumvolumeintervalwithmarginalprobability#openturns.Beta.computeMinimumVolumeInterval

The behaviour of the four methods : 
* computeMinimumVolumeInterval
* computeMinimumVolumeIntervalWithMarginalProbability
* computeMinimumVolumeLevelSet
* computeMinimumVolumeLevelSetWithThreshold

should be clarified within a either a Notebook tutorial or a Reference Guide page with graphics and examples. This would allow to clarify this definition.

**Comment by jschueller** [comment]
I dont see any code

**Comment by mbaudin47** [comment]
There should be an equation, but there is "\begin{eqnarray*}" in the image.

![screenshot-computemvls](https://user-images.githubusercontent.com/31351465/51398676-7ff50180-1b44-11e9-8f5f-afdb129d8b1d.png)

**Comment by mbaudin47** [comment]
Missing dollar character in the .rst ?

**Comment by jschueller** [comment]
It renders fine in my browser

**Comment by mbaudin47** [comment]
You are true: the formatting issue depends on the browser. The only problem is the description of the algorithms, not the LaTeX formatting.
